### ISSUE TITLE
Hide secrets in the web app

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1009]
### Describe the ideal solution

When viewing existing sources or destinations, secrets such as the API token or web-hook URL are visible from within the web UI. They should not visible from within the UI, and should in fact not even be sent to the UI to display.

### Describe your use cases

Not displaying the secrets in the web UI will prevent shoulder surfing attacks on the secret keys. Not returning the API token at all will prevent administrators from recovering the key, which is the preferred way to treat secrets like API tokens.

### Additional context

<img width="557" alt="Screen Shot 2020-06-08 at 5 56 28 PM" src="https://user-images.githubusercontent.com/49166439/84094300-6494cb80-a9b1-11ea-8d55-b5b0ac5ace4b.png">

- This token should be hidden

**Comment by nhakmiller** [comment]
This is primarily on the backend to hide/censor these secrets before sending them to the frontend to display, but I wanted to include the frontend team as well to verify that it won't cause issues. For example, if I return a destination like this:
```
{ "name": "a destination", "webhook": "****"}
```
And the user updates the name, the frontend needs to tell the backend to only update the name (and not for example update the webhook field to "****"). If the user changes the webhook field, then the frontend should send that back to the backend. It may be that this is already the frontend's behavior in which case no changes are needed from the frontend team, I just wanted to verify.

**Comment by 3nvi** [comment]
Nope, it's not like that currently. Should we split that into 2 tickets (FE & BE) or do  you want too manage both here?

**Comment by nhakmiller** [comment]
> Nope, it's not like that currently. Should we split that into 2 tickets (FE & BE) or do you want too manage both here?

Up to you. If you think it will be enough work to warrant a separate ticket feel free to open one for the FE, but if it's minor enough work we can just link both of the PRs to this story.
