### ISSUE TITLE
Migrate existing Panther to Dark theme

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1014]
This epic involves keeping all UX the same and just changing all of our UI in order to use the new components and API introduced  by the new pounce version

**Comment by jacknagz** [comment]
@3nvi isn't this done?

**Comment by 3nvi** [comment]
It's still missing one piece, but I feel that this piece is unrelated to the dark theme, so I'll close it

**Comment by 3nvi** [comment]
Removed unrelated ticket, since it doesn't affect the original scope of the epic
