### ISSUE TITLE
Feature Request - ECR monitoring &  scanning

### ISSUE THREAD

**Issue by gavinelder** [panther-labs/panther#1016]
### Describe the ideal solution

Make panther ECR aware to leverage AWS provided Scan on push to ECR registries via Clair image scanning, this is a pull based solution which requires manual intervention to identify if there is images which are vulnerable or have issues.

Further to this having the ability to monitor ECR pull / pushes.   

#### Example rules

As a security engineer I feel being able to write rules or alerts based upon a set of criteria. 

- Trigger an alert if image is pushed which then has a CVSS score above 7 
- Trigger an alert if an image is pushed which has security fixes
- As above but for image pulls. 
- Image pull or push from non-trusted source. 
- Has an image been uploaded outside of CI ? 

### How frequently would you use such feature

This would be a set and forget alert system with configuration of the ECR repository being a single action then manage compliance via alerts or the web-ui. 

### Describe alternatives you have considered

A clear and concise description of any alternative solutions or features you have considered.

### References

https://marbot.io/blog/how-to-monitor-ecr-image-scanning.html
https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr-eventbridge.html
https://asecure.cloud/a/detect-ecr-vuln-findings/

**Comment by nhakmiller** [comment]
We're moving these issues into an internal issue tracking system. I know this one is a bit old, but adding more scanners did finally get on the roadmap for this quarter so we'll see about prioritizing this one.
