### ISSUE TITLE
Log Onboarding May Timeout with Many Log Types

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#1023]
### Describe the bug
Since we changed to adding glue tables if they do not exist to the source api, the run times are longer. This is not an issue if the user has only a few log types if there are large numbers > 10 then the api times out since appsync has a 30sec timeout.

Since having large numbers of sources per bucket is unusual and there is a work around (see below) I don't think this is a pressing issue.

### Work Around
If this is a customer issue, they can onboard the same bucket multiple times with different names for the source and only a few log types per source.

### Possible Solutions
Either make source api optionally async (lots of work), users need to get any errors back so we need a true async api . Possibly move to a socket based api (according to Aggelos) could work with a long lambda timeout. This operation should never take more than a 1 minute. The one case where we could get large variation is that the panther views need to be updated and that is  done via Athena which can have long lags before starting. That said, re-trying after any error would fix that ephemeral issue.

**Comment by kostaspap** [comment]
This is fixed by this: https://github.com/panther-labs/panther/issues/1370

**Comment by kostaspap** [comment]
Resolving in favor of https://github.com/panther-labs/panther/issues/1370
