### ISSUE TITLE
Prevent Python saves if tests do not pass

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#1025]
### Describe the ideal solution

When editing a rule or policy, the save operation should fail if the rule/policy is enabled and unit tests are failing. Unit tests don't have much value unless they are enforced.

If a rule/policy does not have unit tests, we can either allow it ("all" of the 0 tests are passing) or deny it (you can't put a rule in production if it doesn't have tests).

### Describe alternatives you have considered

Today, we assume rule authors will always run tests on their own when developing Python in the web app. This is better than nothing, but imagine the frustration if you don't get an alert you were expecting because you made a typo which the existing unit tests would have prevented.

**Comment by 3nvi** [comment]
Just verifying that this is not related to the front-end, correct?

**Comment by austinbyers** [comment]
Right, this is backend only as long as rule/policy saves already gracefully handle error conditions

**Comment by kostaspap** [comment]
> If a rule/policy does not have unit tests, we can either allow it ("all" of the 0 tests are passing) or deny it (you can't put a rule in production if it doesn't have tests).

In my eyes the first option is probably preferable. I am afraid the second can be disruptive for some teams. In the end, we should let the customers decide what's best for their usecases :)

Users can still save a policy/rule with failing tests if it is disabled, right? I think you are implying this, just making sure are thoughts are aligned.

**Comment by austinbyers** [comment]
> Users can still save a policy/rule with failing tests if it is disabled, right?

Yes, that's what I envisioned

**Comment by kostaspap** [comment]
Summing up different scenarios: 
1. Policy/Rule enabled and tests passing: Allow saving
2. Policy/Rule disabled and tests passing: Allow saving
3. Policy/Rule enabled and tests failing: Block saving
4. Policy/Rule disabled and tests failing: Allow saving
5. Policy/Rule enabled and no tests: Allow saving
6. Policy/Rule disabled and no tests: Allow saving.
