### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#1032]
### Description

Generic improvements of our externally facing documentation.

### Criteria

- [ ] How to onboard each SaaS Integration
- [ ] Unified sections around writing analysis
- [ ] Tutorials and Guides for each data source (CloudTrail, S3, etc)

**Comment by kostaspap** [comment]
Related: https://github.com/panther-labs/panther-enterprise/issues/666

**Comment by mattthetraveler** [comment]
FYI we have this [epic](https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther/2085) in progress, looks like this issue overlaps.

**Comment by kostaspap** [comment]
Closing in favor of bigger epic: https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther/2085
