### ISSUE TITLE
JIRA Destination not Working

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1063]
### Describe the bug

A JIRA destination (properly configured as far as I can tell) is failing to send messages, logging WARN's in the `alert_delivery` lambda until eventually exceeding the max retries and erroring out.

### Steps to reproduce

1. Go to destinations
2. Configure a JIRA destination with all the required fields
3. Trigger a policy/rule at the severity of the JIRA destination
4. Observe WARN's in the `alert_delivery` lambda until the max retries are exceeded, at which point it errors out

### Expected behavior

A properly configured JIRA destination will deliver messages.

### Environment

- Tagged release 1.4

### Additional context

This was observed in another user's account, I don't have access to the original JIRA instance where this was observed so I am mostly troubleshooting from the Panther side.

When attempting to send to a JIRA destination with the issue type `Bug` I see this error:
```
"error": "request failed: 400 Bad Request: {\"errorMessages\":[],\"errors\":{\"issuetype\":\"issue type is required\"}}"
```

When attempting to send to a JIRA destination with the issue type `Task` I see this error:
```
    "error": "request failed: 400 Bad Request: {\"errorMessages\":[],\"errors\":{\"summary\":\"Field 'summary' cannot be set. It is not on the appropriate screen, or unknown.\",\"description\":\"Field 'description' cannot be set. It is not on the appropriate screen, or unknown.\"}}"
```

**Comment by nhakmiller** [comment]
Assigned to myself and Kostas since we've worked a lot with destinations, but really this one is up for grabs for whoever has time.

**Comment by nhakmiller** [comment]
Ok I think the issue is we only accept JIRA issue types `Bug`,  `Task`, and `Story`. But in JIRA the types of issue types is configurable, hypothetically someone could configure their JIRA account to have none of those issue types. We should probably make the issue type field a free text field and allow users to specify any issue type.

I was able to confirm this by first creating a working JIRA destination that communicated to our JIRA instance that created `Bug` issue types. I verified this was working. I then changed the `Bug` issue type to `BugTest` in JIRA and re-triggered the alert. This time it failed with the expected warning. I suspect this is the root of the issue.

@alexmylonas @3nvi @s0l0ist , what would the lift be to make the issue type field of the JIRA destination a free text field instead of a multi select? As far as I can tell that would resolve this issue for users who do not have a `Bug`, `Task`, or `Story` issue type, as I don't see any validation happening in the backend. I'm going to assign this to the frontend team since I don't see any changes that need to be made on the backend anymore. Would be a "nice to have" for this release, but if you guys are already swamped don't worry about it. At least I can take this info back to users about how to resolve the issue in the meantime (create an issue type of `Bug`, `Task`, or `Story`).

**Comment by alexmylonas** [comment]
Not sure if this can make it to v1.5, i am adding `p1` priority though

**Comment by alexmylonas** [comment]
@nhakmiller After changes to the input format i am getting this error
```
{
 data: null
  errorInfo: null
  errorType: "Lambda:Unhandled"
  locations: [{line: 2, column: 3, sourceName: null}]
  message: "invalid output configuration specified for alert output, missing required fields"
  path: ["addDestination"]
}
```

It seems like a backend error, no?

**Comment by nhakmiller** [comment]
> @nhakmiller After changes to the input format i am getting this error
> 
> ```
> {
>  data: null
>   errorInfo: null
>   errorType: "Lambda:Unhandled"
>   locations: [{line: 2, column: 3, sourceName: null}]
>   message: "invalid output configuration specified for alert output, missing required fields"
>   path: ["addDestination"]
> }
> ```
> 
> It seems like a backend error, no?

`missing required fields` seems like an odd error, all the fields should still be getting sent but the issue type field is just free text instead of selected from a drop down. Do you have a branch I could take a look at and maybe deploy?

**Comment by alexmylonas** [comment]
> > @nhakmiller After changes to the input format i am getting this error
> > ```
> > {
> >  data: null
> >   errorInfo: null
> >   errorType: "Lambda:Unhandled"
> >   locations: [{line: 2, column: 3, sourceName: null}]
> >   message: "invalid output configuration specified for alert output, missing required fields"
> >   path: ["addDestination"]
> > }
> > ```
> > 
> > 
> > It seems like a backend error, no?
> 
> `missing required fields` seems like an odd error, all the fields should still be getting sent but the issue type field is just free text instead of selected from a drop down. Do you have a branch I could take a look at and maybe deploy?

@nhakmiller I found the problem! The `username` seems required by graphql (and probably the backend) but not by the FE so it was failing due to missing on input. 

Also there is slight discrepancy, we save it as username but we ask user to fill this field as an email. What's the correct type?

**Comment by nhakmiller** [comment]
> Also there is slight discrepancy, we save it as username but we ask user to fill this field as an email. What's the correct type?

What we need is the email. I think in JIRA your email is the username, but you also have like a display name in JIRA that customers were putting in instead of their email. I'm ok with calling it whichever, and if you want I can update the backend API to expect either.
