### ISSUE TITLE
MFA Visual Enhancements

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1077]
### Description

Based on feedback from users, we need to improve some minor aspects in our MFA screen. Specifically, the issues are that:

- MFA TOTP is just named "Organization"
- Only QR code is presented and not the textual representation

To combat that  we need  to investigate how can we rename aspects of the TOTP parameters to rename the word `Organization` to something that makes more sense. We also need to show the related `otpauth` URL without the need for QR code scan

### Acceptance Criteria

- Remove the word `Organization` from the OTP URL parameter (see `formatSecretCode` under `helpers/utils`)
- Show the secret code under the QR code, so users that can't (or don't want ) to scan the QR code, can see the  OTP URL directly

**Comment by jacknagz** [comment]
As part of this - can we also fix an MFA bug I found today? You can put more than 6 digits in the input box:

![Screen Shot 2020-07-01 at 7.54.56 PM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/b936cd80-037f-4f11-a987-f47dabc8a103)

**Comment by 3nvi** [comment]
Sure

**Comment by alexmylonas** [comment]
It's strange that on Jack's screenshot there is no form error. I always get the `Code should contain exactly six digits.`

@3nvi Do you think is worth it to create a new input field that has 6 empty single character fields? Similar to [this](https://40818419.github.io/react-code-input/)

**Comment by 3nvi** [comment]
1. It doesn't have error cause the field is not **blurred** yet  (errors get added on blur)

2. Just  add a `maxLength` prop to the specific `<Field>` instance. That should do it.
