### ISSUE TITLE
Store Cloud Security Resource History in Data Lake

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1094]
### Description

Currently the Cloud Security and Log Analysis / Data Analytics pieces of the platform are almost entirely separated.  Additionally, we don't keep track of resource history. We only track a resources current state. We could improve both of these things by storing resource history in the data lake, alongside the processed logs. This would make resources queryable by the data analytics piece of the platform, as well as making it possible to track changes to a resource over time.

### Acceptance Criteria

- Every time a resource snapshot is different from its previous snapshot, that new snapshot should be stored in the data lake
  - Ideally, if the snapshot is the same it should not be stored in the data lake. That way viewing a resource in the data lake is akin to viewing a series of snapshots with timestamps of when the snapshot changed.
-  There should be a meaningful way to reference this data based on timestamps to know what the state of a resource was at a given time

**Comment by jacknagz** [comment]
@nhakmiller is this tracking for Jan 08th? Can we update the milestone if so?

**Comment by rleighton** [comment]
Yes, one more PR I’m finishing tomorrow

**Comment by kostaspap** [comment]
> @nhakmiller is this tracking for Jan 08th? Can we update the milestone if so?

Updated the Milestone (sprint) , the Release was already accurate (1.15)
