### ISSUE TITLE
Repository: Scan all paths with FOSSA

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#111]
**Is your feature request related to a problem? Please describe.**

Currently, we only have FOSSA configured for a handful of Lambda functions/libraries.

**Describe the solution you'd like**

Scan all components of Panther to ensure that we are covered in the entire repo.

**Describe alternatives you've considered**

None

**Additional context**

See the [FOSSA config file](https://github.com/panther-labs/panther/blob/master/.fossa.yml) for more info on what we are currently scanning

**Comment by austinbyers** [comment]
Closed via #241
