### ISSUE TITLE
Threshold alarms for rules

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#1111]
Users should be able to configure threshold alarms: Alarms that fires if a rule has reached a given threshold of matches over the deduplication period.

## Acceptance criteria

- Users can configure a threshold per rule in the Panther UI. 
- Users can configure threshold per rule through Analysis Tool/Bulk upload
- Functionality has been tested E2E
- Unit/integration tests have been added as appropriate

**Comment by jacknagz** [comment]
@kostaspap could you please add acceptance criteria here?

**Comment by kostaspap** [comment]
> @kostaspap could you please add acceptance criteria here?

Done!
