### ISSUE TITLE
Numbers Not Showing Up in Overview

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#112]
**Describe the bug**

The numbers in the middle of the donut chart are not showing up anymore.

**To Reproduce**

1. Go to overview page
2. Observe donut charts
3. There are no numbers, even when you hover your mouse

**Expected behavior**

There are numbers associated to the graphs.

**Screenshots**

![Screen Shot 2020-02-04 at 5 21 04 PM](https://user-images.githubusercontent.com/49166439/73802565-e8744800-4772-11ea-9f2b-42c016685c46.png)

**Environment**
How are you deploying or using Panther?

- Dev deployment on master 7bbd3a1

**Additional context**

Reported by external user, verified by me.

**Comment by 3nvi** [comment]
This will not be implemented due to an upcoming revamp that will remove those donuts. Will keep this issue up until the re-design is completed (for reference) and will close it as soon as the redesign is completed

**Comment by 3nvi** [comment]
Starting work since v1 is gonna roll without the re-design
