### ISSUE TITLE
Add the implementation to the Alerts API 

### ISSUE THREAD

**Issue by georgeSkoumas** [panther-labs/panther#1122]
This is the second backend component for the TopN attribute summaries feature. We have to add the implementation to the Alerts API, in a file called **get_alert_summaries.go**

1. The call should take as arguments: _alertID_, and a _list of attribute names_
2. The call should return a list of queryIds for summary results (the FE will poll these and display results)

**The code should**:
    .0 if no attributes are specified, read the rule python, extract default attributes and update lazily the rule definition with the attributes
    .1 lookup the alert in ddb (example code [here](https://github.com/panther-labs/panther-enterprise/blob/master/internal/log_analysis/alerts_api/api/get_alert.go#L42)) to get logTypes and time range
    .2 for each logType , look up the event in the parser [registry](https://github.com/panther-labs/panther-enterprise/blob/master/internal/log_analysis/log_processor/registry/registry.go) and collect a list of `table.column` called `summaries`
    .3 For each table.column  in `summaries` execute an async [query](https://github.com/panther-labs/panther-enterprise/blob/master/internal/core/database_api/athena/driver/api/execute_async_query.go#L20) of:

        SELECT <column>, count(1) as c 
        FROM <table> 
        WHERE p_alert_id='<alertId' and <time range> 
        GROUP BY <column>
        ORDER BY c
        LIMIT 5

    .4 for each async query, collect the queryIds for return

**Comment by rleighton** [comment]
This is in the wrong repo. Closing.
