### ISSUE TITLE
Design: Alert Status

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1162]
### Description

The user should be able to see the status of an alert in the table and the alert details page, providing a quick way of changing it.

More context can be found in the [related Front-end ticket](https://github.com/panther-labs/panther/issues/1135)

### Acceptance Criteria

- The status of the alert is displayed in every alerts table
- The user can change the  alert without going to an "details" page (i.e. directly from the table)
- The user can change the alert form the alert details page (proposal: use same component)
- The user should be able to filter by alert status. See [here](https://github.com/panther-labs/panther/issues/1134). This will be implemented as a typical "form dropdown entry" on the related page, but @dimitriszoitas let us know if you have something else in mind.

**Comment by 3nvi** [comment]
@dimitriszoitas existing work can be seen in the screenshots attached to [this PR](https://github.com/panther-labs/panther/pull/1156)

**Comment by dimitriszoitas** [comment]
I have created a collection with the screens related to this ticket here: https://share.goabstract.com/f16440e2-06fb-4cf6-a871-9329e6921c2b
