### ISSUE TITLE
Design: Rule and Policy Versions

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1166]
### Description

We should allow Rule & Policies to have versions and the user should be able to revert to a previous version

### Acceptance Criteria

- Rule/Policies should display the current version both in details and in edit pages
- Users should have a way of browsing different version of a Rule/Policy
- Users should be able to revert to a previous version of a Rule/Policy 

This has to do with all the details and not just the body (Python)

### Additional Context

Users would optionally be able to "recover" deleted Rules/Policies, but I don't know if that's within the scope of the implementation (@s0l0ist to comment)

**Comment by dimitriszoitas** [comment]
@s0l0ist @3nvi please review [this collection](https://share.goabstract.com/e42690eb-1a93-492b-8d30-60931b487800) and let me know if you have any feedback.

I have the following question:

In the details pages we do have created and last modified. Are we going to use a number for versions (eg v36) or are we going to use just the dates? If we dont use a version number then there is no need to also display the version of the rule/policy in the details page, only in the edit page. If we do have to add a version number though, I'll add it to the version history in the edit page as well.

**Comment by dimitriszoitas** [comment]
Also, some further enhancements for this could be to highlight the fields that have changed from the last version, and/or count the changes made (how many fields have been edited) and display it in the timeline. I dont know if we can do that at the moment though.

**Comment by 3nvi** [comment]
We should be iterative. I like the designs, but  I need validation from @s0l0ist and @austinbyers that **everything** we see in those SS can be supported from the backend

**Comment by dimitriszoitas** [comment]
I believe that if we do want to have a version history, the information I currently have in the mockups is the minimum needed for a functionality like that

**Comment by dimitriszoitas** [comment]
@s0l0ist @3nvi are we ok with this so that we can close the issue?

**Comment by 3nvi** [comment]
I'm still waiting for @s0l0ist or @austinbyers 's feedback for [this](https://github.com/panther-labs/panther/issues/1166#issuecomment-692649299)

**Comment by s0l0ist** [comment]
I thought we had said this had been supported in the backend for some time as we take a snapshot version for every change to a Rule or Policy.

**Comment by austinbyers** [comment]
I don't have an Abstract account (I just sent a request), so I can't yet see the designs, but yes we already have version information available in the backend. We don't have version "numbers" in the backend (they are technically long random strings), so use timestamps when showing old versions.

Today, in the `analysis-api`, you can already:

* Fetch a policy/rule/global by a specific versionID, even if the policy has already been deleted
* See the versionID in every Get/Update response

What we don't yet have:

* A way to list all the versions associated with a policy - this is easy to add
    * This will return a list of (versionID, timestamp) pairs. If you need more information (like userID) in this list, it may be a bit more complicated / inefficient in the backend, but we can make it work.
* An explicit `revert` endpoint - we can add one in the backend, or you can just call UpdatePolicy and pass in the old configuration to "revert"

**Comment by austinbyers** [comment]
Ah, I can see the designs now. Yes, I like them! I agree showing the username in the version history is helpful, so we'll find a way to make it work in the backend

**Comment by 3nvi** [comment]
Perfect, with this feedback I think that we can close this issue. @dimitriszoitas please close it yourself  when the associated design is moved to a branch. @s0l0ist, as the owner of this effort, please make sure to create the appropriate BE and FE tickets with explicit acceptance criteria based off of these designs
