### ISSUE TITLE
Design: Destination Status and Tests

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1168]
### Description

Users should be able to "mock" the firing of an alert to a certain destination, to validate that everything is configured correctly

### Acceptance Criteria

- Users should have a way of triggering a fake alert at any given time
- Users should be able to go to the created items in the "destination" (i.e. go to specified slack channel)

### Additional Context

It's interesting to  see whether this should be part  of the Alert creation process (i.e. a mandatory step before "storing" a destination) or something external

**Comment by dimitriszoitas** [comment]
Are we going to have a kind of confirmation (eg a pin code or simply a button) at the end of this process to validate?

**Comment by 3nvi** [comment]
I don't think that a code will be present, but @s0l0ist can verify

**Comment by dimitriszoitas** [comment]
Okay, I will proceed with just a validation/confirmation button that everything worked well and if there is a need for a pin input, we'll add it later

**Comment by dimitriszoitas** [comment]
I have made a few adjustments to the destination setup and also added the test alert trigger
You can find the collection [here](https://share.goabstract.com/b81ec1c6-38df-4861-9514-44cdea387aa9)

**Comment by s0l0ist** [comment]
@dimitriszoitas , I've left a comment on how we should show errors (if any) from the test alert.

Overall, this looks great! @3nvi, I don't want to have this part mandatory -- the user should be able to skip the test if they want. Not a big deal, but I'd rather lower the barrier to entry where possible.

**Comment by dimitriszoitas** [comment]
@s0l0ist I have updated the mockups in the shared link above. I would like your feedback on this approach so we can close this issue.

**Comment by s0l0ist** [comment]
LGTM
