### ISSUE TITLE
Check doc links in CI

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#1169]
### Description

It is very easy to have broken documentation links, especially ones that rely on relative paths. In fact, we have 48 broken links live in our documentation right now: https://github.com/panther-labs/panther/pull/1167

We should add some simple CI checks to block merges with broken links.

### Acceptance Criteria

CI will fail if any of the following are true:

- A link is invalid
    - This could be a relative path, e.g. `[link text](../path/overview.md#Header)`, in which case both the file and the header within that file need to exist.
    - All other paths must be a valid URL. For example, `[https://example.com](example)` is flipped and should fail CI (this happened in our live documentation)
- There are documentation pages not linked in the SUMMARY table of contents
- There are images in the `assets` folder which are not linked anywhere (these should be deleted)

**Comment by 3nvi** [comment]
We can also enhance this check by making sure  that the  UI always links to a valid doc (i.e. URL path still exists). We can do that easily with a static analysis, since the code for  the docs  is checked out in  the same repo.

If you want to, the FE team can own the JS related checks :)

**Comment by austinbyers** [comment]
> We can also enhance this check by making sure that the UI always links to a valid doc (i.e. URL path still exists). We can do that easily with a static analysis, since the code for the docs is checked out in the same repo.

This turned out to be fairly complex, but I was able to implement it

**Comment by 3nvi** [comment]
> > We can also enhance this check by making sure that the UI always links to a valid doc (i.e. URL path still exists). We can do that easily with a static analysis, since the code for the docs is checked out in the same repo.
> 
> This turned out to be fairly complex, but I was able to implement it

Amazing! Thanks @austinbyers
