### ISSUE TITLE
Docs: Update to Dark theme

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1175]
### Description

In our next release, Panther is going to go "dark" and the related docs should reflect that.

Although the design is not finished, the current implementation is a stepping stone to allow the incremental redesign to take place. Because of this, although the UI is not final, it's different enough to warrant an update on the docs.

Be aware that future work will also force a doc update, as more and more things in the UI become finalized

### Acceptance Criteria

- All screenshots  in our documentation that have a white theme, get replaced with equivalent screenshots using the dark theme
- All light-themed screenshots in any article that's pending a release has its icons updated
- All light-themed screenshots in our marketing website get updated

**Comment by kartikeypan** [comment]
This is done and ready: https://docs.runpanther.io/v/v1.6.0-docs/
