### ISSUE TITLE
Standard Field: RequestID

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#1182]
### Describe the ideal solution

Security events are often spread into multiple log lines and to link these events together, a request ID is generally set to provide context. We should create a standardized data field for request IDs to join across data sets.

### Describe your use cases

Searching the data lake to understand behavior for a given request.

### How frequently would you use such a feature

Daily

### Describe alternatives you have considered

None

### References

You can see this field in multiple AWS logs today

**Comment by kostaspap** [comment]
Is this referring to `requestID` fields of CloudTrail and S3 Server access logs? I'm not sure we can use this field to correlate events between the two datasets btw, I think they are not associated.

**Comment by alxarch** [comment]
I think this is a very useful feature that can easily be added to the 'new' parser logic I implemented. Code speaks louder than comments though so I will add the feature and link the implementation here. Can also address issue [370 from enterprise](https://github.com/panther-labs/panther-enterprise/issues/370)

**Comment by rleighton** [comment]
The main use case for this is not correlation (like we do with IP addresses) but tracing. Many API loggers will pass the request id thru multiple layers of micoservices so they can trace activity. Usually this is done to facilitate debugging and optimization but can be very handy for security to see the effect of 1 API call (which itself might call 20 other services).
