### ISSUE TITLE
Design: New field for Rules detail page. 

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#1188]
### Description

We need a new Rule configuration field named "Threshold". 
This field will have a numeric value from 0 to very high number e.g. 10 million or something. It need to be displayed in the Rules Detail page.

**Comment by dimitriszoitas** [comment]
Is this something that should be displayed in the Rules table in Rule overview page? If yes, we'll have to go with a different approach for the overview because there isnt enough width to display that info as well. A different approach will be a card-like UI for each rule.

**Comment by dimitriszoitas** [comment]
I have created a collection with the changes here:

https://share.goabstract.com/47e686c6-f1da-4500-9387-c0ca4917fd6f?collectionLayerId=b1941e72-3f4f-48ec-9656-19ac5c1df654&mode=design

**Comment by kostaspap** [comment]
> I have created a collection with the changes here:
> 
> https://share.goabstract.com/47e686c6-f1da-4500-9387-c0ca4917fd6f?collectionLayerId=b1941e72-3f4f-48ec-9656-19ac5c1df654&mode=design

design looks good!

**Comment by dimitriszoitas** [comment]
[Here](https://share.goabstract.com/47e686c6-f1da-4500-9387-c0ca4917fd6f?collectionLayerId=eda90eb3-d696-4f6d-9fec-9e2c4d3e6d55&mode=design) you can see a new component in the rules overview page that replace the table we had so that I can fit more info (threshold). Whenever you can please give me some feedback. Thank you

**Comment by kostaspap** [comment]
> [Here](https://share.goabstract.com/47e686c6-f1da-4500-9387-c0ca4917fd6f?collectionLayerId=eda90eb3-d696-4f6d-9fec-9e2c4d3e6d55&mode=design) you can see a new component in the rules overview page that replace the table we had so that I can fit more info (threshold). Whenever you can please give me some feedback. Thank you

I personally don't feel that we need to display it in the List Rules page. I think it would be enough to display it in the Rules detail page.
