### ISSUE TITLE
git-secrets scanning in continuous integration

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#119]
**Is your feature request related to a problem? Please describe.**

It was flagged internally awhile back to add support for secret scanning, this issue is to track that request.

**Describe the solution you'd like**

Add a https://github.com/awslabs/git-secrets check to CI.

**Comment by austinbyers** [comment]
It's not actually a check that runs in CI, it's a pre-commit hook that runs before committing code. There may not be anything we need to do in the repo itself

**Comment by austinbyers** [comment]
Yeah, this is a pre-commit hook developers can install locally. By the time CI is running, it's too late - the secret has been published
