### ISSUE TITLE
Log Analysis Overview: Data Latency Graph

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#1191]
### Describe the ideal solution

I'd like to add a new graph on the log analysis overview to show the average data latency by log type. 

Latency is measured as the delta between event time and parse time. 

Here is a sample graph showing this data created with Sigma:

![Screen Shot 2020-07-17 at 1.50.42 PM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/cfe68ddb-d9c1-42cf-9d87-c1a93466eea0)

It should be an average over the time period specified. 

### Describe your use cases

Tracking how long it takes for log data to make it into the Panther platform.

### How frequently would you use such a feature

Daily

###  Acceptance criteria

- The user can see the average difference between the `p_event_time` and `p_parse_time` fields graphically
  - This will allow the user's to identify when there are issues slowing down the ingestion of data, and get a general idea for how quickly their detections will be working
- The difference is displayed per log type
  - The user can filter to just the log types they care about
  - When multiple log types are displayed at once, the display adjusts so they can be clearly differentiated
  - This will allow users to see if latency issues are isolated to only certain log types

**Comment by nhakmiller** [comment]
I think this epic comprises three issues:

- Design
- Backend support
- Frontend support

The frontend piece is probably blocked by the design piece, but I think reasonably the backend piece is not blocked by either. I can create an issue for the backend piece at least on Monday and see if we can slot it in for the next release.

**Comment by alexmylonas** [comment]
What's the priority on this? @nhakmiller you think you could start working on this on current sprint?

**Comment by nhakmiller** [comment]
> What's the priority on this? @nhakmiller you think you could start working on this on current sprint?

By current sprint do you mean 1.6 or 1.7? I think we can start working on this for 1.7, it's a bit late for 1.6.

**Comment by alexmylonas** [comment]
Yeap, I was referring to v1.7 sorry for the misunderstanding. Cool then, I 'll create the issues, you referenced above, so we can start working on this.

**Comment by 3nvi** [comment]
related design screens:

https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/849670d3-62c0-462f-b399-bf6174c4352b/collections/ef90166e-2279-4166-af63-e4b40b4f545c
