### ISSUE TITLE
panther-created S3 buckets have AWS Account IDs in their name

### ISSUE THREAD

**Issue by kbroughton** [panther-labs/panther#120]
**Describe the bug**
This is a minor security bug but might be considered more of an enhancement. 

I know AWS uses account IDs in created resources all the time, but there are two good reasons not to do so.

1.  Pacu allows unauthenticated enumeration attacks given only a victim AWS account ID. This can be very useful. It's best to leak the account ID in as few places as possible.

2. Sometimes an attacker gains a degree of privilege to read or write to a bucket but cannot list buckets. Having random strings in bucket names adds a little protection. So using a random GUID instead of the AWS account ID means any panther-created buckets can't be brute-force scanned by someone with a big database of AWS Account Ids.

**To Reproduce**
1. deploy panther
2. note the S3 bucket names created

**Expected behavior**
Create all S3 resources with random short GUIDs instead of Account IDs

**Screenshots**

**Environment**
N/A

**Additional context**
As a pen tester, we love finding account IDs and knowing S3 bucket names.

**Comment by nhakmiller** [comment]
Thanks for the suggestion. 

As far as I'm aware, Panther creates the following 5 buckets:

- panther-analysis-versions
- panther-processed-data
- panther-s3-logs
- panther-source
- panther-athena-results

panther-s3-logs and panther-source could both be easily renamed with a random ID, as those are only referenced during the deployment stage.

panther-analysis-versions would be pretty easy to rename as it is already stored as an environment variable in the lambda that uses it, we would just need to pass in the random string to CloudFormation during the initial deployment.

panther-athena-results and panther-processed-data are part of the Log Analysis/Historical Search flow which I am less familiar with. @rleighton @kostaspap , would you imagine it is difficult to name these two buckets with a random ID generated at first deployment? I think it would just get passed through CloudFormation as a parameter, and stored in an environment variable in lambdas that need it.

--

As to whether or not we should do this, I think it is a good idea from a defense in depth perspective. Obviously the bucket names are not secret, but if it is easy for us to implement and makes enumeration that much harder than I'm all for it.

It also can leak information in that if I know a company has account ID 11111, I can try to create a bucket with a name in the format `panther-source-1111-region` (or whatever the right format is) and if I can't create it then I can guess that they are running Panther, which again isn't the end of the world but if we can avoid leaking that info we should.

**Comment by kostaspap** [comment]
Definitely something we have to take into consideration. Just to note, our current pattern of `<bucket-prefix>-<accountId>-<region>` is how many AWS services name buckets by default. E.g. Athena by default will create a bucket named `athena-query-results-123456789012-us-west-2`. We just followed AWS pattern, but we can change that. 
We need to find a reliable way to persist this information/GUID between deployments. If for some reason we would happen to falsely assume that the stack is not there, CFN would create a new S3 bucket and would all our log analysis data would go there - so we would "lose" the older data (or at least, lose the reference to the old data).

**Comment by nhakmiller** [comment]
That's what I assumed but I wasn't sure.

The source and s3-logs buckets work by describing the stack after it is created and getting the bucket names as outputs of the stack. Then future deployments do that same thing. We already have a block of logic in the deploy process for "first time" deployments, so I think it would be feasible to do something similar for these. Or perhaps we could specify the name on the first deployment, and then on subsequent deployments just don't overwrite the parameter. @austinbyers will probably have some good insight too.

**Comment by austinbyers** [comment]
I agree we could avoid relying on account IDs for S3, since it's globally namespaced. For the reasons mentioned as well as the possibility of a DOS attack - knowing an account ID you can register the bucket name and prevent Panther from deploying (not a huge deal, but we'd then have to work around this limitation regardless)

For the most part, bucket names are passed around explicitly in the deploy process, making this change should be doable
