### ISSUE TITLE
Verify saving a rule succeeds if it has more than one tests

### ISSUE THREAD

**Issue by giorgosp** [panther-labs/panther#1211]
A feature of the rule engine is to directly run a rule and its unit tests. This facilitates to run rules tests from the UI and the API on demand. We use this feature to [prevent saving a rule if its tests fail](https://github.com/panther-labs/panther/issues/1025).

However, the rule engine assumes that direct analysis will be requested with only one rule, as per the following snippet:
```
# Since this is used for testing single rules, it should only ever have one rule
if len(request['rules']) != 1:
   raise RuntimeError('exactly one rule expected, found {}'.format(len(request['rules'])))
```

As a result, saving a new rule with more than one test will fail, as the rule engine will return raise the above error.

The policy engine doesn't have a similar check but the similar behaviour should be verified as well.

I am planning to write a test to validate that assumption and fix the bug.

**Comment by kostaspap** [comment]
The code snippet checks the number of rules provided - not the number of tests though.

**Comment by giorgosp** [comment]
Indeed, good point. Got confused for a moment. Will push a commit that saves a rule/policy with multiple tests and close this one.

**Comment by kostaspap** [comment]
After doing some testing it seems that the code is working fine. Removing the `bug` and reducing priority.
