### ISSUE TITLE
Display test output when saving a rule/policy is prevented due to failing tests

### ISSUE THREAD

**Issue by giorgosp** [panther-labs/panther#1212]
### Describe the ideal solution

Saving rules/policies is prevented if their tests fail. Currently, we only display a message like "cannot save rule due to failing tests". If the rule has many tests, the user has to "think" and click the Run All button in order to run all the tests and see which are failing.

We could fast-forward this for the user by displaying the "Run All" test summary in addition to the "cannot save.." message
when saving a rule/policy is prevented.

### Describe your use cases

When a rule/policy has multiple tests and the user wants to modify it but some of the tests fail.

### How frequently would you use such feature

Not sure

**Comment by 3nvi** [comment]
@giorgosp re-assigned you since (until we figure out a better way) each ticket must have an "owner"
