### ISSUE TITLE
Create Rule operation populates rule fields with older values

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#1213]
### Describe the bug

Creating a rule operation seems to use data from older operation

### Steps to reproduce

1. Go to Log Analysis -> Rules
2. Click on Create -> Single
3. Populate some fields, e.g. ID
4. Click "Cancel"
5. Click again on Create -> Single

You will see that the Rule has kept the older Rule id. 
### Expected behavior

I expect that clicking to create a single rule, displays me a fresh page. 

### Environment

How are you deploying or using Panther?

- fb6cab1a83e73b38f1010a0fa634dd9b2ecd705d
- OS: MacOS 10.15.5
- Browser: Chrome 84.0.4147.89

**Comment by 3nvi** [comment]
Actually this is a feature. We are "restoring" any work you had **in the same session** in  case you wanted to continue where you left off. The values get cleared when:


- You close  your tab
- You startt work on a new tab
- You "commit" your work (i.e. "save")

I understand that sometimes, "leaving" is intentional and "restoring"  shouldn't occur though. But all in all, this is explicitly implemented and not a bug

**Comment by 3nvi** [comment]
Would you want us to implement a manual "flush" of the saved entities when the button "cancel" is clicked?

**Comment by kostaspap** [comment]
> Would you want us to implement a manual "flush" of the saved entities when the button "cancel" is clicked?

Interesting 😄  Yes, for me it seems confusing (a "bug") the fact that once I press cancel when writing a rule, then try to create another one I got some values already populated. IMO, it would be more clear if when I try to navigate out of this window (clicking Cancel, navigating away, etc) I get a warning "Are you sure you want to close this window? All unsaved changes will be lost" (or similar). 

If you say it is a feature I believe you. But as a user without knowledge of the above, it felt like a bug :P

**Comment by 3nvi** [comment]
ok, will clear it when users manually  press cancel. We can add the modal later (although I always felt the modal was a bit more pervasive)
