### ISSUE TITLE
Redesign Auth pages

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1228]
### Description

The auth pages need to abide by the designs

### Designs

https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/849670d3-62c0-462f-b399-bf6174c4352b/collections/a49fd2fc-f2f9-4543-afc4-6c55bc4e61ec

### Acceptance Criteria

As Auth pages we consider the: SignIn, ForgetPassword, ForgetPasswordConfirm, TOTP, MFA & SetNewPassword pages

- Auth pages should be responsive on pounce breakpoints 
- Auth pages should closely follow the UI shown in the designs
- There should be a basic testing for sign-in & forget password, in which we validate that Cognito API has been correctly invoked

**Comment by jacknagz** [comment]
@3nvi can we rework the acceptance criteria?

**Comment by 3nvi** [comment]
@jacknagz The functional requirements are exactly the same, thus the only thing that changes is the UI. I've updated the criteria to be more verbose, but I don't think I can add additional criteria :/

**Comment by 3nvi** [comment]
Implemented
