### ISSUE TITLE
Policy should have "un-ignore" button on resources

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#1243]
### Issue
Currently when you click on the "..." and ignore a resource not passing. However, there is no way on the page to revert this change. Rather you have to edit the policy. This is not intuitive. If an action is reversible, the control to reverse should be available near the control to change. Suggest having an "un-ignore" button to revert "ignore" in the same menu.

**Comment by 3nvi** [comment]
This is something that I wanted to implement as well, but I'm limited due to the API. I asked @austinbyers if there was a way to support it, but currently there isn't one. 

We could normally "hack" around it in a GraphQL resolver (by fetching a Policy's details, changing a field & updating the entire policy itself), but AppSync is limited when it comes to what you can do in a resolver.  Thus, due to the fact that we don't use a "proper" GraphQL server, I need to delegate that task to the actual lambda service. 

If we think this is something needed, we can plan it, but I'm removing the milestone since I don't see it being implemented in early Q3

**Comment by austinbyers** [comment]
> I asked @austinbyers if there was a way to support it, but currently there isn't one.

I don't recall this conversation, but I probably just forgot. The tricky thing in the backend is that suppressions are technically a regex-like pattern. The "ignore" button adds a new suppression which is the full resource ID, but you could also have a suppression like "my-dev-bucket-*". In that case, an "unignore" button wouldn't make sense on individual resources today.

Possible solutions:

- Show "unignore" option only when applicable - if a suppression pattern exactly matches the resourceID. This would work for the specific case of undoing a click of the "ignore" button, but not in other cases.
- We add an "allowlist" that would override the ignore pattern - e.g. unignore this specific resource even though I want to ignore all others with a similar pattern

**Comment by 3nvi** [comment]
I'm up for the first solution. It's just that hte compliance API doesn't give me the `suppressions` back 😄 I remember I asked about them so I could escape some API calls.

Only if I had that would I be able to push an update to the entire policy (supposing that I'm allowed to send & update a single field in a policy through the API)

**Comment by austinbyers** [comment]
> I'm up for the first solution. It's just that hte compliance API doesn't give me the suppressions back 😄 I remember I asked about them so I could escape some API calls.

Right, you'd have to get the list of suppressions from the policy first. If you're on the policy page listing resources below, you already have that information shown

> Only if I had that would I be able to push an update to the entire policy (supposing that I'm allowed to send & update a single field in a policy through the API)

We have a `/suppress` endpoint for updating just the suppression information: https://github.com/panther-labs/panther/blob/master/api/gateway/analysis/api.yml#L478

But this can only add suppressions, it can't remove them. And policies do not support partial updates currently, so no matter what I guess there would have to be a backend component to this

**Comment by 3nvi** [comment]
> > I'm up for the first solution. It's just that hte compliance API doesn't give me the suppressions back 😄 I remember I asked about them so I could escape some API calls.
> 
> Right, you'd have to get the list of suppressions from the policy first. If you're on the policy page listing resources below, you already have that information shown
> 
> > Only if I had that would I be able to push an update to the entire policy (supposing that I'm allowed to send & update a single field in a policy through the API)
> 
> We have a `/suppress` endpoint for updating just the suppression information: https://github.com/panther-labs/panther/blob/master/api/gateway/analysis/api.yml#L478
> 
> But this can only add suppressions, it can't remove them. And policies do not support partial updates currently, so no matter what I guess there would have to be a backend component to this

I think so as well. In policy details page I have the info I need, but in resource details page I can't get the necessary info (without a myriad requests). Those UXs should align, so I feel that we indeed  need something in the backend for this feature

**Comment by 3nvi** [comment]
Adding to product board
