### ISSUE TITLE
Alerts name changes columns width if too big

### ISSUE THREAD

**Issue by alexmylonas** [panther-labs/panther#1248]
### Describe the bug

If there is an Alert name with many characters, it's changes the columns width and malformes the next "View Rule" pill.

Not a serious issue but bad UX. 

### Steps to reproduce

1. Go to Alerts Page
2. Scroll through until there is an alert with a big name
3. Check that "View Rule" text is wrapped on the pill 

### Expected Behaviour

Handle bigger names gracefully, either slice string or wrap text. But I would like to @dimitriszoitas to weigh in here for a suggestion!

### Environment

- Panther version or commit: a77364f9050a59bf76b7fe0a7e1c2b51c6c64a17

### Screenshots
![Screen-Recording-2020-07-28-at-1](https://user-images.githubusercontent.com/14179917/88651552-7271ed80-d0d2-11ea-99e3-97236ad785af.gif)

**Comment by 3nvi** [comment]
Removing Dimitris as it's unrelated to his work. We can fix that with a simple `flexbox` CSS rule
