### ISSUE TITLE
Implement Logarithmic scale for Log Analysis Metrics

### ISSUE THREAD

**Issue by alexmylonas** [panther-labs/panther#1256]
### Description

We have recently implemented 2 graphs for Log Analysis. For the graph of `Events by Log Types` some events like `S3 Server Access` have orders of magnitude difference from other metrics.
i.e. S3 Server access events per day averaging at 400k where the next bigger is around 6k.

This results in a graph that doesn't have much granuality, introducing a logarithmic scale will yield better visual results.

### Acceptance Criteria

- Alter line graphs to use Logarithmic scale instead of linear
- This should be conditional, not all linear graphs should use logarithmic scale.

A current situation screenshot:
![Screenshot 2020-07-29 at 1 32 50 PM](https://user-images.githubusercontent.com/14179917/88790012-27261080-d1a0-11ea-9f46-33288cf40bce.png)

**Comment by 3nvi** [comment]
Will be included as part of #1399
