### ISSUE TITLE
Allow resending invitation email

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#1265]
### Describe the ideal solution

If a user loses their invitation email, there is currently no way to reset their password. All an admin can do is delete their user and re-add them.

It would be great if the "force password reset" worked for new users as well, or a separate "resend invitation" link. We already support this in the backend:

1. Invite a new user from the Panther web app
2. Invoke the `users-api` Lambda function directly:

```json
{
  "inviteUser": {
    "requesterId": "...",
    "givenName": "Alice",
    "familyName": "Jones",
    "email": "user@example.com",
    "messageAction": "RESEND"
  }
}
```

3. See the invitation email show up again (with a different autogenerated password)

All the web team has to do is set "messageAction" to "RESEND" for users which have not yet been confirmed, and then they can re-invite the same user the same way they triggered the original user invite

**Comment by austinbyers** [comment]
I've updated the issue - this is already implemented in the backend and should be trivial for the web team to add when they get a moment. Reassigned to the web team

**Comment by 3nvi** [comment]
Yup, will plan for 1.8 ;)
