### ISSUE TITLE
Fixes and enhancements on Charts

### ISSUE THREAD

**Issue by dimitriszoitas** [panther-labs/panther#1330]
### Description

Based on the library capabilities, we have to slightly redesign the UI. Also we have to add zoom handlers and a switch to display the line chart in log scale. Lastly we have to define certain colors (50-60 colors) that will be clearly visible when used in lines

### Acceptance Criteria

- User should be able to zoom in and out easily
- Lines should be easy to see
- User should be able to switch from log scale to normal

**Comment by dimitriszoitas** [comment]
Progress of this issue can be found [here](https://share.goabstract.com/bfb890ea-bed2-4759-891d-dacf90f07ab2)

**Comment by 3nvi** [comment]
Given the fact that https://github.com/panther-labs/panther/issues/1257 exists, we can take the conversation there.

Closing for now
