### ISSUE TITLE
Text for Rule Threshold not aligned properly

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#1334]
### Describe the bug

Text for Rule Threshold not aligned properly

### Steps to reproduce

1. Go to Log Analysis -> Rules page
2. Click on a Rule. 
3. See the Rule Threshold in the Rule metadata

### Expected behavior

Rule Threshold and Rule Deduplication period are properly aligned. 

### Environment

How are you deploying or using Panther?

- Panther version or commit: https://github.com/panther-labs/panther/commit/67f02fa9aa17213dd7f5a2e0da08984d158f7e4e
- OS: 10.15.6 
- Browser: Chrome Version 84.0.4147.105 (Official Build) (64-bit)

### Screenshots

![Screen Shot 2020-08-10 at 3.09.28 PM.png](https://images.zenhubusercontent.com/5e4fc81c2009ef65e12fafd8/0f7449ec-682b-4cd9-81e7-8eea1c318ff2)

**Comment by 3nvi** [comment]
@kostaspap is that still an issue?
