### ISSUE TITLE
Fix User Experience for SSO Login

### ISSUE THREAD

**Issue by dimitriszoitas** [panther-labs/panther#1339]
### Description

We need to change the login user experience to be optimal for both users that have SSO and dont have SSO. Converting to a 2-stage login with just the e-mail at first step and then if the user has SSO the ability to option with either a password or SSO. If the user doesnt have SSO then only the password field should be present

### Acceptance Criteria

- User should be able to login with email/password and with email/sso
- User should be able to login in 2 steps

**Comment by 3nvi** [comment]
@dimitriszoitas take a look here https://panther-labs.atlassian.net/wiki/spaces/EN/pages/593166340/RFC+Improved+SSO+Login+Flow?src=mail&src.mail.timestamp=1597087892833&src.mail.notification=com.atlassian.confluence.plugins.confluence-mentions-plugin%3Amention-created-notification&src.mail.recipient=8a7f808a6ba019b1016bac085bcd0167&src.mail.action=view

We might end up not needing this
