### ISSUE TITLE
Top destinations backend work

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1361]
### Description

Generate and present destination usage metrics.

### Acceptance Criteria

- Log metrics for how many alarms are being sent to each destination
- Make these metrics queryable via the metrics API

**Comment by s0l0ist** [comment]
@nhakmiller what is the status of this issue? I'm punting to v1.12 in the meantime.

**Comment by 3nvi** [comment]
> @nhakmiller what is the status of this issue? I'm punting to v1.12 in the meantime.

We have to clarify what 1.12 means. Release or sprint?

**Comment by nhakmiller** [comment]
> > @nhakmiller what is the status of this issue? I'm punting to v1.12 in the meantime.
> 
> We have to clarify what 1.12 means. Release or sprint? If it's a sprint, I feel that it's wrong to modify what was already planned. We should simply remove it's existing milestone tag and leave it as is, to see if it should get groomed

Yeah we don't have this actually planned for 1.12, somehow it fell through the planning cracks. I'll mark it 1.13 and see that we get it planned.
