### ISSUE TITLE
GetAlerts API should be more selective listing s3 objects

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#1366]
### Issue
Today each S3 object is searched serially calling the s3 select api, if there are many objects this can be slow, sometimes causing a timeout for users when there are very large numbers of objects.

### Solution
Use the timestamp of the alert to start listing

**Comment by kostaspap** [comment]
We only need to fetch 25 events per API call - 1 go routine should be enough for that. I suspect there is some other issue going on there.

**Comment by rleighton** [comment]
Updated description based on slack call

**Comment by rleighton** [comment]
Moving this to next release due to extra time needed for release 1.7.1 and PTO
