### ISSUE TITLE
Design: S3 onboarding flow misleading

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#1375]
### Describe the bug

When a user goes to onboard a new S3 data source to Panther, ask them to enable SNS notification for that S3 bucket **before** the source is saved in the backend (section titled `Step 2: Adding Notifications For New Data`). This is problematic since the SNS notification require some permissions to be set on Panther's side, permissions that are configured when the source is saved in the backend. With the current flow, the step to setup the SNS notification fails when it tries to subscribe the customer's SNS topic to Panther's SQS queue.

### Steps to reproduce

1. Go to Log Analysis -> Sources
2. Click on `Add Source`
3. Select S3
4. Populate the first page of the wizard. Click `Continue Setup` and see the issue

### Expected behavior

We should suggest the user to do the steps shown in `Step 2: Adding Notifications For New Data` AFTER the source has been saved in the backend. 

### Environment

How are you deploying or using Panther?

- Panther version or commit: https://github.com/panther-labs/panther/commit/714b1937905d4859a9f3835283d0277811c4b1db

### Screenshots

![Screen Shot 2020-08-17 at 12.51.46 PM.png](https://images.zenhubusercontent.com/5e4fc81c2009ef65e12fafd8/99bcd635-7fe5-4846-8fdb-218f7e3c410c)

**Comment by dimitriszoitas** [comment]
I updated the success screen to this https://share.goabstract.com/2f8be99e-9b41-429a-a529-faa39306b721?mode=design&sha=d0570e02d9fb58bb4e79266e5e7ff6e3978973a8

are we ok with something like that?

**Comment by 3nvi** [comment]
@kostaspap if we are, we can include it in the 1.8 designs & release (cc @dimitriszoitas )

**Comment by kostaspap** [comment]
> @kostaspap if we are, we can include it in the 1.8 designs & release (cc @dimitriszoitas )

Checked the design, looks good.

**Comment by 3nvi** [comment]
@dimitriszoitas let's add it to 1.8 designs
