### ISSUE TITLE
Users should only be able to pick log types deployed when creating rules

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#1387]
### Describe the bug
When users pick log types not deployed when creating/editing a rule this can create errors in sql generation.

### Solution
The UI should use an API to populate a the pick list for associating log types to rules. There is already an internal function in the server code to list the deployed log types.

**Comment by 3nvi** [comment]
> When users pick log types not deployed when creating/editing a rule this can create errors in sql generation.

Could you please explain this a bit more? I can't fully understand what a "log type that's not deployed" is. 


Also, could this be a duplicate of https://github.com/panther-labs/panther/issues/1282?

**Comment by rleighton** [comment]
> > When users pick log types not deployed when creating/editing a rule this can create errors in sql generation.
> 
> Could you please explain this a bit more? I can't fully understand what a "log type that's not deployed" is.
> 
> Also, could this be a duplicate of #1282?

The system provisions the database tables on demand as log source sources are onboarded. Once created they cannot be deleted. User's should not reference log types (which map to tables) that do not exist in the system.

It is a duplicate of that that issue, I updated the spec on that issue.
