### ISSUE TITLE
gluesync CLI tool does not use `-start` flag

### ISSUE THREAD

**Issue by alxarch** [panther-labs/panther#1388]
### Describe the bug

The CLI tool `gluesync` has a `-start` flag to set the starting date to sync partitions from.
The tool has a bug that ignores this flag if it is set at the CLI and can only use a start time for the partition sync if it is running interactively and it is left empty by asking the start date with a prompt. Since we will need to use `gluesync` for deployment of 1.7 this bug is critical for the release. If a fix is not merged until the release we should inform those handling the deployments that `gluesync` *must* be run interatively and *without* a `-start` flag to function properly.

### Steps to reproduce

1. mage build:tools
2. `out/bin/../gluesync -start 2020-04-02`
3. The flag is ignored and partitions resort to table creation time for the time range to sync

### Expected behavior

`-start` flag should be setting the start date o sync from

**Comment by rleighton** [comment]
Fixed
