### ISSUE TITLE
Design: Destination delivery statuses

### ISSUE THREAD

**Issue by s0l0ist** [panther-labs/panther#1392]
### Description

This **design** issue is for how the user should interact with a re-send button and how they should visualize this information in the panther UI.

When alerts are sent to a destination, we should provide a way for our uses to understand if the alert was delivered successfully. In the event of a failure, there needs to be a way to re-send the alert to the destination that failed.

### Acceptance Criteria

Users should be able to click on an alert, go to the alert details, and quickly check if the alert was delivered successfully or not. Ideally, we should only have a visual indication if there was a problem.

The failure message should contain some information about the failure if possible containing a history of attempts to send (in the event the alert was re-tried automatically or manually).

The shape of the data will be a list of objects containing data from _each_ attempt to send the alert. It is acceptable to have more than one entry for every destination: 
```javascript
[
  {
    outputId: "aaa" // the outputId of the destination (slack)
    success: true, // if the alert was sent successfully or not
    statusCode: 201, // http status code
    message: "", // optional success or failure message of the response
    deliveryAttemptedAt: 2020-01-01T00:00.000Z // timestamp when the alert was attempted to be delivered
  },
  {
    outputId: "bbb" // the outputId of the destination (asana)
    success: false, // if the alert was sent successfully or not
    statusCode: 500, // http status code
    message: "client timeout", // optional success or failure message of the response
    deliveryAttemptedAt: 2020-01-01T00:00.000Z // timestamp when the alert was attempted to be delivered
  },
  {
    outputId: "bbb" // the outputId of the destination (asana)
    success: true, // if the alert was sent successfully or not
    statusCode: 200, // http status code
    message: "success", // optional success or failure message of the response
    deliveryAttemptedAt: 2020-01-01T00:00.000Z // timestamp when the alert was attempted to be delivered
  },
  ...
]
```

- Alert tables:
  - A visual indicator in both tables (in the list alerts & rules pages) containing alerts that informs the user there is a problem and they should click to view the alert details.

- Alert details:
  - Should not show extra information if there were no issues delivering the alerts
  - Should have an optional toggle somewhere that the user can click to reveal the information about the delivery status (should include all successful and/or failed attempts and the data associated)
  - Should have a visual indicator (kind of a highlight) and automatically expand the area (the user needed to click to expand before) so the user can immediately see where the problem is occurring and why.
  - A button should also be present in this expanded area to re-send alerts. When clicked, the browser initiates the API call and will update the alert content in the expanded area automatically with the response data. If successful, the error highlight should disappear but the expanded area should remain so the user can see the result was a success.

**Comment by dimitriszoitas** [comment]
I have created a collection [here](https://share.goabstract.com/b8db36c3-a821-4ad7-9132-c965c3544675)

@s0l0ist  please let me know if you're ok with the approach

Thank you

**Comment by 3nvi** [comment]
Left my  comments :)

**Comment by dimitriszoitas** [comment]
@3nvi @s0l0ist I have addressed your comments - please let me know if the mockup in the collection shared above is ok so we can close this issue.

If understand correctly, when a delivery fails to reach a destination, the backend will try again and again (up to 10 times) until it succeeds. In that case, do we show both the failed attempts AND the success one? And if yes (i guess we are going to be showing all of the attempts) what's going to happened when I click the button Try sending again? will it only re-send the ones that never succeeded?

I also added a retries counter in each row to display how many times that specific alert was retried to a specific destination. Expanding the row can show the internal history of each destination. IF this is an issue for the current version, then we should go with just a table with way to many rows.
