### ISSUE TITLE
Create Alert Card & Deprecate Alerts Table

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1397]
### Description

Due to lack of real estate, the alerts table will be getting replaced with alerts cards. The alerts cards will share similar information to the currently visible alerts table, but will allow us to easily extend it & add more values

### Designs

https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/849670d3-62c0-462f-b399-bf6174c4352b/commits/latest/files/c2bbc1a8-4778-4cd6-93a5-4630d8868201/layers/FA1F7045-29D1-4B29-98FC-AD10075AACE1?collectionId=ef90166e-2279-4166-af63-e4b40b4f545c&collectionLayerId=b3aa0c9b-cbbd-4dfe-9f90-64c212b0f97c

### Acceptance Criteria

- An `AlertCard` can be created using the `GenericItemCard` component, following the `DestinationCard` principles
- The `AlertCard` is tested for displaying the correct information
- Alerts table is no longer present, but gets replaced with Alert Cards in the following pages:
  - ListAlertsPage
  - LogAnalysisOverviewPage
  - RuleDetailsPage

### Notes

- Destinations won't be shown in the `AlertCard` (not currently returned by the API)
- Log Types won't be shown in the `AlertCard` (not currently shown by the API)

**Comment by s0l0ist** [comment]
@3nvi @alexmylonas if this is complete, please close. Moving to next milestone

**Comment by 3nvi** [comment]
We are tracking this as a side-effect of other tickets. I think it's safe to close
