### ISSUE TITLE
Allow Alert Status update from all components

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1398]
### Description

Currently, updating the status of the alert is only doable from within the ListAlertsPage or the RuleDetailsPage.

We should make sure use the `UpdateAlertDropdown` to every place where the `AlertBadge` is being  shown

### Acceptance Criteria

- Users can edit an alert from any place the `AlertBadge` is being shown

**Comment by alexmylonas** [comment]
@3nvi This seems to be already implemented and introduced via #1541 to `RuleDetails` and `LogAnalysisOverview`.
`AlertStatusBadge`is currently used only on `UpdateAlertDropdown`

I will make #1541 close this

**Comment by 3nvi** [comment]
sure
