### ISSUE TITLE
API for Most Active Rules

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1402]
The log analysis overview page needs to show a chart with the top rules ranked by the number of alerts they sent in a certain time frame

https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/master/commits/d0570e02d9fb58bb4e79266e5e7ff6e3978973a8/files/c2bbc1a8-4778-4cd6-93a5-4630d8868201/layers/49B988DE-947E-4204-AA7B-5B48AE7E50E4

### Acceptance Criteria

- The API accepts a date range  as input
- The API returns a list  of rule information (as designated by the needs of the chart above) along with the number of alerts sent
- If it's helpful, the API can optionally return only a fixed number of results (10 or 20) since the chart will only showcase 5  or 10

**Comment by alexmylonas** [comment]
@nhakmiller Do you any updates or timeline regarding this?

**Comment by nhakmiller** [comment]
> @nhakmiller Do you any updates or timeline regarding this?

Re-assigned to @lindsey-w , after touching  base with @3nvi we're planning to have this done by Friday September 25th.
