### ISSUE TITLE
Alert event view crashes when alert was created by rule with threshold

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#1407]
### Describe the bug

Alert event view crashes when alert was created by rule with threshold

### Steps to reproduce

1. Create a new rule with a threshold 10. Enable it. 
2. Send 10+ messages to Panther that will match this rule. 
3. Wait for alert to be generated
4. Click on the alert. Try listing all events that matched the rule

### Expected behavior

You should see all the events that matched the rule. 

### Environment

How are you deploying or using Panther?

- Panther version : 1.7.0

### Additional context

The issue is caused because of the following: 
1. The AlertsAPI looks depends on alertCreationTime and alertUpdateTime when filtering the events that triggered an alert. It is looking based on these time indexes to find the events that matched an event. You can see how alertCreationTime is used here: https://github.com/panther-labs/panther/blob/c6def71ba5863195d2384c96c5e48f5d6e981a99/internal/log_analysis/alerts_api/api/get_alert.go#L127
2. The alert forwarder is the service storing alertCreationTime and alertUpdateTime.https://github.com/panther-labs/panther/blob/c6def71ba5863195d2384c96c5e48f5d6e981a99/internal/log_analysis/alert_forwarder/forwarder/forwarder.go#L163-L198
The bug occurs because in case of rules with a threshold, we use as "alertCreationTime" the time that the threshold was breached - NOT the time the first event was matched. 

### Solution

We need to store a new field in the alerts called "firstEventmatchedTime". Alerts API should use that time when looking into S3 to find matched events. 
a. [This](https://github.com/panther-labs/panther/blob/c6def71ba5863195d2384c96c5e48f5d6e981a99/internal/log_analysis/alert_forwarder/forwarder/forwarder.go#L175-L178) should be updated to be like the following:
```
CreationTime: alertDedup.UpdateTime,
UpdateTime:   alertDedup.UpdateTime,
FirstEventMatchedTime: alertDedup.CreationTime
```
The line `CreationTime:   alertDedup.UpdateTime` might look weird at first, however, the alert UpdateTime is updated on subsequent rule matches: https://github.com/panther-labs/panther/blob/c6def71ba5863195d2384c96c5e48f5d6e981a99/internal/log_analysis/alert_forwarder/forwarder/forwarder.go#L140

b. [This](https://github.com/panther-labs/panther/blob/c6def71ba5863195d2384c96c5e48f5d6e981a99/internal/log_analysis/alerts_api/api/get_alert.go#L127) should be modified so that it uses the `FirstEventMatchedTime` instead of `AlertCreationTime`
c. [This](https://github.com/panther-labs/panther/blob/c6def71ba5863195d2384c96c5e48f5d6e981a99/internal/log_analysis/alerts_api/api/get_alert.go#L179) should be modified to use FirstEventMatchedTime instead of CreationTime.

**Comment by rleighton** [comment]
Fixed
