### ISSUE TITLE
[Design] Bulk change Alert Statuses

### ISSUE THREAD

**Issue by s0l0ist** [panther-labs/panther#1411]
### Description

Individually changing each alert's status is tedious and cumbersome, especially when writing a test rule and later going back to update the status of the alerts.

The current backend Alerts API allows for updating a single alert. This needs to be extended to allow for multiple alerts.

### Related Services

- Alerts API Update Status 
  - needs to accept an array of alert IDs
  - return corresponding alert summaries back to the frontend

### Designs

Paste the link to your designs [here](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/0d293ff7-a6c6-4ddc-9dd0-442c63b91995/collections/0e79571a-428a-4c7f-bb8d-f6c4e457eb57)
@dimitriszoitas 

### Acceptance Criteria

**Any** view that displays/lists **multiple** alerts needs to have the ability to check multiple alerts via a checkbox (or all on the page) and bulk and set their status (Open, Triaged, Ignored, Resolved).

@3nvi , would be nice to have your thoughts as well on how this should be implemented as there could be several ways.

- User views a list of alerts
- User sees there's an option to change the alert's status
- User can either update a single alert's status the way it currently exists
- User also sees the ability to check multiple alerts
- User can scroll and click multiple alerts and change their status
- User can also click a button to select all the alerts on the page, pick status for all of them which can be saved on status selection or from a separate 'submit' button.
  - Ex: user wants to change all `INFO` alerts to `Resolved` he can filter, check all with one click, and set the status.

**Comment by s0l0ist** [comment]
@dimitriszoitas, let's start that this sprint if you can

**Comment by dimitriszoitas** [comment]
@s0l0ist @3nvi please have a look at [these mockups](https://share.goabstract.com/f71b637a-8c83-4eeb-b8f6-cba12ec06602)

Having the multiple select functionality will affect the following:

1. We'll have to add a new "card" variation with a checkbox (to select all)
2. Of course we'll have to add a new card component for the alert with a checkbox
3. When 1 or more alerts are selected, the search and sort functionality will stop working and an action functionality will appear in place. 

Finally I would like to ask if this multiple selection will also happen in the Log Analysis Overview where we display the latest alerts. If yes then we'll have to change a couple of things there as well.

Let me know what you think

**Comment by s0l0ist** [comment]
@dimitriszoitas I like this a lot!

**Comment by 3nvi** [comment]
Design looks nice, but I see a lot of additional UI there. If this is part of the ticket, then it's going to increase the effort.

I still think it's doable in 1.13 though. @s0l0ist can you create the necessary ticket? Keep in mind that only what you include in the acceptance criteria will be implemented, so be specific 😆 


P.S. As a rule of thumb, we never modify existing sprint effort, so I don't see that fitting in 1.12

**Comment by dimitriszoitas** [comment]
@3nvi depending on the release, we'll be adding the ui gradually. I'm working on the main branch so I'm just adding/changing the UI there. The basic components needed for this issue are:

1. Checkbox to select all in card
2. Checkbox in component
3. When item is checked then the filter area changes to action area.

Also please let me know if the multi select applies to the overview page so that I use the same components there.

**Comment by s0l0ist** [comment]
@dimitriszoitas , I'm not sure it needs to be on the overview pages. However, it should be on the rule details page which shows a list of alerts below.

**Comment by 3nvi** [comment]
@s0l0ist currently we allow users to update a single alert status in the overview page (since work was already done for this & I felt that it came for free).

I don't see a reason why we should or shouldn't support it. I'm ok not supporting it if we want to, but, so far, individual alert updates **are** allowed in the overview page

**Comment by s0l0ist** [comment]
@3nvi i don't have a strong opinion on it. If it is easy/free once the cards are created why not.

**Comment by 3nvi** [comment]
I think we'll already need a re-usable component/hook since we are gonna have mass-actions on ListAlerts page and the Rule Details page (the alerts showed).

Thus, I think we should add it to the overview Jim, unless you feel we don't need it. We can accommodate both
