### ISSUE TITLE
Showcase Destinations on Cloud Security entities

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1433]
### Description

Each policy in Cloud Security is tied to a particular destination. Right now this destination is the union of the destination assigned to the severity of the policy,  as well as any destination override that has been assigned to the policy itself.

This data is never displayed to the user, so they currently need to "do the math" on their own to calculate where the alert for a particular policy will end up to. This task provides this information through  the API in order for the front-end to showcase it to the user. 

### Acceptance Criteria

- The `policy-api` should return a list of `destinations` for each policy. The destinations should map to `Destination` items containing at minimum`{id, destinationType}`. This is both for `PolicySummary` and the `PolicyDetails`
- The `resources-api` should return a list of `destinations` for each resource. This is calculated as the "join" of the destinations for the policies associated with this particular resource. This is for both `ResourceSummary` and `ResourceDetails`.
- The `compliance-api` should return the exact same information for **all** `ComplianceItem` entities.

### Caveats

At minimum this should be implemented for  the policies. If calculating it for the resources is hard or costly, then we can plan around it  or implement it later down the line

### Designs

You can see the related designs for this here:

https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/master/files/323d0ca1-81a8-40e7-83ee-0a05b870bb4a

**Comment by austinbyers** [comment]
We can implement this in the backend (we will just have to lookup destinations on every request), but why do you feel it should happen in the raw APIs and not, for example, in AppSync or the frontend? Usually such "joins" happen higher up our stack: for example, showing the display name of a user or integration is a lookup that happens in the frontend

**Comment by 3nvi** [comment]
> showing the display name of a user or integration is a lookup that happens in the frontend based on IDs from the backend

This is something really bad and needs to change actually.

> Usually such "joins" happen higher up our stack

You are right. But I avoid them because of one thing: **performance**

Right now, the `policy-api` returns the overrides of the policy only for  `PolicyDetails`, but `PolicySummary` doesn't have it. If I wanted to I could make N+1 requests to show the destinations of N policies (by getting the "details" for each one, but that's not performant)

A similar  thing happens with the compliance  API. Right now I'd have to make N + 2 requests since the `ComplianceItem` doesn't contain any information about destinations.

All in all, you are right. I should be doing that and it **is** the responsibility of the API, but as long as the lambda API  doesn't offer a performant way to allow  me to do that, I'm limited. Should you wish to, I can explain how the APIs should ideally  be built to enable the Appsync to do things like that

**Comment by austinbyers** [comment]
You're right that it's always more performant to do this on the backend. I've added a note to make sure we think about this sort of thing when designing a new API.

I'll add them to the existing APIs for now, but the extra lookup is wasted for backend API calls. So I'll need to add a way to request the extra information only for the frontend, i.e. "give me these fields"

We'll see if I'm able to finish it for 1.8, but I certainly can for 1.9

**Comment by austinbyers** [comment]
Reassigning to @nhakmiller 's team, I have to drop other dev work to prioritize API design

**Comment by nhakmiller** [comment]
@3nvi I think there may be some confusion on this one. This is not true:

> Right now this destination is the union of the destination assigned to the severity of the policy, as well as any destination override that has been assigned to the policy itself.

Destination overrides replace the set of severities assigned to the policy based on its severity. So the destination that a policy/rule gets sent to is either the default destinations based on severity, OR the destination override. Do you still think this task is necessary?

**Comment by nhakmiller** [comment]
@3nvi bumping this thread, given my info above is this still a requirement?

**Comment by 3nvi** [comment]
Are both of these exposed through our APIs? If so, then perfect. If  not, we should add them

**Comment by s0l0ist** [comment]
@nhakmiller is correct, there's no 'union' of the two. Destination Overrides take precedence over default severities. 

@3nvi We already have a destinations API that is used to map/resolve delivery statuses in the frontend. We can do the same async fetch and map/resolve in the frontend to get the destinations that will apply for each Policy. I'm not sure we need any further backend changes as long as the summary/details page includes the destination overrides field.

if destination overrides is `null` or empty `[]`, grab the list of **default** destinations, filter against each policy's severity to get the destinations for the policy. If we have overrides, use them and perform the same filter.

Punting to v1.12
