### ISSUE TITLE
Adding a new Log source of type AWS S3 with KMS key results in error if bucket and key are in a different region than the one where panther is deployed

### ISSUE THREAD

**Issue by stanzahk** [panther-labs/panther#1436]
### Describe the bug

I am trying to configure GuardDuty log type ingestion in eu-central-1 region and the logs are encrypted with a customer managed KMS key.
Panther is deployed in region us-east-1.
Adding the source result in error "source xxxxxxxxx did not pass configuration check because of log processing role cannot access kms key"

### Steps to reproduce

1. deploy panther to region us-east-1
2. activate guardduty in region eu-central-1.
3. configure guarduty event export to S3 bucket with a customer managed KMS key, both in eu-central-1
4. Setup a log source on panther
5. deploy the CF stack for the service role in us-east-1, as suggested by panther itself (actually it just creates a IAM role)
6. see the error "source xxxxxxxxx did not pass configuration check because of log processing role cannot access kms key"

`source xxxxxx did not pass configuration check because of log processing role cannot access kms key: InvalidInputError null`

`{"level":"error","ts":1598543357.1080272,"caller":"api/put_integration.go:48","msg":"failed to put integration","application":"panther","requestId":"a646cd09-778a-418f-be79-0d3c4c91cca7","error":"source DY-guard-duty-logs did not pass configuration check because of log processing role cannot access kms key"}`

`
{"level":"error","ts":1598543357.108098,"caller":"oplog/oplog.go:185","msg":"cloudsec:snapshot:PutIntegration","application":"panther","requestId":"a646cd09-778a-418f-be79-0d3c4c91cca7","input":{"PutIntegrationSettings":{"awsAccountId":"(redacted string len=12)","cweEnabled":null,"integrationLabel":"xxxxxxxxxxx","integrationType":"aws-s3","kmsKey":"arn:aws:kms:eu-central-1:xxxxxxx:key/xxxxxxxxxxxx","logTypes":["AWS.GuardDuty"],"remediationEnabled":null,"s3Bucket":"xxxxxxxxxxxxxx","s3Prefix":"","scanIntervalMins":0,"sqsConfig":null,"userId":"xxxxxxxxxxxxxxxx"}},"error":"source xxxxxxxxxxx did not pass configuration check because of log processing role cannot access kms key","namespace":"cloudsec","component":"snapshot","operation":"PutIntegration","status":"failure","startOp":1598543356.9713798,"opTime":0.136661513,"endOp":1598543357.1080413,"sysSizeMB":69,"heapSizeMB":8,"heapChangeMB":0,"gcPercent":0.000119913372689967,"gcPauseMilliseconds":0,"gcCycles":0,"percentMemUsed":53}
`

### Expected behavior
The service role used to acces logs in the s3 bucket should be able to access the KMS key properly.

### Environment

How are you deploying or using Panther?

- Panther version or commit: v1.7.1
- OS: Linux
- Browser: Firefox 80

### Additional context

- I have impersonated the service role at step 5 with aws cli and I was able to succesfully call the describe-key api.
- I have succesfully done the above operation with guadduty logs bucket and kms key both in the same region where panther is deployed.

To me it seems that the KMS key check fails whenever the KMS key is in a different region than the one where panther is deployed.

**Comment by nhakmiller** [comment]
Thanks for reporting this issue! We're looking into it now trying to replicate.
