### ISSUE TITLE
Display dedup() and title() output in the rule test results (Design)

### ISSUE THREAD

**Issue by giorgosp** [panther-labs/panther#1447]
Please see #983 for more context by Jack.

This is the output of a rule test.

<img width="1009" alt="Screenshot 2020-09-01 at 11 56 29 AM" src="https://user-images.githubusercontent.com/3627869/91829465-2fafb200-ec4a-11ea-9983-6481314ddd09.png">

Every rule has 3 functions (or qualities let's say):
```
def rule(event):
   # whatever, check if the rule should fire

def dedup(event):
    return event.get('recipientAccountId')

def title(event):
    return 'AWS logins detected without MFA in account'
```

- `rule(event)` is the function that checks whether the the rule should trigger an alert based on the input event
- `dedup(event)` is the function that returns an identifier so that we can deduplicate alerts if an alert is triggered multiple times
- `title(event)` returns a human-friendly name for the alert

A rule test is an automatic way to check and verify the rule functions behavior with custom input.

Now, when a rule test is run, the UI displays the result (pass/fail) and the name of the test, based on the `rule(event)` function only.
The change we want to introduce is to also display **the result** of the `dedup` and `title` functions along with the test result.

**Comment by dimitriszoitas** [comment]
I've revised the mockup, you can view the changes [here](https://share.goabstract.com/ab41929c-aa50-433f-bbb1-f7e5df996ecd?mode=design&sha=9737cc6b0e9feb7b131d4140483c105ceca91953)
