### ISSUE TITLE
Rule Testing: Show Dedup and Title Output (Frontend)

### ISSUE THREAD

**Issue by giorgosp** [panther-labs/panther#1448]
Please see #983 and #1447 for more context.

### Designs

https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/6c4082e9-dc0b-4e26-b60e-cc96e60306ee/commits/e83db616a4a6ea9e13ebf782f9e6b9b20cc71466/files/c2bbc1a8-4778-4cd6-93a5-4630d8868201/layers/FEEF6C46-1D8D-4D6E-9C80-9ED62F99D2E3?mode=design&sha=9737cc6b0e9feb7b131d4140483c105ceca91953

### Motivation

- Will allow users to see the test results for their `dedup` and `title` functions

**Comment by giorgosp** [comment]
The backend is ready for this. The related PR is #1625 and is merged into the `title-dedup-epic` feature branch, where we can merge the frontend PR there and then merge the feature branch into master.

**Comment by vorillaz** [comment]
Closed by #1805
