### ISSUE TITLE
List Alerts: Runtime Error on Title Search

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#1468]
### Describe the bug

When a user searches for an alert string that has no results, the API returns an invalid memory address:

```
Couldn't load your alerts
Runtime error: invalid memory address or nil pointer dereference
```

### Steps to reproduce

Note: This error only occurs on deployments with a lot of alerts

1. Go https://your.domain/log-analysis/alerts
2. Search for an alert title string that doesn't exist in the database
3. See the alert
4. Cry

### Expected behavior

The Lambda should better handle this use case or the database should be indexed in a more optimized manner

### Environment

Panther Enterprise v1.7.1

### Screenshots

![alerts-memory-bug.gif](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/bdbd30e1-a5d0-4ca7-acc1-62eb1bb22dae)

**Comment by rleighton** [comment]
I got an alarm, did a PR: https://github.com/panther-labs/panther/pull/1467
