### ISSUE TITLE
Implement  Redesigned Bulk Uploader

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1472]
### Description

The Bulk uploader is a feature where users can upload a base64-encoded  zipfile containing rules, policies and/or python modules, instead of having  to write them 1-by-1 by hand.

Up until now, we have a simple Sidesheet  that  was handling this, but we want  to revamp the look of it in order to make it  more clear, appealing and straightforward to the user

### Designs

https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/0d293ff7-a6c6-4ddc-9dd0-442c63b91995/commits/3c6c0abfd80455b24fc0327f61a114da3375de38/files/8cc3cb34-8b80-405f-97ad-3adafc365a4f/layers/12494265-818D-4A90-BDE1-D278DC3BFDFD?collectionId=8c2fcbab-6254-4f20-ae74-2a4d193dc5e4&collectionLayerId=4f06885e-0c08-4923-9886-ebb293b2fcc8

### Acceptance Criteria

- The "Add New Policy" and "Add New Rule" button should not provide the option for "single or bulk" anymore, but should be links that just redirect the user to wherever the "single" was redirecting users to
- The SideSheet that was handling bulk upload gets removed from Panther
- An extra page gets added under the Settings Navigation, in which we implement the bulk upload logic
- The single base64-encoded zipfile cannot only be uploaded through a "click", but can also be "drag & dropped" into a region
- The upload should start instantly when the user drops or selects a file
- The user should be able to drag & drop (or select) the **same** file multiple times in a row (i.e. the underlying `<input />` element should not reject the same file, even if it already "has" it)
- A file upload progress should be shown to the user while the file is uploading
- An indicator should be shown to the user while the request is processing in the server
- The results should be shown back instantly when they arrive from the API
- A link to the [related docs](https://docs.runpanther.io/user-guide/analysis/panther-analysis-tool) must be visible in the page (hint: use const `ANALYSIS_UPLOAD_DOC_URL`)

**Comment by austinbyers** [comment]
If this is still planned for v1.9, you'll need to add the `sync-to-release` label since the branch has already been updated

**Comment by 3nvi** [comment]
This is actually done. I dunno why the issue hasn't closed yet
