### ISSUE TITLE
Sending test alerts to destinations should show errors in the UI

### ISSUE THREAD

**Issue by s0l0ist** [panther-labs/panther#1496]
### Describe the ideal solution

Sending a test alert to a given destination should display errors to the user.

### Describe your use cases

Sometimes there are errors when onboarding a destination, it would be helpful to provide the error message/body to the user in some way so that debugging can start. We should have a generic error plus an option somewhere to view the raw error message.

### How frequently would you use such a feature

Monthly? Only really when onboarding a destination.

### Describe alternatives you have considered

- Use a static message and log to CW
- Simply console.error the message in the browser as not all errors can be wrapped nicely. It would at least be a good starting point for advanced users.

**Comment by dimitriszoitas** [comment]
@3nvi @s0l0ist please have a look at this mockup and leave your feedback https://share.goabstract.com/cc95d58f-515d-4476-b519-6b00ebf58910?mode=design&sha=843f48f3834df278ff649c27930b69d873b59d1e

**Comment by 3nvi** [comment]
Left my feedback

**Comment by dimitriszoitas** [comment]
@s0l0ist @3nvi same here, are we ok? do we need any changes?

**Comment by 3nvi** [comment]
@dimitriszoitas Need some updates, see Abstract

**Comment by dimitriszoitas** [comment]
@s0l0ist can you please help me out with the following, based on your comment in abstract:

1. Can I have an example of the API status response
2. Can I also have an example of an internal error so that I make a different mockup with an error snack?

Thank you

**Comment by s0l0ist** [comment]
The response is the same shape (and will not change) as the delivery history section uses. 

The values that will change is the http status code, success Boolean will be false, and the message payload could be _anything_ (string, Json, html doc). We need to truncate the width of the response message as we do already in the delivery history for an alert because we don't know how it could fail.

**Comment by dimitriszoitas** [comment]
@s0l0ist @3nvi please let me know if you're ok with the updated mockup so I can close this issue

**Comment by s0l0ist** [comment]
@dimitriszoitas , I think we can omit the `success`, `outputId`, and `dispatchedAt` fields from being shown to the user as they really don't provide any useful context.

The only fields the user should care about is the `message` and `statusCode`. Given we should only display these two fields, I think we should be able to come up with a more user-friendly way of displaying the message as opposed to rendering a JSON body.

**Comment by 3nvi** [comment]
I think

> @dimitriszoitas , I think we can omit the `success`, `outputId`, and `dispatchedAt` fields from being shown to the user as they really don't provide any useful context.
> 
> The only fields the user should care about is the `message` and `statusCode`. Given we should only display these two fields, I think we should be able to come up with a more user-friendly way of displaying the message as opposed to rendering a JSON body.

I think we can decide that on our own. If we are happy with the "general approach" we can pick the `{key,value}` pairs we want to show.

@dimitriszoitas I think the background color is a bit too "bold", but I'm fine with whatever decision we make

**Comment by dimitriszoitas** [comment]
@3nvi  it's the color i've used in other errors as well

**Comment by 3nvi** [comment]
Sure thing then, @s0l0ist should we close it and create a small FE ticket for the web team? Is there any word needed from your end that I haven't accounted for?
