### ISSUE TITLE
Separate screen for "Add Notification for New Data" in source onboarding

### ISSUE THREAD

**Issue by dimitriszoitas** [panther-labs/panther#1501]
### Description

We have to change the current flow where the user adds an S3 source in Log Analysis, and we ask them to add notification for new data in the same screen we verify their source creation. 

### Acceptance Criteria

- The prompt for the user to add notifications should be in a separate step/screen before the verification
- Make the step appear required so the users clearly know they have to do it

**Comment by 3nvi** [comment]
@dimitriszoitas need this asap. It's been in progress for 4 days with an estimate of 1

**Comment by dimitriszoitas** [comment]
I have revised the flow and it can be found [here](https://share.goabstract.com/1f716dde-228c-499b-b147-d1742d242e2a)

**Comment by dimitriszoitas** [comment]
@3nvi @s0l0ist please let me know if this flow works as intended so that we can close this issue

**Comment by 3nvi** [comment]
Just want to verify with @kostaspap that we actually  have a way of "verifying" that notifications are setup correctly. Else we'll have to remove the "verify" button 😞

**Comment by kostaspap** [comment]
> Just want to verify with @kostaspap that we actually have a way of "verifying" that notifications are setup correctly. Else we'll have to remove the "verify" button 😞

I replied on abstract.

**Comment by s0l0ist** [comment]
I don't have context for this change. Deferring to @3nvi / @kostaspap
