### ISSUE TITLE
Create an Error Detail page

### ISSUE THREAD

**Issue by dimitriszoitas** [panther-labs/panther#1507]
### Description

When the user clicks on an error (from the alerts page) they should be directed to a page similar to the alert details page with the following information excluded: severity, reference, runbook, tags.

### Acceptance Criteria

- Page should be at a similar format as the alert's details page
- It should be easily identifiable that this is an error page

**Comment by kostaspap** [comment]
Following discussions with @dimitriszoitas  on Slack, fixing the milestone to be 1.9.

**Comment by dimitriszoitas** [comment]
@kostaspap please review [this collection](https://share.goabstract.com/f89373ca-f0ce-4152-9f65-380686d3d755?collectionLayerId=a20f567f-8e7d-424a-93cf-8fd5687ac1ae&mode=design) whenever you have the time. I've made changes to a every component related to rule matches/rule errors.

**Comment by 3nvi** [comment]
To be clear, we just highlighted to  top section to make it clear that there is an error right? Was that the intended requirement?

**Comment by dimitriszoitas** [comment]
> To be clear, we just highlighted to top section to make it clear that there is an error right? Was that the intended requirement?

We should be able to distinguish the error from the rule match, so i edited all the components related to that, and also created an error detail page similar to the rule match page, and made the changes needed as well.

**Comment by 3nvi** [comment]
Sorry, I'm a bit lost. The collection has multiple screens, so I can't understand exactly where the the error details page is

**Comment by kostaspap** [comment]
@dimitriszoitas I like it!
