### ISSUE TITLE
Saving a log source redirects to cloud-security sources list

### ISSUE THREAD

**Issue by giorgosp** [panther-labs/panther#1508]
### Describe the bug

I successfully created an s3 log source. However, I got redirected to the cloud-security sources list page instead of the
log sources list page.

Also, when I click on the name of the **s3** source, I get the error shown in the attached screenshot
<img width="1304" alt="Screenshot 2020-09-10 at 2 52 59 PM" src="https://user-images.githubusercontent.com/3627869/92737289-aef86080-f383-11ea-8884-ad73c308a14c.png">

### Environment

How are you deploying or using Panther?

- Panther OSS master@e8fdd91595c568a1c6da270d7f44ada66bd8dd1a
- MacOS 10.15.6
- Browser: Firefox 79.0 64bit

**Comment by 3nvi** [comment]
Yeah, this was noticced in one of the 1.9 PRs

It's fixed here https://github.com/panther-labs/panther/pull/1504
