### ISSUE TITLE
[Feature] Store crash log reporting preference

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#152]
## Introduction
In the front-end, whenever a runtime exception occurs, it would be beneficial for the Panther team to be able to receive an alert for it.

As a user, I want to be able to enable or disable crash reporting. I should be able to opt-in or out of this behavior through a switch in the general settings.

This task involves the creation of the necessary storage entity, in order to store the user's preference.

## Implementation

The proposal is as follows:

A single boolean-like value in the `organization-api` which would have a name similar to `forwardErrorLogs`, `submitErrorLogs`, `allowErrorLogSubmission`, etc.

This value will accept the following values:

`True` - If the user (org) chose to allow crash reporting
`False` - If the user (org) chose to not partake in the reporting
`nil` - If the user hasn't yet submitted yet with a decision (this is the initial value).

This single value will be:

* Returned as part of the `GetOrganization` API endpoint:

```go
GetOrganization    *GetOrganizationInput    `json:"getOrganization"`
```

* Updated as part of the `UpdateOrganization` API endpoint:

```go
UpdateOrganization *UpdateOrganizationInput `json:"updateOrganization"`
```

**Comment by 3nvi** [comment]
Links to #121

**Comment by austinbyers** [comment]
Thanks for the detailed description! Let's only assign one person at a time so there's a clear owner for the implementation

**Comment by 3nvi** [comment]
I honestly didn't know which one should own it & I didn't want to arbitrarily choose. Thus, I figured the best way was to tag people capable of doing it.

Normally, I wouldn't tag anyone, but this was blocking my current work, so I needed it sooner than later

**Comment by 3nvi** [comment]
Blocks #153
