### ISSUE TITLE
Rearrange the Alert filters.

### ISSUE THREAD

**Issue by vorillaz** [panther-labs/panther#1525]
## Description
For alert page filters we need to rearrange the grid in order to fit the new date range picker

## Screenshots
![Screenshot 2020-09-11 at 7 12 43 PM](https://user-images.githubusercontent.com/1022166/92955697-4c2fc380-f46e-11ea-9df3-60c05df8ca7e.png)

## Acceptance Criteria
A mockup that has the alert filters along with a grid that fits a date range picker

**Comment by dimitriszoitas** [comment]
@vorillaz let me know what you think: https://share.goabstract.com/793002a2-a8f4-4947-93e2-bbec6fcecfe0?mode=design&sha=aa6038dc671051d75eb006a36508f278fbb6216d
