### ISSUE TITLE
GatewayAPI client should retry on invocation errors

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#1554]
### Description

In Panther we have created our own client to talk to Gateway API endpoints: https://github.com/panther-labs/panther/blob/master/pkg/gatewayapi/gateway_sig4_client.go

The client will not perform any retries by default. If we fail to invoke a Lambda for any reason (e.g. network glitch) our lambdas will fail. 

### Acceptance Criteria

- The Gateway API client is configured to retry on specific errors that we deem retryable (connection errors, 5xx, etc)

**Comment by austinbyers** [comment]
Keep in mind API Gateway is an HTTP REST endpoint. This is an HTTP client, not an AWS client. We modify the request routing to add the AWS SIG4 signature required for authorization. I'm sure there are ways to configure HTTP retries, it just won't look the same as the AWS retries

**Comment by kostaspap** [comment]
> it just won't look the same as the AWS retries

I am not 100% what this means, but in general I was thinking doing a (configurable) number of retries with exponential backoff + jitter.

**Comment by austinbyers** [comment]
We are very likely to completely remove internal API gateways soon, in which case this will no longer be an issue.

I'll close the issue once we agree as a team on the path forward for internal API architecture next week

**Comment by austinbyers** [comment]
We are removing internal API gateways completely. Closing this issue in favor of #1686
