### ISSUE TITLE
Rules Should Check Existence of Keys Before Access

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#158]
**Describe the bug**
Some rules access event keys that do not exist:
```
2020-02-10T20:22:09.442Z
[ERROR]	2020-02-10T20:22:09.442Z	0169ff1f-8846-52f9-98d9-a9a435ee134f	failed to run rule AWS.S3ServerAccess.InsecureAccess KeyError 'cipherSuite'
2020-02-10T20:22:09.441Z
[ERROR]	2020-02-10T20:22:09.441Z	0169ff1f-8846-52f9-98d9-a9a435ee134f	failed to run rule AWS.S3ServerAccess.AccessError KeyError 'errorCode'
2020-02-10T20:22:09.441Z
[ERROR]	2020-02-10T20:22:09.441Z	0169ff1f-8846-52f9-98d9-a9a435ee134f	failed to run rule AWS.S3ServerAccess.IPWhitelist KeyError 'remoteIP'
```
The issue may only be these rules but all rules should be reviewed.

**To Reproduce**
Run latest master with all log sources, use CW Insights to review error logs.

**Expected behavior**
Rules should not fail with key errors.

**Comment by jacknagz** [comment]
@rleighton Thanks for reporting! We should move this to the [panther-analysis](https://github.com/panther-labs/panther-analysis/issues) repo

**Comment by nhakmiller** [comment]
Migrated to issue 17 in the `panther-analysis` repo.
