### ISSUE TITLE
Raising an exception in a Rule title or dedup function does not fail UI tests

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#1592]
### Describe the bug

If the title or dedup function raises an exception the UI tests do not fail.

### Steps to reproduce
![image](https://user-images.githubusercontent.com/18419762/94006850-79357d80-fd6e-11ea-852b-e901e8c9a8ca.png)

**Comment by rleighton** [comment]
Exceptions in these functions need to create error logs.

**Comment by kostaspap** [comment]
This should be fixed with https://github.com/panther-labs/panther/issues/983

**Comment by giorgosp** [comment]
Actually I will be fixing this separately, it may make it to 1.9 too.
