### ISSUE TITLE
Flaky unit test in log processor

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#1600]
### Describe the bug

[CircleCI is currently failing on the master branch](https://app.circleci.com/pipelines/github/panther-labs/panther/7481/workflows/1bc211d6-d4f0-44bc-a173-e439d0ed62af/jobs/20423):

```
--- FAIL: TestSendDataIfTimeLimitHasBeenReached (1.58s)
    s3_test.go:363: FAIL:	Upload(string,string)
        		at: [s3_test.go:343]
    s3_test.go:363: FAIL: 0 out of 1 expectation(s) were met.
        	The code you are testing needs to make 1 more call(s).
        	at: [s3_test.go:363]
    s3_test.go:364: FAIL:	Publish(string)
        		at: [s3_test.go:344]
    s3_test.go:364: FAIL: 0 out of 1 expectation(s) were met.
        	The code you are testing needs to make 1 more call(s).
        	at: [s3_test.go:364]
FAIL
coverage: 79.5% of statements
FAIL	github.com/panther-labs/panther/internal/log_analysis/log_processor/destinations	2.051s
```

The same error also happened [5 days ago](https://app.circleci.com/pipelines/github/panther-labs/panther/7336/workflows/bbe38256-d5e8-4fa0-bf89-0e4bd05223e7/jobs/19637) and [15 days ago](https://app.circleci.com/pipelines/github/panther-labs/panther/7005/workflows/faef8d88-c91b-472a-929d-9bfb35477174/jobs/17873), but not before that as best I can tell.

### Expected behavior

Unit tests should always pass in any environment.

**Comment by 3nvi** [comment]
I've actually notified the team multiple times in the past as well. It fails every once every 30 PRs I think. That's fully tolerable from my side, but we should indeed check it

**Comment by 3nvi** [comment]
I also saw a failure on Gsuite tests here:

https://app.circleci.com/pipelines/github/panther-labs/panther-enterprise/3471/workflows/c5969288-e6bf-409f-b888-af6282d8489a/jobs/11298

**Comment by alxarch** [comment]
Can we define the scope for this issue to set an estimate? Do we want to investigate the _specific_ test that failed or to go over circleCI history to find all tests that have inconsistent behavior?

**Comment by kostaspap** [comment]
> Can we define the scope for this issue to set an estimate? Do we want to investigate the _specific_ test that failed or to go over circleCI history to find all tests that have inconsistent behavior?

This is a fix for the specific tests

**Comment by austinbyers** [comment]
The scope is limited to this specific test I put in the PR description: `TestSendDataIfTimeLimitHasBeenReached`

And then you can decide whether to include the GSuite test Aggelos mentioned, or create a separate issue to track it if you prefer

**Comment by austinbyers** [comment]
Raising this to a high priority issue - it has forced me to restart CI builds several times this week, which means it's costing a lot of developer time

**Comment by kostaspap** [comment]
> I also saw a failure on Gsuite tests here:
> 
> https://app.circleci.com/pipelines/github/panther-labs/panther-enterprise/3471/workflows/c5969288-e6bf-409f-b888-af6282d8489a/jobs/11298

This issue has now been fixed @3nvi
