### ISSUE TITLE
Default values in policy page filters unclear

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#1610]
### Describe the bug

I found the UI in the Policy filters a bit confusing. It is unclear what the default filter settings are when someone tries to add a filter. See the screenshots I attach below and the accompanying text.

### Steps to reproduce

1. Go to `Cloud Security`
2. Click  on `Policies`
3. Click on `Filter Options`
4. Select `Status` to be `Pass`
You will see a screen like the one below:
![Screen Shot 2020-09-25 at 9.58.57 AM.png](https://images.zenhubusercontent.com/5e4fc81c2009ef65e12fafd8/d864e103-ff21-44bb-ba7c-2339e9cfb53e)

It might seem like a bug in Panther: Someone has selected to display "Passing" policies and it seems like we should be seeing only the "Enabled" ones but we are not... Mystery solved when clicking on "Enabled"
![Screen Shot 2020-09-25 at 9.59.09 AM.png](https://images.zenhubusercontent.com/5e4fc81c2009ef65e12fafd8/380aeea1-c708-4a82-a3e5-61ee76775c75)

I think we should make more clear what the default filter values are when someone selects to filter on something. 

### Expected behavior

A more clear indication of what is the default value of the filters

### Environment

How are you deploying or using Panther?

- Panther version or commit: v1.9.0-RC1

**Comment by dimitriszoitas** [comment]
We should change that filter to:

Display
-All Policies
-Enabled Policies
-Disabled Policies

**Comment by 3nvi** [comment]
Can we make the necessary updates in the mocks?

**Comment by dimitriszoitas** [comment]
@vorillaz whenever you can please make the changes, if you need something from me please let me know
