### ISSUE TITLE
Alert Event JSON Display Should Have Expand/Collapse All Controls

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#1616]
### Describe the ideal solution

2 customers this week asked for expand/collapse all controls for the event display for alerts.

When viewing an alert event there are 2 controls:

 - expand all: when clicked, all items would recursively expand
 - collapse all: when clicked, all top level items would have their children recursively collapsed

The current view remains the default view.

### Describe your use cases

Users want to see all the event data at one time. This avoids unnecessary clicks.

### How frequently would you use such feature

Every second of every minute of every hour of every day.

### Acceptance criteria

When viewing an alert event there are 2 controls:

 - expand all: when clicked, all items would recursively expand
 - collapse all: when clicked, all top level items would have their children recursively collapsed

The current view remains the default view.

### Additional context

If this is easy to implement, I think we should consider doing it sooner than later, so I labeled p1 (feel free to change).

The FE team will decide what this will look like (no requirements) in terms of the controls.

@3nvi said the JSON viewer is a 3rd party widget and may already have controls for expand/collapse all.

**Comment by jacknagz** [comment]
Hey @rleighton could you use the Epic/Story template? Otherwise, the team won't have enough context to understand this feature/change.

**Comment by 3nvi** [comment]
@dimitriszoitas any quick ideas on how this would look?

**Comment by 3nvi** [comment]
> @dimitriszoitas any quick ideas on how this would look?

@dimitriszoitas ping

**Comment by dimitriszoitas** [comment]
I will either add two small buttons to perfom these actions or one that will toggle between expand/collapse all. I will tag you to the relative mockup @3nvi

**Comment by dimitriszoitas** [comment]
@3nvi have a look [here](https://share.goabstract.com/56ae4caa-bebf-4f7d-92ba-7358bf5e4031?mode=design&sha=e4ca5b6511f7d0aa0fc24fbcade6089db34fae18)

**Comment by 3nvi** [comment]
Looks good!
