### ISSUE TITLE
Small UI/UX Bugs/Improvements from v1.9

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#1617]
### Bug 1

**Description:** The Alert Overview Rule Threshold attribute is set to time instead of int (1min vs 1)
**Reproducing**: Open any alert and look at the Rule Threshold
**Expected Behavior**: The Rule Threshold should just be an integer

![Screen Shot 2020-09-26 at 5.00.01 PM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/286680c3-6d03-4aa4-a612-ee6c161ade6e)

### Bug 2

**Description:** The error box presented when attempting to save a rule with failing unit tests cannot be cleared
**Reproducing**: Open the rule editor, make a change to the rule which fails the unit tests, and try to save.
**Expected Behavior**: The error should have an 'x' to clear or should go away after a couple of seconds.

![Screen Shot 2020-09-26 at 5.07.56 PM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/d7e8a390-7cf5-4b9f-a9bb-92faa4a0833a)

### Improvement 1

**Description:** On the log analysis page, there is no specification of what the "last period was" in the alert count box
**Reproducing**: View the total alert count box in the log analysis overview
**Expected Behavior**: We should display what the last period was (3d)

![Screen Shot 2020-09-26 at 5.08.42 PM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/fdfd0be1-617a-44e8-b019-26632e04a1c3)

### Environment

Panther v1.9.0-RC1

**Comment by alexmylonas** [comment]
Extra AC: 
Alerts fetched on Log Overview should be `OPEN` or `TRIAGED`

**Comment by jacknagz** [comment]
@alexmylonas agreed! we shouldn't see any closed alerts

**Comment by alexmylonas** [comment]
> Expected Behavior: We should display what the last period was (3d)

@jacknagz This is a bit more complicated. This card hasn't a fixed period. For example, if users select from date picker to view last hour, in red we'll display the alerts for that timeframe and the last period will be the alerts generated one hour before the selected hour. 

The 3-day period only applies to the initial loading of the page. 

I think displaying those timeframes directly on this element would look bad, should I add a small tooltip?

**Comment by jacknagz** [comment]
@alexmylonas this request isn't applicable anymore since we have a date picker. It was just a stop-gap ask at the time. You can ignore it
