### ISSUE TITLE
Sort by Rule Ordering

### ISSUE THREAD

**Issue by lindsey-w** [panther-labs/panther#1630]
### Describe the bug

Clicking on "Rule" column on the Log Analysis Rules page sorts the rules in order of their RuleID rather than the display name. 

### Steps to reproduce

1. Go to Log Analysis -> Rules 
2. Click on 'Rule" to sort by Rule

### Expected behavior

The rules sorted in order of the display name shown.  

### Environment

How are you deploying or using Panther?

- Panther version or commit: v1.9.0
- OS: macOS 10.15.6
- Browser: Brave v1.13.86

### Screenshots

![image](https://user-images.githubusercontent.com/43453975/94713822-288acb00-0300-11eb-8797-7a2ca1662b22.png)

**Comment by vorillaz** [comment]
Hey @lindsey-w thanks for this one, I have a feature in progress that affects the look and feel of this page, thus it will get resolved in the upcoming days.
