### ISSUE TITLE
Error Reported for Empty Metrics

### ISSUE THREAD

**Issue by lindsey-w** [panther-labs/panther#1648]
### Describe the bug

When querying a metric from a newly deployed panther instance (that has not yet created the specified metric), an error is returned rather than an empty array/object.

### Steps to reproduce

Query the metric api for a metric that has not yet been created in the panther instance.  For example, a freshly deployed panther instance might not have the `alertsCreated` metrics yet, and this api call will return an error:

```
aws lambda invoke --function-name panther-metrics-api --payload '{"GetMetrics":{"fromDate":"2020-08-17T17:50:00Z","toDate":"2020-08-29T17:50:00Z","metricNames":["alertsByRuleID"], "intervalMinutes":14}}' response.json
```

```
% cat response.json | python -mjson.tool
{
    "errorMessage": "Could not find data points for the given metric in the selected time period",
    "errorType": "DoesNotExistError"
}
```

### Expected behavior

An empty array/object returned rather than an error

### Environment

How are you deploying or using Panther?

- Panther version: v1.9.0

### Screenshots

![image](https://user-images.githubusercontent.com/43453975/94846255-b1c00180-03d5-11eb-8f4e-cd60225e5b55.png)

**Comment by 3nvi** [comment]
Yup, I think we've discussed with @nhakmiller about it. Thanks for reporting it @lindsey-w
