### ISSUE TITLE
Support Sophos Central logs

### ISSUE THREAD

**Issue by rynjms** [panther-labs/panther#1661]
### Describe the ideal solution

Panther would parse Sophos Central logs.

### Describe your use cases

Write alerting rules to alert upon events generated by Sophos Central. My organization uses this as endpoint protection on Windows and Mac systems. Alerts can indicate blocked web traffic, malware infections, control failures, DLP activity, and other events of security interest.

### How frequently would you use such feature

I would use this daily.

### Describe alternatives you have considered

None considered.

### References

None.

### Additional context

I can submit a PR for this enhancement, but was following the Panther contribution guidelines to create an issue before doing so. I already have this working in my production Panther deployment, with some basic alerting rules set up.

**Comment by kostaspap** [comment]
Resolved with https://github.com/panther-labs/panther/pull/1770
