### ISSUE TITLE
Include Docs for Adding Sources Wizard

### ISSUE THREAD

**Issue by wey-chiang** [panther-labs/panther#1668]
### Describe the ideal solution

On Step 2 `Setup IAM Roles` there should be a link to the docs i.e. Check out the [documentation](https://docs.runpanther.io/cloud-security/setup#configure-real-time-monitoring) for more information.

Ideally, the version of the docs linked should be the same version as the Panther instance

**Comment by 3nvi** [comment]
Closing in favor of https://github.com/panther-labs/panther-enterprise/issues/1384
