### ISSUE TITLE
Delivery marked a successful even though it has failed

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#1684]
### Describe the bug

An alert failed to deliver to a destination. However, the UI was reporting the delivery as successful

### Steps to reproduce

1. Create more than one destinations. Make sure that one destination is misconfigured
2. Trigger an alert
3. We will report that delivery was successful, however a destination has failed

### Expected behavior

We should report that delivery was not successful

### Environment

How are you deploying or using Panther?

- Panther version or commit: 1.10 testing

### Screenshots

![Screen Shot 2020-10-07 at 3.58.15 PM.png](https://images.zenhubusercontent.com/5e4fc81c2009ef65e12fafd8/4ca2a4e0-ec7d-474c-a80d-79333e09646a)

**Comment by 3nvi** [comment]
Currently, we are evaluating the **latest** delivery in order to determine if the delivery was successful or not. That's why you see this

**Comment by s0l0ist** [comment]
I think @kostaspap's finding relates to having multiple destinations that are all passing, but one that is failing. This section should group by valid destinations (not ones that have been deleted) and determine if all of them are successful. If one destination's history is actively failing, then it should report the entire delivery has failed to grab attention.

**Comment by s0l0ist** [comment]
Moving to a `p1` as this shouldn't be a blocker IMO.
