### ISSUE TITLE
Failing to upload new rules from Panther CLI tool

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#1685]
### Describe the bug

Getting an error when uploading Panther rules from Panther CLI. 

### Steps to reproduce

1. Download latest version of rules from OSS repo
2. Download the latest analysis tool
3. Run `panther_analysis_tool upload`

```
[INFO]: Uploading pack to Panther
[WARNING]: Failed to upload to Panther
	status code: 500
	error message:
```

### Expected behavior

Rules/Policies should be uploaded

### Environment

How are you deploying or using Panther?

- Panther version or commit: v1.8.0-270-ga0f0f931
- Panther Analysis Tool: 0.3.5

**Comment by nhakmiller** [comment]
I was able to verify this. I've determined it's not an issue with `panther` or the `panther_analysis_tool`, but in fact an issue with master in the `panther-analysis` repo.

I've opened this https://github.com/panther-labs/panther-analysis/pull/121 PR in `panther-analysis` to resolve the issue, and I've opened this https://github.com/panther-labs/panther_analysis_tool/issues/54 issue in the `panther_analysis_repo` to add more validation to the `panther_analysis_tool` before attempting to zip/upload analysis.

**Comment by nhakmiller** [comment]
Closing this issue since it's not a problem with `panther`. Lets keep further discussion in either the issue or PR linked above.
