### ISSUE TITLE
Product Analytics doesn't let you save

### ISSUE THREAD

**Issue by s0l0ist** [panther-labs/panther#1716]
### Describe the bug

By default, the "product analytics" modal will not let you save the new settings. Also `There a couple` => `There are a couple`

Toggling the toggle also appears to toggle the buttons `disabled` functionality. The combination which will allow you to proceed will be to set it to `OFF` and then the `save` button will be enabled for you to click. Obviously, this is not the intended behavior. It should allow the user to save the preference regardless of the toggle.

### Steps to reproduce

1. Deploy a panther upgrade from v1.9.0 -> v1.10.0
2. Refresh the browser and see the new modal pop up
3. Try to click save (the button is disabled)

### Expected behavior

The `save` button should not ever be disabled.

### Environment

- v1.10.0-RC1

### Screenshots

<img width="562" alt="Screen Shot 2020-10-10 at 10 01 57 AM" src="https://user-images.githubusercontent.com/3663107/95658513-93968780-0ae0-11eb-947e-eebcc5a6694d.png">

**Comment by alexmylonas** [comment]
I am closing this since it was not affecting OSS
