### ISSUE TITLE
Design for Unified Detections

### ISSUE THREAD

**Issue by dimitriszoitas** [panther-labs/panther#1719]
### Description

As the number of features grows within Panther, there has been an increase in similar capabilities, such as alerting, integrations, and detections. 

### Acceptance Criteria

- Users can click into a “Detection” on the main menu to list the currently configured ones or create a new one
- When creating new “Detections”, users can step through a wizard, select the “type”, and then write/test as normal
- The type would be either Policy, Rule, or Batch / Each type would have a slightly different set of options
- Users can opt-out from collection at any time
- Default "Sort by" field should be "by last modified"

**Comment by dimitriszoitas** [comment]
@jacknagz  please have a look at these: 

1. [Overview Page](https://share.goabstract.com/da7cbfe6-05d5-4356-848b-33612fccb3be)
2. [Detections flow (with adding new rule)](https://share.goabstract.com/45490f6d-24ed-4954-bed5-a6fb0fef8b38)

**Comment by jacknagz** [comment]
Left some comments!

**Comment by dimitriszoitas** [comment]
@mattthetraveler @jacknagz please review the following collections and leave me your feedback so we can wrap up this issue and continue with integrations:

[Detections Overview](https://share.goabstract.com/051a4b46-1012-4c9f-af5a-7057dc7ac877)
[Detections - Rule Flows](https://share.goabstract.com/a2f17ed6-f883-4078-8b87-48c32c2a94c0)
[Detections - Policies Flows](https://share.goabstract.com/bba63b5f-7b47-46c2-8895-4c5fa9c3c155)

Also, if you can please let me know what fields the create/edit form of the scheduled queries will have so I can design that flow as well.

Thank you

**Comment by mattthetraveler** [comment]
Left some comments @dimitriszoitas !

**Comment by jacknagz** [comment]
@dimitriszoitas @mattthetraveler what's the status here? Are we good?

**Comment by jacknagz** [comment]
@dimitriszoitas for the scheduled rules, we'll have the following settings:

- Scheduled Query Name (as the input, similar to log or resource type)
- Frequency
- Timeout

@rleighton anything I missed?

**Comment by mattthetraveler** [comment]
@jacknagz for overview, rule, and policies we're good. Just open on Scheduled Queries. The delivery of this will likely coincide with delivering scheduled queries.

**Comment by jacknagz** [comment]
@mattthetraveler understood, but we can get the designs done prior to the feature shipping

**Comment by dimitriszoitas** [comment]
I have added the Scheduled Rule flow [here](https://share.goabstract.com/43193931-0daf-4ba5-9087-e05ee095cb76)

Waiting for feedback :)

Thank you!

**Comment by jacknagz** [comment]
Left some comments - I think we are close

**Comment by dimitriszoitas** [comment]
@mattthetraveler I think I've revised and resolved every comment, so if there is nothing new let me know If I can close this issue!

**Comment by mattthetraveler** [comment]
Agreed, closing this!
