### ISSUE TITLE
Rules API should include Rule threshold in Rule Summary response

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#1726]
### Description

Rules API should include Rule threshold in Rule Summary response. See comment https://github.com/panther-labs/panther/pull/1710

### Related Services

panther-analysis-api

### Acceptance Criteria

- Rules API should include Rule threshold in Rule Summary response.

**Comment by austinbyers** [comment]
There is no longer a "rule summary", but the analysis-api `ListRules` call does indeed return the threshold (and in fact every field). This was probably fixed by #2036
