### ISSUE TITLE
Dynamically Setting Alert Fields

### ISSUE THREAD

**Issue by wey-chiang** [panther-labs/panther#1729]
### Description

The gist is allowing rules to specify customized severity, destinations, reference, runbook, etc. dynamically in alerts similar to how custom titles are allowed.

### RFC

https://github.com/panther-labs/panther-enterprise/tree/master/designs/security/dynamic-alert-fields

Actual PR here:
https://github.com/panther-labs/panther/pull/2106

### Acceptance Criteria

- Users can use python to dynamically set the following fields: description, reference, severity, runbook, destination override and summary attributes
- All custom fields should be stored in DDB with the Rule
- Order of precedence should be: rule default severity < rule static severity < rule static destination override < dynamic severity < dynamic destination override

**Comment by wey-chiang** [comment]
Merged earlier
https://github.com/panther-labs/panther/pull/2106

This giant PR included a lot of tech debt that was cleaned up

**Comment by mattthetraveler** [comment]
reopening this to capture remaining FE work

**Comment by wey-chiang** [comment]
Just closed out #2245 which should cover the remaining BE work required to support the FE changes

**Comment by jacknagz** [comment]
@wey-chiang @mattthetraveler which milestone/release are we targeting for here?

**Comment by wey-chiang** [comment]
> which milestone/release are we targeting for here?

@jacknagz The BE work has been merged and was silently released in v1.14

There still remains FE work to be done -- likely targeting the v1.15 release

**Comment by mattthetraveler** [comment]
Correct, FE is being worked on currently, on target for 1.15. See issue below
https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther/2166

**Comment by jacknagz** [comment]
@wey-chiang can you please close this if it's complete? thank you!!
