### ISSUE TITLE
QR Code is non compliant

### ISSUE THREAD

**Issue by s0l0ist** [panther-labs/panther#1740]
### Describe the bug

MFA QR Code is non-standard in the respect that the 3 large registration squares are missing a single pixel of white space around them and the centers are not solid black. While this might seem insignificant, it is part of the specification.
Additionally, the fourth checkbit registration mark is similarly non-standard.

### Steps to reproduce

1. Go through the MFA onboarding process

### Expected behavior

QR Code should comply with the spec

### Environment

How are you deploying or using Panther?

- latest master

### Additional context

This is found in the `SignIn` page after a successful username/password login

### Notes

We are not sure if this is valid or not and we should investigate it further. This issue might require to be closed, if the findings deem that the QR code complies with the spec. 

The related library used is [`qrcode.react`](https://www.npmjs.com/package/qrcode.react)

**Comment by 3nvi** [comment]
@s0l0ist  can we get a bit more info on that? Can you link the spec along with a SS?

**Comment by s0l0ist** [comment]
I don't have a link. This was direct feedback from an OSS user I believe on slack.
