### ISSUE TITLE
Universal Data Model

### ISSUE THREAD

**Issue by lindsey-w** [panther-labs/panther#1743]
### Description

The main goal of this is to simplify the rules logic by (1) normalizing data (2) narrow down to a core group of detections enabled by default.

Benefits Include:
- Simplified rule logic.
- Reduction of code duplication by reusing logic for event types that might use different field names.
- Help prevent alert fatigue right out of the gate by only enabling a core, high-fidelity set of rules out of the box. This default rule set might be grouped into a pack, which is discussed in this RFC.

### RFC

[RFC Pull Request](https://github.com/panther-labs/panther-enterprise/pull/966)

### Designs

WIP

### Acceptance Criteria

WIP

- Users can add new mappings for log type -> common schema/data model in the UI
- Users can write detections based using common schema/data model
- A default of set of rules is developed, using common schema/data model
- When deploying panther, a limited set of rules are enabled by default
- `PAT` can run tests against globals

**Comment by lindsey-w** [comment]
> * When deploying panther, a limited set of rules are enabled by default

Don't know if this should be in this epic or in [this one](https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther/1728)

**Comment by mattthetraveler** [comment]
Hi @lindsey-w is this on track for 1.14?

**Comment by lindsey-w** [comment]
CLI support is on track for 1.14. It looks like the design task for the frontend work is done / waiting for final approval.
