### ISSUE TITLE
Implement Rule Details "Matches" section

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1747]
### Description

In this task, the rule details page is already  split into  tabs and the task is to make sure that the "Rule Matches" tab works correctly. Specifically, this task will include the effort of moving the Alert Cards into their dedicated tab and adding the necessary filters

A "Rule Match" is essentially a typical Alert that didn't have python runtime errors when it ran. If it did, it would have been a "Rule Error"

### Related Services

Frontend - Rule Details page

### Designs

https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/70fbde80-1195-4df9-a583-6962f57e3e19/commits/ba31ffa546856d449e2a15fd451d1b3da8c4db9d/files/c2bbc1a8-4778-4cd6-93a5-4630d8868201/layers/2707278E-4CD9-4F3C-919E-1E3BCC4A0402

### Acceptance Criteria

- Move the Alert Cards from below the tabber, to within the "Alerts" tab
- Make sure to lazy load the tab's content, as well as API query that fetches those alerts
- Show a loading spinner while data is loading
- Show an message if the filtering results into no data (i.e. "No data found for your filters')
- Show an illustration if no rule matches exist at all
- Make sure to only include non-error alerts (i.e. don't include rule errors  in this tab)
- Add a filters section for the alert cards, mimicking the one found in the List Alerts Page.  Contrary to the designs, the filters present in this page should be:
  - Alert title filter 
  - Status filter (accept multiple values)
  - Filter by max events
  - Filter by min events
- Add a sorting option, allowing the alerts to be sorted by newest/oldest based on their creation time

### Notes

- Whether the filters should be "mapped" to the URL is optional. Contrary to the list alerts page, the filters <-> URL mapping is not needed here. The developer should choose whatever makes it easier for them to implement. Both are acceptable

**Comment by 3nvi** [comment]
@kostaspap we can't know the total number of rule matches & rule errors for a particular rule, right? I think it's a dynamoDB limitation

**Comment by kostaspap** [comment]
> @kostaspap we can't know the total number of rule matches & rule errors for a particular rule, right? I think it's a dynamoDB limitation

Correct. To get this number we would have to scan the table, get back all results and count them (there is no `count(*)` function in DDB). 
It is doable but requires some work since we would need to store this information separate and generally adds a lot of complexity. Definitely not available now.
