### ISSUE TITLE
Alerts API should allow filtering based on Alert type (rule error or rule match)

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#1749]
### Description

Alerts API should allow filtering based on Alert type (rule error or rule match)

### Related Services

panther-alerts-api

### Acceptance Criteria

A concise list of specific user stories that qualify this story as done.

- Alerts API supports an "Alert type" filter that allows retrieving all alerts that are related to rule errors
- Alerts API supports an "Alert type" filter that allows retrieving all alerts that are related to rule errors for a specific Rule ID

**Comment by s0l0ist** [comment]
I was thinking of this as well, but for determining if the alert came from a rule, policy, or scheduled query, etc. 

I think we can make a column holding an enum in the alerts table  similar to how we added alert statuses (open, closed, triaged, resolved).

The caveat is that we should perform a migration for values that don't exist or just treat an empty value as one of the "types" (rule).

**Comment by kostaspap** [comment]
> I was thinking of this as well, but for determining if the alert came from a rule, policy, or scheduled query, etc.
> 
> I think we can make a column holding an enum in the alerts table similar to how we added alert statuses (open, closed, triaged, resolved).
> 
> The caveat is that we should perform a migration for values that don't exist or just treat an empty value as one of the "types" (rule).

I don't think we need migration necessarily. "empty" means rule, and whatever we do from now on can have a title :)
