### ISSUE TITLE
Redesign Rule Creation & Edit page

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1752]
### Description

Currently our RuleForm is a single big page of data that makes it hard for someone to add what needs to add, as well as have a good overview of the entire screen.

This ticket makes sure to redesign the form (and essentially the create/edit pages) in order  to split the content into 2 tabs:

- Settings
- Functions & Tests

### Related Services

Rule Creation & Rule Edit page

### Designs

[Settings Tab](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/70fbde80-1195-4df9-a583-6962f57e3e19/commits/45ee05f75334fe2a184c7a8f9380b197d3d74146/files/c2bbc1a8-4778-4cd6-93a5-4630d8868201/layers/394C5577-2F80-42E5-8FB2-4AF7DB6AF2ED)

[Functions & Tests Tab](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/70fbde80-1195-4df9-a583-6962f57e3e19/commits/3a182e15ef096837206a0f428c01137eaa390841/files/c2bbc1a8-4778-4cd6-93a5-4630d8868201/layers/139A08A0-9828-485A-A78B-4C48B8BF00CE)

### Acceptance Criteria

- Move Save & Cancel button in the breadcrumbs
- Change the UI of the Save & Cancel Button to align with the designs
- Split the form's content into 2  tabs (no need to map each tab to a URL parameter. It's **fully optional**)
- Lazy load the content of each form (check if this creates issues with Formik submissions)
- Add a `*` to the required fields
- Split the UI accordingly
- Validate  that tests still pass
- Write a single Integration test for the new tabbed-form, as well as snacpshot tests for each tab
- Remove error alert UI and replace with an error snackbar (for backend errors)

**Comment by s0l0ist** [comment]
punted to v1.14
