### ISSUE TITLE
Make the AWS Event Processor Partition Aware

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#176]
## Introduction

The `aws-event-processor` used for processing CloudTrail logs for the Cloud Security suite assumes the partition is `aws` (as opposed to `cn` or `gov`) in several places. The `aws-event-processor` should be able to determine what the actual partition is based on the log and reflect that.

## Implementation

Wherever the `aws-event-processor` creates an ARN manually and sets the partition to `aws`, it should instead look up the partition based on the log and set it to that.

Alternatively, since we will probably never support cross partition processing, we could have the partition be an environment variable in the lambda set at deploy time. This might be more performant as it replaces a worst case of one lookup for every log with one lookup per lambda invocation, saving potentially thousands to tens of thousands of gzip `.Get` operations per lambda invocation.

A third implementation suggestion from @austinbyers:

We could use the AWS_REGION environment variable in the Lambda function to figure out what the partition should be.

**Comment by austinbyers** [comment]
Just passing the AWS partition as an environment variable seems the simplest, but that assumes CloudTrail events are not being sent from other partitions, which is I think a reasonable assumption

**Comment by nhakmiller** [comment]
Closing this since I don't see us working on it within the next two quarters. If & when we need to support the cn or gov partitions, there will be a lot of cutover work anyways which can encapsulate this issue.
