### ISSUE TITLE
Docs - aws-vault failure due to missing MFA 

### ISSUE THREAD

**Issue by gavinelder** [panther-labs/panther#178]
**Describe the bug**

The panther deploy will fail using `aws-vault` if MFA is not enabled for the credentials, this is not an issue with Panther but a piece of information to be added to the documentation. 

**To Reproduce**
Steps to reproduce the behaviour:

```AWS_REGION=us-east-1 aws-vault exec panther-deployer -- mage deploy```

The deploy will fail with a failure around `InvalidClientTokenId` 

**Resolution** 

Enable MFA device.

**Comment by austinbyers** [comment]
I was able to deploy Panther from an IAM user with no MFA:

1. Create an admin IAM user with access keys (no MFA)
1. `aws-vault --version`  => v5.2.0
1. `aws-vault add panther-deployer`
1. `aws-vault exec panther-deployer -- aws s3 ls` - see buckets in the Panther account
1. `AWS_REGION=us-east-1 aws-vault exec testdev -- mage deploy` - succeeded

What's your `~/.aws/config` file look like? What version of aws-vault are you using? What Panther version/commit did you deploy from?

**Comment by austinbyers** [comment]
This is for using an IAM user directly, are you trying to use an assumed IAM role without MFA?

**Comment by gavinelder** [comment]
Hey @austinbyers 

1. no aws config for this ( our tooling does this dynamically 
2. `go get github.com/99designs/aws-vault` 
3. create deploy credentials 
4. destroy all CF stacks 
5. run `AWS_REGION=us-east-1 aws-vault exec panther-deployer -- mage deploy` (where panther-deployer is a iam user created with admin credentials) 
 
fails on deploying `panther-app` 

I deleted the stack but will attempt a deploy in another region this now to get exact error in the stack.

**Comment by austinbyers** [comment]
Oh, the error is in CloudFormation, I do see it:

![Screen Shot 2020-02-12 at 3 58 30 PM](https://user-images.githubusercontent.com/3608925/74388558-8938b800-4db0-11ea-915a-dc36fff5d568.png)

We don't actually use the gateway logging role yet, we could remove that. I'll try that, but I suspect it might be a problem for any IAM role created by CloudFormation with aws-vault? Strange

**Comment by austinbyers** [comment]
Confirmed the following:

- Deployment works with an access key from an admin user (export AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY)
- Deployment does NOT work with `aws-vault` when using the same admin user access keys
    - The problem is not with the `GatewayLoggingRole` specifically, it's any IAM role
