### ISSUE TITLE
Bug - Interaction with the role drop down causes invite failure.

### ISSUE THREAD

**Issue by gavinelder** [panther-labs/panther#179]
**Describe the bug**
Interaction with the drop-down does not cause failure.

**To Reproduce**

#### Failure case 

1. Go to 'Invite user '
2. fill out all necessary details
3. select the role drop down and select admin
4. click invite  

#### Success case

1. Go to 'Invite user '
2. fill out all necessary details
3. Don't touch role drop down
4. click invite  

**Expected behavior**

Interaction with the drop-down does not cause failure.

**Screenshots**

![image](https://user-images.githubusercontent.com/1226100/74388692-f28dea80-4df3-11ea-9215-b9955a5ce96e.png)

**Environment**
How are you deploying or using Panther?

- Panther version or commit: [current master]
- OS: [e.g. MacOS 10.15.3 ]
- Browser: [Chrome]

**Additional context**

**Comment by austinbyers** [comment]
Thanks for the report! We were able to reproduce it, the team is looking at it and we should have a fix by the end of the week

**Comment by austinbyers** [comment]
We confirmed it's still possible to invite other users as long as the dropdown isn't touched, like you said.

@3nvi this is just a bug when interacting with the dropdown

**Comment by nhakmiller** [comment]
Confirmed the bug on both tagged release v0.2.0 and on master at commit `2cc1100`.

**Comment by 3nvi** [comment]
Yup, seems like an easy fix
