### ISSUE TITLE
Policy-based Alerts

### ISSUE THREAD

**Issue by s0l0ist** [panther-labs/panther#1809]
### Description

The alerting pipeline is separated out into two different paths:
- For rules
- For policies

However, there are stages in the pipeline we'd like to unify. A good first step is to persist alert's generated by policies into the same DDB table where the other alerts are currently stored.

### Related Services

Alert Forwarder (policy)
- Needs to also send to DDB when dispatching to destinations

### Designs

N/A

### Acceptance Criteria

- An alert is triggered via a policy
- User can optionally see the alert delivered to a destination
- User can visit the list alert's page and see a persisted alert that was triggered by a policy
- User can see Resource Type in policy failure alert
- User can see Source in policy failure alert

**Comment by mattthetraveler** [comment]
Hey @s0l0ist following up from our call, adding these two requests for this epic:

- Ability to present Resource Type in failed policy alert
- Ability to present Source in failed policy alert

For visual reference, take a look at Jim's latest mock up [here](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/df9d59c8-eeb1-452d-a5f5-3712b64010be/commits/aabcb6e59dbca9d9c94a2611f1b681e20d4205d3/files/29396687-8ca0-4c55-a4c7-2399489f10a9/layers/9DF07065-5715-406A-9D19-E731CD57539D?mode=design&sha=aabcb6e59dbca9d9c94a2611f1b681e20d4205d3). Will update the acceptance criteria accordingly.

**Comment by mattthetraveler** [comment]
FYI @s0l0ist I renamed this to policy-based alerts to more accurately represent the output of this work
