### ISSUE TITLE
Log Analysis Overview: Selecting a logtype messes up other options

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1827]
### Describe the bug

On the Log Analysis Overview page, there are several configurable options to change how the graphs look. There is at least the interval option, time frame option, and linear/logarithmic scale option. When you set any of these away from the default value, then select a specific log type on one of the graphs, it silently/invisibly resets the configurable options.

### Steps to reproduce

1. Go to Log Analysis overview page (the 1.11  release environment should work)
1. On the `Alert Severity` graph, select the `Logarithmic` option. The graph should be re-drawn in a logarithmic scale
1. On the left hand side of the graph, select just one severity (that has values). The graph will be re-drawn with just the values of the selected severity, but now in a linear scale. The `Logarithmic` setting will still appear to be selected
1. Select the `Linear` button again. Nothing will happen because the graph is already in a linear scale.
1. Select the `Logarithmic` button again. Now the graph will be re-drawn in a logarithmic scale.

This same behavior applies to the interval and time frame options, and applies whenever you select a single element from the line chart. That is, if you are looking at the events by log type graph with all log types selected, set a non-default interval or timeframe (or both), then select just one log type, then when the graph is re-drawn it will again have the default interval and timeframes set despite the page showing your non-default interval and timeframes.

### Expected behavior

Either:
- Selecting the log type/severity does not reset the other options (preferred)
- Or selecting the log type/severity does reset the other options, and the page is updated to reflect this

### Environment

How are you deploying or using Panther?

- Panther version v1.11 candidate release

### Screenshots

These screenshots are a bit awkward because most of the values go away in the logarithmic scale, but notice how in the second screenshot all the alerts are selected and the scale is logarithmic and in the third screenshot only the `Info` severity alerts are selected and the scale is linear, despite the graph clearly showing the `Logarithmic` button selected.

<img width="886" alt="Screen Shot 2020-10-21 at 9 30 12 AM" src="https://user-images.githubusercontent.com/49166439/96750625-04f7f500-1381-11eb-9f16-b5dbeafbee76.png">
<img width="885" alt="Screen Shot 2020-10-21 at 9 30 31 AM" src="https://user-images.githubusercontent.com/49166439/96750633-088b7c00-1381-11eb-85f6-a0c2bf0714de.png">
<img width="886" alt="Screen Shot 2020-10-21 at 9 31 50 AM" src="https://user-images.githubusercontent.com/49166439/96750644-0b866c80-1381-11eb-9655-cc03396b476f.png">

**Comment by alexmylonas** [comment]
I could replicated & resolve issue mentioned, fix here -> #1873 

If you some1 else can also verify functionality works as intended with the fix, i would appreciate it!

**Comment by 3nvi** [comment]
> I could replicated & resolve both issues mentioned, fix here -> #1873
> 
> If you some1 else can also verify functionality works as intended with the fix, i would appreciate it!

Will do
