### ISSUE TITLE
Log Analysis Overview - UX - Graph axis units

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1828]
### Describe the bug

On the data latency graph, very large values are displayed as seconds. 10,000,000,000 seconds is not a super useful number, it would be preferable to have this in hours or even days as appropriate.

### Steps to reproduce

1. Go to Log Analysis Overview
1. Select a timeframe on the data latency graph that shows results with very large numbers (in the 1.11  release test environment, there is a good example on October 12th)
1. Observe massive scale on the y-axis

### Ideal behavior

The units would automatically adjust to larger units to conveniently display the value.

### Environment

How are you deploying or using Panther?

- Panther version 1.11 release candidate

### Screenshots

<img width="1217" alt="Screen Shot 2020-10-21 at 9 44 03 AM" src="https://user-images.githubusercontent.com/49166439/96751393-f78f3a80-1381-11eb-8d31-1e80270d67a6.png">

**Comment by nhakmiller** [comment]
Capturing some context from the confluence comments before deleting them:

```
Dimitris Zoitas
@Aggelos Arvanitakis do you know if we could change the y axis depending on the content of the graph dynamically?

------

Aggelos Arvanitakis
Perhaps according to https://echarts.apache.org/en/option.html#yAxis.type

If that won’t work, perhaps we’d need to do it with a custom solution. 

@Alex Mylonas what do you think?

------

Alex Mylonas
The more accurate description of this, is do we have the ability to change the axis label conditionally.

Which we do but we need to extend our API I think, not a big problem.

Should I open an issue for this?
```

**Comment by 3nvi** [comment]
@alexmylonas can we do a research and follow up on this within the next few days to see if there's an easy way to do it?

**Comment by alexmylonas** [comment]
I think this should be easy to implement. The scale will remain big, meaning it will start from 0 sec to 10,000,000,000sec because that's the actual value of the data.

But we can transform axis label to be transformed to hours or even days depending on the value.

What concerns me is how this value (10,000,000,000sec) can be returned by the API for any given timeframe and interval? I am guessing we don't take so much to process data.

**Comment by nhakmiller** [comment]
This particular value is a bit of an anomaly, because we testing with some hand crafted logs that created this number. But in general, logs that are a few hours up to a few days late may have thousands/tens of thousands of seconds of latency (as this latency includes late delivery times).
