### ISSUE TITLE
Log Analysis Overview: Alert title clickable area extends across the entire page

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1829]
### Describe the bug

In the Recent Alerts and High Severity Alerts tables, the alert title is clickable. This takes you directly to the alert. However, the clickable area of the alert title extends across the entire page. This makes it very easy to accidentally click through to the alert when scrolling the list or trying to select the triage options.

### Steps to reproduce

1. Go to the Log Analysis Overview page
2. Scroll down to the Recent Alerts section
3. Hover your mouse over the alert title, the cursor should change to indicate it is clickable
4. Slide your mouse cursor all the way to the right of the page, the clickable cursor should stay
5. Click on the far right side of the page, you'll get redirected to the alert details page

### Expected behavior

Only the actual title text is clickable.

### Environment

How are you deploying or using Panther?

- Panther version 1.11 release candidate

### Screenshots

<img width="1199" alt="Screen Shot 2020-10-21 at 9 48 19 AM" src="https://user-images.githubusercontent.com/49166439/96752587-851f5a00-1383-11eb-9f09-84352cfe1bfd.png">

**Comment by 3nvi** [comment]
Yeah observed this as well. This is super minor and we can easily handle it in the next batch of work
