### ISSUE TITLE
Log Analysis Rules: Enable filter isn't counted as one of the enabled filters

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1830]
### Describe the bug

When you enable filters on this page, there is a little number indicating how many filters are in use. Setting the `Enabled` filter doesn't increment this number. This can lead to confusion about how many filters are actually enabled, causing a user to possibly believe that one of the filters isn't being applied correctly.

### Steps to reproduce

1. Go to Log Analysis Rules
1. Set some number of filters besides the `Enabled` filter. Observe the counter increment
1. Set the `Enabled` filter. Observe the counter does not increment

### Expected behavior

If there is a filter counter, it should correctly represent the number of filters being applied.

During the discussion of this finding, we agreed that really just a "filters are set/not set" indicator is probably sufficient. So if fixing the counter is complicated, we could instead just have some "filters are on"/"filters are off" indicator.

### Environment

How are you deploying or using Panther?

- Panther version 1.11 release candidate

### Screenshots

<img width="1000" alt="filter_options_counter" src="https://user-images.githubusercontent.com/49166439/96753003-18f12600-1384-11eb-8f27-9b901d075d6b.png">

**Comment by 3nvi** [comment]
Verified that with the latest changes that have been applied to 1.11, this is not an issue anymore
