### ISSUE TITLE
Log Analysis Rules - UX - Rules details card seems squashed

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1831]
### Describe the bug

I'm not sure if bug is the right label, and maybe we should have caught this during the design phase, but on the rules page the rules cards have all the info squashed into the bottom right of the card. This is different from the alerts card on the alerts page, where the data seems to more naturally fill the space. See attached screenshots for referece.

### Steps to reproduce

1. Go to Log Analysis Rules
1. Observe the rules cards. The threshold, time created, enabled, and severity are all aggregated into the bottom right of the card. The log type and title are on the far left. There is a large empty space between them.
1. Go to Log Analysis Alerts
1. Observe the alerts cards. On each card, much more of the horizontal space is being consumed so the cards feel more full.

### Ideal behavior

Rules cards take more advantage of the available space.

### Environment

How are you deploying or using Panther?

- Panther version v1.11 release candidate

### Additional context

While discussing the layout, we considered the possibility that this space is being reserved for future use (e.g. some destinations information or similar). If so, we can probably just disregard this issue.

### Screenshots

<img width="1172" alt="Screen Shot 2020-10-21 at 11 55 08 AM" src="https://user-images.githubusercontent.com/49166439/96769706-52ca2880-1394-11eb-8288-e3b5adc59c19.png">

<img width="1169" alt="Screen Shot 2020-10-21 at 11 55 18 AM" src="https://user-images.githubusercontent.com/49166439/96769721-58c00980-1394-11eb-8448-f1bedfe5ee34.png">

**Comment by 3nvi** [comment]
This is because a PR sync was `closed` instead of `merged` which prompted issues. It has since been fixed (see SS)

<img width="1582" alt="Screen Shot 2020-10-22 at 11 57 21 AM" src="https://user-images.githubusercontent.com/10436045/96849023-c7b56500-145d-11eb-985a-40973327892f.png">
