### ISSUE TITLE
Log Analysis Alerts - Inconsistent time zone consideration for default options

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1832]
### Describe the bug

On the Log Analysis Alerts page, the calendar allows you pick a start & stop date & time. This time is in UTC. There has been lots of discussion about using the users time zone vs. UTC, but that's not what this bug report is about.

Instead of using the `Custom` time picker, you can use a time preset. This includes `Last 24 Hours`, `Last Week`, etc. If you select one of these presets, then the time that gets input into the time picker ends at the current time in the users timezone, not at the current time in UTC. For example, say it is 1400 UTC on October 21st.  A particular user is in UTC-7, so their clock says 0700. They open the time picker and click the `Last 24 hours` preset. The time picker then sets the start date to 0700 on October 20th and the end date to 0700 on October 21st (based presumably on the users clock). But these times are getting interpreted by the system as UTC times, which means the window is actually 7 hours behind.

### Steps to reproduce

1. Ensure your system clock is offset from UTC
1. Go to Log Analysis Alerts
1. Open the time picker
1. Select the `Last 24 hours` preset
1. Observe the start/end time of the time picker are automatically set based on your system time, not based on UTC time
1. Assuming you are behind UTC (e.g. UTC-X), any alerts that arrived in say the last five minutes will NOT be displayed despite having occurred in the last 24 hours

### Expected behavior

The time picker presets automatically preset to UTC times if the input form is expecting times in UTC.

### Environment

How are you deploying or using Panther?

- Panther version 1.11 release candidate

### Screenshots

Observe my system clock (on UTC-7) in the top right. Upon clicking `Last 24 hours`,  the timeframe is set to 24 hours before my system clock. But because the form is expecting UTC  time,  this means I will not see any alerts that happened in the last 7  hours despite having selected the `Last 24 hours` preset.

<img width="749" alt="Screen Shot 2020-10-21 at 12 09 47 PM" src="https://user-images.githubusercontent.com/49166439/96771305-5494eb80-1396-11eb-8f73-55b3ade25b27.png">

**Comment by nhakmiller** [comment]
This also applies to the time picker on the Data Analytics Indicator Search. Presumably, it applies to everywhere this time picker is in use.

**Comment by 3nvi** [comment]
> This also applies to the time picker on the Data Analytics Indicator Search. Presumably, it applies to everywhere this time picker is in use.

Yup, it does

**Comment by 3nvi** [comment]
@vorillaz How do you envision combatting this? Should we add a prop for `timezone` and have all the selections converted according to the `timezone` that the user has added? This is a bit weird, since the user will select a time and we'll convert it in the input (which might seem counter-intuitive). At the same time, a user might select "Last 24 Hours" and we'll modify it to UTC which may confuse him/her as well.

Another options is to just add an apollo link (or some sort of pre-flight middleware) to convert all datetime inputs to UTC. That will leave `DateRangePicker` pristine. I feel this might be the best option here, but I need your input

**Comment by vorillaz** [comment]
I don't think that's the case. All values under the hood should get converted to UTC. 
We should not expose any timezone settings, IMHO.

My suggestion would be as follows:
- Sniff user's timezone, in Nick's case it would be UTC-7
- Grab the selected timeframe (eg 24 hours in UTC)
- Add or subtract the Timezone frame and send back to the server.

This should be a middleware between the time picker and the call site, the component should not be aware of any timezone settings.

**Comment by 3nvi** [comment]
I fully agree.

> I don't think that's the case. All values under the hood should get converted to UTC.
> We should not expose any timezone settings, IMHO.
> 
> My suggestion would be as follows:
> 
> * Sniff user's timezone, in Nick's case it would be UTC-7
> * Grab the selected timeframe (eg 24 hours in UTC)
> * Add or subtract the Timezone frame and send back to the server.
> 
> This should be a middleware between the time picker and the call site, the component should not be aware of any timezone settings.

I fully agree. I'll try and see if I can squeeze it in 1.12 (since this is pretty important).
