### ISSUE TITLE
Log Analysis Alerts - Time picker has no default values

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1833]
### Describe the bug

When you first load the Log Analysis Alerts page, the time picker has an empty start/stop date. If this is expected behavior (say because the default is to allow an infinite time range) then please disregard this issue.

### Steps to reproduce

1. Go to Log Analysis Alerts
1. Observe the time picker. Not start/stop date is set.
1. Open the time picker. Both the start and stop time are set to the current time, but are clearly not being applied since that would not show any alerts (or at least very few that happened in that exact minute)

### Expected behavior

The timepicker shows the default time range when the page is loaded.

### Environment

How are you deploying or using Panther?

- Panther version 1.11 release candidate

### Screenshots

<img width="1576" alt="Screen Shot 2020-10-21 at 12 12 01 PM" src="https://user-images.githubusercontent.com/49166439/96771853-1ea43700-1397-11eb-9a82-17d4197f4fec.png">

**Comment by 3nvi** [comment]
@nhakmiller I'm not sure if this is a bug. No date filtering has been sett for the alerts. What do you expect to see if we don't factor in a date range in our results?

I personally feel that this works as expected. Thoughts?

**Comment by nhakmiller** [comment]
> @nhakmiller I'm not sure if this is a bug. No date filtering has been sett for the alerts. What do you expect to see if we don't factor in a date range in our results?
> 
> I personally feel that this works as expected. Thoughts?

Hmm yeah that's probably fair. I think we were under the impression that there is some default range being applied it just doesn't show up, but if there is no default I think this makes sense. I'll close this issue.
