### ISSUE TITLE
Graphs with time pickers - Selecting calendar icon should close calendar

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1836]
### Describe the bug

On any graph with a time picker, you click a little calendar icon to open up the time picker. You then must click either the `Apply` or `Cancel` button to apply close the time picker. It would be ideal to be able to click the same calendar icon to close the time picker again.

This is useful because sometimes users just want to view the time picker options in more detail so they click the icon to see the nice visual display of selected days (including for example day of the week info, which you can't see when the time picker is collapsed). After quickly viewing this information, it feels intuitive to just click the calendar icon again (without having  moved your mouse from its original position) to collapse the time picker without changing anything. Instead you have to go click on the `Cancel` button to achieve this.

### Steps to reproduce

1. Go to Log Analysis Alerts
1. Click on the time picker calendar icon, observe the calendar options expand. Select an option and click apply.
1. Click on the calendar icon again to view the selected dates.
1. Try to close the time picker by clicking the calendar icon, it stays open until you click the `Cancel` button

### Ideal behavior

Clicking the calendar icon closes the time picker.

### Environment

How are you deploying or using Panther?

- Panther v1.11 release candidate

**Comment by 3nvi** [comment]
Thanks for that @nhakmiller . This was actually planned as an enhancement, but always de-prioritized against other tickets.

You can see a high level description of the planned enhancements [here](https://github.com/panther-labs/panther-enterprise/issues/650)

**Comment by nhakmiller** [comment]
> Thanks for that @nhakmiller . This was actually planned as an enhancement, but always de-prioritized against other tickets.
> 
> You can see a high level description of the planned enhancements [here](https://github.com/panther-labs/panther-enterprise/issues/650)

Should this issue be closed then? Or should we keep them both open?

**Comment by 3nvi** [comment]
Let's keep em both for now

**Comment by 3nvi** [comment]
@dimitriszoitas we have the following options:

- Keep Apply/Cancel and automatically revert to the previous value when the user clicks outside of the datetimepicker
- Keep Apply/Cancel and automatically apply the currently active value when the user clicks outside of the datetimepicker
- Remove Apply/Cancel and:
  - Automatically apply + close the datetimepicker when the user selects a range
  - Close the datetimepicker (and keep the previous/existing value) when the user clicks outside

**Comment by dimitriszoitas** [comment]
Neither of the above behaviours are correct but the "lesser evil" is the first one. Automatically applied dates in an app that makes calls to apis will be too heavy.

So, assuming that 95% of the time that the user clicks on the calendar, they are GOING to change the dates (there is no other reason to click on the calendar unless they want to change the date) we can: 

1. Until the user makes any change to the selected dates we can have the apply button inactive
2. If the user clicks on the calendar icon, or outside of the calendar area without making any changes then everything's good
3. If the user has made changes and doesn't click on the apply button but clicks outside of the calendar area or on the calendar icon, then this action will have the same behavior as the "cancel" button

What do you think @3nvi ?

**Comment by 3nvi** [comment]
> Neither of the above behaviours are correct but the "lesser evil" is the first one. Automatically applied dates in an app that makes calls to apis will be too heavy.
> 
> So, assuming that 95% of the time that the user clicks on the calendar, they are GOING to change the dates (there is no other reason to click on the calendar unless they want to change the date) we can:
> 
> 1. Until the user makes any change to the selected dates we can have the apply button inactive
> 2. If the user clicks on the calendar icon, or outside of the calendar area without making any changes then everything's good
> 3. If the user has made changes and doesn't click on the apply button but clicks outside of the calendar area or on the calendar icon, then this action will have the same behavior as the "cancel" button
> 
> What do you think @3nvi ?

Yeah I think that's roughly the 1st scenario

**Comment by nhakmiller** [comment]
I like the first scenario too, from a user perspective.

**Comment by nhakmiller** [comment]
@3nvi will this fix be present in v1.13?

**Comment by 3nvi** [comment]
This should be already present in 1.12 and in master. If it's not feel free to re-open in order to investigate, but make sure you've tested the latest 1.12 first

**Comment by nhakmiller** [comment]
Ok sorry to be super nit-picky/annoying, but I just tested and it's almost perfect but there's still one thing. When you click the Apply button, it doesn't close the time picker.

So things that are great:
- Clicking outside the calendar closes the calendar and discards changes (fantastic)
- Clicking the calendar icon when it is open closes the calendar and discards changes (amazing)

But the one last thing that would really bring joy into my cold dark life is that if I click the `Apply` button it applies the settings and closes the calendar popup.

This is sort of different from the original issue, but I will re-open this one and if you'd prefer I can migrate it tomorrow to a different issue.

**Comment by 3nvi** [comment]
@nhakmiller You're not nitpicky. That's a bug that happened as a side-effect of this fix and was not caught by a test. I spotted it yesterday & was planning to fix it silently (without an associated issue) today, but I'll now track it with this issue instead :)
