### ISSUE TITLE
Panther Snowflake Panther_Admin has insufficient privileges

### ISSUE THREAD

**Issue by serbantanasa** [panther-labs/panther#1843]
### Describe the bug

Snowflake onboarding fails due to insufficient privileges to panther_admin user
### Steps to reproduce

mage deploy and attempt to install panther snowflake integration for rc 1.11

First error is:
`SQL compilation error: Database 'PANTHER_STORED_PROCEDURES' does not exist or not authorized.`

### Expected behavior

panther_admin creates all the tables, columns, stages, pipes etc. 

### Environment

How are you deploying or using Panther?

- Panther version or commit: [e.g. v0.1.1]
- OS: [e.g. MacOS 10.15.3]
- Browser: [e.g. Chrome 80.0.3987.87, Safari Version 13.0.5 (15608.5.11)]

### Additional context

`  
GRANT USAGE ON DATABASE panther_stored_procedures
  TO ROLE panther_admin_role;
  
GRANT USAGE ON SCHEMA panther_stored_procedures.PUBLIC
  TO ROLE panther_admin_role;   
  
GRANT CREATE FUNCTION, MODIFY, USAGE
  ON ALL SCHEMAS IN DATABASE panther_stored_procedures
  TO ROLE panther_admin_role;
  
GRANT CREATE PROCEDURE, MODIFY, USAGE 
  ON ALL SCHEMAS IN DATABASE panther_stored_procedures
  TO ROLE panther_admin_role;    `

**Comment by rleighton** [comment]
I’m guessing you did not execute the create table statements in the
directions. This needs to be done first

**Comment by serbantanasa** [comment]
There are no create table instructions. There are some create database instructions, and those were executed. I did everything as listed in the documentation, in the order listed. It was the `create procedure` step that failed, judging by the history in Snowflake. This caused the add_columns to fail, which made the pipes not create-- in the end the tables were in place, but only contained a variant `data` element.

**Comment by rleighton** [comment]
The error is that the stored procedure database does not exist. Since that
is supposed to be created at the start by the user. Are you sure you
created it?

**Comment by serbantanasa** [comment]
The database is created, the panther_admin does not see it because it does not have privileges granted to it. Running the commands i listed further down in the description cleared the error

**Comment by rleighton** [comment]
Check you are using the correct secret in the master template for the
admin. If that were the read only secret then it would behave this way

**Comment by serbantanasa** [comment]
![image.png](https://images.zenhubusercontent.com/5f7622458c57e5dde81c65d8/65d770de-9078-44da-887b-6b78a978e941)

the `stored_procedure` database existed all along it was simply not authorized for `panther_admin`. Once I add the privileges the commands work as expected.
