### ISSUE TITLE
OpsGenie destination doesn't support European region

### ISSUE THREAD

**Issue by rjpereira** [panther-labs/panther#1846]
OpsGenie destination can't be configured with region: currently doesn't support the European endpoints.
(more information at https://github.com/panther-labs/panther/blob/master/internal/core/alert_delivery/outputs/opsgenie.go#L28 )

### Steps to reproduce

1. Go to '.Settings/Destinations'
2. Click on '+ Add Destination'
3. Select OpsGenie
4. Enter API Key from an European OpsGenie account

### Expected behavior

Test send would work.

### Environment

Recommended cloudformation

**Comment by s0l0ist** [comment]
Hi @rjpereira, thank you for bringing this to our attention - this is indeed a bug. We will investigate the best way to handle the fix.
