### ISSUE TITLE
Rule Test - Error Ordering

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#1862]
### Describe the bug

When a rule test generates an error, the list of each test name is re-ordered which causing confusion when fixing the failing test

### Steps to reproduce

1. Run all tests with an existing rule, take note of the order of the tests in the TEST PASSED report on the bottom
2. Purposefully fail one of the tests by changing the data or the rule
3. See that the failing test name has now been pushed to the bottom of the report

### Expected behavior

No matter the result, keep the order in the test report the same

### Environment

Panther Enterprise v1.10

### Screenshots

Take note of the position of the 'AWS command executed' test

![Screen Shot 2020-10-23 at 5.11.37 PM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/1b44ac05-79ee-4240-8fa6-ddf73506e979)

![Screen Shot 2020-10-23 at 5.11.23 PM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/d4d8dfad-c26c-42b3-b8b9-c58435141180)

**Comment by 3nvi** [comment]
This is due to the fact that each type of result (pass/fail/error) gets added to a different bucket when it returns from the API. Up until now, there was nothing that could be done about it, but due to some API re-work on the epic related to title/dedup function testing, this will be fixed soon :)

**Comment by 3nvi** [comment]
Should be resolved in 1.12

**Comment by jacknagz** [comment]
> Should be resolved in 1.12

Confirmed!
