### ISSUE TITLE
Change indicator search linegraph to stacked bar chart

### ISSUE THREAD

**Issue by dimitriszoitas** [panther-labs/panther#1866]
### Description

We need to change this to a stacked bar chart from a smoothed line chart. These are individual events not a a continuous function.

### Acceptance Criteria

- Chart should be a stacked bar
- Chart should be able to support many Logtypes

**Comment by dimitriszoitas** [comment]
@rleighton please feel free to add/remove the acceptance criteria if I'm missing anything.

**Comment by dimitriszoitas** [comment]
@3nvi @rleighton please have a look at [this mockup](https://share.goabstract.com/a5a097aa-7512-4283-a384-551005feabfc?mode=design&sha=aee917448a1a254378032b41440491c88123fca3)

I'll have to investigate a little bit more tha hover behavior over each segment and that needs some study on the library we're using. I'll need to know:

1. what info would I be ideally showing when hovering over each segment
2. Since we're not having the time slider below the graph (we cant have it below a bar chart) should I add an extra filter to define the x axis?
3. In case we want to display more than 10 log types i would suggest we avoid the stacked bar and keep to a simple bar chart, and when you hover over the bar we can have a popup analyzing/breaking down the total hits for each log typ

**Comment by rleighton** [comment]
Looks good!
A:
1. Hover over values for each log type
2. That's too bad, I'm surprised
3. I like this idea, that's fine.

**Comment by dimitriszoitas** [comment]
Regarding 2, it's the nature of the results, since they are not continuous, we can't "zoom" in time. We can present the results dynamically depending on the date range we've selected in the filters above.

For example if I have selected one day we can have 12 columns one for every 2 hours of that day. If I have selected one week we could display either 7 or 14 columns (one or two for each day of the week) etc.

If we want to search deeper into that day I'll have to talk with Aggelos to see if it is possible to click on a column and load another chart analyzing in depth that specific column e.g. If that column is part of a weekly chart, by clicking on it we'll navigate internally to a chart presenting bi-hourly results for that specific day.

**Comment by dimitriszoitas** [comment]
I've created a collection and also updated the link in my initial comment. You can find the [collection here](https://share.goabstract.com/4ac154ec-502c-4aa7-a47c-fa167da6bca3)

**Comment by rleighton** [comment]
> Regarding 2, it's the nature of the results, since they are not continuous, we can't "zoom" in time. We can present the results dynamically depending on the date range we've selected in the filters above.
> 
> For example if I have selected one day we can have 12 columns one for every 2 hours of that day. If I have selected one week we could display either 7 or 14 columns (one or two for each day of the week) etc.
> 
> If we want to search deeper into that day I'll have to talk with Aggelos to see if it is possible to click on a column and load another chart analyzing in depth that specific column e.g. If that column is part of a weekly chart, by clicking on it we'll navigate internally to a chart presenting bi-hourly results for that specific day.

Maybe look for a "histogram" type. The other option is just a line chart but only "points". The you would get the zoom. Need the zoom.

**Comment by dimitriszoitas** [comment]
You're absolutely right - I found that component in the library and revised the mockups

**Comment by dimitriszoitas** [comment]
@rleighton let me know if this looks ok so I can close the issue
