### ISSUE TITLE
Undefined label in otpauth url for second factor TOTP QR code

### ISSUE THREAD

**Issue by stoggi** [panther-labs/panther#187]
**Describe the bug**
The generated QR code to scan for the TOTP second factor authentication has an `undefined` name

    otpauth://totp/undefined?secret=ABCDEFG&issuer=Panther

This causes the Google Authenticator app (and most likely others) to display it incorrectly.

**To Reproduce**

1. Deploy a new install of Panther
2. Create a new user and login for the first time
 a) when setting up your MFA, scan with a QR code reader like 
 b) observe the `undefined` logo encoded otpauth string `otpauth://totp/undefined?secret=...`

**Expected behavior**
The format for otpauth URIs is:

    otpauth://TYPE/LABEL?PARAMETERS

From [Google Authenticator Wiki](https://github.com/google/google-authenticator/wiki/Key-Uri-Format) and also nicely described nicely [here](https://www1.auth.iij.jp/smartkey/en/uri_v2.html)

For panther, the expected otpauth URI would be:

    otpauth://totp/Panther:username?secret=ABCDEFG&issuer=Panther

**Screenshots**

Undefined label in Google Authenticator:
![image](https://user-images.githubusercontent.com/5227285/74487938-acd13f00-4f25-11ea-897c-90e6ebe46ffc.png)

**Environment**
- Panther commit: [b3f87412fabcd67c51799bd518a93ed4b2fe290e]
- TOTP App: [Android Google Authenticator](https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en)

**Comment by stoggi** [comment]
URI is generated here:
https://github.com/panther-labs/panther/blob/8ddce61d662dab7293360c05289893c73e0eef08/web/src/helpers/utils.tsx#L47

Which means `userInfo.email` is undefined here:
https://github.com/panther-labs/panther/blob/4e3b401269e4ab41ff73e496908ee1a9d537473e/web/src/components/forms/totp-form/index.tsx#L74

Possibly because the user info context hasn't been created yet?
https://github.com/panther-labs/panther/blob/4e3b401269e4ab41ff73e496908ee1a9d537473e/web/src/components/utils/auth-context.tsx#L137

**Comment by 3nvi** [comment]
@stoggi Thank you so much for  the detailed description. I'll make sure to prioritize it.

The product has been tested  with apps  like Duo or  1Password , so you can use these until the issue is resolved

**Comment by 3nvi** [comment]
The issue seems to be related to the fact that Cognito doesn't return any user data (i.e.. email) until the full sign-in process is complete.
