### ISSUE TITLE
Redesign Policy Creation & Edit page

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1887]
### Description

Currently our PolicyForm is a single big page of data that makes it hard for someone to add what needs to add, as well as have a good overview of the entire screen.

This ticket makes sure to redesign the form (and essentially the create/edit pages) in order  to split the content into 2 tabs:

- Settings
- Functions & Tests
- Auto-Remediation

### Related Services

Policy Creation & Policy Edit page

### Designs

[Settings Tab](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/70fbde80-1195-4df9-a583-6962f57e3e19/commits/cb541d2e898cba66c61836518dee3dac5007be57/files/323d0ca1-81a8-40e7-83ee-0a05b870bb4a/layers/9627ED0F-CF14-419F-8FAA-34761ED45A43)

[Functions & Tests Tab](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/70fbde80-1195-4df9-a583-6962f57e3e19/commits/cb541d2e898cba66c61836518dee3dac5007be57/files/323d0ca1-81a8-40e7-83ee-0a05b870bb4a/layers/1B24D50A-480C-45CB-B038-DDD76E22B231)

[Auto-Remediation](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/70fbde80-1195-4df9-a583-6962f57e3e19/commits/cb541d2e898cba66c61836518dee3dac5007be57/files/323d0ca1-81a8-40e7-83ee-0a05b870bb4a/layers/7858128A-047D-4213-8141-DF704DB1E50D)

### Acceptance Criteria

- Move Save & Cancel button in the breadcrumbs
- Change the UI of the Save & Cancel Button to align with the designs
- Split the form's content into 3  tabs (no need to map each tab to a URL parameter. It's **fully optional**)
- Lazy load the content of each form (check if this creates issues with Formik submissions)
- Add a `*` to the required fields
- Split the UI accordingly
- Validate  that tests still pass
- Write a single Integration test for the new tabbed-form, as well as snapshot tests for each tab

**Comment by s0l0ist** [comment]
punted to v1.14
