### ISSUE TITLE
Log Analysis Rules - UX - Allow text entry in Log Type box

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1894]
### Describe the ideal solution

On the Log Analysis Rules page you can filter the results by log type. You do this by clicking the Log Types drop down in the top right of the page. When you click on this box, you can scroll through all the available log types and click on one to select it.

You are not able to enter text into this box to filter to the log type you want. This makes navigating to a log type near the bottom or middle of the list a hassle. Ideally I would be able to start typing the log type  and the dropdown would filter to just log types that match what I'm typing.

In the past I have used the `bug` label for UX improvement requests, but that seems incorrect. I'm trying out the `enhancement` label here, that seems more appropriate.  Please let me know how the web team feels about this 🙏 

### Describe your use cases

This would speed up my ability to filter to specific log types that I care about.

### How frequently would you use such feature

Weekly.

### Describe alternatives you have considered

Displaying all the log types at once might work. Or alternatively only displaying enabled log types would make the list much smaller and more useful (I don't know if it is currently possible for the frontend to query for this information).

### Additional context

<img width="439" alt="Screen Shot 2020-10-29 at 10 55 33 AM" src="https://user-images.githubusercontent.com/49166439/97612940-46b61a80-19d5-11eb-885d-d20b7ea2e2b0.png">

**Comment by 3nvi** [comment]
If it helps out that much that you made a ticket , then I'll help out :)
