### ISSUE TITLE
Unified Alert Page

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#1897]
### Description

Unify the alerting pages between rules, policies, and scheduled queries and implement simplified UI design to consolidate overlapping experiences.

### Acceptance Criteria

- users should be able to see all generated alerts across all types of detections (rules, policies, scheduled rules)
- users should be taken to the alert overview page when clicking a real-time rule or scheduled query alert
- user should be taken to the policy overview if clicking a cloud-security based alert
- user should be able to filter by type and attributes per type
- user should be able to multi-select log types in filter (which was nixed in v1.11)

**Comment by 3nvi** [comment]
Removing 1.13 milestone, since this is a bigger effort that spans over multiple releases
