### ISSUE TITLE
Design unified alerts page

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#1899]
### Description

Mockup what a unified alerts page that has rules, policies, and scheduled queries will look like in new simplified UI. 

### Related Services

Frontend work requires to unify alerts for policies and rules. Backend for rules and policies will remain separate for the time being.

### Acceptance Criteria

- Unified view that shows rules, policies, and scheduled queries.
- Ability to filter on resource type for policies
- Ability to filter on log types for rules

**Comment by dimitriszoitas** [comment]
Hey @mattthetraveler, I'm working on this these last days and I'm having some issues getting everything "unified"

[Here](https://share.goabstract.com/e860aa7f-0fc9-4438-a20c-3ef0bc3c4670?mode=design&sha=aabcb6e59dbca9d9c94a2611f1b681e20d4205d3) you can find all the card components that we have designed up to today. I'd like to have some info regarding the Alerts components (what should I be keeping, removing or adding) and also if you can update the issue with the filters that each type of alert could be filtered. 

What I have in mind is have one dropdown for the user to select the type of alerts they want to see (All, Rules, Scheduled Rules, Policies) and based on that selection the filter popup we're using will have the filters dynamically changed.

**Comment by mattthetraveler** [comment]
Hi @dimitriszoitas per our discussion today, here's further clarification on needed attributes for each alert category below. Your current mock up basically covers everything already but I added in a few extra changes.

One design change that I recommend- in the alert sub-details section, I believe we should start with "Alert Type" and then "Rule", "Scheduled Query", or "Policy" rather than the other way around. I believe it'll make it easier to identify the type of alert.

**Rules**
- Title
- Alert type
- Rule
- Destinations
- Log Types
- Events
- Date Created
- Severity
- Status

**Scheduled Query**
- Title
- Alert Type
- Scheduled Query Title
- Destinations
- Log Types
- Events
- Date Created
- Severity
- Status

(Note that we should update naming to "Scheduled Queries")

**Policies**
- Title
- Alert Type
- Policies
- Source
- Resource Type
- Status (we should use "Fail" instead of "Unhealthy")
- Severity

Let me know if there are questions.

**Comment by kostaspap** [comment]
> Hi @dimitriszoitas per our discussion today, here's further clarification on needed attributes for each alert category below. Your current mock up basically covers everything already but I added in a few extra changes.
> 
> One design change that I recommend- in the alert sub-details section, I believe we should start with "Alert Type" and then "Rule", "Scheduled Query", or "Policy" rather than the other way around. I believe it'll make it easier to identify the type of alert.
> 
> **Rules**
> 
> * Title
> * Alert type
> * Rule
> * Destinations
> * Log Types
> * Events
> * Date Created
> * Severity
> * Status
> 
> **Scheduled Query**
> 
> * Title
> * Alert Type
> * Scheduled Query Title
> * Destinations
> * Log Types
> * Events
> * Date Created
> * Severity
> * Status
> 
> (Note that we should update naming to "Scheduled Queries")
> 
> **Policies**
> 
> * Title
> * Alert Type
> * Policies
> * Source
> * Resource Type
> * Status (we should use "Fail" instead of "Unhealthy")
> * Severity
> 
> Let me know if there are questions.

Currently we also have Rule Error as alert type. That should be included as well int he list ^^

**Comment by dimitriszoitas** [comment]
@mattthetraveler please have a look at [this mockup](https://share.goabstract.com/60d188cc-0c36-4720-bb89-497cbebd5286)

I have made the following changes:

- In the card components for each alert type, I only kept the color coding in the left border and removed it from the text of the "alert type". The reason is that it was way too colorful
- I didn't go with the complex dropdown with checkboxes for the alert type filter because it was way too complicated. I kept a multiselect alert type input in the filter dropdown.
- When someone selects an alert for a mass action, we could automatically "lock" the alert types that we cannot apply the same actions. For example, at the moment we can mass change the alert statuses in rules/scheduled queries, and we can mass delete failed policies.

**Comment by 3nvi** [comment]
@mattthetraveler shall we close this?

**Comment by mattthetraveler** [comment]
Looks good @dimitriszoitas 

Yes will close this @3nvi
