### ISSUE TITLE
Design JSON view of logs

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#1909]
### Description

I want to be able to copy JSON from Data Explorer to populate test data when developing rules.

### Related Services

Data Explorer backend and frontend will be updated

### Designs

https://panther-labs.atlassian.net/wiki/spaces/EN/pages/610435079/RFC+Exploring+and+Copying+SQL+Results?focusedCommentId=795967528#Backend

### Acceptance Criteria

- When viewing specific rows in Data Explorer, the user can click to pop-up a pretty JSON version of the row

**Comment by dimitriszoitas** [comment]
@mattthetraveler Could I have an example of how a row from the screenshot in the RFC would look like as a prettified json?

Thank you!

(Just saw you already had this issue created so I deleted my comment from the epic)

**Comment by mattthetraveler** [comment]
Hi @dimitriszoitas 

We want to give the user the ability to each row in the search result into a format like below

![image.png](https://images.zenhubusercontent.com/5f99c6c3032b975d7ec7e099/198cf7bd-18d3-4bfb-be6e-f1be513f5b2d)

The goal is to allow the user to expand and copy certain fields within an event (or even the entire event) and then drop it into a test record when they're creating new rules.

**Comment by dimitriszoitas** [comment]
Hello @mattthetraveler,

Please review [these screens](https://share.goabstract.com/58765850-eb88-49b2-9964-f616daeed12c) and let me know if they are ok

Thank you

**Comment by dimitriszoitas** [comment]
@mattthetraveler @3nvi reminder for a feedback on this :)

**Comment by 3nvi** [comment]
As long as the table headers are aligned we are cool
