### ISSUE TITLE
[Design] Unified Integrations

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#1917]
### Description

Design consolidated integrations tab that shows data sources, log schemas, alert destinations, and cloud scanners in sub-tabs. Users should be able to view, edit, and add integrations within these  sub-tab.

### Related Services

- Relies on effort to update UI to choose "data transporters" (SQS, S3, EventBridge) for data sources
- Backend unaffected

### Designs

- To be designed 

### Acceptance Criteria

- User should be able to view, edit, and add data sources in "Data Schemas" sub-tab
- User should be able to view, edit, and add log schemas in "Log Sources" sub-tab (to replace current Log Analysis>Sources)
  - We should replicate the layout in the external[ Integrations page today](https://runpanther.io/integrations/). Same categorizations
  - Each support log should have it's own tile with a logo and title
  - Each SaaS log puller should have an enterprise label on it
  - Each supported log details page should have a title, description, app info, use cases, how it works (same content as in external integrations page) as well as a section that lists out available Data Transports: SNS, S3, SQS, or Eventbridge (depends on the log source)
     - By clicking into the supported Data Transports, the user will be taken into the existing onboarding experience with the log types for the respective log source already selected.
- Users should be able to view, edit, and add destinations in "Alert Destinations" sub-tab (to replace current Settings>Destinations)
- Users should be able to view, edit, and add accounts in "Accounts" sub-tab (to replace current Cloud Security>Sources)

**Comment by mattthetraveler** [comment]
Some feedback from DropBox: "might also be good to rename Cloud Security “Sources” to Accounts to be more clear and consistent? (I guess unless other source types are eventually planned for that)"

So instead of Cloud Scanners, maybe rename to "Accounts"?

**Comment by dimitriszoitas** [comment]
@mattthetraveler Please review the following collections:

[Data Schemas](https://share.goabstract.com/2cc6c1f5-06bb-4bbf-92bc-ab28120ad5ea)
[Alert Destinations](https://share.goabstract.com/f8389484-d590-419e-8fa2-9b8bb8f599ca)
[Log Sources](https://share.goabstract.com/dbf178c4-c6fa-4a20-9646-6d95d07de6db)
[Cloud Scanners](https://share.goabstract.com/96a7b795-f26c-433a-b567-12ed553fa8ce)

**Comment by mattthetraveler** [comment]
Hey @dimitriszoitas updated the acceptance criteria to expand the scope of this. We should mimic the external integrations page in the "add new log source" experience and link data transport options in the individual supported log pages.

**Comment by dimitriszoitas** [comment]
hey @mattthetraveler, please review again [this collection](https://share.goabstract.com/dbf178c4-c6fa-4a20-9646-6d95d07de6db) and let me know if everything looks ok. Also let me know if all the other collections of integrations are ok so I can tag them as done in abstract and close this issue (when we're ok with the log sources collection)

Thank you

**Comment by jacknagz** [comment]
@dimitriszoitas left a small comment (and updated the AC) about "Cloud Accounts" vs "Accounts"
