### ISSUE TITLE
Show Python revision history, allow reverting

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#192]
## Description
We store every revision to Python policies and rules, but we don't do anything with them. The idea was to give users the power to revert a bad rule change.

For example, deleted rules are removed from Dynamo but still exist in S3 and could be recovered.

## Acceptance Criteria

- Users can see the version history of any rule or policy (version number, timestamp, author)
- Users can revert rules and policies to any previous version
- Users can optionally show deleted rules/policies and restore them

OR

- Remove rule revision history if we don't ever plan to use it to greatly simplify the core analysis api

The Dynamo table storing policies and rules does have backups enabled, so it's not unreasonable to say that catastrophic failures could be reverted this way. But I think it would be better to allow users to revert individual rules + policies

### Backend
We already store old versions, and the `GetPolicy` / `GetRule` endpoint already allow you to retrieve older versions (even deleted ones). Changes we need to `analysis-api`:

- Add `ListVersions` endpoint which returns a list of version IDs, timestamps, and author (for a given policy/rule ID)
- Add some way to list deleted rules

### Frontend

- On rule/policy details, add dropdown to show older versions
- On rule/policy edit page, allow reverting to old version
- On rule/policy list, add option to show deleted rules

**Comment by 3nvi** [comment]
For me this is not super hard. Will we add this for v1?

**Comment by austinbyers** [comment]
I don't think it's a priority, no, but should be an easy add after

**Comment by 3nvi** [comment]
@austinbyers 

> * Add ListVersions endpoint which returns a list of version IDs, timestamps, and author (for a given policy/rule ID)
> * Add some way to list deleted rules

Is any of the above implemented? If not we can turn that into an epic, else I can just assign myself in this one and remove the backend related work from the description

**Comment by austinbyers** [comment]
Some backend exists (rule/policy versions are stored and you can GetPolicy or GetRule by a specific version), but we probably need other endpoints as well (listing, mainly)

I converted to an epic

**Comment by austinbyers** [comment]
Reassigning this (very old epic) to @s0l0ist , who will tentatively be working on it this quarter!

The main requirement now is that alerts link back to the specific version of the policy/rule that triggered the alert, so users can see the version of the Python at the time. The rule/policy page should support loading old versions, show if the rule is the current version, and if not, how long ago it was.

Being able to list old/deleted versions and revert/restore can come later
