### ISSUE TITLE
Destination Delivery Failure

### ISSUE THREAD

**Issue by lindsey-w** [panther-labs/panther#1931]
### Describe the bug

When a destination times out or does not respond for over 60 seconds, the lambda dispatching the alerts to the destinations will timeout.  When this happens, the entire alert SQS batch will be retried, which attempts to send the alert to all the configured destinations again.  Further, the delivery status is not updated because the lambda waits for responses before writing the delivery statuses.  This can result in multiple deliveries of the same alert to destinations where there is not a timeout.    

### Steps to reproduce

1. A destination times out (vs return 40x/50x)
2. A triggered alert that has this destination configured will not show any destination information

### Expected behavior

The lambda should kill the routine if it takes longer than X time and return an HTTP status code on its behalf so that the lambda can record the delivery status and exit successfully. 

### Environment

How are you deploying or using Panther?

- Panther version or commit: v1.12.0-RC
- OS: osx 10.15
- Browser: Brave 1.13.86

### Screenshots

When a single destination causes a lambda timeout, none of the destinations show up on the triggered alert's page:

![image](https://user-images.githubusercontent.com/43453975/98062614-3f42a700-1e03-11eb-8d6d-96f5a6a0b97c.png)

**Comment by s0l0ist** [comment]
Excellent find and great write up 😉

**Comment by kostaspap** [comment]
> Excellent find and great write up 😉
> 
> Additional Context:
> 
> * lambda timeout occurs in goroutines
> 
> Solution:
> 
> * find a way to race between routine request/response completion and a timeout of 30 seconds

We should start using `context.Context` [object](https://blog.golang.org/context) when making requests to such endpoints. It could help with timeouts when performing HTTP requests.
