### ISSUE TITLE
Table updates during deployments are broken

### ISSUE THREAD

**Issue by alxarch** [panther-labs/panther#1957]
### Describe the bug

The solution provided in #1912 changed the way updates happen for log tables.
The general approach of sending a message to the datacatalog updater SQS was correct.
The problematic choice was to only update the log types used in current sources. This breaks 'all' views if a client for some reason has deleted a source after collecting data.
Creation of views fails if the schema was modified to include new indicator or core fields. In the case of 1.12 release that includes the `p_alert_context` added to rule matches table. 
Since log tables created at any point would be left in the data lake and will be visible for queries, they should be properly updated and included in the 'all' views *regardless of whether they are being used by a source*. 

On a minor note, there was a change to the `DeployedLogTypes` function that includes stuff from the 'panther_cloudsecurity' database which I am not sure should be there.

## Suggested solution

We use the logtypes API to fetch **all available log types** and filter them with `DeployedLogTypes` to get the right set of log types to update.

Update: The code for 'full' database sync during upgrades and 'create tables' during source updates has to be split as the logic is somewhat different in each case. The linked PR addresses that.

**Comment by rleighton** [comment]
We hit the this upgrading the internal account due to the schema change also.

**Comment by rleighton** [comment]
Q: If a log source is deleted (not mentioned in any source), why do we need to up date it?

**Comment by alxarch** [comment]
The current way 'all' views work is to include all tables _deployed to glue_. Updating the views based on log types used in views is more complex since we need to keep modified/deleted sources in sync with the views. My suggestion is to keep this behavior since it will be confusing to have tables in the data explorer that are not present in 'all' views.

The current code uses the same handler for both updating the full database when deploying and when a source is updated. I suggest to split these into two separate events since their logic is quite diffrerent.

**Comment by alxarch** [comment]
Closed by #1975
