### ISSUE TITLE
Design "data models" sub-tab

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#1974]
### Description

In the analysis tab in the new simplified UI, I want to have the ability to add data models in with YAML

### Related Services

[See Backend services here](https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther/1768) 

### Designs

Here is the [RFC](https://github.com/panther-labs/panther-enterprise/tree/master/designs/security/simplify-detections)

### Acceptance Criteria

- Within the new Analysis tab in the simplified UI, we should add a new "Data Models" sub-tab (under Global Helpers)
- To add new Data Model, form should have two sections: Settings and Data Model Mappings
- Within Setting tab, available attributes should be Log Types, Detection ID, and Enabled
- Within Data Model Mappings tab, there should be a field to drop in a YAML function. This should be mandatory for the user.
- Within Data Model Mappings tab, there should an option to drop in a Python Module. This should be optional for the user.

**Comment by lindsey-w** [comment]
I'm excited about this! A couple of things I thought of:
- Rather than `rules pack` I think they might be called `data model` (or `data models`).  Just to not get it mixed up with the pack work being discussed [here](https://github.com/panther-labs/panther-enterprise/pull/1011).  
- I don't know that I have a better naming convention, but within the `new` editor, `Functions` might be a little misleading.  Perhaps `Data Model Mappings` or `Definitions` (definitions being the YML / python). However, this does branch off from what would be displayed for Rules/Policies - so perhaps leaving it `Functions` is fine for consistency sake? 
- Just a quick note that for these: YAML will be required, and python is optional (vs Rule/Policy where python is required and tests are optional)

**Comment by mattthetraveler** [comment]
Updated the issue @lindsey-w !

**Comment by dimitriszoitas** [comment]
@mattthetraveler @lindsey-w  a couple of questions so I can get started on this:

1. When the user lands to the Data Models page, do they see a list of the added models or just a form to add a new one (like the bulk uploader)?
2. When you say "a field to drop in a YAML function" do you mean an editor or a file uploader ?
3. Same question for the Python Module
4. In the RFC I see this: "Users can enable/disable automatic updates from this page".  Should I also have this in the mockup?
5. Should I have any extra buttons? Submit/Upload/Save to complete this action?
6. Are there possible errors that could occur, and what are they?

**Comment by mattthetraveler** [comment]
> When the user lands to the Data Models page, do they see a list of the added models or just a form to add a new one (like the bulk uploader)?
Yes, the user should see a list of added data models
> When you say "a field to drop in a YAML function" do you mean an editor or a file uploader ?
it should be an editor
> Same question for the Python Module
an editor for this as well
> In the RFC I see this: "Users can enable/disable automatic updates from this page". Should I also have this in the mockup?
Looks like I had the wrong RFC linked, so disregard for this issue! I've updated the link, should reflect the acceptance criteria.
> Should I have any extra buttons? Submit/Upload/Save to complete this action?
I believe "Submit" should suffice to complete the action. @lindsey-w any thoughts here?
> Are there possible errors that could occur, and what are they?
Incorrect format in the editor when adding YAML is first that comes to mind. @lindsey-w any others?

**Comment by dimitriszoitas** [comment]
If we do have a list of added data models should we also consider having a Name for the model in the creation form?
Also what info/attributes are we going to display in the list for each data model (e.g. name, log types, status enabled/disabled)?
And lastly, what are some actions that could be applied to each model in the list (e.g. delete, edit, etc)

**Comment by lindsey-w** [comment]
> I believe "Submit" should suffice to complete the action. @lindsey-w any thoughts here?
Is this w/r/t a confirmation that the user wants to create a new Data Model? I agree, `Submit` should suffice.  I was imagining this would have a similar workflow to the rules editor - with an edit/delete options on the overview page, and on the editor page Delete/Cancel/Update buttons. Where if you want to _delete_ a Data Model, it does have a confirmation but the other buttons do not trigger an 'are you sure' confirmation.  

> Incorrect format in the editor when adding YAML is first that comes to mind. @lindsey-w any others?
Agreed! I can't think of anything else at the moment. 

> If we do have a list of added data models should we also consider having a Name for the model in the creation form?
Good point! I like that idea. 

> Also what info/attributes are we going to display in the list for each data model (e.g. name, log types, status enabled/disabled)?

ID, Name, Log Types, Status

I know we don't display the python for rules/policies in the overview - but for Data Models, would it be useful to display the YAML?  It might be useful to display the YAML even as a table where the `name` attributes on the left column and the `field` (or `method`) attributes in the right column? But that might make things more complicated than necessary here.  Thoughts @mattthetraveler @nhakmiller? 

> And lastly, what are some actions that could be applied to each model in the list (e.g. delete, edit, etc)
I think just those two options: Edit / Delete

**Comment by nhakmiller** [comment]
> but for Data Models, would it be useful to display the YAML? It might be useful to display the YAML even as a table where the name attributes on the left column and the field (or method) attributes in the right column?

I think this would be a lot of information for an overview page. These YAML files could be several dozen lines long, so the overview page would be a bit crowded with this showing up.

Data models will also definitely need a unique ID, which maybe the same as the name (we could implement it either way). Not sure if you've formalized/thought about this @lindsey-w , but if we use the unique ID as the name then it cannot be edited. So the options are:

- Only have a unique ID. This is set by the user in the "new data model" creation page, and cannot later be changed in the editor
- Have a unique ID and a name. These both can be set in the "new data model" page, but only the name can be updated later.

Whichever way, we'll want to make sure the backend is aligned of course.

**Comment by lindsey-w** [comment]
> I think this would be a lot of information for an overview page. These YAML files could be several dozen lines long, so the overview page would be a bit crowded with this showing up.

Good point - agreed.

> * Have a unique ID and a name. These both can be set in the "new data model" page, but only the name can be updated later.

I would lean towards this (to be consistent with rules/polices), but I have not implemented this in the change I just merged.  The current version does _not_ allow IDs to be changed, but it doesn't have the name field yet.  This shouldn't be hard to add, I can work on it before the end of the week.

**Comment by dimitriszoitas** [comment]
I have created a collection for the mockups mentioned above. You can find it [here](https://share.goabstract.com/0c598870-5b8c-4feb-b12c-39ae3cb87248)

I would like of course your feedback, along with the following:

1. If you can, comment or slack me with a few "realistic" content (names, titles, IDs)
2. Let me know if we CAN have a syntax validation for Python Modules (I know we can have for YAML but I don't see something for Python Modules in global helpers)

thank you!

**Comment by lindsey-w** [comment]
This looks great! 

Here are a couple of examples:

---
Name: OneLogin DataModel
ID: onelogin.datamodel
LogTypes: OneLogin.Events
Associated YAML:
```
Mappings:
- name: source_ip
  field: ipaddr
- name: user
  method: get_user
```
Associated Python:
```
def get_user(event):
    if event.get('actor_user_name'):
        return event.get('actor_user_name')
    return event.get('user_name')
```
--- 
Name: GSuite DataModel
ID: gsuite.reports.datamodel
LogTypes: GSuite.Reports
Associated YAML:
```
Mappings:
- name: source_ip
  field: ipAddress  
- name: user
  field: $.events[*].parameters[?(@.name == 'USER_EMAIL')].value
```
(This example doesn't have associated python)

--- 
_Additional example names:_
Name: Osquery DataModel
ID: osquery.all.datamodel
LogTypes: Osquery.Status, Osquery.Differential, Osquery.Batch

Name: Box Enterprise Events DataMdoel
ID: Box.Events.DM
LogTypes: Box.Events

---

I'm unsure about the second question - would someone from the frontend team know?

**Comment by nhakmiller** [comment]
I'm sure the frontend could do some basic python validation, but most likely any real python validation would have to happen on the backend. We could add this, but we don't have it today.  I imagine it would live alongside the rule testing API call, something like test data model. I say we hold off on adding a validate button for the python for now since we  aren't validating python anywhere  else really, and in the future if we add  this feature we can re-visit it  here and  elsewhere.

**Comment by dimitriszoitas** [comment]
Hello again - I have revised the mockups, please have a look at the collection again and let me know if it's good to go and close this issue ;)

Thanks!

**Comment by mattthetraveler** [comment]
Made one last comment but small change, overall looks good! @dimitriszoitas

**Comment by dimitriszoitas** [comment]
@mattthetraveler I made the change, so if everything looks okay we can close this issue - let me know whenever you cam

**Comment by mattthetraveler** [comment]
@dimitriszoitas this looks great, closing this out!
