### ISSUE TITLE
Destinations - Specify JIRA Tag

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1977]
### Description

As an analyst, I want to be able to specify tags for outputs that are sent to JIRA from Panther so that it's clear which issues were generated by Panther.

### Related Services

Destinations - JIRA

### Designs

N/A

### Acceptance Criteria
- An additional optional field in the JIRA destination set up form that asks the user to specify tags for Panther related outputs.
- A JIRA destination can store a custom tag, and any alerts forwarded to that JIRA destination will be tagged with that custom tag or tags.

**Comment by 3nvi** [comment]
This should include a BE and FE work. Could we make this an epic?

**Comment by nhakmiller** [comment]
> This should include a BE and FE work. Could we make this an epic?

Sure.
