### ISSUE TITLE
Update quickstart documentation to include mage setup:all

### ISSUE THREAD

**Issue by stoggi** [panther-labs/panther#198]
### Describe the bug

When following the Quick Start Guide in a clean environment, the first invocation of `mage deploy` fails because `mage setup:all` has not yet been run.

### Steps to reproduce

1. Clone a fresh copy of panther into a new directory
2. Run `./dev.sh` with aws credentials
3. Run `mage deploy`
4. Observe the error:
    ```21:45:55	FATAL	.setup/swagger not found (stat .setup/swagger: no such file or directory): run 'mage setup:all'```
### Expected behavior

The error message is not very friendly, although it does mention to run `mage setup:all`. However this is something the Quick Start Guide could easily before running `mage deploy`. Alternatively on a deploy, mage could detect that the setup has not yet been run, and run it automatically with `mg.Deps()`.

### Environment

- Panther master at commit 48f2f244d453bb0cbaa3077c7d80f024b1a97a5c
- OS: Linux (Manjaro 19)
- Deployment method: docker container via ./dev.sh

### Screenshots

![image](https://user-images.githubusercontent.com/5227285/74613499-daabc300-5173-11ea-92f5-f048bfbdaa0f.png)

**Comment by 3nvi** [comment]
Yup, just noticed. Thanks for letting us know. Will update asap :)

**Comment by austinbyers** [comment]
This is actually a bug - you shouldn't need `swagger` to deploy. I'll assign the issue to myself to track its resolution in our `mage` tooling.

Thanks for reporting!
