### ISSUE TITLE
Custom JIRA Tags - Frontend work

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1981]
### Description

Allow users to specify a custom tag in the destination configuration page for JIRA destinations.

### Related Services

The destination onboarding wizard.

### Designs

Not sure if any design work needs to be done, it's just one new field. BUT it's already a fairly big form so maybe some re-design would be needed.

### Acceptance Criteria

You can specify a custom tag setting for JIRA destinations.

**Comment by 3nvi** [comment]
@nhakmiller wouldn't we need a backend change for this?

**Comment by nhakmiller** [comment]
> @nhakmiller wouldn't we need a backend change for this?

Indeed we will. As you suggested on the epic https://github.com/panther-labs/panther/issues/1977, I created a frontend and backend task https://github.com/panther-labs/panther/issues/1980.

**Comment by 3nvi** [comment]
Oh I missed that! Sorry for that

**Comment by mattthetraveler** [comment]
@3nvi do you think this will require new designs for the new field?

**Comment by 3nvi** [comment]
I think we can infer it, unless @dimitriszoitas feels we should do some sort of re-arrangement due to the excess amount of fields

**Comment by dimitriszoitas** [comment]
I'll have to update to mockup either way, but I think that adding a large combo-box below our current fields will suffice. @3nvi let me know if you want to chat a couple of minutes on this.

**Comment by nhakmiller** [comment]
@dimitriszoitas actually I think this design work could be merged with this design work too: https://github.com/panther-labs/panther/issues/2154, they are for the same form. Not sure if it is easier  for you to do both designs  at  once or  one then  the other (of if you're already done with this one), just wanted to throw it out there as an option.

**Comment by 3nvi** [comment]
Yeah I agree. We chatted and agreed to add a big single-line multi-combobox as the last field
