### ISSUE TITLE
Log Analysis Overview Metrics Bug: EventsProcessed

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#1991]
### Describe the bug

When only a single log type sends through the pipeline, the Log Analysis overview shows 'EventsProcessed' instead of the log type

### Steps to reproduce

1. In a new deployment, only send a single log type, like CloudTrail
2. Go to Log Analysis -> Overview -> Events by Log Type
3. Note the `EventsProcessed`

### Expected behavior

Showing the breakdown by type, in this case, a single line saying 'AWS.CloudTrail'. See the screenshots below for more info

### Environment

Panther Enterprise v1.11.0

### Screenshots

Bug:

![Screen Shot 2020-11-09 at 9.28.31 AM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/7d19dac5-afab-4f6f-bbc0-84c76cbc9c53)

Expected:

![Screen Shot 2020-11-09 at 10.20.03 AM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/00a2c6ed-f35f-46e2-896f-69e6c60a1b7e)

**Comment by nhakmiller** [comment]
Most likely due to the dynamic generation of the metric query. We could consider more explicitly building the labels or possibly looking up the registered log types instead of listing the metrics when generating the query.

**Comment by rleighton** [comment]
I vaguely remember that this is a “feature “ in cloud watch

**Comment by 3nvi** [comment]
@nhakmiller assigned to security engineering team. Let me know if web should be involved somehow

**Comment by nhakmiller** [comment]
> @nhakmiller assigned to security engineering team. Let me know if web should be involved somehow

Will do, but I think it will mostly be backend work.
