### ISSUE TITLE
New Log Parsers

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#200]
### Description

Add parser support for hosts, networks, containers, and network-based logs to support additional data analysis and historical search capabilities.

The log types in question:

Host:
- [x] [OSSEC](https://www.ossec.net/docs/formats/alerts.html)
- [x] Syslog (RFC 5424 and default formats)
- [ ] [Go-Audit](https://github.com/slackhq/go-audit)
- [ ] [Sysmon](https://eqllib.readthedocs.io/en/latest/guides/sysmon.html) (Windows)
- [ ] [Santa](https://github.com/google/santa)

Application:
- [x] [Apache](https://httpd.apache.org/docs/2.4/logs.html)
- [ ] [EKS Control Plane](https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html)
- [x] Kolide Server
- [ ] [Kubernetes Audit](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/)
- [x] [Teleport](https://github.com/gravitational/teleport) Audit

Network:
- [ ] [Zeek](https://docs.zeek.org/en/current/frameworks/logging.html) (JSON format, [Ref](https://docs.zeek.org/en/current/script-reference/log-files.html))
- [ ] [Suricata](https://suricata.readthedocs.io/en/suricata-4.1.0/output/eve/eve-json-format.html) (JSON format)

### Acceptance Criteria

- New parser(s) for each log type listed above
- New data is properly classified, analyzed, and alerted upon (tested end-to-end)
- 2-3 example rules per log type
- Data is searchable in Athena
- Documentation is updated

**Comment by stoggi** [comment]
Started looking into OSSEC log format https://www.ossec.net/docs/docs/formats/alerts.html

Source code for ossec 3.3.0 **src/analysisd/format/to_json.c** has methods to convert to JSON for the different log types. Including an extended format defined in **src/analysisd/format/json_extended.c**

An initial attempt at a go struct for the EventInfo type is:

```go
type EventInfo struct {
	Rule           *Rule     `json:"rule" validate:"required"`
	ID             *string   `json:"id,omitempty"`
	Timestamp      *int      `json:"Timestamp,omitempty"`
	Decoder        *string   `json:"decoder" validate:"required"`
	DecoderParent  *string   `json:"decoder_parent,omitempty"`
	Action         *string   `json:"action,omitempty"`
	Protocol       *string   `json:"protocol,omitempty"`
	SrcIP          *string   `json:"srcip,omitempty"`
	SrcGeoIP       *string   `json:"srcgeoip,omitempty"`
	SrcPort        *string   `json:"srcport,omitempty"`
	Srcuser        *string   `json:"srcuser,omitempty"`
	DstIP          *string   `json:"dstip,omitempty"`
	DstGeoIP       *string   `json:"dstgeoip,omitempty"`
	DstPort        *string   `json:"dstport,omitempty"`
	Dstuser        *string   `json:"dstuser,omitempty"`
	Location       *string   `json:"location,omitempty"`
	FullLog        *string   `json:"full_log,omitempty"`
	PreviousOutput *string   `json:"previous_output,omitempty"`
	Hostname       *string   `json:"hostname,omitempty"`
	ProgramName    *string   `json:"program_name,omitempty"`
	Status         *string   `json:"status,omitempty"`
	Command        *string   `json:"command,omitempty"`
	URL            *string   `json:"url,omitempty"`
	Data           *string   `json:"data,omitempty"`
	SystemName     *string   `json:"systemname,omitempty"`
	SyscheckFile   *FileDiff `json:"SyscheckFile,omitempty"`

	// NOTE: added to end of struct to allow expansion later
	parsers.PantherLog
}

type Rule struct {
	Level      *int    `json:"level,omitempty"`
	Comment    *string `json:"comment,omitempty"`
	Sidid      *int    `json:"sidid,omitempty"`
	CVE        *string `json:"cve,omitempty"`
	Info       *string `json:"info,omitempty"`
	Frequency  *int    `json:"frequency,omitempty"`
	Firedtimes *int    `json:"firedtimes,omitempty"`
}

type FileDiff struct {
	Path          *string `json:"path" validate:"required"`
	MD5Before    *string `json:"md5_before,omitempty`
	MD5After     *string `json:"md5_after,omitempty`
	SHA1Before   *string `json:"sha1_before,omitempty`
	SHA1After    *string `json:"sha1_after,omitempty`
	OwnerBefore  *string `json:"owner_before,omitempty`
	OwnerAfter   *string `json:"owner_after,omitempty`
	GroupOwnerBefore *string `json:"gowner_before,omitempty`
	GroupOwnerAfter  *string `json:"gowner_after,omitempty`
	PermBefore   *int    `json:"perm_before,omitempty`
	PermAfter    *int    `json:"perm_after,omitempty`
}

type Decoder struct {
	FTS        *string `json:"fts,omitempty"`
	Accumulate *string `json:"accumulate,omitempty"`
	Parent     *string `json:"parent,omitempty"`
	Name       *string `json:"name,omitempty"`
	FTSComment *string `json:"ftscomment,omitempty"`
}
```

**Comment by kostaspap** [comment]
Some work was done in PR https://github.com/panther-labs/panther/pull/459

**Comment by kostaspap** [comment]
Resolving in favor of individual issues
