### ISSUE TITLE
Improve stream processing and memory usage of log processor Lambda

### ISSUE THREAD

**Issue by alxarch** [panther-labs/panther#2001]
### Description

The log processor currently has some major memory-related issues 

- ~We never call `Close()` on S3 object's `Body io.ReadCloser`, possibly leaking http connections to S3 service~ Fixed by use of `s3pipe.Downloader`
- ~We use multiple chained buffered readers (`bufio.Reader`) to read each log file which results in unnecessary data copying in memory.~ Not relevant any more with the `s3pipe.Downloader`
- We have a very crude reading method for log entries that in some cases (CloudTrail) requires to load the full file in memory before we can process it. This forces us to set 'fat' Lambda memory requirements to avoid OOM crashes thus increasing processing costs for all logs.

### Related Services

- Log processor

### Designs

To solve these issues we should abstract the reading of log entries from a file using the following interface:

```golang
// LogEntryStream reads log entries from an underlying `io.Reader`.
type LogEntryStream interface {
  // NextLogEntry returns the next log entry in the stream.
  // If `nil` is returned, it means that an error was encountered while reading or the EOF was reached 
  // and there will be no more log entries in the stream.
  //
  // WARNING: To avoid needless memory copying the byte slice returned is only valid until the next call to NextLogEntry or Close
  NextLogEntry() []byte
  // Close releases any memory or resource handlers managed by the stream and returns any error that occured while parsing
  // Once Close is called all future calls must return the same result and any calls to NextLogEntry should return nil
  Close() error
}
```

To produce a `LogEntryStream` we will be using various `LogEntryStreamFactory` implementations depending on the requirements of the particular log file as determined by it's metadata (i.e. source configuration, object key pattern etc).

```golang
type LogEntryStreamFactory interface {
  BuildLogEntryStream (rc io.ReadCloser) (LogEntryStream, error)
}
```

> NOTE: Detection and decompression of `gzip` log streams should happen **before** passing the initial `rc` argument to the appropriate factory. Special care must be taken so that `rc` *also closes* the original `Body  io.ReadCloser` of the S3 object (Handling this transparently is not currently possible without extensive refactoring of the log processor code).

> NOTE: A 'universal' default for read buffer size should be defined through an environment variable so that we can experiment with higher or lower values on each deployment. This buffer size will be setting the buffer for each buferred reader involved (e.g. bufio.Reader, jsoniter.Iterator) and should be set to some multiple of the anticipated average log entry size across all log types. It would be useful to have such a metric for each deployment fine tune to the specific requirements. 

The following `LogEntryStream` implementations should cover all problems:
- *LineStream* is the default one log entry per line stream as used currently. Extra care will be taken so that no copying happens when a line fits in the buffer. If the line is larger than the buffer, the stream should acquire a buffer from a `sync.Pool` and make sure to return it when `Close` is called. The implementation should acquire a `bufio.Reader` from a pool and use the `ReadLine` method to avoid memory copying. It should return the reader to the pool **after reseting it with `nil`**
- *JSONArrayStream* will handle log entries 'hiding' inside a single JSON array in the input file. A `path` argument should point to the array value that holds the entries (i.e. `[]string{"Records"}` for CloudTrail logs). The entries will be read in streaming fashion without requiring to load the entire array in memory to produce the log entries. The implementation will be acquiring a `jsoniter.Iterator` from a pool , seek to the provided path and use its `ReadArray` and `SkipAndReturnBytes` method to read log entries.  It should return the iterator to the pool when `Close` is called.
- *JSONStream* will handle JSON input that is **not new line delimited** such as EventBridge sources. This will be using a jsoniter.Iterator as well and avoid copying by calling `SkipAndReturnBytes` until an error occurs. Special care must be taken for detecting EOF. The iterator will be returned to the pool on `Close`

### Acceptance Criteria

- [x] Update current log processor logic to use new interface instead of always splitting lines
- [x] Implement `LineStream` to replace the current 'hardcoded' method
- [x] Implement `JSONArrayStream` to handle CloudTrail cases
- [x] Add S3 Key detections to use `JSONArrayStream` for `CloudTrail`.
- [ ] Implement `JSONStream` to handle SQS cases (should also solve proper handling multiline `jsoniter.RawMessages`).
- [ ] Add S3 Key detections to use `JSONStream` for SQS sources.

**Comment by rleighton** [comment]
Nice!

**Comment by kostaspap** [comment]
Followup: 
> - *JSONArrayStream* will handle log entries 'hiding' inside a single JSON array in the input file. A `path` argument should point to the array value that holds the entries (i.e. `[]string{"Records"}` for CloudTrail logs). The entries will be read in streaming fashion without requiring to load the entire array in memory to produce the log entries. The implementation will be acquiring a `jsoniter.Iterator` from a pool , seek to the provided path and use its `ReadArray` and `SkipAndReturnBytes` method to read log entries.  It should return the iterator to the pool when `Close` is called.
- *JSONStream* will handle JSON input that is **not new line delimited** such as EventBridge sources. This will be using a jsoniter.Iterator as well and avoid copying by calling `SkipAndReturnBytes` until an error occurs. Special care must be taken for detecting EOF. The iterator will be returned to the pool on `Close`
