### ISSUE TITLE
Revise/Unify Form Layout in Sources onboarding

### ISSUE THREAD

**Issue by dimitriszoitas** [panther-labs/panther#2005]
### Description

Review live screens and revise where needed so we are consistent in all form layouts for every Source we currently support up to today

### Acceptance Criteria

- Form Layouts for all Sources onboarding should be based in a common grid

**Comment by 3nvi** [comment]
Couple of things to notice is that the `Log Types` Combobox will be removed from the UI for the following log sources:

- Slack
- EventBridge

**Comment by dimitriszoitas** [comment]
Hey @3nvi have a look at [this collection](https://share.goabstract.com/c29edec4-2bdb-4cd9-bf51-7e24a232460d) and let me know if it looks ok

**Comment by 3nvi** [comment]
Yup, looks ok
