### ISSUE TITLE
Update Filter for Unified Alerts Page

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#2022]
### Description

With policy based alerts, rule match alerts, and rule errors alerts being merged into the same view in Unified Alerts page, we need to update our filter to be able to filter on all policy and rule based alerts

### Designs

https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/df9d59c8-eeb1-452d-a5f5-3712b64010be/collections/92f16a44-b3f2-44ff-a132-5198d0673377

### Acceptance Criteria
- Ability to filter on rule ID and policy ID
- Ability to filter on Alert Type (policy fail, rule match, rule error)
- Ability to filter on severity
- Ability to filter  on status
- Ability to filter on resource type
- Ability to filter on Event quantity

**Comment by mattthetraveler** [comment]
FYI @3nvi repurposed this issue to capture the work required to update Filter in new unified Alerts page
