### ISSUE TITLE
PantherAuditRole missing permission to list SNS topic tags

### ISSUE THREAD

**Issue by stoggi** [panther-labs/panther#203]
Received an alert for via rule `AWS.CloudTrail.UnauthorizedAPICall` in Panther because the PantherAuditRole tried and failed to list the tags of an SNS topic.

Error message:
```User: arn:aws:sts::SOURCE_ACCOUNT:assumed-role/PantherAuditRole/1581973794329971471 is not authorized to perform: SNS:ListTagsForResource on resource: arn:aws:sns:us-west-2:SOURCE_ACCOUNT:panther-notifications-topic"```

Looks like we need `sns:ListTagsForResource` here:
https://github.com/panther-labs/panther/blob/48f2f244d453bb0cbaa3077c7d80f024b1a97a5c/deployments/auxiliary/cloudformation/panther-compliance-iam.yml#L92-L102

### Steps to reproduce

1. Create a SNS topic in an account monitored by Panther
2. Observe alert `AWS.CloudTrail.UnauthorizedAPICall` in Panther

### Expected behavior

The panther audit role should have the permissions it needs to run an audit.

### Environment

How are you deploying or using Panther?

- Panther master at commit 48f2f244d453bb0cbaa3077c7d80f024b1a97a5c
- OS: Linux (Manjaro 19)

### Additional context

Alert as seen in Panther ;)
```
{
	"awsRegion": "us-west-2",
	"errorCode": "AccessDenied",
	"errorMessage": "User: arn:aws:sts::SOURCE_ACCOUNT:assumed-role/PantherAuditRole/1581973794329971471 is not authorized to perform: SNS:ListTagsForResource on resource: arn:aws:sns:us-west-2:SOURCE_ACCOUNT:panther-notifications-topic",
	"eventId": "85e3d86b-53dc-4bee-a87b-d3367b16493e",
	"eventName": "ListTagsForResource",
	"eventSource": "sns.amazonaws.com",
	"eventTime": "2020-02-17 21:10:16.000000000",
	"eventType": "AwsApiCall",
	"eventVersion": "1.05",
	"recipientAccountId": "SOURCE_ACCOUNT",
	"requestId": "d2b5e14a-91bf-5f75-8536-b78f92c7fb0d",
	"sourceIpAddress": "cloudformation.amazonaws.com",
	"userAgent": "cloudformation.amazonaws.com",
	"userIdentity": {
		"type": "AssumedRole",
		"principalId": "AROA1234ABCD:1581973794329971471",
		"arn": "arn:aws:sts::SOURCE_ACCOUNT:assumed-role/PantherAuditRole/1581973794329971471",
		"accountId": "SOURCE_ACCOUNT",
		"accessKeyId": "ASIA1234ABCD",
		"sessionContext": {
			"attributes": {
				"mfaAuthenticated": "false",
				"creationDate": "2020-02-17T21:09:55Z"
			},
			"sessionIssuer": {
				"type": "Role",
				"principalId": "AROA1234ABCD",
				"arn": "arn:aws:iam::SOURCE_ACCOUNT:role/PantherAuditRole",
				"accountId": "SOURCE_ACCOUNT",
				"userName": "PantherAuditRole"
			}
		},
		"invokedBy": "cloudformation.amazonaws.com"
	},
	"p_log_type": "AWS.CloudTrail",
	"p_row_id": "ae37bc9d7ae2c2daced3b4781a",
	"p_event_time": "2020-02-17 21:10:16.000000000",
	"p_any_aws_account_ids": [
		"SOURCE_ACCOUNT"
	],
	"p_any_aws_arns": [
		"arn:aws:iam::SOURCE_ACCOUNT:role/PantherAuditRole",
		"arn:aws:sts::SOURCE_ACCOUNT:assumed-role/PantherAuditRole/1581973794329971471"
	]
}
```

**Comment by nhakmiller** [comment]
This is quite interesting, as currently we do not scan SNS topics. Let me see if I can reproduce.

**Comment by nhakmiller** [comment]
It seems that when we initiate a stack drift detection the drift detection occurs with the permissions of the role requesting it (makes sense), so when we initiate a stack drift detection of a stack that has SNS topics we run into this issue. I suspect we will run into this issue somewhat frequently as we encounter CloudFormation'able resources for the first time, but this is an easy fix so I will put it in.

**Comment by stoggi** [comment]
Interesting! Will you likely need `ListTagsForResource` for other services too?

**Comment by nhakmiller** [comment]
Seems likely, I'm investigating that now and should have a PR up soon.
