### ISSUE TITLE
Suggest tags for rules and policies

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2043]
### Description

As a user, when I'm filtering rules and policies using tags, I'd like a dropdown to appear that suggests tags that I've used in the past. I'd also like the same function when I'm creating rules and policies. 

### Related Services

Policies, Rules, Rule Creation, Policy Creation

### Designs

TBD

### Acceptance Criteria

-A dropdown of previously used tags that appears when I'm entering tags to filter on in Rules
-A dropdown of previously used tags that appears when I'm entering tags to filter on in Policies
-A dropdown of previously used tags that appears when I'm entering tags in Rule Creation
-A dropdown of previously used tags that appears when I'm entering tags in Policy Creation
-A running list of tags that come from rules and policies that have been created in the past.

**Comment by 3nvi** [comment]
@mattthetraveler to create an epic including BE and FE (design not needed).

FE: consume a BE api to list the tags
BE: provide a way of exposing already used tags in the system
