### ISSUE TITLE
Update support page with new links

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2044]
### Description

Change existing support page in Panther to direct customers to the following links:

Send us Product Feedback: https://portal.productboard.com/runpanther/1-product-portal/tabs/2-in-progress

Join our Community Slack: http://slack.runpanther.io/

Email us at support@runpanther.io

### Related Services

Support Page

### Acceptance Criteria

- eliminate existing "submit a ticket" button and text in support page
- eliminate existing "live chat" button and text in support page
- insert new button and text for "send us Product Feedback" with[ this link](https://portal.productboard.com/runpanther/1-product-portal/tabs/2-in-progress)
- insert new button and text for "join our Community Slack" with [this link](https://portal.productboard.com/runpanther/1-product-portal/tabs/2-in-progress)
- insert text box for email and use "support@runpanther.io"
- for OSS version, insert a text box labeled "Upgrade to Enterprise" that links customers to our demo experience (https://runpanther.io/request-a-demo/)

**Comment by jacknagz** [comment]
FYI @willow9886

**Comment by dimitriszoitas** [comment]
Hey @mattthetraveler please have a [look at this mockup](https://share.goabstract.com/ba3ba938-ffd2-44b1-8368-3895eae96b79?mode=design&sha=73b28dcf286ab6d1ca66aa70dc02744350639f09) and let me know what you think.

I took the liberty to add a secondary/explanatory text below each main title you are describing in the issue. Let me know if that's ok as well.

Thank you

**Comment by jacknagz** [comment]
@dimitriszoitas looks awesome, just left some comments
