### ISSUE TITLE
Create RFC for Compliance reporting coverage

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2045]
### Description

Create RFC for Compliance reporting for various frameworks (MITRE, CIS, PCI, HIPAA, etc). This will help our users understand how much coverage they are achieving for a given compliance.

### Acceptance Criteria

- Understanding of backend work required to feed data into heat map of framework 
- Understanding of frontend work to display heat map in overview page

**Comment by kostaspap** [comment]
This seems like an issue for security  team - edited label.
