### ISSUE TITLE
Many large file downloads can cause "connection reset by peer" errors

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#2048]
### Describe the bug

Large numbers of large file downloads can exceed S3 bandwidth limits resulting in "connection reset by peer" errors.

The log processor should be robust to this and resume reading from the failure point.

### Steps to reproduce

Process concurrently over 100 files of sizes > 150MB.

### Expected behavior

No failures.

**Comment by kostaspap** [comment]
@rleighton  I believe this one is fixed?

**Comment by rleighton** [comment]
Done
