### ISSUE TITLE
Events with 0 occurences

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2061]
### Describe the bug

In event summaries tab of an Alerts page, there are event summaries that appear with "no occurrences". There should be any event summaries with "no occurrences" as that means there's no event.

### Steps to reproduce

1. Go to Alerts
2. Click on an alert
3. Click on Event Summaries
4. Toggle through event summaries, you're likely to find an event summary that has no occurrences

### Expected behavior

If there isn't an occurrence, then there shouldn't be an event summary page generated. Each event summary should be populated. 

### Environment

- Panther version or commit: v1.12.1-release-1.13-01aa240ce

### Screenshots

![image.png](https://images.zenhubusercontent.com/5f99c6c3032b975d7ec7e099/fc51ce01-a428-400c-92fa-a3ff6ce42893)

**Comment by 3nvi** [comment]
This is not currently possible. We have absolutely no knowledge as to whether a summary attribute will yield occurrences or not. 

We have to execute a query and poll to see if there are results, which only happens when you select the attribute from the dropdown. @rleighton any other ideas?

**Comment by rleighton** [comment]
Not a bug ... just means that attribute was not present.
