### ISSUE TITLE
Box onboarding backend error

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2062]
### Describe the bug

An error occurs when trying to onboard Box, requires user to start over

### Steps to reproduce

1. Go to Box onboarding flow in Sources
2. Attempt to configure and set credentials for Box
3. See error- you'll be forced to Start Over

### Expected behavior

User should be able to successfully set up Box after successfully entering in right credentials.

### Environment

- Panther version or commit: v1.12.1-release-1.13-01aa240ce

### Screenshots

![image.png](https://images.zenhubusercontent.com/5f99c6c3032b975d7ec7e099/98f479e5-cd92-4223-ae5b-29c321d6b6b1)

**Comment by s0l0ist** [comment]
I've tested with the latest changes in the release environment `v1.12.1-release-1.13-91f18d70f` and I cannot reproduce after following the docs.

**Comment by mattthetraveler** [comment]
@s0l0ist Did you use the Shared Test account for Box? Credentials are in 1Password, when @AlexPanther used it he was able to reproduce this again

**Comment by kostaspap** [comment]
Issue moved to [panther-labs/panther-enterprise #1458](https://github.com/panther-labs/panther-enterprise/issues/1458) via [**ZenHub**](https://www.zenhub.com/)
