### ISSUE TITLE
Filter by Alert Type

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2063]
### Description

Add ability to filter by Alert Type in the Alerts page. Currently there is no option to filter by Rule Match or Rule Error

![7a38de10-c862-421a-9171-2dc1fcc2cbb5](https://user-images.githubusercontent.com/10436045/99646404-194f1080-2a59-11eb-9e98-afe2017cbeed.png)

### Related Services

Alerts Page

### Designs

TBD

### Acceptance Criteria

- "Alert Type" field in the Rule page filter
- User should be able to filter on "Rule Errors" or "Rule Matches"
- Depending on delivery of this feature, we will also make "Policy Fail" an option

**Comment by 3nvi** [comment]
Hey Matt, I don't see this being shipped in 1.14 since it was not planned, so I'm removing the milestone

**Comment by 3nvi** [comment]
Closing in favor of https://github.com/panther-labs/panther/issues/2022
