### ISSUE TITLE
Mark tables for hiding/deletion in Data Explorer

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2067]
### Description

Ability to mark tables in Data Explorer "Tables" view for hiding or deletion when logs are no longer being ingested from that source.
Link to feature: https://runpanther.productboard.com/feature-board/planning/features/6196424

### Related Services

Data Explorer

### Designs

TBD

### Acceptance Criteria

- in Data Explorer "Tables" view, enable the ability to select tables to perform the following actions:
   - "hide" table, which would grey out the option and indicate that the table is unused 
   - "delete" table, which would eliminate the table from the list of tables entirely.

**Comment by mattthetraveler** [comment]
Hi @kostaspap made this from the Gitlab request from Mitra last week, let me know if this is accurate!

**Comment by kostaspap** [comment]
Issue moved to [panther-labs/panther-enterprise #1442](https://github.com/panther-labs/panther-enterprise/issues/1442) via [**ZenHub**](https://www.zenhub.com/)
