### ISSUE TITLE
Data Models

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2072]
### Description

As an analyst, I want to be able create and maintain universal data models in the UI that I can reference when writing new rules and policies in the Python editor (see example [here](https://github.com/panther-labs/panther-analysis/pull/156).

Ideally, this is a separate sub-tab in Settings that presents a view of all the Data Models I have active and where I can also add new Data Models.

### Related Services

[See Backend services here](https://github.com/panther-labs/panther/pull/1945)

### Designs

Here is the[ RFC](https://github.com/panther-labs/panther-enterprise/tree/master/designs/security/simplify-detections)

Here are the [Designs](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/df9d59c8-eeb1-452d-a5f5-3712b64010be/collections/65b935ef-579f-4620-9530-c359b8d416e3)

### Acceptance Criteria

- Add a new "Data Models" sub-tab under Settings in current UI, should be under Analysis 
- To add new Data Model, form should have two sections: Settings and Data Model Mappings
- Within Setting tab, available attributes should be Log Types, Detection ID, and Enabled
- Within Data Model Mappings tab: 
   - there should be a field to drop in a YAML function. This should be mandatory for the user.
   - there should an option to drop in a Python Module. This should be optional for the user.
- Within the Data Models view page:
   - Ability to bulk select Data Models with the option to "Delete"
   - Ability to filter by "Most Recent" and "Last Modified", should default to "Last Modified"
- When using Bulk Uploader, update the summary results to include a summary of Data Models that were uploaded after upload is complete
   - There should be a 4 summary box (next to Python Modules, Rules, Policies, and Data Models) with a summary of what's New, Modified, and Total

**Comment by 3nvi** [comment]
@mattthetraveler should we close this?

**Comment by mattthetraveler** [comment]
Hi @3nvi I've updated the description

**Comment by mattthetraveler** [comment]
Hey @3nvi is the 4th PR for this intended to be for updating bulk uploader?

**Comment by 3nvi** [comment]
It relates to filtering. Bulk uploading has another ticket.

4rth PR might never come 😄
