### ISSUE TITLE
Introduce Custom Logs apis

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#2090]
### Description

Introduce the BE components for supporting Custom Logs

### Acceptance Criteria

All Custom Logs-related code is in OSS.

**Comment by mattthetraveler** [comment]
Hey @alxarch or @kostaspap how is this looking for 1.14? is there an RFC with more detailed acceptance criteria as well?

**Comment by kostaspap** [comment]
> Hey @alxarch or @kostaspap how is this looking for 1.14? is there an RFC with more detailed acceptance criteria as well?

This is just about backporting the Custom logs feature to OSS (the feature is already in Enterprise)
