### ISSUE TITLE
Missing input validation for the AWS.S3.Bucket Read and Right Cloud Security Policies

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2093]
### Describe the bug

The AWS.S3.Bucket Read and Right Cloud Security policies are missing input validations which is causing an error in a customers (DropBox) deployment as their resources are missing key "grants"

### Steps to reproduce

1. Add S3 bucket without key grants as a resource
2. See errors generated from AWS.S3.Bucket Read and Right Cloud Security policies

### Expected behavior

if 'Grants' in resource and resource['Grants'] is not None:`

```
{
	“Arn”: “arn:aws:s3:::something-prodsec”,
	“LoggingPolicy”: null,
	“Policy”: null,
	“MFADelete”: null,
	“ObjectLockConfiguration”: null,
	“LifecycleRules”: null,
	“Grants”: null,
	“Versioning”: null,
	“EncryptionRules”: null,
	“PublicAccessBlockConfiguration”: null,
	“AccountId”: “123456789”,
	“Tags”: {
		“something”: “ttd”,
		“user”: “prodsec”,
		“service”: “-”,
		“owner”: “-”,
		“team”: “-”
	},
	“Region”: “us-west-2",
	“ResourceType”: “AWS.S3.Bucket”,
	“Name”: “something-prodsec”,
	“ResourceId”: “arn:aws:s3:::something-prodsec”,
	“TimeCreated”: “2020-06-27T00:11:11Z”,
	“Owner”: {
		“DisplayName”: “aws-corp”,
		“ID”: “15e2a86ec386eb589bcad5377520a52e0e0717cdc970d2a643d3b60374984dda”
	}
}

```
### Environment

- Panther version v1.12

### Screenshots

![image.png](https://images.zenhubusercontent.com/5f99c6c3032b975d7ec7e099/0f1bcd19-da2c-4b7f-be9a-b3a91f818d80)

![image.png](https://images.zenhubusercontent.com/5f99c6c3032b975d7ec7e099/a9bf42a8-415a-4cbb-aa49-85d7f0b943b1)

**Comment by kostaspap** [comment]
Cloud Security is responsibility of the Security Engineering team - reassigning.

**Comment by mattthetraveler** [comment]
Issue is closed [here](https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther-analysis/147)
