### ISSUE TITLE
General Settings displays Lambda Role Names and not ARNs

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2094]
### Describe the bug

Currently in the Settings>General page, there are two fields that have Lambda Role ARN in the title but only display the Lambda Role name. Role names are important but users are confused by how the fields are titled. See below:

![image.png](https://images.zenhubusercontent.com/5f99c6c3032b975d7ec7e099/3b77aada-b30e-46f1-a1c1-84b35323e9c2)

We should correct the titles to say (Database) ReadOnly Lambda Role Names and (Database) Admin Lambda Role Names. Users also need ARNs to change permissions, so we should add two more fields for the ARNs.

### Steps to reproduce

1. Go to General>Settings
2. View right column settings, see 2 Lambda Role ARN fields

### Expected behavior

Should display Role Names in current fields and we should have 2 additional fields that display actual ARNs. Fix should be broken out like this:

- Correct current title names to say '(Database) ReadOnly Lambda **Role Name**' and '(Database) Admin Lambda **Role Name**' instead of ARN
- Add two fields that displays actual ARNs and title them as so: '(Database) ReadOnly Lambda **Role ARN**' and '(Database) Admin Lambda **Role ARN**'

### Environment

- Panther version or commit: v1.13

### Additional context

This was brought up by Auth0 who was looking to update permissions

### Screenshots

![image.png](https://images.zenhubusercontent.com/5f99c6c3032b975d7ec7e099/3b77aada-b30e-46f1-a1c1-84b35323e9c2)

**Comment by rleighton** [comment]
Fixed here: https://github.com/panther-labs/panther-enterprise/pull/1473
