### ISSUE TITLE
Rule/Policy editor bug when trying to update tests

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#210]
### Describe the bug

When trying to update the Log Type or expected result for a rule test through the web UI, it does not work for any test except for the first test.  Additionally, when you update the second/third/nth test it actually updates the first test instead. See the screen recording for a walkthrough of the issue.

### Steps to reproduce

1. Go to the rule editor
2. Try to edit the expected result for any test except the first test
3. The test fails to update
4. Go back to the first test, observe that it has been updated in the way you tried to update the other test
5. Running the tests confirms its not just a graphical issue

### Expected behavior

Updating the nth test updates the nth test, and not the first test.

### Environment

Master at 48f2f24
Google chrome Version 79.0.3945.130 (Official Build) (64-bit)

### Additional context

I don't demonstrate it in the screen recording, but the same thing happens for the Log Type field.

I was able to replicate on multiple different rules.

I was also able to replicate it on policies in the policy editor as well.

### Screenshots

[Screen Recording 2020-02-18 at 1.08.43 PM.mov.zip](https://github.com/panther-labs/panther/files/4221681/Screen.Recording.2020-02-18.at.1.08.43.PM.mov.zip)

**Comment by 3nvi** [comment]
Hmm interesting. That could be tied to a form dependency update that altered the behavior. I'll investigate today
