### ISSUE TITLE
Failed to classify CrowdStrike `aid_master` event

### ISSUE THREAD

**Issue by giorgosp** [panther-labs/panther#2109]
### Describe the bug

The CrowdStrike `aid_master` can be sent through FDR and contains info to relate the `aid` (sensor id) field to `ComputerName`.
The schema of the event doesn't match our `CrowdStrike.Unknown` schema, so we need a separate parser for it (or update the `CrowdStrike.Unknown` schema).

### Steps to reproduce

I have created a CrowdStrike integration, contacted their support to enable the `aid_master` field and saw `failed to classify` in the logs.

### Expected behavior

The `aid_master` event ends up in our data lake, either in the `crowdstrike_unknown` table or in a new `crowdstrike_aidmaster` table.

**Comment by georgepsarakis** [comment]
As mentioned in the description, the failure to classify is explained specifically by the absence of the `event_simpleName` field in this type of event:

https://github.com/panther-labs/panther/blob/9a217c13af85d8ed328faaf894ac3db708b122be/internal/log_analysis/log_processor/parsers/crowdstrikelogs/unknown.go#L52

As far as I understand, [`aid_master`](https://developer.crowdstrike.com/crowdstrike/docs/falcon-data-replicator-guide#section-aid-master) is a special type of raw event provided by the Falcon Data Replicator and originating from [Falcon Insight](https://www.crowdstrike.com/endpoint-security-products/falcon-insight-endpoint-detection-response/). Thus a separate parser will be necessary.

**Comment by giorgosp** [comment]
That's true. Since the events for Falcon Insight are just 3 (`aid_master`,`managedassets`, `notmanaged`) I think it makes sense to have separate parsers for them.
