### ISSUE TITLE
New plain button component

### ISSUE THREAD

**Issue by vorillaz** [panther-labs/panther#2125]
### Description

Up until now, all buttons in Panther are either "solid" or "with an outline". In JSON view for indicator search, a new kind of button was introduced. 
![Screenshot 2020-11-26 at 10 10 52 PM](https://user-images.githubusercontent.com/1022166/100388890-8b64be00-3034-11eb-944d-e2b16b59aadc.png)

Although the buttons can be reconstructed using building blocks from pounce essentially we shall deliver these as standalone components (with hover, active, disabled state, etc...)

**Comment by 3nvi** [comment]
@dimitriszoitas is this whole entity a button? I thought it was only the icon thas was a button

**Comment by dimitriszoitas** [comment]
@vorillaz I have annotated and tagged you in the section where I've added the various states of this button. Let me know If you're ok with it. Thanks!
