### ISSUE TITLE
Support Custom Logs schema updates

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#2126]
### Description

Users should be able to update schemas that they have already created in order to: 
1. Add a new column
2. Add an indicator to an existing column
3. Investigate if possible to remove existing columns

### RFC

TBD

### Designs

TBD

### Acceptance Criteria

- Users can add a column to an existing schema. The new column should be queryable through the data lake and available to the streaming rules
- Users can add an indicator to an existing column. 
- In case an update is not possible, the UI should notify the users

**Comment by 3nvi** [comment]
Reopening as this is an an epic that involves FE work as well
