### ISSUE TITLE
Design Alert Detail Page for Policy Alerts

### ISSUE THREAD

**Issue by dimitriszoitas** [panther-labs/panther#2135]
### Description

Since we're creating alerts generated from Policies, we need to have a detail page for them as well.

### Acceptance Criteria

- Layout similar to Rule Alerts without Events or Summarty Tab

**Comment by dimitriszoitas** [comment]
@3nvi [have a look](https://share.goabstract.com/4fac9036-b9c3-41bb-af26-1d5698df4203) and let me know if everything is ok

**Comment by 3nvi** [comment]
Looks ok @dimitriszoitas . Feel free to close this once the changes are merged into v1.15 branch
