### ISSUE TITLE
Destinations - Support JIRA Custom Fields

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#2154]
### Describe the ideal solution

JIRA allows teams to create [custom fields](https://confluence.atlassian.com/adminjiraserver/adding-a-custom-field-938847222.html) for their issues to adapt JIRA to their workflow. These fields can be [marked as required](https://support.atlassian.com/jira-cloud-administration/docs/specify-field-behavior/). If a team has configured a custom field and specified as required, then the Panther JIRA destination will fail.

As a user of Panther, I don't want to modify my in place JIRA workflow to make Panther work, I want to be able to configure Panther to integrate into my custom JIRA workflow. To support this, Panther would need to be able to specify arbitrary custom fields (and their values) as part of the JIRA destination.

### Describe your use cases

Integrating with custom in place JIRA workflows.

### How frequently would you use such feature

Daily/weekly, depending on how alerts are configurued.

### Describe alternatives you have considered

Alternatively I could modify my JIRA workflow to make these fields not be required, but that would be sub-optimal.

**Comment by austinbyers** [comment]
@s0l0ist I believe we can close this now?
