### ISSUE TITLE
Allow deployment of Panther into existing subnets

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#2159]
### Description

By default, Panther creates a new VPC, Security Group, and two new subnets to deploy  the panther web app load balancer into. This behavior can be overridden, and  users can instead specify an existing VPC & Security Group, and the deployment will create two subnets within that VPC.

Some teams do not have access to create subnets in their network. In this case, it would be preferable to also be able to specify existing subnets and have Panther use those.

### Related Services

The panther load balancer would need to be updated to accept existing subnets, instead of the ones created by Panther.
 
### Designs

None

### Acceptance Criteria

- A user deploys Panther, specifying an existing VPC,  Security Group,  and two existing subnets
- Panther uses these existing networking resources when configuring the web application and the web application load balancer
- Panther does not create any networking infrastructure except for the load balancer.

**Comment by donbecker** [comment]
A quick suggestion here, on a deployment of 1.13.0, the subnets used will need a route to the internet for the image pull. If there will be a validation check on the subnets it may be good to check you have an external route. Otherwise during an install the stack fails after 20 mins when the web stack fails, then does a full rollback.

**Comment by 3nvi** [comment]
Yeah that's true. As long as deployments pull a docker image from a Panther managed ECR, we definitely need something like that

**Comment by kostaspap** [comment]
> A quick suggestion here, on a deployment of 1.13.0, the subnets used will need a route to the internet for the image pull. If there will be a validation check on the subnets it may be good to check you have an external route. Otherwise during an install the stack fails after 20 mins when the web stack fails, then does a full rollback.

> Yeah that's true. As long as deployments pull a docker image from a Panther managed ECR, we definitely need something like that

I think adding a [ECR VPC Endpoint](https://docs.aws.amazon.com/AmazonECR/latest/userguide/vpc-endpoints.html) in the VPC would solve the problem as well. We shouldn't have to go through an IGW for talking to any AWS service.

**Comment by 3nvi** [comment]
> > A quick suggestion here, on a deployment of 1.13.0, the subnets used will need a route to the internet for the image pull. If there will be a validation check on the subnets it may be good to check you have an external route. Otherwise during an install the stack fails after 20 mins when the web stack fails, then does a full rollback.
> 
> > Yeah that's true. As long as deployments pull a docker image from a Panther managed ECR, we definitely need something like that
> 
> I think adding a [ECR VPC Endpoint](https://docs.aws.amazon.com/AmazonECR/latest/userguide/vpc-endpoints.html) is the way AWS recommends solving this issue. We shouldn't have to go through an IGW for talking to any AWS service.

Wasn't aware of this. Yeah you're right.
