### ISSUE TITLE
[FE] Dynamic Alert Fields Support

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2166]
### Description

As an Analyst, I want to be able to dynamically set the severity of an alarm to:
- Route alarms on critical and production resources to monitored Slack channels or kick off related workflows
- Similarly, they can choose to send lower priority alarms to a lower-priority queue to be triaged
- Tailor the alarm runbook and description
I can do this with the new functions `description`, `severity`, `destination`, etc. Now that I can set these fields, I want to see their test results when running unit tests from the UI.

### Related Services

web:
- Edit Rule
- Alert Details page 

### Designs

Find RFC [here](https://github.com/panther-labs/panther-enterprise/pull/1095/files?short_path=f1e6929#diff-f1e69298df6b23442c7d0ca35b77b0050c235b672d5678bae61b0563acbd6900)

### Acceptance Criteria
- Add all dynamic alert fields to `AlertSummary` and `AlertDetails`
- In Edit Rules page:
  - In the Test Result component, in addition to what is already shown (pass/fail status, title and dedup string) we should also display the dynamic fields (i.e. `reference`, `runbook`, `description`, `severity`, and `destination overrides`) if the related function has been defined for it. These fields **might** be present from the API, depending on whether the user has specified the related functions or not.

- In Alert Details page:
  - Whenever displaying any of the dynamic-alert fields, frontend should make sure to read those values directly from the alert itself and **not** from the rule/policy that's associated to this alert

**Comment by mattthetraveler** [comment]
@wey-chiang and @nhakmiller created this issue to capture remaining FE work to bring this to close (took Nick's summary as the acceptance criteria). Let me know if there's any other nuances that should be captured in FE work!

**Comment by nhakmiller** [comment]
I think the acceptance criteria addresses two separate issues, the first bullet point is pretty straightforward I think but it's basically extending existing functionality.

The second bullet point changes how the frontend talks to the backend. Whoever the frontend person is that implements this can coordinate with myself or preferably @wey-chiang but essentially the frontend should no longer communicate to the `analysis-api` when getting alert info. It should only talk to the `alerts-api`. I imagine this is mostly a graph-ql change, but I'm not 100% sure.

**Comment by 3nvi** [comment]
> The second bullet point changes how the frontend talks to the backend. Whoever the frontend person is that implements this can coordinate with myself or preferably @wey-chiang but essentially the frontend should no longer communicate to the analysis-api when getting alert info. It should only talk to the alerts-api. I imagine this is mostly a graph-ql change, but I'm not 100% sure.

Although that's purely a graphql change, we currently make a separate call to the `getRule` lambda function within the alert details page to populate the alert with additional information (runbook, reference, threshold). We can't change the resolver in `getRule` since this is used in multiple places. What we instead need to do is to extend the `getAlert` resolver to also make a call to a different function, get this dynamic data and pass it to the FE (we could remove the `getRule` call, but I don't know if the dynamic-fields API has all the data I need)

This is ok for the details page of an alert (1 call for alert, 1 for rule data & 1 call for dynamic fields), but what happens in the list alerts page? I can't make N + 1 calls there (1 for alert summaries list + N for the dynamic fields of each alert). That's a small performance blocker.

I personally feel that all this should come from the `alerts-api`. We already have a lot of inconsistencies by not storing these data within the alert (i.e. imagine a Rule had `LOW` severity, it generated an alert, and then we changed the Rule and its severity to `CRITICAL`. Now the alert would be marked falsely as `CRITICAL` although it was generated while the rule had a different code & severity attached to it). Because of that I'd like to explore the ability to put the dynamic fields as metadata of the alert itself, rather than data of a different API. If you've talked about this and it's a no-no, then we can move away from this solution.

Generally, this ticket requires a certain engineering discussion and I feel that only way to make progress is to hop on a call. Would somebody be willing to discuss it further?

**Comment by nhakmiller** [comment]
> I personally feel that all this should come from the alerts-api. We already have a lot of inconsistencies by not storing these data within the alert <...>. Because of that I'd like to explore the ability to put the dynamic fields as metadata of the alert itself, rather than data of a different API. If you've talked about this and it's a no-no, then we can move away from this solution.

Perhaps there is some misunderstanding, but this is exactly what I'm suggesting. `GetAlert` should make one API call to the `alerts-api` which will return all the needed info. `ListAlerts` should also make one API call to the `alerts-api`, which will return all the needed info. The `alerts-api` lambda will handle talking to any other backend systems if necessary (it shouldn't be going forward but for backwards compatibility sake it might be). @wey-chiang has begun this work, although there may still be some backwards compatibility work needed.

**Comment by 3nvi** [comment]
ah gotcha! Sorry I thought you originally meant the following:

"The graphql resolver will need to get the alert details from `getAlert` and then make **another** call to some other function to get the dynamic fields of this alert".

Yeah the acceptance criteria is a bit confusing. @mattthetraveler  If you don't mind, I'll update them to something more familiar to a FE engineer

**Comment by mattthetraveler** [comment]
By all means! Do we still need a call to align on this @3nvi ?

**Comment by 3nvi** [comment]
I don't think so, but I'd love if @nhakmiller or @wey-chiang could link to the updated `AlertSummary` & `AlertDetails` structs in the backend when they are implemented, while highlighting the (dynamic) fields that were added. This will allow us to modify the GraphQL schema accordingly.


> @wey-chiang has begun this work, although there may still be some backwards compatibility work needed.

@nhakmiller can you tag the related work and put it as "blocking" for the current FE issue?

**Comment by nhakmiller** [comment]
> @nhakmiller can you tag the related work and put it as "blocking" for the current FE issue?

The backend is storing these fields with the alerts as of #2106, but I don't think it is returning them from the `GetAlert` API call. It should just be a few lines of backend code, I'll ask Weyland to take a look this week if possible.

**Comment by 3nvi** [comment]
Sure thing. Btw they should be in both `AlertSummary` and `AlertDetails` structs

**Comment by nhakmiller** [comment]
> Sure thing. Btw they should be in both `AlertSummary` and `AlertDetails` structs

The backend directly embeds the `AlertSummary` struct in the `AlertDetails` struct I believe. When the frontend makes a `ListAlerts` API call, does it have to make an additional API call for each result? Or is that just for the `GetAlert` API call?

**Comment by 3nvi** [comment]
The `ListAlerts` contains all we need for displaying the UI for the "list alerts" page. We don't make any additional caclls when we are listing multiple alerts.

Thus, in order to show dynamic fields in the alerts page, the needed info **must** be contained within `ListAlerts`

**Comment by wey-chiang** [comment]
> > Sure thing. Btw they should be in both `AlertSummary` and `AlertDetails` structs
> 
> The backend directly embeds the `AlertSummary` struct in the `AlertDetails` struct I believe. 

The `alerts_api` has `AlertSummary` struct embedded only in the `Alert` struct and the `ListAlertsOutput` struct

**Comment by wey-chiang** [comment]
[Drafted a PR](https://github.com/panther-labs/panther/pull/2245/) with changes to the `alerts_api` 

Added `api` to a few function calls & declarations

Main change in logic is in the `utils.go` file:
- Created a new `getRule` function
- `getRule` is only called if any of the generated fields are missing (was having issues getting unit tests to work without this)

**Comment by 3nvi** [comment]
@wey-chiang yup, I saw. Thanks for that!

**Comment by wey-chiang** [comment]
@mattthetraveler @vorillaz Will updating the documentation to fully cover this new feature be included in this work or is that a separate ticket?

**Comment by mattthetraveler** [comment]
Thank you @wey-chiang ! Moving forward we should have a separate ticket for docs for new features

**Comment by 3nvi** [comment]
Missing  the following:

> In Alert Details page:

Whenever displaying any of the dynamic-alert fields, frontend should make sure to read those values directly from the alert itself and not from the rule/policy that's associated to this alert
