### ISSUE TITLE
Admins can delete themselves

### ISSUE THREAD

**Issue by alexmylonas** [panther-labs/panther#217]
### Describe the bug

As the only admin user on the Panther UI, I have the option to delete myself which may lead to unexpected behaviours and a hard recovery process for the account.

### Steps to reproduce

Steps to reproduce the behaviour:

1. Deploy Panther
2. Log in as an admin
3. Delete all other users
4. Delete your user

### Expected behavior

This is pretty open ended imo. Some solutions that we can implement:
1. Only admin cant delete himself either on frontend and/or backend
2. Admins in general can't delete themselves.
3. Last admin must promote someone else as admin before deleting
4. If we allow only admin to be removed, shouldn't a cleanup process triggered?

### Environment

How are you deploying or using Panther?

- Panther version or commit: v0.3
- OS: MacOS 10.15.3
- Browser: All

**Comment by 3nvi** [comment]
Thanks a lot for that!

Although we can easily handle it in the front-end, I believe that the check should perhaps be present only in the backend. Personally, I think that the check should that "There should always be 1 admin present in the system".

Thus, I feel that ta user **should indeed** be able to delete themselves, but only if there is at least one admin lying around. @austinbyers what do you think?

**Comment by austinbyers** [comment]
Agreed - the backend should prevent the last admin user from deleting themselves.

I'll address this as part of the new `users-api` under development

**Comment by 3nvi** [comment]
Perfect, thanks a lot!
