### ISSUE TITLE
Log Analysis Overview - empty chart, glitch with logarithmic

### ISSUE THREAD

**Issue by s0l0ist** [panther-labs/panther#2178]
### Describe the bug

The `Most Active Rules` doesn't show anything even if the data returned is empty. In fact, it doesn't show data at all when there is supposed to be data -- this is a bug with metrics.

When viewing charts in the **logarithmic** mode, the graph timeline is off by a little. By adjusting the bottom time line bar a tiny bit causes the graph to re-draw it correctly.

### Steps to reproduce

1. Go log analysis overview page
2. Click on `Most Active Rules` tab, see nothing
3. Click on any `Logarithmic` mode, then barely adjust the time window bottom bar, see it re-draw.

### Expected behavior

Should have a placeholder for empty data. It should also show data 

### Environment

How are you deploying or using Panther?

- panther v1.14.0-RC

### Screenshots
![image](https://user-images.githubusercontent.com/3663107/100948457-8210a100-34cd-11eb-994b-d90402881c12.png)

![log-analysis-graph-glitch-2](https://user-images.githubusercontent.com/3663107/100948321-3b22ab80-34cd-11eb-9d4c-3d49950bdf28.gif)
![log-analysis-graph-glitch](https://user-images.githubusercontent.com/3663107/100948334-3f4ec900-34cd-11eb-9b52-8c02dee52014.gif)

**Comment by dimitriszoitas** [comment]
Hello, please have a look at[ this screen](https://share.goabstract.com/fa7e6294-3a25-4f43-8302-037035226bd4?mode=design&sha=03d7eb4d679a0c917528fef6829de2720bd5c84b) and let me know if we're ok

**Comment by 3nvi** [comment]
Looks god @dimitriszoitas , I'll take it over from here
