### ISSUE TITLE
Some log type reporting null p_source_id, p_source_label

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#2180]
### Describe the bug

Seeing null `p_source_id`, `p_source_label` columns for data onboarding through S3.

### Steps to reproduce

1. Go to Log Analysis -> Sources
2. Onboard a CloudTrail log type
3. Wait until you have received some data
4. Run the query :
```
SELECT p_source_label, p_source_id FROM panther_logs.aws_cloudtrail
```
5. See `NULL`s

### Expected behavior

`p_source_id`, `p_source_label` should ALWAYS be populated

### Environment

How are you deploying or using Panther?

- Panther version or commit: 1.13

### Additional context

This seems to affect data that have been migrated to the new parser scheme

**Comment by alxarch** [comment]
Very weird, I remember writing the exact code that was added to fix this...
