### ISSUE TITLE
Get rid of Sort by Enabled/Disabled in Rules page

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2190]
### Description

In rules page filter, users can filter by Enabled/Disabled. We also have these same two options available in Sort By. We should get rid of Enabled and Disabled in the Sort By dropdown as it adds clutter to the selection.

### Related Services

Rules Page

### Designs

N/A

### Acceptance Criteria

- Eliminate Enabled as an option from the Sort By dropdown in Rules page
- Eliminate Disabled as an option from the Sort By dropdown in Rules page
This acts as a checklist and high-level context for anyone reading this issue to verify your implementation.

For example:

- We can collect anonymized frontend crash logs from user browsers
- Users can opt in to send these logs to panther
- The crash logs will contain the following fields : browser version
- Users can opt-out from collection at any time
- ...

**Comment by 3nvi** [comment]
Went ahead and added a `p3` for this since it's a nice to have
