### ISSUE TITLE
Logs: Windows Event via Fluentd

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#2191]
### Description

Windows Event logs are traditionally in a difficult to parse format, but Fluentd has native support for ingesting and writing them as JSON. The goal of this story is to write Panther schemas for all related Windows Events that are passed through Fluentd. The data flow is something like this:

Windows Box -> [Fluentd](ttps://docs.fluentd.org/input/windows_eventlog) -> S3 (via `out_s3`) -> Panther

### Related Services

Log Processor

### Designs

None

### Acceptance Criteria

- Panther can natively support Windows Event Logs via Fluentd
- Users can search through various event types in SQL and write Python-based detections

**Comment by horakj** [comment]
Testing variations of Events to Schema in order to ensure backwards compatibility

**Comment by horakj** [comment]
Converting Custom Schema to Go parser
