### ISSUE TITLE
Data Analytics - Docs Refactor

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2208]
### Description

In an effort to make our Docs easier to navigate, we should update the structure in which are Docs are presented and add in new content based on customer feedback.

### RFC

[RFC](https://panther-labs.atlassian.net/wiki/spaces/EN/pages/800325652/RFC+New+Docs+Layout)

### Acceptance Criteria

Refactor Data Analytics to the below structure:
Data Analytics
- Data Explorer
- Indicator Search
- Backends
  - Snowflake
  - Athena

-Review each doc to ensure everything is up to date

**Comment by mattthetraveler** [comment]
Tagging Data Analytics team to this effort. Looking to get feedback and help with the new "Data Analytics" section of our docs.

**Comment by serbantanasa** [comment]
https://github.com/panther-labs/panther-enterprise/pull/1825
