### ISSUE TITLE
[FE] Add launch command for aws cli for adding cloud source

### ISSUE THREAD

**Issue by donbecker** [panther-labs/panther#2237]
### Describe the bug

When adding a cloud source via the web console, after downloading the CLI file, I'd like the web UI to supply the command to run it

### Expected behavior

"Download the autogenerated Cloudformation template and deploy it to the AWS account that you are onboarding via: 

`aws cloudformation deploy --template ./panther-cloudsec-setup.yaml --stack-name panther-cloudsec-setup`

### Environment

How are you deploying or using Panther?

- Panther version: 1.13.0

**Comment by donbecker** [comment]
It appears the correct command may be: 

`aws cloudformation deploy --template ./panther-cloudsec-setup.yaml --stack-name panther-cloudsec-setup --capabilities CAPABILITY_NAMED_IAM`

**Comment by 3nvi** [comment]
Thanks for the issue @donbecker . We'll sync with the team and see when we can allocate time for this. I'll go ahead and modify the related label to "enhancement" since this is not classified as a bug.

**Comment by kostaspap** [comment]
@giorgosp  this seems it could be part of the S3 onboarding revamp work?

**Comment by 3nvi** [comment]
> @giorgosp this seems it could be part of the S3 onboarding revamp work?

Yeah but this recommendation is linked to the Cloud Security Source onboarding, so I feel it's something different

**Comment by giorgosp** [comment]
It applies to wherever we prompt users to install a CFN stack
