### ISSUE TITLE
RDS Scanning Failing due to " db-instance-id is not a valid identifier"

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#2240]
### Describe the bug

InvalidParameterValue: The parameter Filter: db-instance-id is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens.
status code: 400, request id: ffbfa46e-3c0a-4572-9b32-b524d6132cad
RDS.DescribeDBInstances: arn:aws:rds:us-west-2:XXXXXXXX:db:
github.com/panther-labs/panther/internal/compliance/snapshot_poller/pollers/aws.getRDSInstance
/Users/austin/go/src/github.com/panther-labs/panther-enterprise/internal/compliance/snapshot_poller/pollers/aws/rds_instance.go:123
github.com/panther-labs/panther/internal/compliance/snapshot_poller/pollers/aws.PollRDSInstance
/Users/austin/go/src/github.com/panther-labs/panther-enterprise/internal/compliance/snapshot_poller/pollers/aws/rds_instance.go:87
github.com/panther-labs/panther/internal/compliance/snapshot_poller/pollers/aws.singleResourceScan
/Users/austin/go/src/github.com/panther-labs/panther-enterprise/internal/compliance/snapshot_poller/pollers/aws/poll.go:311
github.com/panther-labs/panther/internal/compliance/snapshot_poller/pollers/aws.Poll
/Users/austin/go/src/github.com/panther-labs/panther-enterprise/internal/compliance/snapshot_poller/pollers/aws/poll.go:172
github.com/panther-labs/panther/internal/compliance/snapshot_poller/pollers.Handle
/Users/austin/go/src/github.com/panther-labs/panther-enterprise/internal/compliance/snapshot_poller/pollers/lambda.go:85

### Steps to reproduce

See in a deployment. Ask Russ.

**Comment by nhakmiller** [comment]
I think this was fixed in this patch 9 days ago: https://github.com/panther-labs/panther/pull/2142. Unfortunately looks like it missed 1.14 and GA is going out today, it will be in 1.15.
