### ISSUE TITLE
Add support for new event types in CloudSecurity scanning

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#2243]
### Description

Below are events found we do not support:

**CloudWatch Logs Insights**  
region: us-west-2  
log-group-names: /aws/lambda/panther-aws-event-processor  
start-time: -604800s  
end-time: 0s  
query-string:
```
filter  @message like 'unknown event name'
| fields eventName
| stats count(*) as c by eventName
| sort by c desc
| limit 2000
```
---------------------------------------------
|             eventName              |  c   |
|------------------------------------|------|
| DiscoverPollEndpoint               | 8374 |
| ModifyNetworkInterfaceAttribute    | 134  |
| CreateNetworkInterfacePermission   | 130  |
| ModifyVpcEndpoint                  | 109  |
| AllocateAddress                    | 100  |
| CreateNatGateway                   | 90   |
| SharedSnapshotVolumeCreated        | 82   |
| ReleaseAddress                     | 42   |
| DeleteNatGateway                   | 36   |
| CreateVpcEndpoint                  | 12   |
| DeleteInstanceProfile              | 11   |
| DeleteVpcEndpoints                 | 6    |
| GenerateServiceLastAccessedDetails | 5    |
| PutFunctionConcurrency20171031     | 4    |
| SimulatePrincipalPolicy            | 2    |
| PutFunctionEventInvokeConfig       | 1    |
| UpdateFunctionEventInvokeConfig    | 1    |
| CreateKeyPair                      | 1    |
| DeleteFunctionConcurrency20171031  | 1    |
| ImportKeyPair                      | 1    |
| ReleaseHosts                       | 1    |
| AllocateHosts                      | 1    |
| RebootInstances                    | 1    |
---------------------------------------------

**Comment by rleighton** [comment]
I assigned to @wey-chiang not because it is his, just to get attention to prioritize.

**Comment by wey-chiang** [comment]
Nice, I had some of these queued up but did not realize there were this many!

@rleighton Would it be possible to include the AWS service associated with these events? I know some of these are related to different services i.e. ELBv2, ECS, etc.
