### ISSUE TITLE
It should be possible to hide from the Data Explorer view tables of Custom schemas that are deleted

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#2250]
### Description

Right now, when deleting a custom schema, 

### Designs

TBD

### Acceptance Criteria

- Users can have the option to hide from the Data explorer view the Custom tables that don't have a corresponding schema defined
- The contents of the tables will still be searcheable through Indicator search
- Alerts that have fired for that tables will still have access to that data.

**Comment by mattthetraveler** [comment]
Hey @kostaspap does [this design work](https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther-enterprise/1493) cover this issue?

**Comment by kostaspap** [comment]
> Hey @kostaspap does [this design work](https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther-enterprise/1493) cover this issue?

Yup. Closing this one as duplicate of https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther-enterprise/1442
