### ISSUE TITLE
Group log types together

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2257]
### Description

When selecting log types in rule creation or log onboarding, group together log types that are generally selected together to make it easier for users to set log types.

Example:
As a user onboarding CloudTrail logs as a log source, I usually intend to onboard all types of CloudTrail logs (CloudTrail, CloudTrailInsights, CloudTrailDigest) but sometimes don't click all three. It would be helpful to have all 3 grouped together. 

### Related Services

Data model creation
Rule creation

### Designs

TBD 

### Acceptance Criteria

- Agreed upon list of groupings from engineering team
- Backend api changes to group log types together
- Update log type dropdown in detection creation interface with groupings
- Update log type dropdown in data model creation interface with groupings

**Comment by jacknagz** [comment]
We should update this ticket to apply to all log types by Group. For example, when I type 'CiscoUmbrella', it selects all of the subtypes and then the user can de-select certain ones if desired

**Comment by kostaspap** [comment]
> We should update this ticket to apply to all log types by Group. For example, when I type 'CiscoUmbrella', it selects all of the subtypes and then the user can de-select certain ones if desired

Note that while updating it in the UI will be a short-term fix, we are planning to do a revamp of this in the BE.

**Comment by giorgosp** [comment]
Just found out about this ticket, it would be great if we implemented a "grouped dropdown" as discussed before with @3nvi. This could be handled by the FE alone, without any changes to the backend - providing that if a user selects a log type group, the frontend sends all the log types of the group to the backend.

**Comment by jacknagz** [comment]
@mattthetraveler @3nvi can we get this on the next sprint or the one after?

**Comment by 3nvi** [comment]
If it's indeed a p1, then sure, we can pick it up.

This issue though is significantly harder than it seems and we'll need changes in the Pounce components that our application uses, so we can create "groups" within a dropdown, allow for mass-selection of items within a group, etc.

With the acceptance criteria currently set,  the first thing would be to have @dimitriszoitas design a prototype and then schedule a call to discuss edge cases, initial values, item selection & clearing patterns, etc.

@mattthetraveler should I or you own this?

**Comment by jacknagz** [comment]
@3nvi can you own it?

**Comment by 3nvi** [comment]
Sure

**Comment by mattthetraveler** [comment]
Hey @dimitriszoitas could you share the designs you showed us last week for the log type groupings?
