### ISSUE TITLE
BE: Hide tables of deleted custom logs from table explorer

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#2261]
### Description

DatabaseAPI should offer a method that filters out any custom log tables that are deleted. Alternatively, an existing method can be modified.

### Related Services

panther-database-api, panther-logtypes-api

### Acceptance Criteria

- DatabaseAPI offers a method that filters out any custom log tables that are deleted. Alternatively, an existing method can be modified.

**Comment by 3nvi** [comment]
FE-wise it would be easier to add an entry in the response payload, denoting if this table is `stale` or not. That would prevent us from having to make an additional API call and would make our lives easier :smile

**Comment by rleighton** [comment]
My thoughts were that users can "hide" a table and the UI would call the database api "SupressTable()" and it would mark the table hidden by adding a property to the glue table (there would be a method also to reverse). We can add `hidden bool` to the listing API so the UI can toggle "hidden" tables.

**Comment by 3nvi** [comment]
Based on our convo with @kostaspap , we want a single "checkbox" to hide tables from deleted custom logs and not a way to selectively choose which tables to hide (one by one). Am I wrong on that?

**Comment by kostaspap** [comment]
> Based on our convo with @kostaspap , we want a single "checkbox" to hide tables from deleted custom logs and not a way to selectively choose which tables to hide (one by one). Am I wrong on that?

That's what was discussed, yes. That's at least the usecase we are looking to address. But I see how the Acceptance criteria of the epic are different^^

**Comment by kostaspap** [comment]
My planning is based on what was discussed, not based on what I see in this ticket.

**Comment by rleighton** [comment]
Wouldn't it be easier to NOT have any UI changes and when someone deletes a custom log it marks the table in glue and we suppress from the listing?

**Comment by rleighton** [comment]
Thinking about it more ... what is the down side of literally deleting the glue table (and rebuilding the views) when a user deletes a custom log? Even easier. We will need this as an option because right now if there is corrupted data (which some users have because of bugs in custom logs) then Indicator Search won't work because 1 table has bad data.

**Comment by kostaspap** [comment]
I am really concerned about making it that easy to delete data through the UI. 
I'd prefer the deletion to be a scheduled process somehow, so in case of a mistake (or a bad actor) it is reversible.

**Comment by rleighton** [comment]
> I am really concerned about making it that easy to delete data through the UI.
> I'd prefer the deletion to be a scheduled process somehow, so in case of a mistake (or a bad actor) it is reversible.

Fair. Then I would mark the table (which is reversible) ,  update the views (views need to skip marked tables), update Snowflake. Database api listing skips marked tables. No UI changes in the Data Explorer.

**Comment by 3nvi** [comment]
Should I go ahead and "close" the FE ticket then? Are we use business (cc @mattthetraveler ) is satisfied with the overall functionality

**Comment by rleighton** [comment]
> Should I go ahead and "close" the FE ticket then? Are we use business (cc @mattthetraveler ) is satisfied with the overall functionality?

There needs to be a delete button in Custom Logs .... we don't have that now, right?

**Comment by rleighton** [comment]
The important point to realize is this has to be "delete" and not "not show" because of corrupted data effectively poisoning the views.

**Comment by 3nvi** [comment]
@mattthetraveler

**Comment by kostaspap** [comment]
> Should I go ahead and "close" the FE ticket then? Are we use business (cc @mattthetraveler ) is satisfied with the overall functionality?

@3nvi We are not going to delete, we are just going to hide the tables as part of this work. 
We need the ticker to be able to see hidden tables.

**Comment by mattthetraveler** [comment]
Hey @kostaspap @3nvi just to confirm from discussion on Friday, the user will be able to hide/unhide tables in the Custom Logs tab and hidden tables will not be viewable in Data Explorer. Is this accurate?

**Comment by 3nvi** [comment]
Based on my understanding, the tables will always be hidden (no user involvement or action required)
