### ISSUE TITLE
BE: System status notification system

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#2263]
### Description

Backend system for delivering system notification changes to the user

### Related Services

Which backend services must change for this story to be completed?

### Designs

Paste the link to your designs here

### Acceptance Criteria

A concise list of specific user stories that qualify this story as done.

This acts as a checklist and high-level context for anyone reading this issue to verify your implementation.

For example:

- We can collect anonymized frontend crash logs from user browsers
- Users can opt in to send these logs to panther
- The crash logs will contain the following fields : browser version
- Users can opt-out from collection at any time
- ...

**Comment by jacknagz** [comment]
@kostaspap which milestone are you estimating here?

**Comment by kostaspap** [comment]
> @kostaspap which milestone are you estimating here?

I am estimating for 1.16 release.

**Comment by kostaspap** [comment]
Actually my comment @jacknagz  was aimed for https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther/2262 . This is no planned yet, I can look into this after the #2262 is done

**Comment by kostaspap** [comment]
I am closing this one - we said we will instead track progress in https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther/2559
