### ISSUE TITLE
Create Data Models View Page

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2266]
### Description

As an analyst, I want to be able create and maintain universal data models in the UI that I can reference when writing new rules and policies in the Python editor (see example [here](https://github.com/panther-labs/panther-analysis/pull/156).

Ideally, this is a separate sub-tab in Settings that presents a view of all the Data Models I have active and where I can also add new Data Models.

### Related Services

[See Backend services here](https://github.com/panther-labs/panther/pull/1945)

### Designs

Here is the[ RFC](https://github.com/panther-labs/panther-enterprise/tree/master/designs/security/simplify-detections)

Here are the [Designs](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/df9d59c8-eeb1-452d-a5f5-3712b64010be/collections/65b935ef-579f-4620-9530-c359b8d416e3)

### Acceptance Criteria

- Add a new "Data Models" sub-tab under Settings in current UI, should be under Analysis 
- Within the Data Models view page:
   - Ability to view Data Model cards with the following attributes:
     - Data Models Title
     - Data Models ID
     - Log Types
     - Timestamp
     - Enabled/Disabled
   - Ability to bulk select Data Models with the option to "Delete"
   - Ability to filter by "Most Recent" and "Last Modified", should default to "Last Modified"
   - Ability to select "more options" on Data Models card with a dropdown with the option to "delete"
   - Ability to select the title of the Data Model which will take the user right to the edit form of the Data Model

**Comment by 3nvi** [comment]
Closed via panther-labs/panther-enterprise#1876
