### ISSUE TITLE
Create Add Data Models Form

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2267]
### Description

As an analyst, I want to be able create and maintain universal data models in the UI that I can reference when writing new rules and policies in the Python editor (see example [here](https://github.com/panther-labs/panther-analysis/pull/156).

Ideally, this is a separate sub-tab in Settings that presents a view of all the Data Models I have active and where I can also add new Data Models.

### Related Services

[See Backend services here](https://github.com/panther-labs/panther/pull/1945)

### Designs

Here is the[ RFC](https://github.com/panther-labs/panther-enterprise/tree/master/designs/security/simplify-detections)

Here are the [Designs](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/df9d59c8-eeb1-452d-a5f5-3712b64010be/collections/65b935ef-579f-4620-9530-c359b8d416e3)

### Acceptance Criteria

- To add new Data Model, form should have two sections: Settings and Data Model Mappings
- Within Setting tab, available attributes should be Log Types, Detection ID, and Enabled
- Within Data Model Mappings tab: 
   - there should be a field to drop in a YAML function. This should be mandatory for the user.
   - there should an option to drop in a Python Module. This should be optional for the user.
- Within the Data Models view page:
   - Ability to bulk select Data Models with the option to "Delete"
   - Ability to filter by "Most Recent" and "Last Modified", should default to "Last Modified"

**Comment by 3nvi** [comment]
Closeed via #1876
