### ISSUE TITLE
Group Detections in Packs

### ISSUE THREAD

**Issue by lindsey-w** [panther-labs/panther#2278]
### Description

Detections in the `panther-analysis` repo should be grouped logically in packs.

>  See related internal documentation to get the link to the Google Sheets document titled "Panther Managed Packs | Rule Mappings"
>  All of the proposed pack groupings will be tracked in this document

### Related Services

- BE support for packs

### Designs

N/A 

### Acceptance Criteria

- initial set of pack groupings

**Comment by wey-chiang** [comment]
See related internal documentation to get the link to the Google Sheets document titled "Panther Managed Packs | Rule Mappings"

All of the proposed pack groupings will be tracked in this document
