### ISSUE TITLE
Update Bulk Uploader with Data Models Summary

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2285]
### Description

As an analyst, I want to use Bulk Uploader to upload Data Models and see a summary of models added or modified.

### Related Services

[See Backend services here](https://github.com/panther-labs/panther/pull/1945)

### Designs

Here is the[ RFC](https://github.com/panther-labs/panther-enterprise/tree/master/designs/security/simplify-detections)

Here are the [Designs](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/df9d59c8-eeb1-452d-a5f5-3712b64010be/collections/65b935ef-579f-4620-9530-c359b8d416e3)

### Acceptance Criteria

- When using Bulk Uploader, update the summary results to include a summary of Data Models that were uploaded after upload is complete
   - There should be a 4 summary box (next to Python Modules, Rules, Policies, and Data Models) with a summary of what's New, Modified, and Total

**Comment by mattthetraveler** [comment]
FYI @3nvi @lindsey-w 

Created this issue to capture an additional FE requirement that we stumbled upon today. We need to update bulk uploader to allow users to see Data Models they uploaded

**Comment by 3nvi** [comment]
@mattthetraveler we need some designs for this (the deign doc you linked is not related to the current issue's scope). 
Also is the BE effort ready? If so I'm gonna need to see the API for itt

Need to have the above in order to proceed here

**Comment by mattthetraveler** [comment]
@3nvi just created a task for Jim, as for the API @lindsey-w can you confirm that work is complete? And is there a PR?

**Comment by lindsey-w** [comment]
The input should be the same, it still takes in a zip file - which now can also include data models files.  The return values are updated to include the data models update stats:

```
[INFO]: API Response:
{
  "modifiedDataModels": 1,
  "modifiedGlobals": 0,
  "modifiedPolicies": 0,
  "modifiedRules": 3,
  "newDataModels": 0,
  "newGlobals": 1,
  "newPolicies": 0,
  "newRules": 3,
  "totalDataModels": 9,
  "totalGlobals": 7,
  "totalPolicies": 113,
  "totalRules": 130
}
```

**Comment by 3nvi** [comment]
@mattthetraveler As it stands, this won't make it to this release in favor of making sure that our other goals are reached. If we absolutely need that, we should discuss on what to de-prioritize in favor of it
