### ISSUE TITLE
ApolloClient Unhandled rejection on initial auth

### ISSUE THREAD

**Issue by alexmylonas** [panther-labs/panther#229]
### Describe the bug

There is an unhandled rejection from ApolloClient on auth when a user is not logged in that should be handled

### Steps to reproduce

1. Run UI local
2. Get an error screen with an error (see attached)

### Expected behavior

Error should be handled

### Environment

How are you deploying or using Panther?

- Panther version or commit: v0.2
- OS: [e.g. MacOS 10.15.3]
- Browser: all 

### Screenshots
<img width="295" alt="Screenshot 2020-02-20 at 12 00 56 PM" src="https://user-images.githubusercontent.com/14179917/74923673-e0a2dd80-53d9-11ea-95bf-3406d75f2e55.png">

**Comment by 3nvi** [comment]
Re-opening since @austinbyers saw issues on login flow. Also the related branch is restored.

@alexmylonas can we tests that login & signout works fine? I'll also wait for Austin to report the issues that he had.
