### ISSUE TITLE
Design for Dynamic Alert Fields

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2295]
### Description

As an Analyst, I want to be able to dynamically set the severity of an alarm to:
- Route alarms on critical and production resources to monitored Slack channels or kick off related workflows
- Similarly, they can choose to send lower priority alarms to a lower-priority queue to be triaged
- Tailor the alarm runbook and description
I can do this with the new functions `description`, `severity`, `destination`, etc. Now that I can set these fields, I want to see their test results when running unit tests from the UI.

### Related Services

web:
- Edit Rule

### Designs

Find RFC [here](https://github.com/panther-labs/panther-enterprise/pull/1095/files?short_path=f1e6929#diff-f1e69298df6b23442c7d0ca35b77b0050c235b672d5678bae61b0563acbd6900)

### Acceptance Criteria
- In Edit Rules page:
  - In the Test Record component, in addition to what is already shown (pass/fail status, title and dedup string) we should also display the dynamic fields (`reference`, `runbook`, `description`, `severity`, and `destination overrides`) that are returned if the related function has been defined for it. These fields **might** be present from the API, depending on whether the user has specified the related functions or not.
  - We should have a design for what the returned dynamic fields (`reference`, `runbook`, `description`, `severity`, and `destination overrides`) would look like if they are returned in the Test Record component

**Comment by dimitriszoitas** [comment]
@mattthetraveler please let me know if [this mockup](https://share.goabstract.com/239ce451-9027-4a24-a2bb-33af6007360a?mode=design&sha=c0dc616dbe4787a15a7c86b2ea87692f4780bb95) is okay! Thank you

**Comment by dimitriszoitas** [comment]
@vorillaz also have a look

**Comment by jacknagz** [comment]
@dimitriszoitas this looks great btw

**Comment by mattthetraveler** [comment]
This looks great @dimitriszoitas, no comments from me!

**Comment by vorillaz** [comment]
Closing this one as everything is in place in #2394
