### ISSUE TITLE
Design for Update Bulk Uploader with Data Models Summary

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2304]
### Description

As an analyst, I want to use Bulk Uploader to upload Data Models and see a summary of models added or modified.

### Related Services

[See Backend services here](https://github.com/panther-labs/panther/pull/1945)

[Integration test](https://github.com/panther-labs/panther/blob/master/internal/core/analysis_api/main/integration_test.go#L1539)

### Designs

Here is the[ RFC](https://github.com/panther-labs/panther-enterprise/tree/master/designs/security/simplify-detections)

Here are the [Designs](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/df9d59c8-eeb1-452d-a5f5-3712b64010be/collections/65b935ef-579f-4620-9530-c359b8d416e3)

### Acceptance Criteria

- When using Bulk Uploader, update the summary results to include a summary of Data Models that were uploaded after upload is complete
   - There should be a 4 summary box (next to Python Modules, Rules, Policies, and Data Models) with a summary of what's New, Modified, and Total

**Comment by dimitriszoitas** [comment]
Here is the [updated mockup](https://share.goabstract.com/e90c7466-af83-4164-b67d-978b71aa10bb?mode=design&sha=0938f0478db91b16eb3c1dbe6352e8c51fa67184)

**Comment by jacknagz** [comment]
@dimitriszoitas looks good!

**Comment by 3nvi** [comment]
@mattthetraveler Should this be inside an epic? I can't see the related FE and BE tickets

**Comment by mattthetraveler** [comment]
Yep just added this to the epic @3nvi , thanks for pointing that out

**Comment by mattthetraveler** [comment]
Hey @3nvi I've linked some more tickets in the description and added an epic. @lindsey-w confirmed that this was part of her work
