### ISSUE TITLE
After deleting yourself, you can still navigate UI

### ISSUE THREAD

**Issue by alexmylonas** [panther-labs/panther#231]
### Describe the bug

Deleting yourself has no effect in UI

### Steps to reproduce

1. Run UI
2. Invite new user
3. Verify the new user
4. Delete yourself

### Expected behavior

- It should logged out user and clear cache

### Environment

How are you deploying or using Panther?

- Panther version or commit: v0.2
- OS: MacOS 10.15
- Browser: All

**Comment by 3nvi** [comment]
@alexmylonas Let github that it should close the issue by typing `Closes #231` anywhere in your PR description :)

**Comment by 3nvi** [comment]
Closed through #234
