### ISSUE TITLE
[Design] Cloud Security Scanning Configuration Options

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2334]
### Describe the ideal solution

The Cloud Security scanning system is fairly generic, and intended to work in most cases for the most uses. However, this sometimes falls apart for specific environments/use cases where these general assumptions are wrong.

Users should have more configuration options for Cloud Security scanning, similar to how Log Analysis has several configuration options (e.g. using KMS keys, using prefixes, using SQS/S3, etc). Specifically, we've had requests for the following configuration options:

- Specifying which regions should/should not be scanned to align with Organization SCPs that block all actions in certain regions
- Specifying which resource types should/should not be scanned for certain sources

These settings should be configurable when onboarding new sources.

### Related Services

source-api and snapshot scheduler/poller

### Designs

TBD

### Acceptance Criteria

- When onboarding or editing a Cloud Security Source, the user should be able to:
  - Disable Cloud Security Scanning for certain AWS regions
     - A dropdown with all supported AWS regions where the user should be able to select which multiple regions to ignore
     - The disabled regions should be clearly indicated 
     - An info icon should read: "prevent Panther from scanning certain AWS regions"
  - Disable Cloud Security Scanning for certain Resource types
    - A dropdown with all resource types where the user should be able to select which resources to ignore
     - The disabled resources should be clearly indicated
     - An info icon should read: "prevent Panther from scanning certain Resource Types"

**Comment by mattthetraveler** [comment]
FYI @wey-chiang let me know if anything is missing

**Comment by dimitriszoitas** [comment]
@mattthetraveler @wey-chiang @3nvi  please review this collection: https://share.goabstract.com/0d57c159-8073-40a1-b196-3dbc834c04d1?mode=design&sha=a8efc283c397b6f1cc3e9ad840d3ee24f05c5cd6

Thank you

**Comment by 3nvi** [comment]
Left my comments!

**Comment by dimitriszoitas** [comment]
@3nvi @mattthetraveler @wey-chiang I made a small change here: https://share.goabstract.com/0d57c159-8073-40a1-b196-3dbc834c04d1?mode=design&sha=b61b921be3b17ee62e31623cc0c77f6eee24f17c

Please let me know if we're ok with this so I can close the issue

**Comment by 3nvi** [comment]
Looks good, just [1 small comment](https://share.goabstract.com/0d57c159-8073-40a1-b196-3dbc834c04d1?commentId=25879ab5-9398-429e-8620-2bf3fc5fd23b&sha=b61b921be3b17ee62e31623cc0c77f6eee24f17c) for @wey-chiang / @mattthetraveler

**Comment by dimitriszoitas** [comment]
@mattthetraveler @3nvi @wey-chiang 

Final revision so we can close this ticket:

Collapsed view: https://share.goabstract.com/0d57c159-8073-40a1-b196-3dbc834c04d1?mode=design&sha=5a17a1579e7a134f6cf2e583d55745755fb11b2a

Expanded view: https://share.goabstract.com/9b499dd9-b1b8-4672-8dce-e859f0823734?mode=design&sha=5a17a1579e7a134f6cf2e583d55745755fb11b2a

**Comment by 3nvi** [comment]
Yup, I like it

**Comment by alexmylonas** [comment]
Hey @wey-chiang about `resourceRegexIgnoreList` on your comment [here](https://github.com/panther-labs/panther/pull/2571#pullrequestreview-581554854). I am not sure is accounted for in the updated designs above.

Can you double-check/confirm?
