### ISSUE TITLE
Design Alert Routing by Type in Destinations page

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2337]
### Description

As an analyst, I want to set default alert routing by the alert type (rule match, rule error, etc). Today, this routing is only based on a detection severity (info, low, etc), but it's increasingly common to have destinations configured only for specific purposes, such as handling compliance-based alerts (e.g., my S3 bucket is insecure)

Example user story:
- I want to set up a specific Slack channel as the default alert destination for Rule Errors
- When adding a new Slack destination, I want to see a dropdown of all the alert types and indicate which alert types should be defaulted for Slack

### Related Services

Destinations Page

### Designs

TBD

### Acceptance Criteria

- In add/edit alert destination page, the user should be able to define default alert types for the destination
- The user should be able to select from rule matches, rule errors, policy failures, or scheduled rule matches/errors (once available)

**Comment by jacknagz** [comment]
@mattthetraveler do we have an Epic for the alert routing by type?

**Comment by jacknagz** [comment]
Does this have overlap with the options @kostaspap is adding for Ops alerting?

**Comment by mattthetraveler** [comment]
Updated this to reflect Route by Alert Type @jacknagz

**Comment by dimitriszoitas** [comment]
@mattthetraveler @3nvi please review [this collection](https://share.goabstract.com/de07aa03-4e01-4df8-ba72-80864c971b1a)

I've added the multiselect dropdown and also changed the severity "checkbox" area to be aligned. I've added these extra fields to a couple of destination layouts.

Thank you

**Comment by jacknagz** [comment]
@dimitriszoitas one comment, but LGTM!

**Comment by 3nvi** [comment]
@alexmylonas this is related to your work I believe
