### ISSUE TITLE
Support AWS Network Firewall logs

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#2340]
### Description

Add support for AWS Network Firewall logs: https://docs.aws.amazon.com/network-firewall/latest/developerguide/firewall-logging.html

### Acceptance Criteria

- Users can select AWS Network Firewall logs when onboarding a new S3 source
- Users can write rules for AWS Network Firewall logs

**Comment by georgepsarakis** [comment]
Adding some notes after a quick review of the AWS / Suricata documentation.

## Log Format

- A log sample and information on the log format can be found in the [AWS documentation](https://docs.aws.amazon.com/network-firewall/latest/developerguide/firewall-logging.html#firewall-logging-contents). In short, it contains the following top-level fields:
  * `firewall_name`
  * `availability_zone`
  * `event_timestamp`
  * `event` (nested object, as given by [Suricata EVE JSON output facility](https://suricata.readthedocs.io/en/suricata-4.1.0/output/eve/eve-json-output.html)) 
- The EVE log format is detailed [here](https://suricata.readthedocs.io/en/suricata-4.1.0/output/eve/eve-json-format.html).

## Logging Setup

Instructions on updating the Firewall logging configuration can be found [here](https://docs.aws.amazon.com/network-firewall/latest/developerguide/firewall-update-logging-configuration.html). Only traffic for stateful rules is logged:

> Firewall logging is only available for traffic that you forward to the stateful rules engine.

Stateful [rule groups](https://docs.aws.amazon.com/network-firewall/latest/developerguide/rule-groups.html):

> Defines criteria for examining a packet in the context of traffic flow and of other traffic that's related to the packet.

Log delivery can be configured to use [S3](https://docs.aws.amazon.com/network-firewall/latest/developerguide/logging-s3.html) or Firehose (and eventually S3) as destinations.

The naming pattern is the following:
- **Folder Structure:** `s3-bucket-name/optional-s3-bucket-prefix/AWSLogs/aws-account-id/network-firewall/log-type/Region/firewall-name/timestamp/`
- **Filename:** `aws-account-id_network-firewall_log-type_Region_firewall-name_timestamp_hash.log.gz`

**Comment by rleighton** [comment]
We should look into how to move the nested object attributes up to the top level in our schema to make it useful in queries and improve storage (we use column oriented storage, so we want columns of "like" things to make compression effective and queries fast).

**Comment by georgepsarakis** [comment]
Makes sense, thanks for the feedback @rleighton !
