### ISSUE TITLE
Better management of auxiliary CFN templates

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#2354]
### Description

Every release, Panther publishes a new version of the `deployments/auxiliary/cloudformation` templates to a public S3 bucket. These templates are downloaded directly when onboarding new sources. There are two main problems with this setup:

1. When developers change the aux templates and want to test source onboarding, their only recourse is to publish a new version (see #2338) In other words, **local changes to the aux templates are not reflected when deploying from source**. This would be a problem for any community member who wanted to change them in their own deployments.
2. The aux templates are published from a Makefile, unlike the rest of the Panther assets which are published by mage. This means we have to run two separate commands during every release publish

### Related Services

`mage`, CloudFormation, source-api, and the source onboarding page in the frontend

### Acceptance Criteria

- When deploying Panther from source, the *local* auxiliary templates are used rather than the official release templates published to our public S3 bucket
- The `mage publish` command should also publish the aux templates, and the Makefile in the aux directory can then be removed

### Implementation

Deployments from the source code have a "source" bucket which stages the Lambda binaries. This same bucket can be used to store a copy of the aux templates. So the deploy process becomes:

1. `mage` uploads a copy of the aux templates as part of the packaging of Panther assets
2. When the CloudFormation stacks are deployed, the locations of the aux templates are passed as parameters to the relevant services (instead of hardcoding the panther public bucket URL)

**Comment by kostaspap** [comment]
@austinbyers these templates need to be accessible publicly... When a user starts the process of onboarding any new account, that account needs to be able to access that template.

**Comment by austinbyers** [comment]
> @austinbyers these templates need to be accessible publicly... When a user starts the process of onboarding any new account, that account needs to be able to access the template.

Yes, for releases the aux templates will still be published to our public S3 bucket, as before.

But it seems absurd that the only way *developers* can test is by publishing to our production public bucket. Surely we can come up with something better?

Ideally, these templates could be uploaded to a private dev bucket, and then we use IAM to grant access to other Panther backend services and/or other testing accounts as necessary. For example, you could authorize a specific organization (e.g. the Panther dev AWS org) to read those objects, which is exactly how the enterprise public bucket works anyway.

If that's not feasible, we could make just those objects public, but still contained within the developer accounts. Meaning you would "publish" the aux template as a public object in your own dev bucket. That would still be preferable to publishing to production; we would just need to be careful that only the aux templates become public, not any of the other development assets. It is possible to have some S3 objects public but not others and we can use IAM to restrict public access by path.

I know @rleighton had concerns with these templates in the past, perhaps he and @nhakmiller can chime in here as well about the best way to handle these.

**Comment by rleighton** [comment]
Perhaps we can use CloudFront and configure the origin server as a bucket
in the Panther account itself. See:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-overview.html

**Comment by austinbyers** [comment]
> Perhaps we can use CloudFront and configure the origin server as a bucket

In our experience, CloudFront is far too slow for development. 30 minutes or more in some cases

**Comment by rleighton** [comment]
What if we put the aux templates in bucket in the panther account and when the UI returns the s3 path it uses a signed link generated by the backend?

This is how we deliver CSV downloads for the Data Explorer.

**Comment by austinbyers** [comment]
> What if we put the aux templates in bucket in the panther account and when the UI returns the s3 path it uses a signed link generated by the backend?

That will work for the UI, but will that allow you to deploy the template in a different account? If you click the "launch in CloudFormation" button, will CFN be able to download that file from another account?

I'm guessing the answer is just we make the dev object semi-public by whitelisting specific accounts/org IDs. Easy

**Comment by rleighton** [comment]
> > What if we put the aux templates in bucket in the panther account and when the UI returns the s3 path it uses a signed link generated by the backend?
> 
> That will work for the UI, but will that allow you to deploy the template in a different account? If you click the "launch in CloudFormation" button, will CFN be able to download that file from another account?
> 
> I'm guessing the answer is just we make the dev object semi-public by whitelisting specific accounts/org IDs. Easy

Not sure but I think signed links are public , just with a short expiration time.  Then we stop publishing the aux templates and make them available via the UI and they are always consistent with the current version. We could also have a special page for these where they are just listed, clicking one would download via a signed link.

**Comment by rleighton** [comment]
> > > What if we put the aux templates in bucket in the panther account and when the UI returns the s3 path it uses a signed link generated by the backend?
> > 
> > 
> > That will work for the UI, but will that allow you to deploy the template in a different account? If you click the "launch in CloudFormation" button, will CFN be able to download that file from another account?
> > I'm guessing the answer is just we make the dev object semi-public by whitelisting specific accounts/org IDs. Easy
> 
> Not sure but I think signed links are public , just with a short expiration time. Then we stop publishing the aux templates and make them available via the UI and they are always consistent with the current version. We could also have a special page for these where they are just listed, clicking one would download via a signed link.

... and the new api has methods to pull them down too in the same way.

**Comment by nhakmiller** [comment]
I really don't like that suggestion. Forcing people to go through the UI is extremely onerous for large deployments/power users. Onboarding s3 sources is already very not friendly to automation/power users, I would hate to make it even worse by forcing users through the UI to generate a pre-signed link every time they want to add a source.

I don't think we can reasonably remove the public s3 bucket templates anytime soon. For development purposes I like your idea Austin. Perhaps alternatively (not sure if this is better or worse) a deployment parameter that lets you specify a bucket URL to look for? Then developers can specify a bucket in their dev account, and people who don't want to be reaching out to our public s3 buckets for templates can point at one of their own buckets that's hosting the template (that they downloaded from our public bucket). At that point managing access is up to them and out of our hands.

**Comment by rleighton** [comment]
> > What if we put the aux templates in bucket in the panther account and when the UI returns the s3 path it uses a signed link generated by the backend?
> 
> I really don't like that suggestion. Forcing people to go through the UI is extremely onerous for large deployments/power users. Onboarding s3 sources is already very not friendly to automation/power users, I would hate to make it even worse by forcing users through the UI to generate a pre-signed link every time they want to add a source.
> 
> I don't think we can reasonably remove the public s3 bucket templates anytime soon. For development purposes I like your idea Austin. Perhaps alternatively (not sure if this is better or worse) a deployment parameter that lets you specify a bucket URL to look for? Then developers can specify a bucket in their dev account, and people who don't want to be reaching out to our public s3 buckets for templates can point at one of their own buckets that's hosting the template (that they downloaded from our public bucket). At that point managing access is up to them and out of our hands.

I never suggested removing the public buckets. We keep them and publish every release BUT the application api/UI would always serve data from the deployment which will always be in sync with the release. Doing this now could also avoid some future headaches in China and GovCloud .
