### ISSUE TITLE
Design work for Detection Packs

### ISSUE THREAD

**Issue by lindsey-w** [panther-labs/panther#2363]
### Description

As an analyst, I want to be view, enabled, disable, or update detection packs in the UI.  

### Related Services

Backend changes to the `analysis-api` to support packs.

### Designs

Here is the [RFC](https://github.com/panther-labs/panther-enterprise/pull/1011) 

### Acceptance Criteria

~~Updating Detections - Bulk~~
~~1. User navigates to `[Analysis] -> Packs`~~
~~2. Each pack is shown as a list with an indicator on whether there is a 'new' version of the pack available~~
~~3. User selects checkbox next to the packs they would like to update, selects which release version they would like to update the pack to (from a dropdown?), and clicks `Update`~~
~~4. Those packs are updated / rollbacked to the version specified by the user.~~
 
Updating Detections - Single
1. User navigates to `[Analysis] -> Packs`
2. Each pack is shown as a list with an indicator on whether there is a 'new' version of the pack available
3. User selects the "update" button next to a pack that they would like to update.
 
~~Enable / Disable Pack - Bulk~~
~~1. User navigates to `[Analysis] -> Packs`~~
~~2. Each pack is shown as a list with an indicator on whether it is enabled or disabled~~
~~3. User selects checkbox next to the packs they would like to enable, hits `Enabled`, and all detections within those packs are updated (enabled)~~
 
Enable / Disable Pack - Single
1. User navigates to `[Analysis] -> Packs`
2. User clicks on a pack to get to the Pack description page
3. User clicks `Edit` and toggles the `Enabled` slider, all of the detections in the pack are updated (enabled/disabled).
 
Filter / Sort by Pack
1. User navigates to `[Analysis] -> Detections`
2. Filter options include `Pack` option, similar to `LogType` filter

**Comment by mattthetraveler** [comment]
Hey @dimitriszoitas forgot to include this in sprint planning today

**Comment by dimitriszoitas** [comment]
Hey @mattthetraveler please review the following collection: https://share.goabstract.com/c8d605c8-41b2-4bb7-8657-beb1fce3bf66

After working on this ticket, I will be needing from you the following information:

1. How many types of detection packs are there and which are they? After reading the RFC I understand that we have Rules and Policies packs, but do we have scheduled Rules packs as well? Are we going to have global helpers in a pack as well? What is the information we need to display in the card component for all the different types of packs? e.g. title, description (I believe we should have one), enabled/disabled, version, update available etc.

2. Please describe the information that has to be displayed in the Pack detail page. I think we're going to follow the Detection Detail page layout so having that as a basis please let me know of everything that should be displayed there

3. What is the flow for a pack update/roll back? I have made an example of 3 packs updating but I dont know if this is correct. Also what type of errors could we have?

Thank you

**Comment by mattthetraveler** [comment]
Tagging @lindsey-w to validate these answers

> How many types of detection packs are there and which are they? After reading the RFC I understand that we have Rules and Policies packs, but do we have scheduled Rules packs as well? Are we going to have global helpers in a pack as well? What is the information we need to display in the card component for all the different types of packs? e.g. title, description (I believe we should have one), enabled/disabled, version, update available etc.

In this release we'll only have rules, policies, global helpers, and custom schemas. In Q1 we'll add in scheduled queries and scheduled rules. Agreed that we should have a description for the Pack in the card, so lets keep that. 

Also, note that Detection packs will have a mix of rules/policies/global helpers/schemas, so instead of labeling them as "Policy Packs" or "Rules Packs", we should indicate to the user what types of detections are included in the pack with multiple tags. 

> Please describe the information that has to be displayed in the Pack detail page. I think we're going to follow the Detection Detail page layout so having that as a basis please let me know of everything that should be displayed there

I think it should be a simple view of all the detections in the pack. Nothing too fancy here for now. Maybe a details section at the top that displays the data seen in the Detection Pack card. User should be able to also update and roll back versions in the details page too.

> What is the flow for a pack update/roll back? I have made an example of 3 packs updating but I dont know if this is correct. Also what type of errors could we have?

@lindsey-w could you weigh in here? What you have in the mock up makes intuitive sense to me.

**Comment by lindsey-w** [comment]
> In this release we'll only have rules, policies, global helpers, and custom schemas. In Q1 we'll add in scheduled queries and scheduled rules. Agreed that we should have a description for the Pack in the card, so lets keep that.

I think we were leaning towards managing two "types" here - one for schemas and one for "detection packs" (the rest of them) We might need to create another design task for the schema "pack" management? cc: @nhakmiller  @kostaspap  @alexmylonas 

> I think it should be a simple view of all the detections in the pack. Nothing too fancy here for now. Maybe a details section at the top that displays the data seen in the Detection Pack card. User should be able to also update and roll back versions in the details page too.

I think this makes sense. Some of the metadata I was envisioning was:

```
PackID: A.Pack.ID
Description: This pack groups awesome stuff together
DetectionPatterns:    // These are the detection ids for the detections in this pack
  ID:
    - Detection.ID.One 
    - Detection.ID.Two
DisplayName: Totally Awesome Pack
Enabled: true|false
AvailableVersions:  // these are the versions available to the user to rollback/update to 
    - Name: v1.14.0
       ID: 12345
    - Name: v1.15.0
       ID: 54321
EnabledVersion:  // this is the version currently "installed"
    Name: v1.14.0
    ID: 12345
```

> What is the flow for a pack update/roll back? I have made an example of 3 packs updating but I dont know if this is correct. Also what type of errors could we have?

What you have makes sense, although I don't think it will be reporting the status back up to the user (% done might not apply).  I'll work on getting some errors for you.

**Comment by dimitriszoitas** [comment]
@mattthetraveler Please review again: https://share.goabstract.com/c8d605c8-41b2-4bb7-8657-beb1fce3bf66
@lindsey-w whenever you can please give me the errors (unless I add a generic text and revisit later)

**Comment by nhakmiller** [comment]
> I think we were leaning towards managing two "types" here - one for schemas and one for "detection packs" (the rest of them) We might need to create another design task for the schema "pack" management?

Good callout. @mattthetraveler, we discussed with @kostaspap & team and it sounds like managing schema types should be a different page/process for users (even some of the backend components are shared). Might be worth syncing on if that needs it's own design task.

**Comment by dimitriszoitas** [comment]
@mattthetraveler @lindsey-w 

After reviewing all feedback and talking with @alexmylonas I've created [this flow](https://miro.com/app/board/o9J_lVvtjJ0=/
) in miro

Please leave your feedback on the board, if any

@alexmylonas I have also updated the collection in Abstract [here](https://share.goabstract.com/c8d605c8-41b2-4bb7-8657-beb1fce3bf66)

**Comment by dimitriszoitas** [comment]
Everything ok with this ticket? should i close it?

**Comment by mattthetraveler** [comment]
Hey @dimitriszoitas assuming the latest version is the Abstract version right? and Miro has the same flow but less-up-to-date screens?

**Comment by dimitriszoitas** [comment]
@mattthetraveler miro updated as well just now! Forgot it!

**Comment by mattthetraveler** [comment]
Thank you! Looks good to me. @lindsey-w can you confirm this meets backend requirements?

**Comment by lindsey-w** [comment]
> @lindsey-w can you confirm this meets backend requirements?

Looks good to me!
