### ISSUE TITLE
Allow users to create custom alert title 

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#238]
### Description

This feature allows users to customize the Alert title in Python. 

### Acceptance Criteria

- Rules engine is supporting execution of a new method
- Alert delivery mechanism is delivering the new message

**Comment by jacknagz** [comment]
Hey @kostaspap what about the frontend changes on the list alerts page?

**Comment by kostaspap** [comment]
> Hey @kostaspap what about the frontend changes on the list alerts page?

We have an issue for this #344 in the current milestone. The backend already returns the results
