### ISSUE TITLE
Design for Unified Overview Page

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2381]
## Description

Coordinate the mockups for the [Unified Overview MVP](https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther/2582) with the original stories and acceptance criteria living in the [top-level Epic](https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther/2244)

## Design Checklist

When creating new designs, the following cases should be accounted for, if applicable:

- [ ] Error Messages
- [ ] Success/Failure Scenarios
- [ ] Mocks with Realistic Data

**Comment by dimitriszoitas** [comment]
@mattthetraveler  please review the following collections. In some cases I have 2 alternatives (e.g. for data - volume of events stored, and Alerts)

Alerts Overview: https://share.goabstract.com/f97884a2-404e-47a2-8d6d-8aa8d6d03c5e
Cloud Security Overview: https://share.goabstract.com/c0c23cc3-ea5a-4a49-a6fb-36cd0ae278f0
Data Overview: https://share.goabstract.com/7b1da014-a5ad-4c0a-9829-11a09dd2b5ff
System Health: Will send until EOD

**Comment by jacknagz** [comment]
@dimitriszoitas we are going to need to create a new set of designs for this. I apologize for the runaround, but I've greatly reduced the number of charts we want to show for MVP. I'm going to move this back into TODO until I get a thumbs up from @3nvi on the updated stories and criteria

**Comment by 3nvi** [comment]
@jacknagz @dimitriszoitas I think the related epic looks ok. I'll refrain from creating the FE ticket until we have designs in place

**Comment by dimitriszoitas** [comment]
@3nvi @mattthetraveler @jacknagz 

I have all the screens described in the MVP epic
Please give me your feedback [on this board](https://miro.com/app/board/o9J_lVEhamE=/)

You'll notice that for the Cloud Security I've designed a few alternatives: 3 layout alternatives for what is described in the A.C. and one more that includes 2 tables (Top Failing Policies and Top Failing Resources) that we already have and display,

Thank you

**Comment by jacknagz** [comment]
@dimitriszoitas updated the AC per your designs and left some comments in Miro

**Comment by dimitriszoitas** [comment]
I added the revised screens in miro: https://miro.com/app/board/o9J_lVEhamE=/

For Alerts Overview I have 3 alternatives, one that uses exactly what we have at the moment (component-wise) and 2 more with some UI changes
