### ISSUE TITLE
FE Implementation of Alert Routing by Type in Destinations page

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2385]
### Description

As an analyst, I want to set default alert routing by the alert type (rule match, rule error, etc). Today, this routing is only based on a detection severity (info, low, etc), but it's increasingly common to have destinations configured only for specific purposes, such as handling compliance-based alerts (e.g., my S3 bucket is insecure)

Example user story:
- I want to set up a specific Slack channel as the default alert destination for Rule Errors
- When adding a new Slack destination, I want to see a dropdown of all the alert types and indicate which alert types should be defaulted for Slack

### Related Services

Destinations Page

### Designs

[Designs are here
](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/0d293ff7-a6c6-4ddc-9dd0-442c63b91995/collections/4c465cf2-53df-4aab-830a-f57ad4e3a7f5)
### Acceptance Criteria

- In add/edit alert destination page, the user should be able to define default alert types for the destination
- The user should be able to select from rule matches, rule errors, policy failures, or scheduled rule matches/errors (once available)
- all 3 alert types should be selected by default
- at least one alert type should be selected

**Comment by alexmylonas** [comment]
@mattthetraveler Do we have API changes documented somewhere? If not, would you mind pointing me to the person that implemented those changes on the BE?

**Comment by mattthetraveler** [comment]
Hey @alexmylonas , BE ticket is [here](https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther/2399). Still in progress but you should see updates there.
