### ISSUE TITLE
Lambda-based deployment packaging

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#2400]
### Description

Developers or users who build Panther from source know that the deploy process takes 15-20 minutes. Most of that time is spent compiling the Go Lambda functions and uploading them to S3. If your Internet connection is poor, the upload alone can take 40+ minutes.

Another problem we've started running into recently: Lambda binaries built on developer laptops (typically Macbooks) do not always work in Amazon Linux environments, especially when native code is imported.

What if `mage deploy` actually used a Lambda function to compile and package the Go code? That solves both of those problems - the build environment is consistent and the deploy process should be significantly faster, since the binary uploads will be within the same AWS region.

This is essentially what many of our engineers already do - they have to spin up an EC2 instance in the same AWS region and push their code to it for deployments to finish in any reasonable amount of time. If we automated a version of this, it would save our engineers lots of time

### Related Services

`mage`

### Acceptance Criteria

- By default, Golang Lambda binaries are compiled and packaged in the AWS deployment region, not in the local env
- The web image is not in scope for this - trying to do a Docker build from within Lambda is theoretically possible (especially since Lambda now supports custom docker images), but quite a bit more complicated. We'll leave that for another time

### Implementation Overview

I'm not 100% sure how or even if this will work, but the basic idea is this:

1. There will be a `panther-dev-build` Lambda function only when deploying from source
2. `mage deploy`, rather than running `go build` and `cloudformation package`, will zip the repo source tree and send it to the builder Lambda. The source tree only needs to include Go/Python code (`pkg`, `internal`, `cmd`, etc) and should be significantly smaller than the final Go binaries
3. The `dev-build` Lambda will compile the source, upload it to S3, and return the set of S3 paths corresponding to the source code for each binary
4. `mage deploy` will generate the final CloudFormation template embedding the packaged assets, create the change set, and proceed normally

The only difference between this process and what we have today is replacing the `cloudformation package` step with our own lambda-packager

**Comment by georgepsarakis** [comment]
I am completely unaware of the inner workings of the service, but maybe [CodeDeploy](https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-steps-lambda.html#deployment-process-workflow-lambda) could help in this case.

**Comment by 3nvi** [comment]
> I am completely unaware of the inner workings of the service, but maybe [CodeDeploy](https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-steps-lambda.html#deployment-process-workflow-lambda) could help in this case.

CodeDeploy unfortunately doesn't cover all the use cases that we want. It has a limited number of targets and doesn't allow us to run all the docker-in-docker processes that we need. CodeBuild would be a better alternative, but unfortunately none of them are ideal. 😞

**Comment by austinbyers** [comment]
> I am completely unaware of the inner workings of the service, but maybe CodeDeploy could help in this case.

Great idea! Definitely worth exploring CodeBuild, I've never used it before

> CodeDeploy unfortunately doesn't cover all the use cases that we want. It has a limited number of targets and doesn't allow us to run all the docker-in-docker processes that we need.

To be clear: the web server is *not* in the scope of this issue. Docker builds are a separate beast entirely, we can make a separate issue for that later.

Right now, I'm primarily concerned with the Go binaries. If we can get Go compilation/packaging into the cloud, that's already a huge step forward. A dev laptop, for example, can do a `docker build` and `docker push` locally while AWS /Lambda/CodeBuild is simultaneously compiling/packaging the Lambda source code

**Comment by georgepsarakis** [comment]
Adding a few more references to possibly interesting projects:
- https://github.com/lambci/serverless-actions
- https://github.com/lambci/lambci
