### ISSUE TITLE
Self-signed certificate issue on Firefox

### ISSUE THREAD

**Issue by georgepsarakis** [panther-labs/panther#2402]
## Description

Deploying for the second time, with a newly generated self-signed certificate causes the following issue in Firefox: https://support.mozilla.org/en-US/kb/Certificate-contains-the-same-serial-number-as-another-certificate

Note that removing the certificate from `Privacy & Security > Certificates > Servers` does not fix the issue.

- **Firefox version:** `84.0.2 (64-bit)`
- **OS version**:  `macOS Big Sur 11.1`

## Steps to reproduce

- `mage deploy`
- Open Panther installation URL in Firefox browser.
- `mage teardown`
- `mage deploy`
- Open Panther installation URL in Firefox browser. The `SEC_ERROR_REUSED_ISSUER_AND_SERIAL` error screen is displayed.

## Possible Solution

Consider randomizing the serial number when generating self-signed certificates:

https://github.com/panther-labs/panther/blob/8b267aefb74fc5963b1cdb842df9a3e1df856cd7/internal/core/custom_resources/resources/certificate.go#L86

**Comment by kostaspap** [comment]
Assigned @austinbyers for visibility

**Comment by austinbyers** [comment]
Thanks @georgepsarakis for the detailed report!
