### ISSUE TITLE
OAuth2 sources show up as 'Healthy' after creation even if not Authorized

### ISSUE THREAD

**Issue by alxarch** [panther-labs/panther#2405]
### Describe the bug

When a user onboards a new source that requires OAuth2, the source record must be created *before* following the OAuth2 redirection flow. 

Due to the way SourcesAPI code is structured it is not possible to create a source record if it is 'unhealthy'.

To overcome this without extensive refactoring, we 'hide' the error and hope that the user properly authorizes the app...

Well, that didn't work out.

Customers are left puzzled as to why their 'healthy' source is not receiving any events and the logs are filled with `403` errors.  

It is time we fix this by using wrapped errors instead of plain strings when checking the health status of a source. This will allow the `PutIntegration` handler to behave differently when the source being created is OAuth2 and the error is `NotYetAuthorized`.
The `UpdateIntegration` and `CheckIntegration` handlers should not ignore this error.  

### Steps to reproduce

1. Onboard a new Box source and don't complete the Authorization
2. The source shows up as Healthy

### Expected behavior

The source should clearly be marked as not healthy with a message explaining that it's not yet Authorized

**Comment by alxarch** [comment]
Setting an estimate of 5 as the refactoring could get messy.

**Comment by kostaspap** [comment]
Issue moved to [panther-labs/panther-enterprise #2275](https://github.com/panther-labs/panther-enterprise/issues/2275) via [**ZenHub**](https://www.zenhub.com/)
