### ISSUE TITLE
[Bug] Rule Filtering by Log Type doesn't seem to work

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#2411]
### Describe the bug

When I try to filter a list of rules by a particular log type, the `analysis-api` lambda returns all the rules, ignoring the `logTypes` filter that has been applied

### Steps to reproduce

1. Go to the list rules pages
2. To the right of the breadcrumbs, select a log type like `Gravitational.Teleport`
3. Observe how the list of rules is not filtered

### Steps to validate

To validate that the request fires

1. Press CMD +Shift + I to open the Chrome devtools
2. On the devtools click the "Network" tab
3. Press the "Clear" icon-button on the top-left  corner of the network tab
4. Follow the reproduction steps and validate that each time you changee the log type, a request with the proper headers/payload is being fired

### Expected behavior

The list of rules should be filtered correctly

### Environment

Release 1.15

### Additional context

Have validated that the issue is on the lambda level via the insights screenshots shared below

### Screenshots

<img width="1368" alt="Screen Shot 2021-01-14 at 6 16 57 PM" src="https://user-images.githubusercontent.com/10436045/104617934-bc588b00-5694-11eb-9cde-c52edefd2368.png">

<img width="1381" alt="Screen Shot 2021-01-14 at 6 07 45 PM" src="https://user-images.githubusercontent.com/10436045/104618027-df833a80-5694-11eb-9dfe-c7fe8f6cba2b.png">

**Comment by nhakmiller** [comment]
Wow you're right, the `logTypes` filter is just totally ignored. I can see about a quick fix.

**Comment by 3nvi** [comment]
> Wow you're right, the `logTypes` filter is just totally ignored. I can see about a quick fix.

Perfect. Thanks!
