### ISSUE TITLE
Minor mage logging / usability improvements

### ISSUE THREAD

**Issue by tatehanawalt** [panther-labs/panther#2417]
## Overview:

Developers may run mage commands against multiple different versions of panther.

The mage logs do not specify the version of panther.

If we have the git commit we can be sure of the command context.

## Example:

Specifically I am running integration tests for release testing. I pulled the repo and achieved successful integration test results. Pull resulted in updates to my branch. The commit hash wasn't in the mage logs so I cannot be sure the integration tests are passing for the most recent commit. So I am re-running integration tests.

## Acceptance Criteria

- [ ] Add a `mage version` command to print the panther version
- [ ] Add a `mage endpoint` command to show the Panther web URL
- [ ] Log the version/commit for integration tests and any other interaction with a live deployment

**Comment by tatehanawalt** [comment]
Mainly was hoping to get this through the integration tests.

I am now realizing two commit hash's can be involved with the integration testing.

Do we have any services that have the git hash stored? Or do we tag any resources with the git hash?

**Comment by austinbyers** [comment]
> Mainly was hoping to get this through the integration tests.

Ah, that's a good point - yes, we should log the full version/commit any time we're interacting with a live deployment. Though keep in mind that this won't reflect local (uncommitted) changes, which is usually the case when developers are testing

> Do we have any services that have the git hash stored? Or do we tag any resources with the git hash?

The semver ("1.15.0-RC") is passed as a [tag](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html) to every CloudFormation stack (and then propagated to every supported resource as well). The semver is also used for the documentation links in the web app, compiled into the ops tools, and is passed to our [custom resources](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources.html) which could do version-specific migration if necessary.

The truncated commit SHA is passed to the web stack and is displayed at the bottom of the general settings page.

So, yes, every published Panther release has the full version information embedded within it. But I do also like the idea of adding a version target.

---

So it sounds like the deliverables for this issue are:

- [ ] Add a `mage version` target as shown above
- [ ] Log the version/commit for integration tests and any other interaction with a live deployment

I'll add these into my ongoing deployment work, along with some additional safety checks (e.g. warn before deploying different editions or downgrading a version)

**Comment by austinbyers** [comment]
Adding one more small related task to this issue: we'll add a `mage endpoint` command to just print the web URL of your Panther deployment
