### ISSUE TITLE
Cloud Security scanner only handles some rate limit errors

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#2428]
### Describe the bug

The Cloud Security scanner has special logic for handling rate limit errors, as rate limit errors shouldn't just be retried blindly as that will exasperate the issue. Currently we're catching and handling the `ThrottlingException` error,  but we're not handling any of the following rate limiting errors:

- Throttling
- ThrottlingException
- ThrottledException
- RequestThrottledException
- TooManyRequestsException
- ProvisionedThroughputExceededException
- TransactionInProgressException
- RequestLimitExceeded
- BandwidthLimitExceeded
- LimitExceededException
- RequestThrottled
- SlowDown
- EC2ThrottledException

These errors were turned up by a quick google search looking for additional AWS rate limit error codes. We should carefully examine each of these to determine whether or not they are the type of error we want to handle specially.

### Steps to reproduce

Difficult to reprodudce as it relies on AWS behavior. I was not able to reproduce this in a dev environment, but I didn't want to incur too much costs so I didn't try too hard. I did observe this in a customer account while assisting them with troubleshooting. Presumably you could reproduce like this:

1. Go to the EC2 console
2. Create a few dozen VPCs
3. Manually queue up VPC resource type scans as quickly as possible
4. Eventually rate limit errors should occur, and Panther will not handle them as rate limit errors but instead as normal re-tryable errors

### Expected behavior

Panther apply its rate limit logic to all rate limit errors we encounter.

### Environment

How are you deploying or using Panther?

- Panther version v1.14.X

### Additional context

A user reported Panther rate limit issues and seeing the `RequestLimitExceeded` error reported by Panther when scanning EC2 related resources. This is what prompted this issue.

**Comment by kostaspap** [comment]
The AWS Go SDK is already handling throttling errors by doing exponential backoff with jitter (same to how [Java SDK does it](https://docs.aws.amazon.com/general/latest/gr/api-retries.html)). I imagine this ticket refers to the way we handle the exception after the AWS SDK retries have been exhausted? 
Note that [this change](https://github.com/panther-labs/panther/commit/f84f27d87d3aef49774221a6602db0ed4b74c5b9) increased the number of retries we perform (before we were doing 3 retries, thus retrying for less than 1second), so the number of throttling errors surfacing to application code should be reduced in 1.15.

**Comment by nhakmiller** [comment]
> The AWS Go SDK is already handling throttling errors by doing exponential backoff with jitter (same to how [Java SDK does it](https://docs.aws.amazon.com/general/latest/gr/api-retries.html)). I imagine this ticket refers to the way we handle the exception after the AWS SDK retries have been exhausted?

Correct. We have special logic in this case beyond what the AWS SDK has that handles this situation better for our use cases.

> Note that [this change](https://github.com/panther-labs/panther/commit/f84f27d87d3aef49774221a6602db0ed4b74c5b9) increased the number of retries we perform (before we were doing 3 retries, thus retrying for less than 1second), so the number of throttling errors surfacing to application code should be reduced in 1.15.

We want the opposite of this. We want to reduce the number of requests when we're getting rate limited, otherwise we'll just keep getting rate limited. Luckily that's what our custom logic does already, we just need to update it to handle these cases. We were seeing cases where so many scans were happening in such a short period of time (due to very high resource churn) that users operational tools (e.g. terraform) were unable to interact with their resources. After adding our special rate limit handling logic we reduced that issue by ~90%.
