### ISSUE TITLE
Manage Schemas in an external repository

### ISSUE THREAD

**Issue by alxarch** [panther-labs/panther#2434]
### Description

Our current management of 'native' log types is bound to the releases of Panther itself.
We want to manage our schemas in the same way we manage our rules, in a repository.

### RFC

[Under review](https://github.com/panther-labs/panther-enterprise/pull/1914)

### Designs

N/A

### Acceptance Criteria

* Contributors can define schemas [panther-analysis](https://github.com/panther-labs/panther-analysis) repo in YAML with the same format we use for Custom schemas (https://docs.runpanther.io/enterprise/custom-log-types). The schemas names in that repo doesn't have to start with "Custom".
* Each release of panther-analysis repo includes in the release artifacts a YAML file that contains all the schemas defined in that repo. 
* Panther when it gets deployed/gets updated it fetches a specific version of the schemas in panther-analysis repo. The version that Panther will fetch is a property inside https://github.com/panther-labs/panther/blob/master/deployments/panther_config.yml
* Users update the schemas their Panther instance uses by using the Panther Analysis Tool. We will offer a new subcommand `update-schemas` that: 
* Once invoked, will list the newer versions of the schemas available from the panther-analysis repo. users can select the version they want to update to (defaults to latest)
* We offer a command `update-schemas -latest` that updates their schemas to the latest published version

**Comment by mattthetraveler** [comment]
Hi @alxarch are there any FE/Design tasks related to this?

**Comment by alxarch** [comment]
> Hi @alxarch are there any FE/Design tasks related to this?

Not for this epic. We are focusing on creating the repository and having support for managed schemas in the backend.
We will have such tasks in the next sprint so that users can browse managed schemas along side their own custom ones.

**Comment by kostaspap** [comment]
I believe this can be closed? @mattthetraveler @alxarch
