### ISSUE TITLE
[Enhance] [FE] Support Data Model mass actions

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#2489]
### Description

In the v1.15 release we released an MVP of our Data Models in which a user can connect different fields from different log types, to a unified normalized field. This helps analysts since they can use a single/same field for all of their logs.

A user can see their data models by navigating to `/log-analysis/data-models/` and they can delete or edit them 1-by-1, but they have no way of performing mass actions to them like mass deleting.

That's what we want to support in this PR. Specifically, the only mass actions we'll currently support is mass deleting

### Related Services

- Web
  - Data Models List Page

### Designs

https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/df9d59c8-eeb1-452d-a5f5-3712b64010be/commits/latest/files/46187896-210a-4c7f-92ff-d156f6dc68b2/layers/9267464E-2912-4F67-881C-DD8D6E1A092D?collectionId=65b935ef-579f-4620-9530-c359b8d416e3&collectionLayerId=59aa43d3-d78a-4572-bef5-9b27f14caf8d

### Related GraphQL API

https://github.com/panther-labs/panther-enterprise/blob/542ea50b0eea4134ce8017336f1b97ed81b1b3ad/api/graphql/schema.graphql#L42

### Acceptance Criteria

- Allow user to select multiple Data Models
  - Add Checkboxes in each DataModel Card and allow the user to "select" a card
  - Add a top-level Checkbox to select all data models in the current page
  - Switch filters with mass actions when at least 1 data model is selected
    - Add "Mass deletion" button which will bring up the Deletion modal in order to confirm the deletion
- Sufficient tests should be added
 
### Notes

- Selections **should NOT** be mirrored in the URL
- To see examples of similar behavior, view the following components:
  - ListAlertsPage

**Comment by jacknagz** [comment]
FYI - I decoupled this from the main Data Models epic so we don't keep that Epic open forever (it was for the initial implementation)
