### ISSUE TITLE
FE: Refactor 'Modal' service to be more generic

### ISSUE THREAD

**Issue by alexmylonas** [panther-labs/panther#2513]
### Description

We are using a complex architecture for Modals that doesn't provide so much value when we are using for simple modals. 

Right now, if you want to create a simple modal you will have to create a new Modal component, update ModalManager and ModalContext. 

The suggestion is to move away from this by removing `ModalManager` and changing;
```
showModal({ type: MODALS.WHATEVER, props: ModalProps })
```
with
```
showModal({ component: MyModal, props: myProps })
```
### Related Services

N/A

### Designs

No changes in UI should be noticed

### Acceptance Criteria

- [ ] Remove `ModalManager`
- [ ] Update all Modal invocations
- [ ] Validate all Modal invocations are working as intended

**Comment by 3nvi** [comment]
Nice! Thanks for that @alexmylonas
