### ISSUE TITLE
[Design] Salesforce Log Puller UI

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2527]
## Description

As an analyst, I want to be able to pull important Salesforce audit logs via a SaaS log experience.

## Acceptance Criteria
As an analyst, I want to be able to set up Salesforce as a log source in as few steps as possible.

- SaaS onboarding experience for Salesforce should have a Configure -> Set Credential -> Verify Set Up flow
- Configure
   - a field for name
   - a field for log types: supported logs will be Audit and Access logs
- Set Credentials
    - The user will provide username and password to authenticate in Panther
    - A link to documentation (which will be completed in parallel) that walks the user through giving Panther access in Salesforce
- Verify Set up
    - a screen that verifies set up was accomplished

**Comment by dimitriszoitas** [comment]
@mattthetraveler I'm going to need further info for this. Flow, needed fields, etc.

**Comment by mattthetraveler** [comment]
@kostaspap @georgepsarakis  lets scope this out in our sprint planning tomorrow

**Comment by mattthetraveler** [comment]
@giorgosp I've updated the acceptance criteria per our conversation today. Let me know if the steps are correct! FYI @dimitriszoitas

**Comment by kostaspap** [comment]
> @giorgosp I've updated the acceptance criteria per our conversation today. Let me know if the steps are correct! FYI @dimitriszoitas

Should be the other George, @georgepsarakis  :)

**Comment by dimitriszoitas** [comment]
Hey @mattthetraveler @georgepsarakis 

You can review the flow here: https://miro.com/app/board/o9J_lWU3zBs=/

Please leave your comments for either flow or mockup revisions in the miro board

Thank you

**Comment by georgepsarakis** [comment]
Thanks @dimitriszoitas ! I will also leave the comments inline at the board in order to make it easier to understand the references, but here are some quick thoughts:
- Log type selection will probably not be necessary at this point.
- We will likely need an additional field on the credentials form.

I will analyze the requirements a bit more extensively in #2529 and update this issue accordingly with any final decisions.

**Comment by mattthetraveler** [comment]
@georgepsarakis I thought we we're pulling two log types, Audit and Access.. What if the user wants to pull just Audit logs and not Access logs?

**Comment by georgepsarakis** [comment]
@mattthetraveler we discussed the log type selection with the team and it would be indeed useful to allow selection of specific log types for technical and cost reasons (sorry, my mistake).

@dimitriszoitas in case you need more realistic values for the log types, the following will be used for the time being:
- `Login`
- `LoginAs`
- `Logout`
- `URI`
- `InsecureExternalAssets`

Apart from the username and password, we will also need an additional field named `Security Token`.

**Comment by dimitriszoitas** [comment]
Screens are revised and [miro board updated](https://miro.com/app/board/o9J_lWU3zBs=/) - please let me know if everything is ok so we can close this ticket

**Comment by dimitriszoitas** [comment]
Are we ok with this ticket? Should I close it?

**Comment by mattthetraveler** [comment]
Looks good to me! @georgepsarakis can you give final confirmation that this captures all requirements from the backend?

**Comment by 3nvi** [comment]
@vorillaz have you reviewed those btw?

**Comment by georgepsarakis** [comment]
Seems great, thanks! One question though, for the [success screen](https://miro.com/app/board/o9J_lWU3zBs=/?moveToWidget=3074457353994203668&cot=14), it is likely that we could use a different subtitle just to inform the user for which Salesforce instance we connected successfully. I think this is possible via the healthcheck message, just wanted to confirm with the Frontend team my assumptions. It will be something similar to:

> Connection to Salesforce instance https://COMPANY-DOMAIN.my.salesforce.com was successful and setup is now complete.

From a design aspect I think this is complete though.

**Comment by vorillaz** [comment]
Ηey, everything's looking good as the designs are following the principles of any other integration we have already in place. @dimitriszoitas Feel free to close this one, amazing work by the way. Miro looks super nice.
