### ISSUE TITLE
Design: Allow users to specify the role for S3 sources

### ISSUE THREAD

**Issue by giorgosp** [panther-labs/panther#2554]
### Description

Currently, when onboarding an s3 source, we prompt users to install a CloudFormation template. This template creates an AWS IAM role in the user's account. The role gives permissions to Panther's account to use it and read files from the user's s3 bucket.

We would like users to be able to specify their own role. This will allow them to use a role that have created themselves, through their own automation.

The role field should validate that the role is in the AWS ARN format, like 
`arn:aws:iam::123456789100:role/rolename`

This field is **optional**. If user's don't want to bring their own role, they can still user our CFN template as before.

Some decisions we need to discuss:
**1.** The tricky thing is how to make these options clear to the user. 
- Do we just append the `role` field in the form and have some help text that explains to the user that the role is optional and in the next step Panther will provide a CFN template to create the role?
- Do we put the role field in the page that shows the CFN template? And tell the user to either fill in an existing role of theirs or download the template?

**2.** What happens during s3 source updates?
- Do we allow the user to change the role field? To empty it?
- What if the used Panther's CFN template to create the role?
**Decision:** Always show the roleARN, even if that role was created by the Panther's template.

**3.** What happens with managed bucket notifications? https://github.com/panther-labs/panther-enterprise/issues/1528
Unless we find a better solution, let's proceed with the simple one: If user fills in the `role ARN` field, they have to configure bucket notifications themselves. If not, we ask them if they want Panther to configure their notifications. Note, we need this info about managed notifications before the user downloads the CFN template, so that we add more AWS permissions to the template.

#### Create flow (s3 onboarding) updates
- Users must always fill in the role ARN (they can create it either themselves or utilize Panther's CFN template).
    - When we give users the CFN template option, we ask them if they Panther to manage their notification (so that the backend adds more AWS permissions to the CFN template)
- After user specifies the role:
    - If they didn't opt for Panther-managed notifications **or** Panther failed to create bucket notifications, we show them the existing "Setup your bucket notifications screen" (this is already implemented)
    - Otherwise, we proceed to the next, last step
- Either show them the success page or the page with health check errors

#### Update flow updates
- Add the role ARN field in the update form. We could use the same page as the create flow (with the role ARN pre-filled). 
- The next steps are same as the create flow:
    - If they didn't opt for Panther-managed notifications **or** Panther failed to create bucket notifications, we show them the existing "Setup your bucket notifications screen" (this is already implemented)
    - Otherwise, we proceed to the next, last step
- Either show them the success page or the page with health check errors

**Comment by dimitriszoitas** [comment]
@giorgosp @alexmylonas please have a look at this board: https://miro.com/app/board/o9J_lV_XSG4=/

You can find the mockups related to this issue highlighted with a red background. Please give me your feedback with comments on the miro board.

I will surely need help with the texts.

Thank you

**Comment by giorgosp** [comment]
Great work @dimitriszoitas ! The s3 onboarding is not trivial. I have left several comments. Looking for your and Alex's thoughts too

**Comment by giorgosp** [comment]
@dimitriszoitas @kostaspap @alexmylonas  I adjusted the acceptance criteria on this ticket after the review comments on Miro.  Also added the update flow, for completeness. I think it will help Alex during implementation.
