### ISSUE TITLE
Prevent UPDATE_ROLLBACK_FAILED from deleted layer versions

### ISSUE THREAD

**Issue by tatehanawalt** [panther-labs/panther#2578]
## Description
Existing deployment conditions may lead rollbacks into an UPDATE_ROLLBACK_FAILED state. This can limit or suspend availability of panther.

Unintentional rollbacks should revert lambda layers to the most recent, functional version.

## Overview
Cloudformation stacks will enter the UPDATE__ROLLBACK_FAILED state when references in the stack template are broken.
Cloudformation uses to the last stack configuration for resource ARNs.

Services in panther modify the Lambda Layers dynamically. These updates do not change the arn's in the latest cloudformation configuration file. In cases of rollback, cloudformation fails to revert to the configuration arn, and enters the UPDATE__ROLLBACK_FAILED state.
  
## Reproduce the issue

1. Create a new global module
2. Update Panther. Force log-analysis stack to fail by e.g. modifying the code to throw an exception when a custom resource present in the log-analysis CFN is running
3. See rollback failure.

**Comment by kostaspap** [comment]
> TODO - determine steps to reproduce.
Something that should work: 

1. Create a new global module
2. Update Panther. Force `log-analysis` stack to fail by e.g. modifying the code to throw an exception when a custom resource present in the `log-analysis` CFN is running
3. See rollback failure.

**Comment by tatehanawalt** [comment]
> > TODO - determine steps to reproduce.
> > Something that should work:
> 
> 1. Create a new global module
> 2. Update Panther. Force `log-analysis` stack to fail by e.g. modifying the code to throw an exception when a custom resource present in the `log-analysis` CFN is running
> 3. See rollback failure.

Thank you @kostaspap
