### ISSUE TITLE
Adding GetObject healthcheck for s3 sources

### ISSUE THREAD

**Issue by giorgosp** [panther-labs/panther#2586]
### Description

We want to add an extra health check for s3 sources which answers the question: 
Can Panther read an object on the user's bucket? 
Equivalently, has the user set up permissions properly so that the log processing role can read objects on the user's bucket?

However, this is not as simple as originally thought. There is an open [PR](#2574), but some issues came out during testing.
Because there are multiple permission mechanisms applying on AWS S3 (IAM policies, bucket policies, object ACLs), implementing this check is not as simple as "do a `GetObject` request and expect either an `AccessDenied` or a `Success` response". 
For the same reason, checking for only the role's permissions does not mean that Panther can read the log files on the user's bucket. While Object ACLs may not be commonly used for log files, the user may have set up bucket policies, which this check doesn't account for.

Some potential implementations are described below.

#### Impl 1: Based on `ListObjects` + `GetObject` request
**tl;dr:** Perform a `ListObjects` request and then perform a `GetObject` request for any of the keys in the bucket. If the response is not a success response, fail the health check.
This needs an extra permission to the log processing role (`ListBucket`). 

Why not just make a `GetObject` request for a random non-existent key (eg `panther-health-check`)?
AWS S3 always returns `AccessDenied` for a missing key if the user doesn't have the `s3.ListBucket` permission too.
But adding this permission doesn't solve our issue.

Below is a table that shows the responses for an **`s3.GetObject` request** for a missing and an existing key, given the permissions of the user making the request and the absence of any bucket policies or object ACLs.

Note: `ListBucket` is the name of the permission needed to perform the `ListObjects` operation.

| Perms  | Missing Key | Existing Key
| ------------- | ------------- | ------------- |
| GetObject  | AccessDenied | Success  |
| ListBucket + GetObject  | NoSuchKey  | Success |
| ListBucket  | NoSuchKey  | AccessDenied  |

The table shows that if the request is made for a missing key and the user has the `ListBucket` permission, there is no way to decide whether they also have the `GetObject` permission (because the response for rows 2 and 3 is the same).
However, making a request for an existing key has a success response only if the user has both the ListBucket, GetObject permissions.

#### Impl 2: Explicitly request the permissions (policies) of the log processing role
This should be a more reliable solution, as the log processing role should be able to read all of its policies and permissions.
Panther can then explicitly search inside the policies for the `GetObject` permission it needs.

For this to work, the log processing role should have at least these extra permissions: 
- `iam:ListRolePolicies`
- `iam:GetRolePolicy`
- `iam:ListAttachedRolePolicies`

This solution will require more development time. 
Because we can only request details for 1 policy at a time from the AWS API, if the role has many policies attached, it may slow down the health check which will lead to slowing down the list-sources page.

**Comment by kostaspap** [comment]
I think impl1 makes sense! The only tricky part is that we need to handle the case where the bucket or prefix is empty where the List will return no results.

**Comment by giorgosp** [comment]
> I think impl1 makes sense! The only tricky part is that we need to handle the case where the bucket or prefix is empty where the List will return no results.

We can show a message like the bucket needs to have some data for the health check to work.

**Comment by georgepsarakis** [comment]
Nice analysis! I am assuming that it will be rare for the bucket / prefix to be empty at this point. I am guessing that the first step for anyone performing the setup would be to first configure log storage and confirm it, and then proceed with Panther configuration. Maybe an informational message that we found no files in the bucket yet, would be nice too though. I would also say that this seems somehow best effort at this stage, permissions can always change after the health check runs ... and I think the System Health notifications subsystem will continuously monitor for permission issues.

A minor note on:
> Why not just make a GetObject request for a random non-existent key (eg panther-health-check)?

I would say maybe make this truly random, using a UUID or random number and not a constant value.

**Comment by giorgosp** [comment]
It is definitely best-effort, since it doesn't account for bucket policies or object ACLs.

>I would say maybe make this truly random, using a UUID or random number and not a constant value.

We have to use an existing key in order to at least be sure that the log processing role has the GetObject permission

**Comment by georgepsarakis** [comment]
> We have to use an existing key in order to at least be sure that the log processing role has the GetObject permission

I was not referring to the existing keys, I thought that this concerns the missing key scenario.
