### ISSUE TITLE
AppSync fails to deploy

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#2592]
### Describe the bug

Attempting to deploy the `master` branch (4efc5c22) fails with

> 20:58:04	ERROR	[deploy]	stack panther-appsync: AWS::AppSync::Resolver ListRulesResolver CREATE_FAILED: No field named rules found on type Query

### Steps to reproduce

1. checkout latest `master`
2. `mage deploy`

**Comment by austinbyers** [comment]
Deploys were working for me 7 days ago

**Comment by 3nvi** [comment]
Yeah, we were aware but an open PR (that was fixing that among others) took a bit longer than expected. I've isolated the fix into a [separate PR](https://github.com/panther-labs/panther/pull/2594) and merged it.

Now everything should be fine
