### ISSUE TITLE
Standard Fields - Edge Cases and Oddities

### ISSUE THREAD

**Issue by wey-chiang** [panther-labs/panther#2601]
### Describe the bug

Reviewing the schemas revealed some oddities and edge cases for the Standard Fields that Panther normalizes across all log records.

### Expected behavior

The following are summaries of the anomalous behavior from the `log_processor` testdata. 

Refer to the **Additional Context** section for more details.

#### Anomalous Behavior

- GitLab - Production Tests<br />The `location` field (`"http://34.222.254.254/users/sign_in"`) shows an IP Address. <br />Shouldn't `p_any_ip_addresses` include `34.222.254.254`?<br /><br />
- GSuite - Data clearly shows domain names: <br />i.e. `www.google.com/accounts/OAuthLogin` and `77185425430.apps.googleusercontent.com` <br />However the results do not include any `p_any_domain_names`<br /><br />
- AWS - These values should be included in their respective `p_` fields but are not included:
  - `p_any_aws_arns` - `arn:aws:wafv2:us-west-2:123456789EXAMPLE:regional/webacl/panther_web_dev/f96fe2f4-a2f4-4c06-a4bc-afd495bd675f`
  - `p_any_domain_names` - `web-123456789.us-west-2.elb.amazonaws.com`
  - `p_any_aws_account_ids` - `123456789EXAMPLE` and `123456789EXAMPLE_MANAGED`

#### Others

- Consider `ip-172-31-14-137.us-west-2.compute.internal` <br />While this is explicitly a domain name, it also explicitly denotes an IP address. <br />Would we want to extract `172.31.14.137` as an IP address?<br /><br />
- From the Sophos logs:
  - There is a file path value: `"/Users/jsmith/Dropbox/.dropbox.cache/new_files/eec8381bba1914aa2207f4a53c0fad1e"`. <br />Based on the context of the test data, this appears to be a Win x32 system. <br />However this file path is not a valid Windows file path (would be valid if `/` were `\`)
  - In one of the tests, there is a file path explicitly stated in the `name`. <br />Since the file path input key is not present, the results do not show any file paths. <br />Would this make a case to add support for file paths in the standardized `p_` fields?
- AWS
  - VPC DNS Tests
    - `p_any_domain_names`
      - Why is `xn--fa-hia.com` not included in this `p_` field?
      - What's up with the `"faß.com"` included in this `p_` field?
      - Why is `foo@bar.com` included in this `p_` field? 
      - Shouldn't `foo@bar.com` be included in the `p_any_emails` field?
  - CloudTrail (base and insight) Tests
    - While not particularly useful, shouldn't `p_any_domain_names` match on the following:
      - `kms.amazonaws.com`
      - `ssm.amazonaws.com`

### Additional context

See this [Pull Request Review](https://github.com/panther-labs/panther-analysis/pull/187#pullrequestreview-581874346) for full context.

**Comment by rleighton** [comment]
As the the dns test, that is doing a puny decode of an internationalize
domain name

**Comment by rleighton** [comment]
```
Consider ip-172-31-14-137.us-west-2.compute.internal
While this is explicitly a domain name, it also explicitly denotes an IP address.
Would we want to extract 172.31.14.137 as an IP address?
```
I would say no, you cannot count how this is done ... the pattern  varies significantly in my experience.

**Comment by rleighton** [comment]
```
CloudTrail (base and insight) Tests
While not particularly useful, shouldn't p_any_domain_names match on the following:
kms.amazonaws.com
ssm.amazonaws.com
```

I believe these are put in an ip address field, so they are not ip address... we would have to use conditional logic here (if not ip address then domain). Do able but not very useful for investigations.

**Comment by rleighton** [comment]
```
AWS - These values should be included in their respective p_ fields but are not included:
p_any_aws_arns - arn:aws:wafv2:us-west-2:123456789EXAMPLE:regional/webacl/panther_web_dev/f96fe2f4-a2f4-4c06-a4bc-afd495bd675f
p_any_domain_names - web-123456789.us-west-2.elb.amazonaws.com
p_any_aws_account_ids - 123456789EXAMPLE and 123456789EXAMPLE_MANAGED
``
I'm not sure about the domain name, but the others fail validation due to 'EXAMPLE' in the account names .. take that out and make it 12 digits and it will work.

**Comment by rleighton** [comment]
```
GSuite - Data clearly shows domain names:
i.e. www.google.com/accounts/OAuthLogin and 77185425430.apps.googleusercontent.com
However the results do not include any p_any_domain_names
```
Domain names cannot easily be reliably identified based on their content ... my guess is the fields these are in  are not tagged as domain fields ... they must be tagged to get pulled out.

**Comment by rleighton** [comment]
```
GitLab - Production Tests
The location field ("http://34.222.254.254/users/sign_in") shows an IP Address.
Shouldn't p_any_ip_addresses include 34.222.254.254?
```
Only if it is tagged to extract it in the parser ...

**Comment by georgepsarakis** [comment]
Thanks for opening this @wey-chiang and @rleighton for the feedback, very helpful comments.

Regarding [this](https://github.com/panther-labs/panther/issues/2601#issuecomment-772896343), I understand that it works on production with valid values, but we should change the tests to better reflect the parsed log output. 

I'll take a closer look when I find some time and compile a list of possible changes for the parsers.
