### ISSUE TITLE
Cloud Security region ignore list breaks CloudTrail scanning

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#2619]
### Describe the bug

When you specify any region ignore list in your cloud security source configuration, it causes all scans of CloudTrail resources to fail. This is because when you scan CloudTrail you scan all regions due to the fact that we construct a CloudTrail meta resource.

This affects GuardDuty and Config as well, since these resources also construct a meta resource.

### Steps to reproduce

1. Create a Cloud Security source with a region ignore list
2. Initiate a full account scan
3. Observe errors for the CloudTrail, Guard Duty, and Config scanners

### Expected behavior

Panther should still scan these resources in all regions it is able to do so

### Environment

How are you deploying or using Panther?

- Panther v1.15.3
- 
### Additional context

This is likely happening because we have `getClient` return an error when a denied region is requested, but only the individual resource scanner is handling this error as a special case. Anywhere else that `getClient` is called, this is not handled as a special case leading to these situations where this is treated as a scanning error and fails the scan.

**Comment by wey-chiang** [comment]
Issue cloned.
