### ISSUE TITLE
Rules Engine Should Validate All Functions in Testing

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#2640]
### Describe the bug

The rules engine should validate the return types of executed functions so users know there are issues.

For example, if a user returns a string from `destinations`, then they get no feedback.

### Steps to reproduce

Create a rule with a function like:
```
def destinations(event):
   return 'Some Destination'
```

### Expected behavior

User's should be informed with a nice message during testing that their function does not return the correct type of object.

**Comment by rleighton** [comment]
BTW, the testing API is extremely simple making it very hard to extend. We should change it to have the usual input/output objects that can easily have attributes added as needed w/out changing many interfaces between here and there.

**Comment by wey-chiang** [comment]
Looking at the rules engine: `rule.py:_run_command` function, I think I spotted an issue that went unnoticed:

```
    def _run_command(self, function: Callable, event: PantherEvent, expected_type: Any) -> Any:
        result = function(event)
        # Branch in case of list
        if not isinstance(expected_type, list):
            if not isinstance(result, expected_type):
                raise Exception(
                    'rule [{}] function [{}] returned [{}], expected [{}]'.format(
                        self.rule_id,
                        function.__name__,
                        type(result).__name__,
                        expected_type.__name__,
                    )
                )
        else:
            if not isinstance(expected_type, list) or not all([isinstance(x, (str, bool)) for x in result]):
                raise Exception(
                    'rule [{}] function [{}] returned [{}], expected a list'.format(self.rule_id, function.__name__,
                                                                                    type(result).__name__)
                )
        return result
```

The following line, logically, makes no sense:

`if not isinstance(expected_type, list) or not all([isinstance(x, (str, bool)) for x in result]):`

This should actually be 

`if not isinstance(result, list) or not all([isinstance(x, (str, bool)) for x in result]):`

Need to test to verify but if that is indeed the root issue, I'll include the fix in the destinations lookup work

**Comment by wey-chiang** [comment]
Yeah, looks like once I make that change the UI will yield:

> Exception: rule [RuleAPITestRule] function [destinations] returned [str], expected a list
