### ISSUE TITLE
[BE] Unified Integrations

### ISSUE THREAD

**Issue by alxarch** [panther-labs/panther#2641]
## Background

For the Unified Integrations to work properly the BE must provide two endpoints to describe the _Log Sources_ available.

## Design

The BE should provide 2 new endpoints:
  1. `ListLogSources` that returns a list of Log Sources optional `Category` filter
  2. `GetLogSource` that returns the full details for a single `LogSource` item

Each `Log Source` entry should provide the  information required to render the UI such as:
 - `name`: a user-friendly name for the entry (i.e. `Cisco Umbrella`)
 - `id`: a computer-friendly identifier for the entry (i.e. `cisco_umbrella`). This can be used to resolve icon assets for the Log Source.
 - `App Info`/ `UseCases` / `How It Works`: description stuff that fill the screens about each Log Source
 - `transportMethods`: a list of available transport methods for this `Log Source`
 - `defaultParsers`: a list of log type identifiers to pre-select on a new source
 - `availableParsers`: a list of all available log parsers for this Source.
 - `popularity`: An arbitrary 'score' for sorting the entries. Alphanumeric order would not be very helpful especially in the 'all' page. I suggest we use such a field to have control of the sorting on the definition side.
 
We need to have two lists for log parsers  (`available` / `default`) for the following reasons:
- Some Log Sources have many available log types to choose from and we can provide some as pre-selected but not all (i.e. `AWS`)
- We plan to provide alternative formats for each log type in the near future by separating parsers/schemas. Using this we can list all parsers and have the default ones pre-selected.
- It provides a solution to handling user-defined log parsers (a.k.a. `CustomLogs`). These could all be grouped in a `Custom` Log Source with empty `defaultParsers` and let the user choose which of their own parsers they want to use from the `available` list.
- It avoids having to re-define acros FE/BE the current `ListAvailableLogTypes` that is currently used. That endpoint does not have filtering and in our case, once a user has chosen a Log Source the options for available parsers should be restricted.

## Notes

@3nvi I will add two examples for each endpoint in the comments below and we can discuss this further

**Comment by alxarch** [comment]
## `ListLogSources` endpoint example 

FE wants to show the list page for the `Server` category of `Log Sources`

 <details>
    <summary>ListLogSourcesInput</summary>

```json
{
   "ListLogSources": {
      "Category": "Server"
   }
}
```

 </details>

 <details>
    <summary>ListLogSourcesOutput</summary>

```json
{
   "LogSources": [
      {
          "name": "Apache",
          "id": "apache",
            "popularity": 100,
         "categories": ["Network", "Server"]
      },
      {
          "name": "NGINX",
          "id": "nginx",
          "popularity": 100,
         "categories": ["Network", "Server"]
      },
      {
        "name": "GitLab",
        "id": "gitlab",
         "popularity": 20,
        "categories": ["SaaS", "Server"]
      }
   ]
}
```

</details>

**Comment by kostaspap** [comment]
> ## `ListLogSources` endpoint example
> FE wants to show the list page for the `Server` category of `Log Sources`
> 
> ListLogSourcesInput
> ```json
> {
>    "ListLogSources": {
>       "Category": "Server"
>    }
> }
> ```
> 
> ListLogSourcesOutput
> ```json
> {
>    "LogSources": [
>       {
>           "name": "Apache",
>           "id": "apache",
>             "popularity": 100,
>          "categories": ["Network", "Server"]
>       },
>       {
>           "name": "NGINX",
>           "id": "nginx",
>           "popularity": 100,
>          "categories": ["Network", "Server"]
>       },
>       {
>         "name": "GitLab",
>         "id": "gitlab",
>          "popularity": 20,
>         "categories": ["SaaS", "Server"]
>       }
>    ]
> }
> ```

`popularity`?

**Comment by alxarch** [comment]
## `GetLogSource` endpoint example 

User selected the `Apache` _Log Source_ and FE wants to render the editor screen 

 <details>
    <summary>GetLogSourceInput</summary>

```json
{
   "GetLogSource": {
      "LogSource": "apache"
   }
}
```

 </details>

 <details>
    <summary>GetLogSourceOutput</summary>

```json
{
   "LogSource": {
          "name": "Apache",
          "id": "apache",
         "popularity": 100,
         "categories": ["Network", "Server"],
         "appInfo": "Lorem ipsum dolor sit amet",
         "howItWorks": "Lorem ipsum dolor sit amet",
         "useCases": "Lorem ipsum dolor sit amet",
         "defaultParsers": ["Apache.AccessCommon"],
         "availableParsers": [
            {
               "name": "Apache.AccessCommon",
               "description": "Apache HTTP server access logs using the 'common' format",
               "referenceURL": "https://httpd.apache.org/docs/current/logs.html#common"
            },
             {
               "name": "Apache.AccessCombined",
               "description": "Apache HTTP server access logs using the 'combined' format",
               "referenceURL": "https://httpd.apache.org/docs/current/logs.html#combined"
            },
            {
               "name": "Apache.AccessJSON",
               "description": "Apache HTTP server access logs using JSON format",
               "referenceURL": "https://httpd.apache.org/docs/current/logs.html#logFormat"
            },
         ]
   }  
}
```

</details>

**Comment by 3nvi** [comment]
> ## `ListLogSources` endpoint example
> FE wants to show the list page for the `Server` category of `Log Sources`
> 
> ListLogSourcesInput
> ```json
> {
>    "ListLogSources": {
>       "Category": "Server"
>    }
> }
> ```
> 
> ListLogSourcesOutput

I don't think the category filter is needed. I'll most likely make 1 call, fetch them all & break them down locally

**Comment by 3nvi** [comment]
> ## `GetLogSource` endpoint example
> User selected the `Apache` _Log Source_ and FE wants to render the editor screen
> 
> GetLogSourceInput
> ```json
> {
>    "GetLogSource": {
>       "LogSource": "apache"
>    }
> }
> ```
> 
> GetLogSourceOutput

Shouldn't I give you back the `id` field you returned? I'd expect an input of `id` or `logSourceId`

**Comment by 3nvi** [comment]
Thanks @AlexPanther .

-  Can you help me understand what `popularity` is?
-  Also, to remain consistent in our naming patterns, can we rename `name` to `displayName`?
- Can we add an `isEnterprise` field (or something similar) to denote whether this log source is available on enterprise only or not?
- I think we are missing the transport methods from the `GetLogSource` endpoints. Will need to know whether some support log pullers, EventBridge, etc.

Thoughts?

**Comment by alxarch** [comment]
> Thanks @AlexPanther .

That is not me :D

> 
> * Can you help me understand what `popularity` is?

I think we'll need some sort of sorting method apart from alphabetical.
As I say in the description of the issue, it is just an arbitrary number so we can control the ordering when we define the Log Sources.
If you think alphabetical suffices I can remove it.

> * Also, to remain consistent in our naming patterns, can we rename `name` to `displayName`?

You mean be consistent across APIs? I would not imagine this was a requirement.

> * Can we add an `isEnterprise` field (or something similar) to denote whether this log source is available on enterprise only or not?

Anything that has a transport method other than `SQS` and `S3` is enterprise-only.
It would be wise to add such a field in the BE to avoid having to change FE code if we decide to OSS some other transport method. 

> * I think we are missing the transport methods from the `GetLogSource` endpoints. Will need to know whether some support log pullers, EventBridge, etc.

Yep, fixed that

> 
> Thoughts?

**Comment by 3nvi** [comment]
> If you think alphabetical suffices I can remove it.

We've agreed that API will return sorted data based on popularity

> "ListLogSources": {
      "Category": "Server"
   }
   
We've agreed that if no `Category` is specified, then all log sources will be returned

> Also, to remain consistent in our naming patterns, can we rename name to displayName?

Yes

> Shouldn't transport methods be "enterprise" logs instead of transpont methods?

We required [SaaS logs to be flagged as "enterprise](https://share.goabstract.com/8b3c0525-4469-4ce7-8d9a-c1ea7dd25e84?commentId=15db6b0c-606d-44c5-9b0b-dcbcca2bd6bd&sha=80a6f693c33c39a68588c721a418c04429418043). Field will be named `isEnterprise` and will be present in both endpoints

> Icons?

Will be added statically and will be resolved based on log source ID.

> How can we make sure that during updates only the correct log types are shown as options

We will be including a `logSourceId` in the response of a log integration and the FE or GraphQL layer will resolve it, fetch the available log types for this `logSourceId` and limit the log types shown
