### ISSUE TITLE
Python engines are failing to start

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#2655]
### Describe the bug

On the latest `master` (commit 08912e71), both the `policy-engine` and the `rules-engine` fail to start with

> [ERROR] PermissionError: [Errno 13] Permission denied: '/var/task/src/main.py'

Usually, this means there is a problem with the deployment package (Lambda zipfile). So the prime suspect is #2648 , since that PR changed the contents of the zipfiles.

But @nhakmiller and I both had deployments in different regions with that change reverted and still we see the error. I'm not completely convinced of its innocence yet - see if reverting the change is sufficient and we just weren't testing it correctly.

---

* A fresh source deploy of the `release-1.15` branch has working engines, so it's not an issue with my dev environment.
* The `policy-engine` Python source code hasn't changed at all since the 1.15 release

### Steps to reproduce

1. `mage deploy`
2. Try testing a rule/policy in the web app
3. Look at the CloudWatch logs for the `policy-engine` or `rules-engine`

### Additional context

The [release-master](https://github.com/panther-labs/panther/compare/master...release-1.15#diff-41be1d6088a0d600e4df6973ca6e9d78762a54364cd9f65799f4166f9fa775a6) comparison may be helpful to see what code actually changed

From the AWS Lambda console, you can export the Lambda zipfile exactly as AWS sees it to inspect the contents. From what I can tell, it looks fine

The problem exists in `panther-enterprise` as well

**Comment by giorgosp** [comment]
@austinbyers Seems like it has to do with the permissions of the files included in the zip archive. From a quick google search: https://stackoverflow.com/questions/46076543/permission-denied-after-uploading-aws-lambda-python-zip-from-s3

**Comment by georgepsarakis** [comment]
I deployed 08912e7 with no issues. I also checked with `zipinfo` that artifacts in `out/lambda/` all files seem accessible. As a sidenote, I noticed that the Docker container in [dev.sh](https://github.com/panther-labs/panther/blob/master/dev.sh) uses `root` as a user, but still this should not be an issue if the permissions are correct. Perhaps unrelated but maybe we should change this as well at some point, to better mirror workstation environment (it is also a recommended practice I believe).

**Comment by austinbyers** [comment]
Lowering the priority since it seems to be only an issue with some dev environments. I'm not using the `dev.sh` image

**Comment by nhakmiller** [comment]
We determined the root cause of the issue, an internal tool started silently removing the global read permissions from certain directories on our developers machines, which made the go binaries and python files unreadable by AWS Lambda after uploading them. Disabled that setting in our tool, let the impacted developers know to re-add the permissions, and things appear to be working now. A future improvement to our deploy system could be to automatically set the correct permissions on all assets before uploading them to AWS. Issue opened here https://github.com/panther-labs/panther/issues/2667 to track.
