### ISSUE TITLE
Can't manage users after changing cloudformation to community release

### ISSUE THREAD

**Issue by gorrie** [panther-labs/panther#2668]
### Describe the bug

Panther users created via SAML login may not be deleted after updating Panther cloudformation stack from enterprise to community edition.

### Steps to reproduce

1. Have external id users in enterprise/pro
2. Change stack to community edition
3. External users can not be deleted or edited

### Expected behavior

I expected user management to be possible.  Suggest either purge external users on stack change or allow manual removal instead of error.

### Environment

How are you deploying or using Panther?

- Panther version or commit: updated cloudformation v1.15.2.  Error still present in community-1.15.3 (4501b9394)

### Screenshots

<img width="521" alt="userfail" src="https://user-images.githubusercontent.com/4443401/107835607-faf26b80-6d4e-11eb-91d0-8287a683e51e.png">

**Comment by 3nvi** [comment]
Hey @gorrie unfortunately currently we don't support downgrades, so that's why you are seeing that. You might have to re-deploy Panther from scratch. If you need data retention or there's stuff that's blocking you from doing this, let us know and we'll help you out

cc @austinbyers

**Comment by austinbyers** [comment]
Right, downgrades have never been tested and aren't yet officially supported. I'm actually surprised the community stack update was deployed successfully, that's good to know!

A possible workaround without having to completely start over - you may be able to go to the AWS Cognito console and manually delete each user. Then you can re-invite the first user using the `invite` opstool which you can find in our [release assets](https://github.com/panther-labs/panther/releases/tag/v1.15.0)

**Comment by austinbyers** [comment]
> Panther users created via SAML login may not be deleted after updating Panther cloudformation stack from enterprise to community edition.

Keep in mind that even if the SAML users technically exist in Panther, they still won't be able to login, so it shouldn't cause problems if they stay in the system, but I understand wanting to clear them just for consistency

**Comment by austinbyers** [comment]
Closing the issue since we don't have any plans to work on it for the foreseeable future, but thanks for the report! Like @3nvi said, we're happy to provide best-effort support: you can keep commenting here or you can reach out on our Slack channel
