### ISSUE TITLE
Filter by "Created By"

### ISSUE THREAD

**Issue by lindsey-w** [panther-labs/panther#2709]
### Describe the bug

Filter by "Created By" returning detections for more than what is specified.  

### Steps to reproduce

1. Go to 'Detections
2. Filter by "Created By Me" and Apply
3. List of detections includes those created by other users

### Expected behavior

It would filter to just the detections I created.

### Environment

How are you deploying or using Panther?

- Panther version or commit: 1.16.0-RC (78d974a62)
- OS: MacOS
- Browser: Brave

### Additional context

Looks like the input for the `listDetections` call might just be missing the "createdBy" field value. Example data:

```
{
    "input": {
        "complianceStatus": "",
        "hasRemediation": null,
        "ids": null,
        "resourceTypes": null,
        "logTypes": null,
        "analysisTypes": [
            "POLICY",
            "RULE"
        ],
        "nameContains": "",
        "enabled": null,
        "severity": null,
        "tags": null,
        "createdBy": "",
        "lastModifiedBy": "",
        "initialSet": true,
        "fields": null,
        "sortBy": "lastModified",
        "sortDir": "descending",
        "pageSize": 10,
        "page": 1
    }
}
```

**Comment by 3nvi** [comment]
The `createdBy` maps to the backend value of `initialSet`. I see that in your example `initialSet` is `true`, which means that your are filtering by "detections that were created initially by the system". Thus I'm inclined to believe you have selected "Panther (system)" as the value of "Created by". When I click "Created by me", the URL looks something like:

`/detections/?initialSet=false&page=1&sortBy=lastModified&sortDir=descending`

and the request payload looks something like

```
initialSet: false
page: 1
pageSize: 10
sortBy: "lastModified"
sortDir: "descending"
```

Could it be that something else is going wrong?

**Comment by 3nvi** [comment]
Ah, I now realize your confusion. Currently, we don't have a way to filter by items that werre created by "you you". When we says "created by me" we mean any user that is not Panther. Filtering by "created by" goes like this:


- All = All
- Created by me = You or any other physical system user
- Panther (system) = Created by the Panther team, not a user of said Panther deployment

I 100%  agree we should change this naming to avoid further confusions. Any ideas as to what it should ideally say?

**Comment by lindsey-w** [comment]
Gotcha! Yea, I might have done "created by system" in that example.

Understood.  Yes, I was confused by the wording - I thought "created by me" would return just "mine" vs any non-panther system user. Perhaps "Created by users" or something of the like? I'm not great at naming schemes, haha.
