### ISSUE TITLE
Update cloud security account onboarding flow - backend

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#271]
### Description

This story contains all the features that have to be implemented in the backend to support the new security account onboarding flow. 

### Acceptance Criteria
- Storing an integration will now prompt the backend to assume the appropriate roles (Audit, AutoRemediation) and verify that the real-time event infrastructure is in place (CWE are setup and subscriptions are in place)
- API method that accepts the parameters provided by the user and returns the CFN template that the users have to deploy to their account. Check with @3nvi to validate how this API should look like.

**Comment by nhakmiller** [comment]
Didn't realize the full scope of this issue when I closed it, re-opening.

**Comment by nhakmiller** [comment]
@3nvi @kostaspap , for here and #272, do you want this to be one API call or two? It feels waaaay more natural for me to have this be two API calls, but the description here explains it as one. I'm referring to this line:

`Storing an integration will now prompt the backend to assume the appropriate roles (...) and verify that the real-time event infrastructure is in place`

which makes it seem like the backend calls `CheckIntegration` automatically when the frontend makes an `PutIntegration` API call, which seems weird to me. So which of the following options do you want the backend to do:

1. When the frontend calls `PutIntegration` or `UpdateIntegration`, the backend automatically does the health check and returns an error if the health check fails.
2. First the frontend calls `CheckIntegration`, and the backend returns the health check results. Then the frontend may or may not call `PutIntegration` (perhaps depending on some user input), at which time the backend saves the integration in dynamo regardless of integration status.

Personally I much prefer option 2, but open to hear your inputs.

**Comment by 3nvi** [comment]
Interestingly enough, personally I would say that I want both (1) and (2) :P 

Although there will be no malicious actions, relying on the front-end to perform validation in frail. You shouldn't be able to add an integration if it's not correctly setup and currently - with only Front-end checks in place - someone can easily bypass this by performing a `curl` outside the front-end.

At the same time though, I feel that the front-end should warn you ahead of time that the source is  not looking healthy and not enable the "Save" button, until it is. Thus, I do need a way to `CheckIntegration`.

If I had to only pick (1) or (2), I would pick (2). In general though, I feel that every all validations should always be present in the backend

**Comment by kostaspap** [comment]
I also agree with @3nvi  that we need both :P Someone shouldn't be able to `PutIntegration` if this is not allowed. That seems to be part of the onboarding logic that should be integrated in the backend.
