### ISSUE TITLE
Update log onboarding flow - backend

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#272]
### Description

This story contains all the features that have to be implemented in the backend to support the new log onboarding flow. 

### Acceptance Criteria
- Storing an integration will now prompt the backend to assume the appropriate role (LogProcessing) and try to verify that it has the appropriate S3 permissions (e.g. perform an S3 Object List operation)
- API method that accepts the parameters provided by the user and returns the CFN template that the users have to deploy to their account. Check with @3nvi to validate how this API should look like.

**Comment by nhakmiller** [comment]
Didn't realize the full scope of this issue when I closed it, re-opening.
