### ISSUE TITLE
PantherAlarm-LambdaApplicationWarns-panther-aws-event-processor misfiring

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#274]
### Describe the bug

The above alarm is in ALARM state even though I haven't onboarded CloudSecurity accounts.  
The dashboard showing a warning like this repeating: 

`{"level":"warn","ts":1582644014.660855,"caller":"processor/classify.go:101","msg":"dropping event from unauthorized account","application":"panther","requestId":"16b50fa9-4f16-5229-ac4e-5966727a235a","accountId":"123456789012","eventSource":"kms.amazonaws.com"}
`

### Steps to reproduce

1. Onboard CloudTrail logs
2. Make sure you haven't onboarded the account in Cloud Security

### Expected behavior

No alarm should be firing for such an issue. 

### Environment

How are you deploying or using Panther?

- Panther version or commit: [e.g. v0.1.1]
- OS: MacOS 10.15.3
- Browser: All browsers https://github.com/panther-labs/panther/commit/6d3ebbd4d8b4d6fcfdd24b80514836f85b3c51b2

**Comment by rleighton** [comment]
Please open the PantherOverview dashboard and add relevant log events. I suspect Nick's new code fixes this.

**Comment by kostaspap** [comment]
> Please open the PantherOverview dashboard and add relevant log events. I suspect Nick's new code fixes this.

Added log line

**Comment by nhakmiller** [comment]
Sorry yes my change should fix this, let me merge it.

**Comment by kostaspap** [comment]
Fixed with https://github.com/panther-labs/panther/commit/29be1f269c9e02d183c25b43450ff3b08e4090b0
