### ISSUE TITLE
Apply Rules/Policies on Specific Account/Log Sources

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#281]
### Describe the ideal solution

Allow rules and policies to be applied against certain accounts or log sources. This provides a filtering mechanism that doesn't have to be explicitly written out in the analysis logic.

### Describe your use cases

Avoid detections in non-production accounts

### How frequently would you use such a feature

Daily!

### Describe alternatives you have considered

The alternative is writing the logic into the Python function body

### References

None

**Comment by nhakmiller** [comment]
Most likely this will be captured in prefilters.
