### ISSUE TITLE
The Log Parser should record the time each event is parsed.

### ISSUE THREAD

**Issue by stoggi** [panther-labs/panther#282]
### Describe the ideal solution

When the Parser successfully parses an event, it should record the current time in UTC and store it with the event.

### Describe your use cases

Some log entries may not have a timestamp, for example Syslog RFC5424 (#261). However the `PantherEventTime` field is required to correctly store and find historical events. In this case, it would be good to know that the EventTime was set to a "best guess" of the time it was parsed.

Recording the time an event is parsed is useful when evaluating the "lag" of a logging and alerting system. Knowing how long it takes from log creation to successful log parsing can be a useful metric in overall logging infrastructure health.

In the event when the logs are severely behind, `parsed time - event time` be monitored to ensure the system is catching up.

### Describe alternatives you have considered

In #261, an alternative was considered: A boolean flag that indicated when the `PantherEventTime` was set to the current time. This only accounted for the first use case, where an event has no timestamp, not for monitoring lag.

One consideration is the overhead of calling `time.Now()` for every parsed log. [This blog post](https://blog.cloudflare.com/its-go-time-on-linux/) has some interesting information about `time.Now()` in Golang. On a 64bit Linux system this might add somewhere in the order of 20 nano seconds for each call. Would we want to store `time.Now()` once for the lambda invocation, and pass it to each classifier?

**Comment by rleighton** [comment]
This is needed for V1.

**Comment by rleighton** [comment]
Good point about calling time.Now() for event.

I suggest you change the interface for a parser from:
```
	// Parse attempts to parse the provided log line
	// If the provided log is not of the supported type the method returns nil
	Parse(log string) []interface{}
```
to:
```
	// Parse attempts to parse the provided log line
	// If the provided log is not of the supported type the method returns nil
	Parse(parseTime time.Time, log string) []interface{}
```
See: https://github.com/panther-labs/panther/blob/master/internal/log_analysis/log_processor/parsers/parsers.go#L30

The classifier (which calls the parsers) already keeps a start time:
https://github.com/panther-labs/panther/blob/master/internal/log_analysis/log_processor/classification/classifier.go#L135

So, pass that down to where it calls Parse().

**Comment by kostaspap** [comment]
> One consideration is the overhead of calling `time.Now()` for every parsed log. [This blog post](https://blog.cloudflare.com/its-go-time-on-linux/) has some interesting information about `time.Now()` in Golang. On a 64bit Linux system this might add somewhere in the order of 20 nano seconds for each call. Would we want to store `time.Now()` once for the lambda invocation, and pass it to each classifier?

So I did a quick benchmark to see how long it takes to parse a log. Average time to parse a CloudTrail log on my laptop is `12761 ns` and S3 Server access log is `7990 ns`

Code is really easy for whoever wants to run it
```
func Benchmark(b *testing.B) {
	log := `...`
	parser := &S3ServerAccessParser{}
	for i := 0; i < b.N; i++ {
		parser.Parse(log)
	}
}
```

I'd say go for the easier solution and that I think you can just set the field inside the `SetCoreFieldsPtr` method. I'm not sure 20 ns make any difference performance wise.

**Comment by rleighton** [comment]
> > One consideration is the overhead of calling `time.Now()` for every parsed log. [This blog post](https://blog.cloudflare.com/its-go-time-on-linux/) has some interesting information about `time.Now()` in Golang. On a 64bit Linux system this might add somewhere in the order of 20 nano seconds for each call. Would we want to store `time.Now()` once for the lambda invocation, and pass it to each classifier?
> 
> So I did a quick benchmark to see how long it takes to parse a log. Average time to parse a CloudTrail log on my laptop is `12761 ns` and S3 Server access log is `7990 ns`.
> 
> Code is really easy for whoever wants to run it
> 
> ```
> func Benchmark(b *testing.B) {
> 	log := `...`
> 	parser := &S3ServerAccessParser{}
> 	for i := 0; i < b.N; i++ {
> 		parser.Parse(log)
> 	}
> }
> ```
> 
> I'd say go for the easier solution and that I think you can just set the field inside the `SetCoreFieldsPtr` method. I'm not sure 20 ns make any difference performance wise?
> 
> Also note that in the classifier code we call time.Now() 4 times on every log parsing for the shake of getting metrics (these calls is not included in the benchmark above). If we consider this to be critical, we would have to look into fixing that part as well e.g. doing some sampling when doing measurements.

Let's take the easier path. I plan to review this in the next few weeks for part of a new feature. I personally do not like giving up easy wins when we are doing redundant work (even if it is small). Death by 1000 cuts is how you get slow sw.

**Comment by stoggi** [comment]
>	// Parse attempts to parse the provided log line
>	// If the provided log is not of the supported type the method returns nil
>	Parse(parseTime time.Time, log string) []interface{}

This would also make the tests much nicer, not having to compare against `time.Now().UTC()`

I'm happy to go either way. How about I start with passing in the parseTime, and if it looks like it will take a bit of time I can always fall back to calling time.Now() in the parser.

**Comment by kostaspap** [comment]
> > // Parse attempts to parse the provided log line
> > // If the provided log is not of the supported type the method returns nil
> > Parse(parseTime time.Time, log string) []interface{}
> 
> This would also make the tests much nicer, not having to compare against `time.Now().UTC()`
> 
> I'm happy to go either way. How about I start with passing in the parseTime, and if it looks like it will take a bit of time I can always fall back to calling time.Now() in the parser.

This pattern is problematic. We have now to parse a `time.Time` object down the chain in 3 method calls and have to update *each* parser to make sure that it sets a value passed by the classifier. Many changes and for little value. 
A more proper solution would be that the parsers switch from returning `interface{}` to returning a struct that had the "ParsedTime" field in it - then the classifier would set it. Such a solution is easier to test and makes the code more readable - it is clear to the reviewer how this field is set. Passing it through the parsers means a reviewer will have to go and check each individual parser to make sure it is set properly (sure there are tests for that but I am trying to explain why the solution is not so "clean"). 

You can just set the time in the `SetCoreFieldsPtr` method and eventually we will redesign the Parsers to the pattern described above. I think we already have to test similar scenarios, you could potentially just make a helper test function to test time.Now() timestamps (e.g. fail if timestamp is greater than X seconds to current)

**Comment by rleighton** [comment]
> > > // Parse attempts to parse the provided log line
> > > // If the provided log is not of the supported type the method returns nil
> > > Parse(parseTime time.Time, log string) []interface{}
> > 
> > 
> > This would also make the tests much nicer, not having to compare against `time.Now().UTC()`
> > I'm happy to go either way. How about I start with passing in the parseTime, and if it looks like it will take a bit of time I can always fall back to calling time.Now() in the parser.
> 
> This pattern is problematic. We have now to parse a `time.Time` object down the chain in 3 method calls and have to update _each_ parser to make sure that it sets a value passed by the classifier. Many changes and for little value.
> A more proper solution would be that the parsers switch from returning `interface{}` to returning a struct that had the "ParsedTime" field in it - then the classifier would set it. Such a solution is easier to test and makes the code more readable - it is clear to the reviewer how this field is set. Passing it through the parsers means a reviewer will have to go and check each individual parser to make sure it is set properly (sure there are tests for that but I am trying to explain why the solution is not so "clean"). Now this requires further redesign that we will eventually do (@rleighton is going to get it next) so for the moment let's go for something simpler that doesn't require updating all our interfaces.
> 
> You can just set the time in the `SetCoreFieldsPtr` method and eventually we will redesign the Parsers to the pattern described above. I think we already have to test similar scenarios, you could potentially just make a helper test function to test time.Now() timestamps (e.g. fail if timestamp is greater than X seconds to current)

Yes, let's do what Kostas suggests in light of the fact that we will likely do even more refactoring than described above in the next few months given both new log types (unanticpated requirements) and also we want to make the classifier "smart" w.r.t. to log types. So deferring makes sense. I do think that refactoring interface between the driver and the parsers to be more effective is a near term priority but let's do that as its own task.
