### ISSUE TITLE
Updating documentation

### ISSUE THREAD

**Issue by sugandhalahoti** [panther-labs/panther#283]
### Description

We need to review our product documentation as having good open-source documentation is critical.

### Acceptance Criteria

- Rename all occurrences of "Compliance" to "Cloud Security"
- Correct any grammatical errors and sentence construction issues
- Rename Alerting to Destinations

**Comment by 3nvi** [comment]
@jacknagz @sugandhalahoti What's the status of this?

**Comment by sugandhalahoti** [comment]
This is done. Closing
