### ISSUE TITLE
Optimize web component  & page structure 

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#288]
### Description

As the codebase grows, it's important that we properly maintain a folder & component structure that allows us to scale. For this reason I propose the following;

* Rename every kebab-cased React Component file to Pascal-case
* Convert every React Component that is not already a folder, to a folder
* Update web-related docs on how to write new components & pages, according to the changes above

This will allow:

* Cleaner implementation
* Quicker IDE searches & indexing
* Quicker manual searching from external contributors

### Acceptance Criteria

**Every item** present under the `/src/components/` and `src/pages/` folder should be a folder with the following rules:

* The folder should be the name of the component
* The folder should contain at least one file with the exact same name (as both the folder and the component)
* The folder should contain exactly one `index.tsx` file that exports the component, along with anything else that should **publicly** be exported. No `index` file should have React code.

Example:

Let's say we have a component under `/src/components/my-component.tsx`. We would need to:

- Rename `my-component.tsx` to `MyComponent.tsx` (exactly the same name as the related react component)
- Create the folder: `/src/components/MyComponent/`
- Move the file to `/src/components/MyComponent/MyComponent.tsx`
- Add an index file to export it: `/src/components/MyComponent/index.tsx` with a code like: `export { default } from './MyComponent.tsx`. If we needed to export anything extra, then we would also add it in the `index.tsx` file.

**Comment by alexmylonas** [comment]
@3nvi Some questions regarding specific folders:

1. For files in folder  i.e.`/fields/checkbox` should we do (a)  `Fields/Checkbox/Checkbox.tsx` + `Fields/Checkbox/index.tsx` or (b) `Fields/index.tsx` which will export all files in `Fields/Checkbox.tsx` etc

2. For files in `/utils` folder should we group them by type (a) `/Utils/Modals/ModalManager' + `/Utils/Modals/ModalContext'  or by function (b) `/Utils/Managers/ModalManager' + `/Utils/Managers/SidesheetManager' etc, you have any other solution in mind?

**Comment by 3nvi** [comment]
1. The first one
2. The first one again

**Comment by 3nvi** [comment]
> @3nvi Some questions regarding specific folders:
> 
> 1. For files in folder  i.e.`/fields/checkbox` should we do (a)  `Fields/Checkbox/Checkbox.tsx` + `Fields/Checkbox/index.tsx` or (b) `Fields/index.tsx` which will export all files in `Fields/Checkbox.tsx` etc
> 2. For files in `/utils` folder should we group them by type (a) `/Utils/Modals/ModalManager` + `/Utils/Modals/ModalContext` or by function (b) `/Utils/Managers/ModalManager` + `/Utils/Managers/SidesheetManager` etc, you have any other solution in mind?

1. The first one
2. The first one again
