### ISSUE TITLE
Integrations should return new values when updated

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#324]
### Describe the bug

Currently, when an integration is updated (through the `snapshot-api`), nothing is returned back (apart from a boolean denoting whether there was an error).

When I update an integration, it's really helpful to get the new values of this field.

### Steps to reproduce

Call `updateIntegrationSettings` with some new values and see its return value

### Expected behavior

Call `updateIntegrationSettings` should return an object with the updated information

### Additional Context

We need to do add:

```golang
ReturnValues:     aws.String("ALL_NEW"),
```
to dynamo's `updateItem` method and propagate the return value down the chain. Lastly we need to update the tests.

**Comment by austinbyers** [comment]
I'll take this as well as #325, they're quick fixes that can go together

**Comment by 3nvi** [comment]
Thanks for that!
