### ISSUE TITLE
Remove "only active data is shown" message

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#332]
### Description

On the Cloud Security Overview page, there's a pop-up that shows every time the page is refreshed. We should either make it go away permanently when you click the X, or remove it altogether. As an analyst, I find it visually distracting. The information would be better served in documentation to explain how our product works.

### Acceptance Criteria

No more box

**Comment by 3nvi** [comment]
I think you are referring to the blue-line alert box at the top of the page
