### ISSUE TITLE
App Homepage

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#340]
### Describe the ideal solution

Today, the first page a user will visits is the Cloud Security page. In order to better guide their usage of the product, the app should have a general Home page to provide a quick explanation of each major component (cloud security, log analysis, historical) and a way to click through to each section. 

### Describe your use cases

The use case is primarily a generalized home page for the app. 

### How frequently would you use such feature

Daily

### Describe alternatives you have considered

Nothing

### References

N/A

### Additional context

N/A

**Comment by 3nvi** [comment]
Contacted the designer to get a rough understanding of how he's picturing it. Will give updates asap.
