### ISSUE TITLE
Rules page should include alert dedup time period

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#349]
### Description

Events that match rules are grouped into alerts based on two criteria: 
- The `dedupString` associated with every event matched
- A time period (currently hardcoded to 60 minutes)
This means that if some events match a rule within the given time period and all have the same dedup strings, they will trigger only one Alert.

We want to make this time period configurable per rule.

### Acceptance Criteria

- Users can see the alert dedup time period that is configured for each rule
- Users can edit the alert dedup time period. Time period is in *minutes* and has minimum value of 15' and maximum of 1 day. 
- Default time period when someone creates a new rule is defined at 1 hr.

**Comment by 3nvi** [comment]
@kostaspap I don't understand the description. If possible, please elaborate.

**Comment by alexmylonas** [comment]
@kostaspap Do you any suggestions about how many options and what interval makes the most sense?
i.e [15mins, 30mins,1hr,3h,6h,12h,24h]

**Comment by kostaspap** [comment]
> @kostaspap Do you have any suggestions about how many options and what interval makes the most sense?
> i.e [15mins, 30mins,1hr,3h,6h,12h,24h]

Sounds reasonable. @jacknagz  might have preferences on this.
