### ISSUE TITLE
Document how customers can add custom alarms on log processing

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#353]
### Description

Customer have unique requirements for alarming, specifically with respect to log processing.

As a customer, I would like to know how to configure alarms on log processing volume.

### Acceptance Criteria
- Document in operations doc page how to add alarms on log processing with examples

**Comment by 3nvi** [comment]
@rleighton This has been in progress for quite a while. Should we change its status?

**Comment by rleighton** [comment]
OBE with new work pushing ops oriented info to the UI.
