### ISSUE TITLE
Cloud Security Resource Types

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#355]
### Description

In the next iteration of the Cloud Security UI, there is a breakdown of resources by categories such as compute, database, and more. We need to create this "type" mapping in the backend from our currently supported resources, along with a "platform" description such as AWS. Then, we can begin to show our users a proper breakdown of their cloud inventory.

### Acceptance Criteria

- We add categories for each resource type and platform
- The Resources API returns the proper data for the frontend to render new charts

**Comment by 3nvi** [comment]
@jacknagz should we add this to product board or is it something that we need sooner than later?

**Comment by nhakmiller** [comment]
Sure,  I'll move this to product board for now then.
