### ISSUE TITLE
Support CreateInternetGateway and DeleteInternetGateway in aws_event_processor

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#365]
We currently do not support 'CreateInternetGateway/DeleteInternetGateway'. This is an important resource, probably should have for v1.

**Comment by nhakmiller** [comment]
We don't support these currently because we don't have an EC2 internet gateway resource type in cloud security, and these events don't affect any resource types we do support. I can add these two events to the ignore list with a comment explaining when they will be needed to close this issue, and open a new story for adding support for EC2 internet gateway scanning in cloud security.

**Comment by rleighton** [comment]
> We don't support these currently because we don't have an EC2 internet gateway resource type in cloud security, and these events don't affect any resource types we do support. I can add these two events to the ignore list with a comment explaining when they will be needed to close this issue, and open a new story for adding support for EC2 internet gateway scanning in cloud security.

We do have one for the UI, right?

**Comment by nhakmiller** [comment]
> > We don't support these currently because we don't have an EC2 internet gateway resource type in cloud security, and these events don't affect any resource types we do support. I can add these two events to the ignore list with a comment explaining when they will be needed to close this issue, and open a new story for adding support for EC2 internet gateway scanning in cloud security.
> 
> We do have one for the UI, right?

Correct, but we don't currently prioritize scanning support based on what resources we're using internally, but based on what we think brings the most value to the cloud security tool. We also don't support scanning of SQS queues or SNS topics although we have many of those as well.

**Comment by nhakmiller** [comment]
Closing in favor of #377.
