### ISSUE TITLE
Resetting User not CONFIRMED throws error in platform

### ISSUE THREAD

**Issue by alexmylonas** [panther-labs/panther#397]
### Describe the bug

After resetting a user's password and change it's status in FORCE_CHANGE_PASSWORD and you attempt to reset it again, you 'll get an error.

### Steps to reproduce

1. Go to Users Page
2. Click on "Reset password" for a user
3. Click on it again

### Expected behavior

a. Option should grayed out or hidden for status not CONFIRMED
b. Resending email to that user

### Environment

How are you deploying or using Panther?

- Panther version or commit: 9140b62
- Browser: all

**Comment by austinbyers** [comment]
The `InviteUser` endpoint in `users-api` now lets you RESEND an invitation message:

https://github.com/panther-labs/panther/blob/master/api/lambda/users/models/api.go#L68-L76

```
// InviteUserInput creates a new user with minimal permissions and sends them an invite.
type InviteUserInput struct {
	GivenName  *string `json:"givenName" validate:"required,min=1"`
	FamilyName *string `json:"familyName" validate:"required,min=1"`
	Email      *string `json:"email" validate:"required,email"`

	// RESEND or SUPPRESS the invitation message
	MessageAction *string `json:"messageAction" validate:"omitempty,oneof=RESEND SUPPRESS"`
}
```

But I haven't actually tried that yet. If that's the path we want to go down (resend the password reset email, which isn't really "resetting it"), the users-api might need some changes (inviting a user who already exists is I think an error)

**Comment by alexmylonas** [comment]
I think re-inviting an existing users should always throw an error!

But, If as a admin I need to "resend" a new password to an existing (already resetted) user that could be 
allowed.

Also, resending an invitation should be allowed as option to the dropdown.

I am not sure this doesn't seem like a huge priority and I understand there is some work in the backend for this, we could just go with option:

> a. Option should grayed out or hidden for status not CONFIRMED

And we re-visit this down the path. Thoughts?

Note: The solution for admins will to delete users and re-invite them with the same email.

**Comment by austinbyers** [comment]
> a. Option should grayed out or hidden for status not CONFIRMED

Works for me! I'll make sure to:

- Test RESEND functionality
- Ensure an error is thrown if inviting a user who already exists

**Comment by alexmylonas** [comment]
Just FYI of current state:
1. You can't re-reset a user password
2. You **can** invite users with the same email

![Screenshot 2020-04-01 at 12.45.12 PM.png](https://images.zenhubusercontent.com/5e4fb724a541ae524a4864cc/01cf6415-a0d5-4aab-8df5-da3b8892d5b6)

**Comment by kostaspap** [comment]
> Just FYI of current state:
> 
> 1. You can't re-reset a user password
> 2. You **can** invite users with the same email
> 
> ![Screenshot 2020-04-01 at 12.45.12 PM.png](https://camo.githubusercontent.com/2b62ddc01c33d43d6ddc4efe8b96e9c2abbe6710/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565346662373234613534316165353234613438363463632f30316366363431352d613064352d346161622d386466352d646133623838393264356236)

This looks like a bug. Can you create a bug report @alexmylonas ?

**Comment by kostaspap** [comment]
> Just FYI of current state:
> 
> 1. You can't re-reset a user password
> 2. You **can** invite users with the same email
> 
> ![Screenshot 2020-04-01 at 12.45.12 PM.png](https://camo.githubusercontent.com/2b62ddc01c33d43d6ddc4efe8b96e9c2abbe6710/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565346662373234613534316165353234613438363463632f30316366363431352d613064352d346161622d386466352d646133623838393264356236)

Having multiple users with the same email definitely looks like a bug.

**Comment by austinbyers** [comment]
Yes, it's a bug, i listed it above in my comment, it's on my TODO. No need for a separate issue unless you really want one, I can just link it to this one

**Comment by austinbyers** [comment]
I actually did go ahead and make a separate issue for the duplicate invite, because it's a pure frontend issue unrelated to this one: https://github.com/panther-labs/panther/issues/631

(I thought I would have to do some backend work for it, but I was mistaken)

**Comment by austinbyers** [comment]
Confirmed that RESEND works as is, as long as its triggered for a user whose status is "FORCE_CHANGE_PASSWORD"

**Comment by alexmylonas** [comment]
Getting this pretty consistently on resetting password. 

Although, operation is executed correctly on the backend (changing status and getting a reset email) 

> {"data":{"resetUserPassword":null},"errors":[{"path":["resetUserPassword"],"locations":null,"message":"Can't serialize value (/resetUserPassword) : Expected type 'Boolean' but was 'LinkedHashMap'."}]}

![Screenshot 2020-04-07 at 1.44.32 PM.png](https://images.zenhubusercontent.com/5e4fb724a541ae524a4864cc/29fca854-1b9a-4727-b028-bcac71820dbf)
