### ISSUE TITLE
Teardown doesn't always delete S3 buckets

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#398]
### Describe the bug

Some developers have reported issues removing S3 buckets via `mage teardown`, either taking too long or failing to delete the bucket (in this case, `processed-data`)

```
The bucket you tried to delete is not empty. You must delete all versions in the bucket.
```

### Steps to reproduce

`mage teardown` on an a Panther deployment with lots of data in S3 - I'm not sure exactly how to reproduce

### Expected behavior

`mage teardown` shouldn't error nor take more than a few minutes

### Solution
Open to ideas, but if we implement all of the following, it should help:

* Add a bucket policy at the beginning of deletion that prevents new objects from being written
* Lower the bucket size limit for manual deletion to 1k instead of 10k
* Catch the S3 bucket delete error listed above, sleep for a few seconds, and try again

**Comment by austinbyers** [comment]
We can also delete the buckets in parallel to save some time

**Comment by kostaspap** [comment]
I think this has been fixed @austinbyers ?

**Comment by austinbyers** [comment]
I haven't ever been able to reproduce these issues, but I haven't made any changes yet. Bucket deletion has not changed, even in #467

**Comment by austinbyers** [comment]
Found the error again, for deleting the audit logs bucket:

```
15:37:55	FATAL	failed to delete bucket panther-bootstrap-auditlogs-538yjbxtuck7: BucketNotEmpty: The bucket you tried to delete is not empty. You must delete all versions in the bucket.
```
