### ISSUE TITLE
Alert Destination: Firehose

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#399]
### Describe the ideal solution

Support [AWS Kinesis Firehose](https://aws.amazon.com/kinesis/data-firehose/) as an alert destination.

### Describe your use cases

High-scale alert/data routing

### How frequently would you use such a feature

Daily!

### Describe alternatives you have considered

SNS/SQS, but this is less ideal for loading high-scale data into either S3, Splunk, or ElasticSearch.

**Comment by kostaspap** [comment]
> SNS/SQS, but this is less ideal for loading high-scale data into either S3, Splunk, or ElasticSearch.

1. I am not sure I understand the reason for storing the alerts in Splunk? We offer a UI that allows searching of the alerts. 
2. Notifications are not meant to be high-volume e.g. minimum dedup time for a rule is going to be 15 minutes. To be clear on this, alerts do not include the events that are included in an event. These are available already in S3 and are searchable through Athena.

**Comment by jacknagz** [comment]
Closing this for now until we have a deeper discussion on alert sinks (Q4, tentatively)
