### ISSUE TITLE
Improve perceived speed by not refetching on Deletions

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#406]
### Description

Currently, whenever we delete an entity, we ask Apollo to refetch all the queries related to this entity, so the UI is up to date. Instead of doing that, we can just remove it from the associated cache & while also adding an `optimisticResponse` so that this update becomes instant.

The problem is that data to delete can exist in multiple queries. In addition, if the same query has been asked with different parameters, then Apollo will store different cache entries for each different query+params combination. Of course, you can [override this behavior](https://www.apollographql.com/docs/react/v3.0-beta/caching/cache-field-behavior/#reducing-cache-duplicates-by-specifying-key-arguments), but that's not always what you want. Thus, you may need to remove an entry from:

* multiple cache entries from **different** queries 
* multiple cache entries that come from variations of the **same** query with different parameters 

To make that easy, Apollo recently released [cache eviction & garbage collection](https://www.apollographql.com/docs/react/v3.0-beta/caching/cache-interaction/#garbage-collection-and-cache-eviction). What this can do is remove fields from the cache and then garbage collect any un-needed pointers. For example,

```tsx
// deletes all stored variations of the graphQL query "users". After doing that all the User entries might
// not be needed to be in the cache anymore, so we run `cache.gc()` to remove any dangling data
cache.evict('ROOT_QUERY', 'users');

// removes the field `name` from a single User. Helpful in some situations, but not in ours 
cache.evict('User:1234', 'name'); 
```

Now those solutions help invalidate queries, but doesn't help when we don't want to remove the **whole** query, but instead modify its contents in order to remove the item that got deleted. That's where `cache.modify` comes into place. This allows you to modify [specific entries in the cache](https://github.com/apollographql/apollo-client/pull/5909) and is a generic cache utility function. With this, you can do the following:

```tsx
cache.modify('ROOT_QUERY`, {
  users: (data, helpers) => {
    const objToDelete = helpers.toReference({ __typename: 'User', id: deletedUser.id });
    return data.filter(d => d.__ref !== objectToDelete.__ref); 
  }
});

cache.gc();
``` 
This will make sure that **all variations** of the `users` query (if there are more than one) remove the deleted user from their cache. The UI update is done automatically for you. After that, the Deleted User object is not part oof any query, but its data are still in the cache without reason. We run `cache.gc()` to clean them up.

Sometimes, we want to only remove data from cache **specific variations** of a particular query. The `helpers` param contains a key `storeFieldName` which shows you the particular variation name. Thus you can do something like the following:

```tsx
cache.modify('ROOT_QUERY`, {
  users: (data, helpers) => {
    const objToDelete = helpers.toReference({ __typename: 'User', id: deletedUser.id });
    const shouldDeleteFromVariation = helpers.storeFieldName.includes('a particular param');
    
    if (shouldDeleteFromVariation) {  
      return data.filter(d => d.__ref !== objectToDelete.__ref); 
    }
   return data
  }
});

cache.gc();
``` 

We should make sure to try all of them out, dig into the docs and understand how caching works in Apollo; then attempt to optimize deletions. You can find related code [here](https://github.com/panther-labs/panther-enterprise/pull/16/files#diff-0a116a05dd43f67a869af7beeec878deR27-R34)

### Acceptance Criteria

**Every** deletion that happens in the system should update the cache entries through code instead of relying on `refetchQueries`. Thus:

- Replace the `refetchQueries` with manual code to modify the associated queries that were going to be refetched.
- No deletion should ever have a `refetchQueries` anymore
- Each deletion should never trigger any network request
- Each deletion should be instant (reflected in the UI)

**Comment by darkbasic** [comment]
The link to the code is 404
