### ISSUE TITLE
Optimize UX for updates

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#408]
### Description

Just like with deletions, we don't need to perform a network request for a refetch when something gets updated. We know the values aforehand. In fact, Apollo [**automatically** updates the cache](https://www.apollographql.com/docs/react/data/mutations/#updating-a-single-existing-entity) when an item gets updated, if the mutation returns an `id`.We should leverage that and make sure that all updates have optimistic responses and that they get updated automatically.  You can find related code [here](https://github.com/panther-labs/panther-enterprise/pull/16/files#diff-963bc10850addb399bf425e12946bc44R51-R67).

There are some specific parts that are going to be tough, since not all modification mutations are going to return proper responses containing `id`s. Some of them require the assignee to dig and understand what kind of cache modification would need to happen. These in particular are:

* usePolicySuppression
* RemediationButton

For those particular modifications you can't rely on Apollo (since no `id` is returned), but you need to understand what they do & write an appropriate [update function](https://www.apollographql.com/docs/angular/features/cache-updates/#update) in order to update the cache in the places that would normally be updated from the - soon to be removed - `refetchQueries`.

### Acceptance Criteria

This task should make sure that:

- Modification mutations (a.k.a. updates) never have a `refetchQueries` associated with them.  The locations are:

* ResetUserPasswordModal
* UpdateSourceSidesheet
* EditUser
* usePolicySuppression
* RemediationButton

- Modification mutations (a.k.a. updates) that can't return `id`s  have  an `update` function in order to perform a manual update to the cache.  The locations are:

* ResetUserPasswordModal
* usePolicySuppression
* RemediationButton

- All modification mutations leverage Apollo's internals to perform a cache update automatically (by returning an `id` field). This should happen wherever there is an update in the project (not only in the places mentioned in the bullet above). Check the `schema.graphql` to see which mutations modify data.
 
- An `optimisticResponse` gets added for all the modification mutations (same places as the bullet right above that added the `id` field)

**Comment by alexmylonas** [comment]
By @3nvi in #672 
> Hmm I see that we don't get the "new status" of the user from the server. If we do, we can remove the refetchQueries call that is present on a successful "reset password" operation on the ResetUserPasswordModal.
> 
> This is optional since I think it's covered by #408

**Comment by 3nvi** [comment]
> By @3nvi in #672
> 
> > Hmm I see that we don't get the "new status" of the user from the server. If we do, we can remove the refetchQueries call that is present on a successful "reset password" operation on the ResetUserPasswordModal.
> > This is optional since I think it's covered by #408

We must since we are returning a `User!` type. It should be included. It's a bug if it's not :/
