### ISSUE TITLE
Update schema for mutations that edit entities

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#410]
### Description

Currently, when you update a user or an integration you get back `true` or `false`. Instead we should be getting back the updated `User` or `Integration` item. The backend recently implemented this, so we should alter our schema & update appsync to accomodate that. 

### Acceptance Criteria

- Update `updateUser` to return a `User` object (with `!`)
- Update `updateIntegration` to return an `Integration` object (with `!`)
- Update appsync (if needed) to make sure it returns the server payload instead of just a boolean
- Update other code so that typescript won't yell

**Comment by alexmylonas** [comment]
Tested: 
- `updateUser`
- `updateLogIntegration`
- `updateComplianceIntegration`

All return appropriate payloads!

**Comment by 3nvi** [comment]
yup, we can :)
