### ISSUE TITLE
Reduce auth layer JS footprint

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#413]
### Describe the ideal solution

Importing `@aws-amplify/Auth` just for the authorization part is too heavy, since it adds a whooping 81KB gzipped to the bundle. 

We should investigate alternatives such as [amazon-cognito-indentity-js](https://www.npmjs.com/package/amazon-cognito-identity-js) which are 20% the size of amplify's Auth module. Migration would only affect our Auth layer

Lastly, there seems to be some discussion about modularization [here](https://github.com/aws-amplify/amplify-js/issues/3365). Perhaps the modularization will make `@aws-amplify/Auth` lighter

### Describe your use cases

Basic Website loading

**Comment by bezreyhan** [comment]
I tried out the preview branch that is mentioned in the [RFC](https://github.com/aws-amplify/amplify-js/issues/3365) and it reduced the size of the Auth module to 31kb and the aws-sdk to 10.71kb (the aws-sdk alone was 43.28kb).

If we can use `amazon-cognito-indentity-js` (about 11kb) with the tree shaken version of the aws-sdk, that would reduce the total size to about 22kb.

The Auth module is our biggest dependency and we are considering proxying auth through our own api (client -> api -> Cognito). Is there any documentation that discusses this pattern?

**Comment by 3nvi** [comment]
@bezreyhan Thanks so much for the info. Reduced footprint of `aws-sdk` is amazing and long awaited.

If we can't easily use its tree-shaken version with the identity package, I think I'll just stick with the reductions offered by the preview branch, due to lack of time & resources. Right now we are using our "own api", but still relying on the Auth module under the hood. I guess you can do something similar but take away the Auth dependency. Check it out [here](https://github.com/panther-labs/panther/blob/master/web/src/components/utils/AuthContext/AuthContext.tsx)

**Comment by Amplifiyer** [comment]
@3nvi Have you tried the new amplify V3 version which has tree shaking enabled? Let us know if you see any size reductions.

**Comment by 3nvi** [comment]
Hey @Amplifiyer , last time I checked it was due to be in beta. Is it considered stable now?

**Comment by Amplifiyer** [comment]
Yes it's currently on a stable release.

**Comment by 3nvi** [comment]
Perfect, I'll sync with the rest of the team, to see what prioritization we can give this

**Comment by 3nvi** [comment]
Added to a product doc as a future idea
