### ISSUE TITLE
CloudTrail Extraction Entity Extraction Should Construct ARNs when possible

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#425]
### Describe the ideal solution
CloudTrail entity extraction populates the "p_any" fields . For certain CT events (e.g., EC2) ARNs are not present because they are keyed with globally unique ids (e.g., instance ids). For these cases we can construct an arn and add to "p_any_aws_arns".

### Describe your use cases
This will allow pivots from infra to logs based on arns.

**Comment by jacknagz** [comment]
@rleighton is this still valid?

**Comment by rleighton** [comment]
Yes, still valid. This is good task to do during a tech-debt sprint or between bigger tasks.

**Comment by rleighton** [comment]
This is log processing, giving to @kostaspap
