### ISSUE TITLE
Clickable Rule Tags

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#436]
### Describe the ideal solution

From the Rule Details page, the Tags should be clickable to a filtered List Rules page:

![Screen Shot 2020-03-16 at 5.57.14 PM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/97356fbd-6f82-4978-99b2-acbe90a08efc)

![Screen Shot 2020-03-16 at 5.57.41 PM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/74ea8a16-8000-4247-bcf6-fa7d74bfe176)

### Describe your use cases

Pivoting from a single alert -> rule -> related running rules

### How frequently would you use such a feature

Daily

### Describe alternatives you have considered

None

### References

None

### Additional context

None

**Comment by 3nvi** [comment]
I'll just need to alter the way this is presented, but this is fairly trivial as a task :)

**Comment by 3nvi** [comment]
Let's make sure that tags are shown with blue color and they are `<Link>`s.

See the examples on the `Landing` page
