### ISSUE TITLE
Parsers: Fluentd Syslog Support

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#437]
### Describe the ideal solution

While we added support for parsing raw [Syslog data](https://github.com/panther-labs/panther/tree/master/internal/log_analysis/log_processor/parsers/sysloglogs), we don't have support for sending syslog via Fluentd as outlined [here](https://blog.runpanther.io/cloud-native-security-log-collection/). 

This Story is to add syslog JSON parsers for RFC5424 and RFC3164. [This document](https://docs.fluentd.org/parser/syslog) describes how Fluentd parses the data, and what the resultant fields are.

### Describe your use cases

* Collect syslog data via fluentd

### How frequently would you use such feature

Daily

### Describe alternatives you have considered

Tailing files, but this is much less efficient and more complex to set up.

### References

[Examples](https://docs.fluentd.org/parser/syslog#example)

### Additional context

None

**Comment by rleighton** [comment]
This is done
