### ISSUE TITLE
Generic JSON Parser using json-schema

### ISSUE THREAD

**Issue by stoggi** [panther-labs/panther#438]
### Describe the ideal solution

A generic JSON Parser that can dynamically create a [go struct](https://golang.org/pkg/reflect/#StructOf) at registration time from a [json-schema](https://json-schema.org/).

A new simple JSON parser would be created: `json.go` that can unmarshal a JSON log into a struct.

Registering a new JSON parser would be slightly different for a simple JSON parser compared to a DefaultLogParser:
```go
(&sysloglogs.RFC5424Parser{}).LogType(): DefaultLogParser(&sysloglogs.RFC5424Parser{},
	&sysloglogs.RFC5424{}, sysloglogs.RFC5424Desc),
suricatalogs.AlertLogType: SimpleJSONParser(&jsonlogs.SimpleJSONParser{},
        &suricatalogs.AlertSchema, suricatalogs.AlertDesc),
```

A new method `SimpleJSONParser` in [registry.go](https://github.com/panther-labs/panther/blob/ae31de5e9e7c9b286c291f110549a70c891faff3/internal/log_analysis/log_processor/registry/registry.go#L75-L82) would be added that can:
1. accept a SimpleJSONParser{}
2. accept a JSON schema document that describes the structure of a particular schema
3. accept a description
4. use the json-schema to dynamically generate a struct type using [reflect.StructOf](https://golang.org/pkg/reflect/#StructOf)
5. call DefaultLogParser() with the generated struct type to create the GlueTableMetadata and return the LogParserMetadata as usual.

For 4. above, a new package would be created in `pkg` to recursively iterate through the json-schema document and construct the correct struct definitions to be passed to `reflect.StructOf`

### Describe your use cases

While developing a parser for the [Suricata EVE JSON](https://suricata.readthedocs.io/en/suricata-5.0.2/output/eve/eve-json-output.html) logs, a json-schema document was created to aid in generating the [parser source code](https://github.com/stoggi/panther/tree/stoggi-parser-suricata-alert/internal/log_analysis/log_processor/parsers/suricata). This resulted in 22 source files which only differ based on the event struct to be un-marshalled and marshalled.

A generic JSON parser would:
* Speed up new parser development
* Reduce duplicate code overhead for maintenance
* Lower the barrier to entry for external contributors to submit new parsers without being familiar with the go codebase.

### How frequently would you use such feature

When developing new parsers.

### Describe alternatives you have considered

An alternative is to generate go source code from a json-schema. While this does work, it adds overhead when maintaining the parser API, and introduces complexity into the build process.

### References

- #200

**Comment by alxarch** [comment]
Using `go` structs to parse and validate JSON logs is prone to errors as applications evolve and change their log structures. This is also true for users running older versions of an application than the one a parser was defined for. It is also tedious and repetitive to effectively document new application logs. Although reflection based structs could be a step to the right direction on terms of flexibility they are a solution to only one part of this problem (repetition). I would like to suggest a different approach to JSON parsing using an intermediate representation of a JSON object in a DOM-like structure that could hold any possible JSON value in a form that is easy to query, validate and manipulate. I have written a library called [njson](https://gtihub.com/alxarch/njson) that parses JSON in this way and also supports reflection based unmarshaling for compatibility with current code. I have gone to great lengths to keep allocations to the minimum for all operations and performance is on par with the fastest json parsers written in go. Using `njson` would allow for quick classification of a JSON line and extraction of fields of interest to panther and most important the line wouldn't have to be *reparsed* on each classification allowing for multiple classifications for different versions of an application without sacrificing throughput.  A validation based on JSON schema is also possible (not currently implemented in njson but could be developed to the same low-allocation high performance standards). It would also allow for a more declarative definition of log structure (ie  paths in a JSON object to extract IP addresses from). Unless I'm missing something and the structs (and their tags) are actually used somewhere else.

**Comment by kostaspap** [comment]
We are investigating similar task for enterprise product.
