### ISSUE TITLE
Create a `GetIntegration` endpoint in source-api

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#441]
### Description

Currently we can list, delete, add & update integrations. What we also require is the ability to get a single integration by providing an `id`. This will be helpful in cases where we need the details of a single integration in order to update it

### Acceptance Criteria

- `getInteegration` exists 
- returns the full `Integration` details
- accepts a single `id` param

**Comment by kostaspap** [comment]
Resolving in favor of https://github.com/panther-labs/panther/issues/874
