### ISSUE TITLE
PutIntegration returns empty list

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#446]
### Describe the bug

Whenever I try to create a new integration, I'm getting back an empty list instead of getting the item (or the list of items) that got created.

### Steps to reproduce

1. Go to the lambda console for the `panther-sources-api`
2. Click on Test
3. Attempt to call `putIntegration` like this:

```json
{
  "putIntegration": {
    "integrations": [
      {
        "awsAccountId": "726103014039",
        "integrationLabel": "Test new compliancee",
        "remediationEnabled": true,
        "cweEnabled": true,
        "userId": "cc67e287-24b2-487b-864d-d72ec51080f7",
        "scanIntervalMins": 1440,
        "integrationType": "aws-scan",
        "scanEnabled": true
      }
    ]
  }
}
```
4. Inspect the result

### Expected behavior

A list should be returned with a single item; the item that just got created

### Additional context

I can verify that the data is being received correctly from the lambda

### Screenshots

<img width="1580" alt="Screen Shot 2020-03-18 at 1 31 41 PM" src="https://user-images.githubusercontent.com/10436045/76956701-37d69800-691d-11ea-9e4e-208ee58b93cd.png">

**Comment by 3nvi** [comment]
**UPDATE**
I saw that this behaviour happens when I attempt to add a compliance source when the related AWS ID already exists in another integration

**Comment by 3nvi** [comment]
@nhakmiller We need a way to properly document these behaviors since they slow down development when trying to understand/debug whether the lambda has a bug or the front-end sends the request wrongly. Cloudwatch sometimes doesn't log anything  neither for the appsync nor for the lambda.

**Comment by kostaspap** [comment]
I'm doing some refactoring as part of my current task. I will deal with this.
