### ISSUE TITLE
HTTP -> HTTPS Redirect

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#452]
### Description

Currently the Panther app only listens for HTTPS connections on port 443. This is good because we don't want to be serving insecure connections, but we should re-direct HTTP/80 requests to HTTPS/443 so that you don't get a connection refused page if you don't type out https:// every time (or have an always HTTPS plugin).

### Acceptance Criteria

- When attempting to connect to the Panther app over HTTP, automatically get re-directed to the HTTPS listener instead of getting a connection refused page

**Comment by jacknagz** [comment]
@nhakmiller I believe we resolved this, right?

**Comment by nhakmiller** [comment]
@jacknagz still an open issue to my knowledge, going to http://some-panther-deployment results in a "page not found" instead of a redirect to https://some-panther-deployment. Just haven't prioritized this in lieu of other more pressing  stuff. I can go ahead and throw it on the roadmap for 1.8.
