### ISSUE TITLE
Navigation Highlighting Disappears in Details Pages

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#453]
### Describe the bug

When clicking through from an overview page to a details page, 

### Steps to reproduce

1. Click any overview page (Log Analysis Rules/Alerts, Cloud Security Resources/Policies):

![Screen Shot 2020-03-18 at 11.50.00 AM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/33d879fc-c02b-4512-8d63-718bad021dc7)

2. Click through from Overview to Details:

![Screen Shot 2020-03-18 at 11.50.06 AM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/fab2de1d-3d2c-4404-83fd-efa21a9e3565)

### Expected behavior

The menu highlighting should be retained, giving a visual cue for users where they are.

### Environment

Panther Community Edition
Version v0.3.0-113-g83c6ed8

### Additional context

None

### Screenshots

Provided above

**Comment by 3nvi** [comment]
This is like that by design. It's not a bug, but it's intentional. The link points to a specific URL, if this URL is not present then the link is not highlighted.

I don't mind doing implementing it, but it's not something that's expected nor common. Take for example, dropbox, g-drive, etc. that don't do it

**Comment by jacknagz** [comment]
@3nvi Gmail actually mimics this same functionality. If I click from my Inbox (list emails) to the email details, the  Inbox stays highlighted. 

Another issue I just saw was if you click the top-level icon twice, it shows a blank secondary menu:

![Kapture 2020-03-18 at 13.59.34.gif](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/78887e1b-7035-4fc3-9283-938427e5e832)
