### ISSUE TITLE
Column title not displaying correctly on Policies page

### ISSUE THREAD

**Issue by guilleojeda** [panther-labs/panther#476]
On the Policies page I noticed that when sorting by Severity the column title is not displayed well.
Happening in Chrome latest version, on all zoom levels.
I'm only seeing this for column Severity on page Policies. Other columns are fine, and column Severity on page Rules is fine.

![image](https://user-images.githubusercontent.com/18320860/77202431-1caa8a80-6acd-11ea-95cb-0b3369d00613.png)

**Comment by jacknagz** [comment]
@guilleojeda thanks for reporting! I was able to reproduce this on the latest version:

![Kapture 2020-03-20 at 13 35 41](https://user-images.githubusercontent.com/11466941/77204352-cc70ff80-6aaf-11ea-9fb3-3b3989df6eb8.gif)

We will address this.
