### ISSUE TITLE
Log Onboarding: Health Checks Fail

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#494]
### Describe the bug

The health check after onboarding a new S3 bucket is failing right after launching the generated role.

### Steps to reproduce

Log Analysis > Sources

Fill in bucket information

![Screen Shot 2020-03-22 at 7.00.23 PM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/9703e567-53e6-4cce-bce3-4e6234e30c01)

Click next, launch stack in the CloudFormation console

Try to save the new source, and see:

`source <redacted-account-id> did not pass configuration check because of log processing role has a misconfiguration`

### Expected behavior

The health check to pass

### Environment

- Panther version or commit: v0.3.0-143-g6368a26 (branch/rebased on master)
- OS: macOS 10.15.3
- Browser: Version 80.0.3987.132

### Additional context

None

**Comment by austinbyers** [comment]
I get exactly the same thing when running `mage deploy` with the new log onboarding and #467 :

```
22:19:07	FATAL	error calling lambda to register account for log processing: panther-source-api responded with Unhandled error: {"errorMessage":"source 101802775469 did not pass configuration check because of log processing role has a misconfiguration","errorType":"InvalidInputError"}
```

**Comment by kostaspap** [comment]
Working on it.

**Comment by kostaspap** [comment]
Fixed with https://github.com/panther-labs/panther/pull/501
