### ISSUE TITLE
Link to "S3 Event notifications" from log onboarding

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#553]
### Description

Currently, we need to link users to the [docs](https://docs.runpanther.io/log-analysis/log-processing/notifications-setup) in order to tell them to setup S3 Event notifications whenever they onboard an existing bucket.

This is complicated and forces the user to go outside oof the platform to achieve that. We should investigate alternatives in order to achieve this without the minimum amount of friction.

Me & @kostaspap agree that a `panther-cli` might be a viable solution to facilitate that. It would follow heroku's example

**Comment by nhakmiller** [comment]
That could work. I wonder what it might look like as well to have them deploy a "setup" role when they deploy the log processing role, and the setup role has the permissions needed to do these things. Then the setup role can be left alone or ignored. It could also double as a teardown role for removing the integration.

**Comment by 3nvi** [comment]
@kostaspap what should  our course of action be here?

**Comment by kostaspap** [comment]
> @kostaspap what should our course of action be here?

The `panther-cli` is a much bigger task and will not be done soon since we first need the Panther API. 

The UI current guides users to enable notifications, but it does it at the wrong step - the users should be guided to enable notifications once the source is stored in the backend.  We discussed recently about fixing this and I thought we had a Github issue but I don't see it. 

We can either convert this issue description to fix the current system behavior or just close it.

**Comment by kostaspap** [comment]
> > @kostaspap what should our course of action be here?
> 
> The `panther-cli` is a much bigger task and will not be done soon since we first need the Panther API.
> 
> The UI current guides users to enable notifications, but it does it at the wrong step - the users should be guided to enable notifications once the source is stored in the backend. We discussed recently about fixing this and I thought we had a Github issue but I don't see it.
> 
> We can either convert this issue description to fix the current system behavior or just close it.

I found the issue: https://github.com/panther-labs/panther/issues/1375

I think we can resolve this ticket in favor of #1375

**Comment by 3nvi** [comment]
Agreed. Flagging as duplicate  of #1375
