### ISSUE TITLE
Allow Easy Source Renaming

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#574]
### Describe the ideal solution

A quick way to modify a cloudsec or log analysis source name. Currently, you have to step through the entire update workflow, including downloading a generated template.

### Describe your use cases

The main use case is a typo in the source name.

### How frequently would you use such a feature

Monthly.

### Describe alternatives you have considered

Clicking through the whole update workflow

### References

None

### Additional context

None

**Comment by 3nvi** [comment]
@jacknagz It's not that easy.

For Log Analysis, the "name" is part of the Cloudformation template that gets deployed, so you actually **do need** to go through the entire wizard.

For Compliance that's not the case, but it maintains consistency.

**Comment by 3nvi** [comment]
Closing this as stale.

The UI has since changed and allows you to doo  this with a bit less friction. It's still not ideal, but if we still need something like that, we should create an epic with designs & everything
