### ISSUE TITLE
Filtering Resources with quotes in the name returns all results

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#576]
### Describe the bug

When you are on the resource list page, if you type a filter in the filter box that includes quotes, it just returns everything.

### Steps to reproduce

1. Go to resource list page
2. Click Filter Options
3. In ID / Name filter box put something in in quotes
4. Click the Apply button
5. Observe that results are not filtered
6. remove quotes
7. Observe that results are filtered

### Environment

How are you deploying or using Panther?

- Panther version v0.3.0-190-g28769b4

### Additional context

See screenshots.

### Screenshots

<img width="1099" alt="Screen Shot 2020-03-25 at 5 56 45 PM" src="https://user-images.githubusercontent.com/49166439/77599645-a047eb00-6ec2-11ea-9f40-3d75dddf1f5a.png">
<img width="1118" alt="Screen Shot 2020-03-25 at 5 56 54 PM" src="https://user-images.githubusercontent.com/49166439/77599648-a2aa4500-6ec2-11ea-828b-0cfb40a0f7d2.png">

**Comment by 3nvi** [comment]
```
// ... other fields
"context": {
        "arguments": {
            "input": {
                "idContains": "\"feafe\"",
                "page": 1
            }
        },
        "stash": {},
        "error": {
            "message": "java.lang.RuntimeException: Error signing request DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)\nGET /v1/list?idContains=\"feafe\"&page=1 HTTP/1.1\nContent-Type: application/json\nuser-agent: AWSAppSync-Http-Client\nconnection: close\ndate: Thu, 26 Mar 2020 14:09:22 Z",
            "type": "Http:RuntimeException"
        },
        "outErrors": []
    },
    "fieldInError": true,
// ... other fields
}
```

**Comment by austinbyers** [comment]
Yes, we already have url-decoding in the backend: https://github.com/panther-labs/panther/blob/master/internal/compliance/resources_api/handlers/list_resources.go#L109

**Comment by 3nvi** [comment]
We should url-encode all free text searches then

**Comment by austinbyers** [comment]
Confirmed all apis with free-text search fields are url-decoding in the backend

**Comment by 3nvi** [comment]
Perfect. We'll make sure to URL-encode free searches in the platform and see if it fixes it
