### ISSUE TITLE
Evaluate SIGMA support

### ISSUE THREAD

**Issue by rhaist** [panther-labs/panther#579]
### Describe the ideal solution

I see from your rule language that it shares some similarities with the SIGMA project.
As they already curate a treasure trove of detection rules there might be some good synergy here.

### Describe your use cases

Use existing and future rules from the SIGMA project with panther.

### References

https://github.com/Neo23x0/sigma

**Comment by nhakmiller** [comment]
This looks interesting, I think we can make use of these. Let me do a bit more discovery and see where we have overlap and get back to you.

**Comment by nhakmiller** [comment]
In light of some recent issue cleanup, I'm going to move this issue to the panther-analysis repo https://github.com/panther-labs/panther-analysis and see about having some of our new security researchers/engineers take a look.
