### ISSUE TITLE
clarify license in readme

### ISSUE THREAD

**Issue by kapilt** [panther-labs/panther#583]
### Describe the bug

From the readme, "Panther is dual-licensed under the AGPLv3 and Apache-2.0 licenses."

The common usage of dual-license in oss is for source code that is available wholly under either license, except a cursory look at your license file makes it clear that not the case.
https://github.com/panther-labs/panther/blob/master/LICENSE

Instead an accurate phrase would be "parts of the code base are selectively licensed under either the AGPLv3, Apache-2.0, or Panther Commercial License"

**Comment by jacknagz** [comment]
Thanks @kapilt! That makes sense.

**Comment by austinbyers** [comment]
@kapilt great feedback! I'll clarify in the license

Most of the code is AGPLv3, the idea was to allow common utility code that other people might find especially useful to live under a less restrictive license (Apache v2) - this is the `pkg` folder. But this distinction might do more harm than good in terms of the confusion it causes

For now, I'll just clarify the license text as you suggest, but we'll also sync as a team and see if we can just remove this distinction somehow to simplify things
