### ISSUE TITLE
Rules cant import helper function

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#593]
### Describe the bug

Rules don't appear to be able to import the `aws_globals` file even when one is specified:

`[ERROR]  2020-03-26T15:59:59.425Z  Failed to import rule OSquery.Login.NonOffice. Error: [No module named 'aws_globals']`

I'm assuming this is because the `aws_globals` file defines itself as a policy not a rule. 

Three solutions I can think of if that is the issue:
  1. The rules engine can look up the `aws_globals` policy even though it is a policy
  2. Implement globals as a special type of analysis that both policies and rules can lookup
  3. Minimally just switching policies and rules to look for a different hard coded ID so we can upload them both without overwriting each other

### Steps to reproduce

1. Create a rule that imports `aws_globals`
2. Wait for an event to trigger the rule
3. No alert is created, and if you look at the logs you'll see ERROR messages for it

### Expected behavior

Rules should be able to import the helper functions defined in `aws_globals`

### Environment

How are you deploying or using Panther?

- Panther version v1.0.0-16-g35e1ff7

**Comment by kostaspap** [comment]
This is the expected behavior in terms of design. Rules engine only imports rules - not policies. I think having the rules engine import a Python library defined in Policies is counter-intuitive for the user. There are several concerns when it comes to having cross-references like that (also related to RBAC)

**Comment by nhakmiller** [comment]
> This is the expected behavior in terms of design. I would remove the bug label. Rules engine only imports rules - not policies.
> Having the rules engine import a Python library defined in Policies as I see it is counter-intuitive. There are several concerns when it comes to having cross-references like that (e.g. when it comes to RBAC)

Fair enough.

**Comment by nhakmiller** [comment]
This issue was resolved with formal support for globals in v1.1.0.
