### ISSUE TITLE
Password Validation: Special Characters

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#597]
### Describe the bug

The frontend validation regex for checking user password requirements is missing some special characters. 

### Steps to reproduce

1. Set the user password
2. Add a `+` or `-`
3. See error message: "Include at least 1 special character"

### Expected behavior

All special characters should be expected, or a message should display which characters are available for use.

### Environment

Panther version or commit: v1.0

### Additional context

None

### Screenshots

![image-2.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/25861ea3-cd7c-4a08-a386-cf507d4e418a)

**Comment by kostaspap** [comment]
As I understand this, any character that is not alphanumeric is actually a special character. We should probably update the regex in the frontend to check it that way.
