### ISSUE TITLE
Ignored Resources Show as Failing

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#602]
### Describe the bug

Suppressed Cloud Security resources show up in the policy overview breakdown as "failing" even though they are marked as "ignored".

### Steps to reproduce

1. Ignore a failing resource
2. Refresh
3. See it shows up under both "Failing" and "Ignored"

### Expected behavior

If the resource is ignored, it should only show up in the "Ignored" filter.

### Environment

- Panther version or commit: v0.3.0-190-g28769b4 (just checked on v1, it's still there)

### Additional context

None

### Screenshots

Failing 1 shows, but 7 resources are listed.

![Screen Shot 2020-03-29 at 6.42.55 PM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/7838300f-beb2-482b-832a-02e5049a3eb0)

Same thing here, 20 failings, but 22 resources listed.

![Screen Shot 2020-03-29 at 6.47.31 PM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/c6c4ffed-5e96-45a7-94f6-ec480317d525)

**Comment by 3nvi** [comment]
I don't think this is a front-end issue. @austinbyers can you verify that it's not a bug from your end? We normally don't "mess around" with the status value

**Comment by austinbyers** [comment]
This would be the [describe-policy](https://github.com/panther-labs/panther/blob/master/api/gateway/compliance/api.yml#L225) endpoint in compliance-api, right?

In that case, you just need to include `suppressed=false` in the query - by default all resources are included. So the full query here would be

```
compliance-api/describe-policy?
    policyId=AWS.S3.BucketEncryptionEnabled&
    page=1&
    status="FAIL"&
    suppressed=false
```

**Comment by austinbyers** [comment]
I've confirmed we have integration tests that verify the ability to filter by suppressed status: https://github.com/panther-labs/panther/blob/master/internal/compliance/compliance_api/main/integration_test.go#L465-L473

So it works in the backend

**Comment by 3nvi** [comment]
I'll take a look into it within the week, cause I remember that we did indeed pass the "suppressed" keyword. I'll get back to you on that.

**Comment by austinbyers** [comment]
I found the actual requests, the `suppressed` parameter is indeed missing.

When looking at policies associated with a resource:

<img width="1221" alt="Screen Shot 2020-04-21 at 11 11 27 AM" src="https://user-images.githubusercontent.com/3608925/79898935-e3618500-83c0-11ea-945b-65773b5e0cfe.png">

The associated call to the backend is

```json
{
    "requestMethod": "GET",
    "requestPathParameters": null,
    "requestQueryParameters": {
        "page": "1",
        "pageSize": "10",
        "resourceId": "101802775469::AWS.PasswordPolicy",
        "status": "FAIL"
    },
    "requestResource": "/describe-resource",
}
```

Similarly, when looking at resources associated with a failing policy:

```json
{
    "requestMethod": "GET",
    "requestPathParameters": null,
    "requestQueryParameters": {
        "page": "1",
        "pageSize": "10",
        "policyId": "AWS.CMK.KeyRotation",
        "status": "FAIL"
    },
    "requestResource": "/describe-policy",
}
```
