### ISSUE TITLE
Add swagger to public development image

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#603]
### Describe the ideal solution

Currently all users need to run `setup:swagger` before they deploy. We should consider adding it to our development image so that users can simply run `mage deploy` to deploy for the first time.

### Describe your use cases

Users will have to:

- wait less for a deployment since swagger will already be present
- have a single memorable command to remember (i.e. `mage deploy`)
- docs will be simplified

### How frequently would you use such feature

On each update

### Describe alternatives you have considered

The current alternative is to run `mage setup:swagger deploy`.

### References

https://github.com/panther-labs/panther/issues/369

### Additional context

If we migrate to the proposed solution, we will have to update the public image each time we bump the swagger dependency. Bumping a version shouldn't be something that happens on a daily basis (more like monthly), so although it's not a big thing, it's something we should think about.

**Comment by austinbyers** [comment]
I'm fine with adding swagger to the development image for now. Depending on how we unify our APIs, we may get rid of it entirely (it seems to cause problems)

Is there a documented process for updating the image? I actually don't know how to push a new version to dockerhub

**Comment by 3nvi** [comment]
> Is there a documented process for updating the image? I actually don't know how to push a new version to dockerhub

There isn't. I'll own this issue and add one as part of it

**Comment by 3nvi** [comment]
Added docs for image building. Turns out adding swagger involves:

- Adding `magefile.go`
- Adding `tools/mage/utils.go`
- Adding `tools/mage/setup_namespace.go`
- Allow merging of local PWD and private `.setup` file of image

This will prevent any change in master to be reflected in those files, since it requires a new image being built.

Just because I can see issues arising with that, I'll skip the swagger part
