### ISSUE TITLE
Panther failing to build

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#605]
### Describe the bug

Panther build fails
```
10:44:30        INFO    fmt: license headers
10:44:30        INFO    fmt: gofmt api/lambda internal pkg tools cmd magefile.go
10:44:33        INFO    fmt: python yapf internal/compliance/remediation_aws internal/compliance/policy_engine internal/log_analysis/rules_engine
10:44:33        INFO    fmt: prettier
10:44:42        INFO    doc: generating operational documentation from cloudformation
10:44:42        INFO    doc: generating documentation on supported logs
10:44:42        INFO    build:api: generating Go SDK for 4 APIs (api/gateway/*/api.yml)
10:44:46        INFO    build:lambda: compiling 20 Go Lambda functions (internal/.../main) using go1.14.1
# github.com/panther-labs/panther/api/gateway/analysis/client
api/gateway/analysis/client/panther_analysis_client.go:73:19: undefined: operations
api/gateway/analysis/client/panther_analysis_client.go:118:13: undefined: operations
# github.com/panther-labs/panther/api/gateway/compliance/client
api/gateway/compliance/client/panther_compliance_client.go:73:19: undefined: operations
api/gateway/compliance/client/panther_compliance_client.go:118:13: undefined: operations
# github.com/panther-labs/panther/api/gateway/remediation/client
api/gateway/remediation/client/panther_remediation_client.go:73:19: undefined: operations
api/gateway/remediation/client/panther_remediation_client.go:118:13: undefined: operations
10:44:46        FATAL   go build out/bin/internal/compliance/alert_processor/main/main failed: running "go build -ldflags -s -w -o out/bin/internal/compliance/alert_processor/main ./internal/compliance/alert_processor/main" failed with exit code 2

```

### Steps to reproduce

1. Checkout panther
2. `mage setup:all test:ci`

### Expected behavior

Panther should build

### Environment

How are you deploying or using Panther?

- Panther version or commit: 1c738d9fa723c9efc543e04d1f10307fde38b0b3
- OS: MacOS 10.15.4
- Browser: Not relevant

### Additional context

* It seems that `mage build:api` is modifying the swagger files and this leads to build failures. 
* The problem seems to be due to some inconsistent behavior of `go-swagger`. I see the same problem when running directly swagger installed in the `.setup` folder:
```
$ .setup/swagger version
version: v0.23.0
commit: 3596b40bedd4f06cc918767098568456d2ec2370
$ .setup/swagger generate client -q -f api/gateway/analysis/api.yml -c api/gateway/analysis/client -m api/gateway/analysis/models -r docs/LICENSE_HEADER_AGPL.txt
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   api/gateway/analysis/client/panther_analysis_client.go
```

**Comment by austinbyers** [comment]
I'm not able to reproduce this in CI (https://github.com/panther-labs/panther/pull/614) nor locally on a completely fresh clone.

The offending PR is probably https://github.com/panther-labs/panther/pull/575, can you try reverting just the changes to [build_namespace.go](https://github.com/panther-labs/panther/pull/575/files#diff-1fa38d56318a958a9d2e025b89fb4f30) and [deploy.go](https://github.com/panther-labs/panther/pull/575/files#diff-696ce149f6ddfbb5da1206a974a4a793) ? If that doesn't work, you can try reverting the entire PR (and downgrade swagger to the version we had before)

**Comment by kostaspap** [comment]
After the latest refactoring the issue no longer appears. I tried with https://github.com/panther-labs/panther/commit/45017102d989ea7c7cef9e9139594c35be39cce2 and was able to build the project successfully.

**Comment by austinbyers** [comment]
@nhakmiller and I were able to reproduce this by first cloning the repo to `/tmp` instead of the standard GOPATH (~/go/src/github.com/panther-labs/panther)

It's a bug in `swagger` itself - the imports it generates are incorrect. I'll find a workaround
