### ISSUE TITLE
Fine grain IAM Trust for PantherLogProcessingRole-cloudtrail

### ISSUE THREAD

**Issue by willbengtson** [panther-labs/panther#608]
The current trust that for the PantherLogProcessingRole-cloudtrail role allows the entire account that Panther runs from to be able to AssumeRule.  This should be more restrictive and only trust the LambdaRole for the Lambda processing the Cloudtrail Log source.  Panther can be deployed in a multi-tenant AWS account which would create a vulnerability / privilege escalation path for unauthorized CloudTrail access.

**Comment by kostaspap** [comment]
Yes the recommendation makes sense. Will look into fixing this for new log sources.
