### ISSUE TITLE
LogSubscriptions

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#609]
### Description
Enable outside sources to subscribe via S3 event notifications for data in the log processing bucket.

### Acceptance Criteria
* Update panther_config.yml to allow a list of principals that can read from the bucket and subscribe to SNS from log processor.

**Comment by austinbyers** [comment]
@rleighton I'm closing this because it seems #612 satisfies the acceptance criteria. Feel free to re-open if it's incomplete with more context about what still needs to happen.
