### ISSUE TITLE
Rules don't verify LogType for unit tests

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#610]
### Describe the bug

When creating and editing rule tests, you can set a log type that is not one of the supported log types for that rule and the tests will still run and pass.

### Steps to reproduce

1. Go to the rule editor
2. Create a new test case
3. Set the log type of the test case to be a log type not supported by the rule
4. Run the test
5. The rule is evaluated as normal and will return passing if the event defined in the test case passes

### Expected behavior

A test case for a log type that a rule is not applied to doesn't pass.

### Environment

How are you deploying or using Panther?

- Panther version 1.0

### Additional context

I believe we can actual remove this field both here and in the policy pages, and instead have this be implied based on the rule/policy being tested if necessary.

**Comment by nhakmiller** [comment]
Additional context from internal discussions:

```
Nick
Looks like the rules engine does not verify log type during testing

Whereas the policy engine will return this if the resource type is specified incorrectly for a test:
ERROR
<Policy Name>
test resource type AWS.CloudTrail is not applicable to this policy

Kostas
I don’t thing we need the log type?
I don’t see why the engine should fail

Nick
I was going to make the same comment on the github issue if one got created, but I think the field is totally extraneous at this point

Kostas
I mean, it’s just an event in the end
It could pass or fail depending on the python code
But not sure it makes sense to verify anything else
I mean, could be a CloudTrail event but have the label “alb” :P

Austin
With policies, I believe the resource type is part of the log itself (we add it) - you could write a generic policy which applies to all resources and then switch on the type in the python code
I’m not sure if the same is true for logs
But I think that’d be reasonable to do the same thing - you could imagine a rule which is almost identical across two different log types except for one edge case, in which case having two different rules completely would be overkill

Nick
It exists because in the policy engine we take a list of resources and a list of policies, and apply each policy to the resource that have the right type. So for testing purposes, we need the test cases to specify a resource type that the policy applies to. We mimicked this UI into the rules section. The rules engine though actually has explicit logic for handling tests, which don't consider the type at all.
That's true Austin, but I just double checked the code to verify and we're no longer using the resource object in the policy engine so those fields would just be normal fields that could be defined in the unit test case like any other I think
```

**Comment by kostaspap** [comment]
I don't see this is a bug. As I see it, it is the expected behavior. The rule could be used for the additional log type and it would work properly. Why would we throw an exception for something that actually passes successfully the Python rule?
 I would instead prefer to have a feature issue on how we expect testing to work - and where and why we should require the users to pass the "LogType" as a field to the testing.

**Comment by nhakmiller** [comment]
I think it is a bug because users are required to explicitly set a log type for the test and can't run/save the test if they don't, but setting the log type doesn't do anything. Either setting the log type should do something, or we should remove the log type field from rule (and ideally policy) unit tests. I think either is a good solution.

**Comment by kostaspap** [comment]
Fair point, I see why this might be confusing or be considered a bug.

**Comment by jacknagz** [comment]
> When creating and editing rule tests, you can set a log type that is not one of the supported log types for that rule and the tests will still run and pass.

This is how policies work - it should be consistent

**Comment by giorgosp** [comment]
After some discussions with @kostaspap and digging into the code, my understanding is inline to what @nhakmiller said.

The policy engine, as it is implemented, needs to have a set of Panther polices preloaded and for every AWS Resource that comes as an input, it uses the policies' resource type to find out which should be run for the input resource.
When the user creates a policy unit test, they don't really need to define a resource type for the test. We already know the policy under test and its resource types, so after we preload the policy under test to the engine, we can just use one of its policies to make the engine run it.

The log type field in the rule unit test doesn't seem to be of any use as well.

It would make sense to remove both the `Resource Type` field from the policy unit test and the `Log Type` field from the rule unit test as they currently don't offer anything to the user. I am just having seconds thoughts regarding its priority.

What do you guys think?
cc @jacknagz

**Comment by nhakmiller** [comment]
> When the user creates a policy unit test, they don't really need to define a resource type for the test. We already know the policy under test and its resource types, so after we preload the policy under test to the engine, we can just use one of the policies' resource types to make the engine run it.

Perhaps I am misremembering, but I don't believe the policy engine actually makes a distinction between test and non-test runs. Are you suggesting that the `analysis-api` could auto-populate the resource type fields on the tests it is running based on one of the resource types in the policy being tested? Or are you suggesting that we add a new "testing only" path to the `policy-engine` that doesn't check the resource type at all? Either seems reasonable, but both require backend code changes.

Additionally removing this field would require changes to our existing policies & rules in the `panther-analysis` repo, and would require changes to the `panther_analysis_tool` repo to update the schema.

I am more than happy to have the log/resource type field removed, but I do think there are some required backend changes.

**Comment by giorgosp** [comment]
Discussed it offline with @nhakmiller and posting here for visibility:

>Are you suggesting that the analysis-api could auto-populate the resource type fields on the tests it is running based on one of the resource types in the policy being tested?
This is the idea, exactly. No need to change the engine code.

>Additionally removing this field would require changes to our existing policies & rules in the panther-analysis repo, and would require changes to the panther_analysis_tool repo to update the schema.
This is important so that the change is backwards compatible, i.e. the api and the tools can run policy tests ignoring the extraneous fields if they are present in customers' old policies.
