### ISSUE TITLE
Expose Alert Title from alerts-api

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#617]
### Describe the ideal solution

The front-end requires to show the title of an alert in the corresponding Table, but it currently doesn't have a way of fetching it from the API.

This ticket will make sure to expose this information through the Alerts-api

### Describe your use cases

Showcasing `title` in:

- RuleDetails page
- AlertsList page

### How frequently would you use such feature

Daily

### Describe alternatives you have considered

Not showing it. This is not considered a solution

**Comment by kostaspap** [comment]
I am going to return the `title` in the `getAlert` and `listAlerts` methods of the `panther-alerts-api` lambda. That should be sufficient, right?

**Comment by 3nvi** [comment]
Yup
