### ISSUE TITLE
Validate Log and Resource types

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#619]
### Description

The Panther backend should validate the Log & Resource Types

### Acceptance Criteria

1. Panther backend validates Log Types
2. Panther backend validates Resource types
3. In case some create/update operation for a rule/policy includes an invalid log or resource type, backend should throw exception.

**Comment by austinbyers** [comment]
For cloud security resource types, the list might be available here: https://github.com/panther-labs/panther/blob/08bc329c18139d50fb9159c9b2707b7bf9673450/internal/compliance/snapshot_poller/pollers/aws/poll.go#L100-L131

@kostaspap how would we get the list of supported log types, including custom logs?

**Comment by kostaspap** [comment]
> For cloud security resource types, we might be able to use this:
> 
> https://github.com/panther-labs/panther/blob/08bc329c18139d50fb9159c9b2707b7bf9673450/internal/compliance/snapshot_poller/pollers/aws/poll.go#L100-L131
> 
> @kostaspap how would we get the list of supported log analysis types, including custom logs?

Yeah it is possible. You can use the `logtypes-api`. See here: https://github.com/panther-labs/panther-enterprise/blob/4f4e98593bdff368c0ecab89ff6e6b426380225d/internal/log_analysis/datacatalog_updater/process/setup.go#L72-L78

**Comment by kostaspap** [comment]
Increasing priority of this. Since there is no log type or resource validation, user can easily put the wrong log type - and then spent hours debugging why their rule is not firing. Have encountered this issue twice the last weeks.

**Comment by austinbyers** [comment]
> Since there is no log type or resource validation, user can easily put the wrong log type

The frontend already "validates" the log/resource type in the sense that it only allows options from the available collection:

![Screen Shot 2021-01-05 at 5 45 28 PM](https://user-images.githubusercontent.com/3608925/103719594-321a7380-4f7e-11eb-94cf-645ad28d35f7.png)

So how did the users cause this problem? Were they doing a bulk upload?

**Comment by kostaspap** [comment]
Yup, users run into this issue when uploading rules through PAT

**Comment by austinbyers** [comment]
Ok, noted. I'll tentatively assign to @tatehanawalt for next sprint

**Comment by tatehanawalt** [comment]
So it looks like (at least from the api interface) these items are:

created: `internal/core/analysis_apis/handlers/create_update*.go` - where tableItem is the shared type between the items
saved in: `internal/core/analysis_apis/handlers/dynamo.go` - with the 'writeItem' method

and item type is stored as tableItem.Type which can be a DetectionType (alias of string) defined in api/lambda/analysis/models/api.go

There's also internal/core/analysis_api/handlers/bulk_upload.go which i think is probably where @kostaspap is running into the bulk issue.

@austinbyers can you verify if I'm seeing this correctly?

If I have this right, I think a potential solution would be to solve add a receiver method to tableItem that would run the checks for the prospective item (policy, rule, etc...)

**Comment by austinbyers** [comment]
> There's also internal/core/analysis_api/handlers/bulk_upload.go

This is the only entry path by which a Panther user can actually trigger the bug right now, though you can also trigger the bug by directly invoking the create/update analysis-api Lambda endpoints. The normal "create" and "update" flows will have validation from the frontend, but of course we want to add it in the backend as well. So yes, the validation will apply to every `analysis-api` endpoint which can modify any "resourceType" or "logType":

* CreatePolicy
* CreateRule
* UpdatePolicy
* UpdateRule
* CreateDataModel
* UpdateDataModel

> If I have this right, I think a potential solution we could add a receiver function to tableItem to run checks for the prospective item (policy, rule, etc...)

Hmm it's just a design decision, but I don't like the idea of tying a cross-service API call to the low-level Dynamo struct. To be consistent with what we have today, the validation should happen *before* the table item is even created (which is also technically more performant - we don't allocate the struct until we know we need it).

So, for example, you would add this validation (for policies) right before https://github.com/panther-labs/panther/blob/master/internal/core/analysis_api/handlers/create_update_policy.go#L61

**Comment by austinbyers** [comment]
> Do we have any bulk upload test data I can use to test this?

To test directly, you can simply invoke the `analysis-api` Lambda function with a `CreatePolicy` API payload (or choose any I listed above) with a `resourceType` that does not exist.

To test from the point of view of the user, you can clone our [detection pack source](https://github.com/panther-labs/panther-analysis), change some resource/log types, build a zipfile (instructions in that repo) and then upload it to Panther via the web UI

**Comment by tatehanawalt** [comment]
I have a test implementation working for rules in calls that executed the CreateRule handler. I added some lambda:invoke stuff to a policy in deployments/core.yml allowing panther-analaysis-api to invoke the panther-logtypes-api. Currently I'm retrieving the logTypes on each call to CreateRule.

ResourceTypes and LogTypes are both mapped to tableItem ResourceTypes. Does this mean the log types returned from the logtypes-api can be used to validate entries in either ResourceTypes or LogTypes inputs?

My demo method is:
```
func getLogTypes() []string {
	var listLogTypesOutput logtypesapi.AvailableLogTypes
	payload := logtypesapi.LogTypesAPIPayload{
	  ListAvailableLogTypes: &struct{}{},
	}
	if err := genericapi.Invoke(lambdaLogTypesClient, "panther-logtypes-api", &payload, &listLogTypesOutput); err != nil {
	  fmt.Printf("Error: %v\n", err)
	  return nil
	}
	return listLogTypesOutput.LogTypes
}
```
(code not showing package imports, a search method, and a lambdaClient initialization)

This code was just a test. If I this ends up in the solution I would substitute fmt with zap and I'm sure I can clean it elsewhere. 

This method could be a bottleneck for requests if we don't have some sort of caching. It's not as much of an issue with the bulk upload since we can run the validation without refreshing the valid LogTypes.

I kind of hacked this together from looking at the code base. @austinbyers is there a more common method of inter-service communication with the logtypes-api than what I have here with the Invoke call?

In any case the above returns the logtypes needed to solve issue this for rules.

**Comment by kostaspap** [comment]
> I have a test implementation working for rules in calls that executed the CreateRule handler. I added some lambda:invoke stuff to a policy in deployments/core.yml allowing panther-analaysis-api to invoke the panther-logtypes-api function. Currently I'm retrieving the logTypes on each call to CreateRule.
> 
> ResourceTypes and LogTypes are both mapped to tableItem ResourceTypes. Does this mean the log types returned from the logtypes-api can be used to validate entries in either ResourceTypes or LogTypes inputs?
> 
> My demo method is:
> 
> ```
> func getLogTypes() []string {
> 	var listLogTypesOutput logtypesapi.AvailableLogTypes
> 	payload := logtypesapi.LogTypesAPIPayload{
> 	  ListAvailableLogTypes: &struct{}{},
> 	}
> 	if err := genericapi.Invoke(lambdaLogTypesClient, "panther-logtypes-api", &payload, &listLogTypesOutput); err != nil {
> 	  fmt.Printf("Error: %v\n", err)
> 	  return nil
> 	}
> 	return listLogTypesOutput.LogTypes
> }
> ```
> 
> (code not showing package imports, a search method, and a lambdaClient initialization)
> 
> This code was just a test. If I this ends up in the solution I would substitute fmt with zap and I'm sure I can clean it elsewhere.
> 
> This method could be a bottleneck for requests if we don't have some sort of caching. It's not as much of an issue with the bulk upload since we can run the validation without refreshing the valid LogTypes.
> 
> I kind of hacked this together from looking at the code base. @austinbyers is there a more common method of inter-service communication with the logtypes-api than what I have here with the Invoke call?
> 
> In any case the above returns the logtypes needed to solve issue this for rules.

@tatehanawalt Note that this particular API offers a client that you can use to interact with it, you can initialize it like [this](https://github.com/panther-labs/panther/blob/8b267aefb74fc5963b1cdb842df9a3e1df856cd7/internal/log_analysis/datacatalog_updater/main/lambda.go#L81-L84).

**Comment by tatehanawalt** [comment]
Thank you Kostas thats what I was looking for

**Comment by austinbyers** [comment]
> This method could be a bottleneck for requests if we don't have some sort of caching

As for caching, don't. We only need this validation when a user updates their detections, and if they have recently added new custom log types, those need to be available immediately. We've found caching to be a premature optimization in most cases for user-facing apis
