### ISSUE TITLE
User which fails to invite still added to user list

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#631]
### Describe the bug

If you invite a user with an email that already exists, the backend rejects the request, but the frontend still shows the newly added user:

<img width="1006" alt="Screen Shot 2020-04-01 at 12 19 56 PM" src="https://user-images.githubusercontent.com/3608925/78177645-4c358d00-7413-11ea-883b-400610411547.png">

If you refresh the page, it will go away, which proves the duplicate user was never added in the backend

### Steps to reproduce

1. Invite a user with an email that already exists
2. See both the error message and the user in the list
3. Refresh the page and see the "duplicate" user removed

### Expected behavior

Either don't add the new user to the list until the response is successful or remove it from the list after a failed response

### Environment

- Latest master

**Comment by 3nvi** [comment]
After some investigation, it turns out it's an issue with Apollo. This didn't use to be a bug

https://github.com/apollographql/apollo-client/issues/5790

**Comment by 3nvi** [comment]
Keeping this issue open since we can do some work with front-end validations in order to work our way around the problem

**Comment by 3nvi** [comment]
I suggest a temporary fix, where we don't allow users to add a user that already exists through the form
