### ISSUE TITLE
Allow Deployment of Policy/Rule Engine in secure mode

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#648]
### Describe the ideal solution

Previously, we had a series of controls in place within the policy/rule engine that would prevent malicious actions from being taken by the policies/rules. This was to protect against a threat model where some policies/rules being run could have been written or inserted by malicious actors. We have since changed the threat model to assume all policies/rules are coming from trusted sources, and so disabled most of these checks. Users should be able to opt in to the threat model that does not treat all policies/rules as trusted if they want, in exchange for the tradeoffs that comes with.

Security controls we used to enforce within the policy/rule engine:

1. Sub process isolation. Each invocation of a policy/rule would be run in a sub-process, which prevents it from accessing shared resources of the lambda function. This incurs a significant performance overhead in starting the sub process, but prevents the policies/rules from accessing the lambda credentials, for example.
2. Policy/rule corruption detection. The policy/rule engine would monitor for changes to the policies/rules during execution. This incurs some performance overhead, but prevents the policies/rules from modifying each other.
3. Network access blocks. The policy/rule engine would prevent outbound (and inbound) network traffic while executing policies/rules. This prevents policies/rules from communicating to other services during policy/rule execution, but also prevents the possible exfiltration of data (possibly related to / could be implemented instead by #645)

When assuming the policies/rules are coming from a trusted source, none of these protections are necessary. But for users/organizations who don't feel comfortable with that threat model, being able to optionally enable these additional protections may be worth the cost. 

### Describe your use cases

The use case would be preventing malicious policies/rules from abusing the Panther system.

### How frequently would you use such feature

Users who decide to enable these features would use them hundreds/thousands/millions of times per day, every single time a policy or rule was evaluated.

### Describe alternatives you have considered

Alternatives could include deploying into a VPC per #645, although this could also be supplementary instead of a replacement. This would limit the scope of what could be accomplished by a malicious policy/rule.

More stringent controls could be put in place to control who has access to policies/rules, which would reduce the possibility of a malicious policy/rule from occurring in the first place. This would be more proactive rather than reactive, but requires some thought on how we would best be able to accomplish this.

**Comment by nhakmiller** [comment]
Changing the label from `security` to `security-feature`. The new `security-feature` label will be used for issues that relate to adding new security functionality to the product, such as this one. The `security` label will be reserved for issues that indicate a security vulnerability in the product, and must be resolved within a certain SLA.

**Comment by rleighton** [comment]
Since adding the snowflake lambda we have the CF infra to create VPC lambdas. This is a simple config change for the python-based lambdas + load testing (to see if this change has any scalability issues). I'm thinking I should try this for 1.7

**Comment by austinbyers** [comment]
#645 is the issue related to Lambdas in VPCs. This one is more generic - can we run the Python in an isolated subprocess, for example, to prevent malicious Python from corrupting the Lambda function? That's what we used to do

**Comment by austinbyers** [comment]
#645 (network access / VPC) has been the most common request, so I'm going to close this issue in favor of that one. If in the future we need an additional level of isolation beyond lambda and the network, we can create a new issue for that specific feature
