### ISSUE TITLE
Create Rule button dropdown visibility issues

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#651]
### Describe the bug

Go to "Log Analysis"->"Rules"->"Create new". The words "Single" and "Bulk upload" are merged with the background. See attached screenshot for more details

### Steps to reproduce

1. Go to "Log Analysis"
2. Click on "Rules"
3. Click on "Create new"

### Expected behavior

I expected that the words "Single" and "Bulk upload" will be easier to read. 

### Environment

How are you deploying or using Panther?

- Panther version or commit: db0d7a2466960986597a08e94fd8b43f9e4d93c0
- OS: MacOS 10.15.4
- Browser: Chrome  80.0.3987.149 (Official Build) (64-bit)

### Screenshots

![Screen Shot 2020-04-03 at 11.01.09 AM.png](https://images.zenhubusercontent.com/5e4fc81c2009ef65e12fafd8/8f74f57b-0ac0-4ce8-9a49-18f1f0df27eb)

**Comment by 3nvi** [comment]
This has long been resolved
