### ISSUE TITLE
Settings breadcrumb leads to 404

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#658]
### Describe the bug

`panther-url/settings` leads to a 404 page, but it's linked in breadcrumbs

### Steps to reproduce

1. Go to `/settings/users` while logged into Panther as an admin
2. Click the settings breadcrumb at the top of the page
3. Note the error message: `/settings` does not exist

### Expected behavior

Either no breadcrumbs in settings pages, or `/settings` should redirect to `/settings/general`

### Environment

- latest master

**Comment by 3nvi** [comment]
@alexmylonas Look at the `Routes.tsx` file
