### ISSUE TITLE
Deploying to potentially unsupported region - 

### ISSUE THREAD

**Issue by gavinelder** [panther-labs/panther#67]
**Describe the bug**

When attempting to deploy into AWS-CN partition I believe I am running into an error creating a Simple email service subscription , I don't believe this service is available. 

Are you aware of required services or Topics required at this stage of the deploy ?

```shell 
> mage -debug deploy
-----
-----
/python-analysis.zip exists and is up to date
deploy: uploading ACM certificate
Error: SubscriptionRequiredException: The AWS Access Key Id needs a subscription for the service
	status code: 400, request id: 48c98adb-c18a-40cb-b335-e828445fac31
```` 

**To Reproduce**
1. Deploy within AWS-Cn

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Within the docker image on mac. 

**Additional context**

**Comment by gavinelder** [comment]
Actually I believe it may be Amazon certificate manager which is missing.

**Comment by austinbyers** [comment]
Good find! What region exactly are you deploying to so we can reproduce it?

Thankfully, AWS has a [nice table](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/) showing which services are supported in which regions. AWS certificate manager is supported in all regions, including gov regions and asia-pacific, except Beijing and Ningxia.

We should do a full audit of all of our AWS services and which regions they won't work in and update our documentation accordingly. Certificate manager is used to enable HTTPS on the web app, but if that is indeed the issue we could downgrade to HTTP so you can at least get a deployment up and running.

**Comment by gavinelder** [comment]
Hi @austinbyers sadly the AWS-CN partition consists of Beijing and Ningxia so aws-cn support is probably reliant on allowing the customer to bring their own SSL cert or downgrading to http. 

Let me know what the outcome is.

**Comment by nhakmiller** [comment]
Thanks for reporting this issue, @gavinelder . It looks the [AWS recommended workaround](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_server-certs.html) in cases where ACM is not supported is to use IAM for certificate management.

I just did a quick test on my local deployment, and was able to trivially use the same certificate and key files we use to import to ACM to import to IAM instead. Then switching the load balancer over to the IAM certificate worked with no issue.

I will see about updating the deploy tool to handle this case and fall back to IAM certificate management when ACM is not available.

**Comment by nhakmiller** [comment]
@gavinelder I've put up a PR here https://github.com/panther-labs/panther/pull/69, unfortunately I don't have an account setup in the AWS-CN partition so I've not been able to test it yet. I'm looking into getting one setup, but if you're able to test this patch out and let us know if it resolves your issue that would be greatly appreciated.
