### ISSUE TITLE
Parquet Support for Log Processing

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#674]
### Description
Currently log processing outputs data as JSON. While JSON is flexible, it not as efficient for Athena queries as a column oriented format such as Parquet.

This task will implement a process that will convert and compact files into Parquet format.

There will be a new 'historical' bucket created to hold the Parquet data. The hourly partition files in the JSON bucket will be converted to Parquet and written to the historical bucket. The Glue partition will be updated to point to the Parquet data.

Since data will be copied from the JSON bucket, there exists the possibility of "late data", data written to a JSON partition AFTER the Parquet copy has been created. This process must deal with this possibility and re-process any JSON partitions into Parquet.

### Acceptance Criteria
- Hourly JSON data is converted to Parquet and the Glue partition updated to point to Parquet files
- If late data is detected,  new Parquet files need to be generated and he Glue partition updated to point to Parquet new files
- New user config parameters will be created to allow control of data retention for log processing. JSON data will default to 30 days and historical data 365 days.

**Comment by kostaspap** [comment]
> There will be a new 'historical' bucket created to hold the Parquet data

I don't think we need a separate bucket - we can just use our existing bucket and store the data under different prefix. We should try to be "frugal" with the number of AWS resources we create inside a customer account.
