### ISSUE TITLE
Backend Support for Global Module

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#684]
### Description

The global helper module is a special python module that can be imported by policies or rules in order to support code re-use and central management of certain things like lists of IP addresses. Currently this module is implemented as just a special type of policy or rule, but we need to support it as a dedicated analysis type `global` in order to address a number of issues we've encountered since adding support for globals.

### Acceptance Criteria

- The analysis-api should support specific endpoints for creating, editing, and deleting globals
- The policy and rule engine should allow policies and rules to import any `global` that has been created
- Remove unnecessary logic for managing globals the old way from the policy engine, rule engine, and resource processor

Note that for now we will only have support for a single global, but the groundwork should be laid such that it will be simple to transition to multiple globals

**Comment by kostaspap** [comment]
I imagine we also need a migration script to migrate existing `aws_globals` methods that the customers might have already deployed?

**Comment by nhakmiller** [comment]
This feature has been implemented. Future improvements (such as multiple globals) can go under a different story.
