### ISSUE TITLE
Mage command to deploy Panther modifies source files

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#691]
### Describe the bug

Mage command to deploy Panther modifies source files.

### Steps to reproduce

1. Checkout master branch
2. Run `mage deploy`
3. Run `git status` to see changed files

### Expected behavior

Running `mage deploy` command doesn't modify source files. 

### Environment

How are you deploying or using Panther?

- Panther version or commit: https://github.com/panther-labs/panther/commit/45017102d989ea7c7cef9e9139594c35be39cce2
- OS: MacOS 10.15.4
- Browser: Irrelevant

### Additional context

Might worth writing down/documenting the DAG of the different operations that mage performs - and how the are depending on each other. Similar to the graph in [this](https://proandroiddev.com/understanding-gradle-the-build-lifecycle-5118c1da613f) post.

**Comment by austinbyers** [comment]
I see two types of changes (testing commit 7a87e60a)

1. `go.mod` and `go.sum` change after `mage setup`
    - go can freely change these files when it builds or tests, I'll do some research to see if I can make these more stable.
2. Generated API files (`api/gateway/*/{client,models}`, `web/__generated__/`) change after `mage build`
    - This fix is easy, we just need to `mage fmt` the generated files

**Comment by alexmylonas** [comment]
@austinbyers This seem to still occur on c8125e9ce6460ec12ad703e266c9e0dca6189027

Example diff: 
![Screenshot 2020-04-14 at 6 22 47 PM](https://user-images.githubusercontent.com/14179917/79242421-fcc47780-7e7c-11ea-86ab-66ab0d0941c1.png)

**Comment by austinbyers** [comment]
@alexmylonas that commit is on a branch, are you sure your branch is up to date with master?

From master (7fa37cc2b), I did a brand new clone of the panther repo. `mage setup` showed no diffs, `mage build:api` no diffs, `mage build:lambda` no diffs, and `mage fmt` still no diffs.
