### ISSUE TITLE
DynamoDB Caches

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#710]
### Describe the ideal solution

To support more complex rules and policies, we should pre-create a DDB table that's hooked up to the analysis engine by default. This table can be used as a key/value store for lists, indicators, counters, etc. Helper functions should exist to expose a clean API to users.

### Describe your use cases

* Keeping state between rules
* Counters
* Workaround for thresholding
* Indicator matching (low amount)

### How frequently would you use such a feature

Daily

**Comment by BatteryCandy** [comment]
+1 This is an excellent addition!

**Comment by nhakmiller** [comment]
@austinbyers did your recent changes resolve this issue?

**Comment by austinbyers** [comment]
Ah yes, good call!

The Dynamo table was added in #890 and #903 and then the helper functions added in https://github.com/panther-labs/panther-analysis/pull/54 and https://github.com/panther-labs/panther-analysis/pull/55
