### ISSUE TITLE
Support GitLab JSON logs 

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#720]
### Description

GitLab has an advanced log system where everything is logged. We want to be able to analyze these logs through Panther. 

The logs we are going to support are:
- production_json.log
- api_json.log
- application_json.log
- integrations_json.log
- git_json.log
- audit_json.log
- graphql_json.log
- mail_room_json.log
- exceptions_json.log

Log samples for these logs are available here: https://docs.gitlab.com/ee/administration/logs.html
### Acceptance Criteria

- Parsers are available for each log type
- Each parser has appropriate unit tests
- Corresponding tables are created in Glue Data catalog
-  Users can select the new logs as log source when creating/editing a rule

**Comment by alxarch** [comment]
I took a stab at implementing this at #719. I have left out `mail_room_json` and `graphql_json` logs.

 - `mail_room_json` has no specified format in the documentation
 - `graphql_json` logs GraphQL queries as they happened without even a timestamp and with a  
   generic map for the query parameters. I don't think it's interesting for log analysis.

Further investigation should go into whether the sample log records in the documentation do not cover all possible fields of the logs. Especially in the case of `production_json` and `api_json` logs

**Comment by kostaspap** [comment]
Closed with #719
