### ISSUE TITLE
Store events that failed classification in a separate table

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#722]
### Description

Currently when we try to classify a log line and it fails, we log a warning. In case the source is an S3 object we also log the S3 object location and the number of the line inside the file that we failed to process. 
This approach has two problems: 
1. Difficult to identify the specific log line that failed processing. 
2. Even more difficult to re-process the failed log line once a parser patch is applied. 

We should instead store all events that failed parsing in a separate table. This would allow easier debugging and potentially replying failed events until they succeed. 

### Acceptance Criteria

- We create a new table in Glue Data catalog to contain events that we failed to parse
- Log processor pushes the data that failed classification to that table. 
- We use as partitioning time the processing time
- This table doesn't have to be included in the current Athena views. 

The table should include the following fields:
* p_parse_time: timestamp
* p_source_id: string
* p_source_label: string
* raw: string
* p_classification_errors: [string]

, where `raw` contains the log line that we failed to classify.

**Comment by jacknagz** [comment]
100% for this.

**Comment by rleighton** [comment]
We currently plan to do this in similar manner to rule engine exceptions. Giving to @kostaspap

**Comment by alxarch** [comment]
Updated the estimate because it will require a new glue table and that has more side effects than just the core functionality.

**Comment by giorgosp** [comment]
+1, this is very important. I feel though that this ticket is only a part of a bigger solution regarding unclassified events.

Some questions that come to mind are:
- Will this table be visible to the SaaS users?
- How are we (or the users) going to use and benefit from this table? Will there be a UI (or a cli tool etc) so that we or the users can replay the events that match an SQL query?

**Comment by kostaspap** [comment]
> +1, this is very important. I feel though that this ticket is only a part of a bigger solution regarding unclassified events.

Yup, agreed. This will play along with the system status notification system, so users can be notified if we fail to parse events from their sources. 

> Some questions that come to mind are:
> 
> * Will this table be visible to the SaaS users?

Yes, it will be a table like all others. 

> * How are we (or the users) going to use and benefit from this table? Will there be a UI (or a cli tool etc) so that we or the users can replay the events that match an SQL query?

Making sure that the logs are available for troubleshooting is the first step (now we just ... drop them). I think yes, eventually we want to add the capability to replay failed logs by choosing e.g. source & time range. But that's more down the road.

**Comment by giorgosp** [comment]
Will the users be able to handle the failed the events? My understanding is that they will only be able to fix issues with their custom logs.

Also, since we won't have access to the unclassified logs table,  how can we troubleshoot issues with the builtin parsers without asking the users to anonymize and send over the logs? 
A solution I was thinking for this is to include the json keys in the `failed to classify` error log.

**Comment by kostaspap** [comment]
> Will the users be able to handle the failed the events? My understanding is that they will only be able to fix issues with their custom logs.

Correct, for anything else they can reach out. 

> Also, since we won't have access to the unclassified logs table, how can we troubleshoot issues with the builtin parsers without asking the users to anonymize and send over the logs?
> A solution I was thinking for this is to include the json keys in the `failed to classify` error log.
Nope, we don't have and should not have access to customer data.

**Comment by kostaspap** [comment]
Issue moved to [panther-labs/panther-enterprise #1834](https://github.com/panther-labs/panther-enterprise/issues/1834) via [**ZenHub**](https://www.zenhub.com/)
