### ISSUE TITLE
Panther failing to deploy in ap-southeast-1

### ISSUE THREAD

**Issue by weikiat8** [panther-labs/panther#747]
### Describe the bug
....
13:04:40        INFO    deploy: uploading load balancer certificate keys/panther-tls-public.crt with key keys/panther-tls-private.key
13:04:40        INFO    build:api: generating Go SDK for 4 APIs (api/gateway/*/api.yml)
13:04:41        INFO    deploy: CREATE CloudFormation stack panther-bootstrap
13:04:49        INFO    build:lambda: compiling 20 Go Lambda functions (internal/.../main) using go1.14.1
13:10:20        FATAL   execute change set for stack panther-bootstrap is ROLLBACK_COMPLETE:

Cloudtrail logs for the load balancer in CloudFormation Stack panther-bootstrap has an error - "InvalidConfigurationRequestException" and s3bucket access permission error.

"invokedBy": "cloudformation.amazonaws.com"
    },
    "eventTime": "2020-04-21T12:43:38Z",
    "eventSource": "elasticloadbalancing.amazonaws.com",
    "eventName": "ModifyLoadBalancerAttributes",
    "awsRegion": "ap-southeast-1",
    "sourceIPAddress": "cloudformation.amazonaws.com",
    "userAgent": "cloudformation.amazonaws.com",
    "errorCode": "InvalidConfigurationRequestException",
    "errorMessage": "Access Denied for bucket: panther-bootstrap-auditlogs-cm1jpam02hj9. Please check S3bucket permission",
    "requestParameters": {
        "attributes": [
            {
                "key": "idle_timeout.timeout_seconds",
                "value": "30"
            },
            {
                "key": "access_logs.s3.enabled",
                "value": "true"
            },
            {
                "key": "access_logs.s3.bucket",
                "value": "panther-bootstrap-auditlogs-cm1jpam02hj9"
            }
        ],
        "loadBalancerArn": "arn:aws:elasticloadbalancing:ap-southeast-1:xxxxxxxxxx:loadbalancer/app/web/xxxxxxxxxxxxxxx"
    }

### Steps to reproduce

1. checkout panther
2. set AWS variables incl. region=ap-southeast-1
3. ./dev.sh exec into panther container
4. mage setup:all
5. mage deploy

### Expected behavior

Able to deploy in ap-southeast-1

### Environment

- Panther version or commit: 1.0.1
- OS: Ubuntu 18
- Browser: Edge

**Comment by austinbyers** [comment]
Thanks for the report! I'll take a look soon and see if I can reproduce the issue

**Comment by austinbyers** [comment]
I was able to reproduce (tested with #742):

> 3:36:07	ERROR	stack panther-bootstrap: AWS::ElasticLoadBalancingV2::LoadBalancer PublicLoadBalancer CREATE_FAILED: Access Denied for bucket: panther-bootstrap-auditlogs-16djwakra2dkl. Please check S3bucket permission

The "AuditLogsBucket" and "AuditLogsBucketPolicy" resources in the bootstrap stack are created successfully according to the CloudFormation events, and the ELB depends on the bucket policy (which we enforce in CFN).

I'm not sure why the ELB doesn't like the bucket policy in that specific region, nor when we'll be able to fix it, but as a workaround you can just disable ELB access logging by commenting out these 4 lines:

https://github.com/panther-labs/panther/blob/05f995357d9b2bfdbfbf2b1d5cf90d4c8aab4107/deployments/bootstrap.yml#L584-L587

With that change, I was able to deploy successfully to ap-southeast-1

**Comment by kostaspap** [comment]
Thanks for reporting the issue @weikiat8 ! I identified the issue and is getting fixed with #749

**Comment by kostaspap** [comment]
@weikiat8 the fix has been included in v1.1.0 https://github.com/panther-labs/panther/releases/tag/v1.1.0 . Feel free to try it again!
