### ISSUE TITLE
Alert details breadcrumb capitalizes first letter

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#751]
### Describe the bug

It's more like a "nuance" than a bug. The top of the Alert Details page capitalizes the first letter of the Alert ID. 

### Steps to reproduce

1. Go to `Log Analysis` -> `Alerts`
1. Click on any alert. 
1. See the AlertID in the top of the page (see screenshot below)

### Expected behavior

AlertID should be lowercase. 

### Environment

How are you deploying or using Panther?

- Panther version or commit: https://github.com/panther-labs/panther/commit/d81bdd6307cffc211f921d8dcd987fb39b0141cd
- OS: MacOS 10.15.3
- Browser: Chrome 81.0.4044.113 

### Screenshots

As you can see below, the first `F` is capitalized. 
![Screen Shot 2020-04-22 at 3.47.49 PM.png](https://images.zenhubusercontent.com/5e4fc81c2009ef65e12fafd8/4d46710c-c7b8-459c-bfbe-543086fc83d5)

**Comment by alexmylonas** [comment]
There is another related small issue. Because the hex is capitalized before that point is no longer recognized as hex. I will fix them both!
