### ISSUE TITLE
Add Log Source to Alert Summary

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#774]
### Describe the ideal solution

A way to group alerts by log source (generally this is localized into a single account) to better understand noisy accounts.

### Describe your use cases

In an upcoming design change, we need to allow alert search by log source.

### How frequently would you use such a feature

Daily - It's very common to understand which account generated the alert

### Describe alternatives you have considered

None

### References

https://github.com/panther-labs/panther/blob/master/api/lambda/alerts/models/api.go#L79-L90

**Comment by kostaspap** [comment]
By log source we mean the label of the onboarded source? Note that this will in many cases not be associated with the account that generated the alert. In some cases no account is really associated (e.g. OsQuery, GitLab logs, GCP etc) in others is just the aggregator account (CloudTrail, S3 access etc). Added the Log Source imo will not help create an association with the "actor".
