### ISSUE TITLE
SNS/SQS Data Input Support

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#775]
### Describe the ideal solution

A user can analyze data with Panther from either an SNS Topic or SQS Queue.

### Describe your use cases

Analyzing streaming data that does not natively send to S3.

### How frequently would you use such feature

Daily

### Describe alternatives you have considered

Writing a custom solution out to S3, but this is non-ideal for some scenarios.

**Comment by kostaspap** [comment]
Already being worked on in enterprise

**Comment by austinbyers** [comment]
Labeling as "wontfix" for the community edition
