### ISSUE TITLE
Show confetti on every new user's first login

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#796]
### Describe the ideal solution

Confetti is currently shown once per installation. Ideally it should be shown once per user sign-in 🎉 

The hard part is figuring out when is the user's first login since Cognito doesn't store this. Also what happens if during the first login they refresh? 
 
### Describe your use cases

Fun

### How frequently would you use such feature

Once per user 

### Describe alternatives you have considered

Not doing it at all

### References

Katy Perry

### Additional context

Baby you're a firework

**Comment by jacknagz** [comment]
> Baby you're a firework

😹

**Comment by 3nvi** [comment]
@austinbyers  I'm pretty sure you have different priorities, but I'd love a way in the users-api to mark whether the user is logging in for the first time or not. 

Ideally that should be boolean directly mapped to a cognito attribute, thus I'd "get it" through Cognito and "update it" through the users-api

**Comment by 3nvi** [comment]
I'd normally be able to set it myself since new users need to set an MFA, but that wouldn't be valid for SSO users (which bypass the typical flow of new users)

**Comment by jacknagz** [comment]
@3nvi I believe we did this already, right?

**Comment by 3nvi** [comment]
Nope, it's not done.

Currently confetti shows up **once** fr the first user of a Panther deployment. We want to make sure to show it for every user, the **first** time they visit the platform.

**Comment by 3nvi** [comment]
@austinbyers should we add it to product board or is this something we can easily do?
