### ISSUE TITLE
Extract common fields from Request Metadata of GCP Audit logs

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#801]
### Description

Extract additional IPs & Domains from Request Metadata of GCP Audit logs. 

* Additional IP information can be found here: https://github.com/panther-labs/panther/pull/779#discussion_r417244891
* Additional Host information can be found here: https://github.com/panther-labs/panther/pull/779#discussion_r417245414

### Acceptance Criteria

- Common fields are identified and extracted from GCP Audit logs

**Comment by jacknagz** [comment]
@kostaspap would you mind updating this ticket with a clearer description? It's unclear with the link to the discussion what we're trying to accomplish here.

**Comment by kostaspap** [comment]
> @kostaspap would you mind updating this ticket with a clearer description? It's unclear with the link to the discussion what we're trying to accomplish here.

Added some more context
