### ISSUE TITLE
Change phrasing on unit tests

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#812]
### Description

In the web UI, the phrasing on the unit tests can for policies & rules can be confusing. The `Expected result is True` and `Expected result is False` radio buttons can be unintuitive to users, and should be update to more directly reflect what is being tested (e.g. `Expected result is True` could be changed to `Test resource is compliant`). Additionally, we could update the green `PASS` and red `FAIL` text could maybe be updated to something like `Test Passed` and `Test Failed`, or something like that.

### Acceptance Criteria

- users are able to intuitively grasp the results of the unit tests via the web UI

**Comment by kostaspap** [comment]
In case of the rules, the wording could be "Event should trigger alert"/"Event should not trigger alert"
