### ISSUE TITLE
Delete Test Confirmation

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#814]
### Describe the ideal solution

When writing or editing rule/policy tests, it's easy to accidentally delete the unit tests. We should prompt the user for confirmation if possible.

### Describe your use cases

Just clicking around and using the product casually. If you are switching between the tests too quickly, you can accidentally delete them.

### How frequently would you use such feature

Daily

### Describe alternatives you have considered

Not accidentally clicking the X :joy:

### References

None

### Additional context

None

**Comment by 3nvi** [comment]
I personally believe this is a non issue since even if you accidentally click, you still need to press "save" for the test to actually be removed/deleted.

Do you feel that you need a confirmation even in this case?
