### ISSUE TITLE
Panther tables not shipping with default views

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#834]
### Describe the bug

On a fresh deployment of Panther, there are supposed to be a number of views available on the panther tables in Athena to assist with making generalized search (views such as `panther_views.all_logs` and `panther_views.all_rule_matches`). These views are no longer being created by default.

### Steps to reproduce

1. Do a fresh deployment of Panther
2. Go to the AWS Athena console
3. Scroll down to where the views are listed on the bottom left, observe that there are none

### Expected behavior

Panther should deploy with a handful of default views.

### Environment

v1.2.0 candidate commit.

### Additional context

@rleighton confirmed this in his accounts.

### Screenshots

<img width="368" alt="Screen Shot 2020-05-05 at 7 04 22 PM" src="https://user-images.githubusercontent.com/49166439/81132420-3ed45c80-8f03-11ea-84ff-6d4399f2dacb.png">

**Comment by rleighton** [comment]
This is due to 2 issue: 
1) missing error check 
2) the issue discussed at standup with gcp schemas
The bad schema caused creating the view to fail and the missing error check caused it to go un-noticed.

**Comment by rleighton** [comment]
Resoved
