### ISSUE TITLE
Universal web images

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#846]
### Description

We currently build a custom docker image for each new deployment which includes string constants for the user's environment (AWS account ID, GraphQL API, etc). In order to have a static deployment package, we need a way to build the web image such that it can be published and shared and then accept configuration dynamically.

### Acceptance Criteria

- `mage deploy` continues to build the image from source. We need this for developers and users who choose to modify their source.
- The built image is generic and could be published to DockerHub/ECR

This issue is just about changing the built image itself, don't worry about automating its publication

**Comment by 3nvi** [comment]
@austinbyers One thing to know is that the image related to the ECS Task will need to be upgraded directly on the CFN (on the `panther_web` stack) on every release, since having `:latest` won't do it anymore (since a user trying to upgrade from 1.1 -> 1.2 might won't be able to)

**Comment by austinbyers** [comment]
Yep, that's perfect. The SAR app would be explicitly versioned as well.

As for implementation, ideally we just pass the current `.env` parameters as actual environment variables to the running ECS task:

https://github.com/panther-labs/panther/blob/369b0da0060c2cda71f09ee3cc286360022b6e38/deployments/web_server.yml#L137-L141

Then you can write those variables to a file when the task starts, or just reference them from the environment when serving assets
