### ISSUE TITLE
Support Apache Access Logs

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#867]
### Description

Support Apache Access Logs

### Acceptance Criteria

- Parsers are in place
- Unit tests for parsers
- Log type selectable in UI
- Glue tables created

**Comment by alxarch** [comment]
[Apache reference](https://httpd.apache.org/docs/current/logs.html#accesslog) Defines two 'official' log formats:
- [Common Log Format](https://httpd.apache.org/docs/current/logs.html#common)
- [Combined Log Format](https://httpd.apache.org/docs/current/logs.html#combined)

**Comment by alxarch** [comment]
Apache also defines a log format directive with log format expressions (the above mentioned formats are such expressions). Supporting any custom log format is beyond the scope of this issue and should be considered as a case for custom logs.
