### ISSUE TITLE
CloudTrail p_any_aws_account_ids Bug

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#873]
### Describe the bug

Lack of validation on the `userIdentity.accountId` field

### Steps to reproduce

```
	"userIdentity": {
		"type": "AWSAccount",
		"principalId": "",
		"accountId": "ANONYMOUS_PRINCIPAL"
	},
	"p_log_type": "AWS.CloudTrail",
	"p_row_id": "367279b18168c2cb91f884ce029856",
	"p_event_time": "2020-05-12 21:42:46.000000000",
	"p_parse_time": "2020-05-12 21:47:12.961614255",
	"p_any_ip_addresses": [
		"136.24.229.58"
	],
	"p_any_aws_account_ids": [
		"123456789012",
		"ANONYMOUS_PRINCIPAL"
	]
```

### Expected behavior

Check a regex (12-digit account ID) prior to parsing into the p_any_account_ids field.

### Environment

- Panther version or commit: v1.1.1-267-g5a652680

### Additional context

Discovered when testing S3 access logging via CloudTrail

### Screenshots

None

**Comment by rleighton** [comment]
I'll have a PR out today. Good catch

**Comment by rleighton** [comment]
Fixed
