### ISSUE TITLE
Alerts should have a user customizable TTL (default off)

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#883]
Currently alerts have no expiration. At some point in time customers will be paying for ddb storage they do not need/want. 

There should be a configuration option (default unset) that customers can set to expire alerts in ddb.

Alerts and their matches will still be available for search in S3, which has its own configurable expiration.

**Comment by kostaspap** [comment]
DDB storage costs should be minimum if any. The first 25GB of storage are for free with $0.25/GB thereafter. https://aws.amazon.com/dynamodb/pricing/on-demand/

Every alert contains a minimum set of information (alert id, times, etc but not the actual event matches) which means that it is few KBs maximum. 

We could delete them if we wanted to. I think we could just have a "data expiration" period that defines when we expire data from S3 and from DDB? Not sure it makes sense to keep the alerts in DDB longer than we keep the actual data. Simpler to configure I would say as well. Thoughts?

**Comment by jacknagz** [comment]
I think this could be a setting on the deployment itself and not in the application.
