### ISSUE TITLE
Showcase Log Onboarding Steps

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#886]
### Describe the ideal solution

We should separate the Step 1 and Step 2 of the log onboarding so users are reminded that they have to configure bucket notifications. The stack launched does not take care of it.

The flow should be something like this:

1. User adds basic information
2. User launches stack
3. We verify the connection and give a reminder to configure their S3 event notifications

### Describe your use cases

Easier onboarding - Updating S3 buckets is a non-trivial task that sometimes requires manual steps or code changes outside of Panther to work.

### Designs

https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/70fbde80-1195-4df9-a583-6962f57e3e19/commits/37590523135a8bd8a3e8a0ae7f6d46c8bb52b7ee/files/c2bbc1a8-4778-4cd6-93a5-4630d8868201/layers/470D23BE-968A-466D-8F4F-12EF02FCB18E

### Acceptance Criteria

- After the user has setup IAM we do a health check (as it already happens). If the user fails it, we should show an error screen. If the user passes the check (which happens while you see the hourglass), then the user should go to the next step (instead of showing a success screen as it happens now).
- Add another step in the wizard right after verification step (inbetween the IAM setup and the final step) with the designs shown in the link above
- This step should only be present when onboarding an S3 source, not when editing it
- The "read more" should link to `LOG_ONBOARDING_SNS_DOC_URL` variable and you should  remove any other link where this constant is referenced **within the same wizard**
- When the user clicks the "I have setup ...." you should direct him to a success page (there's no API request or response involved)

**Comment by 3nvi** [comment]
I again think that `configure their S3 event notifications` is wrongly handled. Voiced my concerns early  on for  that, since it adds a layer of complexity and takes user out of Panther

**Comment by kostaspap** [comment]
> I again think that `configure their S3 event notifications` is wrongly handled. Voiced my concerns early on for that, since it adds a layer of complexity and takes user out of Panther

A few users in our OSS have run into the issue that the UI is not providing proper guidance on how to onboard the source from S3, I believe this is why @jacknagz created this issue. The problem is that if we want to offer any type of UI option for onboarding resources, it has to be a variation of the current solution (unless someone comes up with a better solution). 

We already discussed that a CLI could help with onboarding sources but this requires an API to be in place, a bigger task that is planned but not yet in place. Definitely not a trivial change.

**Comment by 3nvi** [comment]
I understand that and I do think  that a CLI is the proper solution here. In the meantime, I just want  to perhaps re-think  the S3 onboarding process. What jack suggests is:

- Fill data
- Go out of Panther and run cloudformation
- Come back and  press `Next`
- Click Save (now  you think you' re done)
- Be  asked to  go to docs  and  follow  a different onboarding

At he end of the day, we  ask a user to follow a wizard  only to  let to him know that  he must do another full onboarding himself (for events). That's my problem
