### ISSUE TITLE
Deleting a Rule Redirects to Policies Page

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#894]
### Describe the bug

When you delete a Rule, you are redirected to the List Policies page

### Steps to reproduce

Delete a rule

### Expected behavior

Take you to the List Rules page

### Environment

Plan: Enterprise
Version: v1.1.1-267-g5a652680

**Comment by 3nvi** [comment]
This is fixed in the latest master. You can view the  related behavior here

https://github.com/panther-labs/panther/blob/master/web/src/components/modals/DeleteRuleModal/DeleteRuleModal.tsx#L87
