### ISSUE TITLE
List python entities on GlobalModule

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#911]
### Describe the ideal solution

An API endpoint that allows us to get a JSON schema (or any shape), describing the entities (constants, classes, functions, etc.) present in the user's global module

### Describe your use cases

People writing rules that they want to quickly have access to the globally defined constants & functions, without having to remember their name

### How frequently would you use such feature

ie. Weekly

### Describe alternatives you have considered

Not supporting autocomplete

### Additional context

What we'll want is a backend service written in python that can import the global helpers and then enumerate their classes and functions with something like dir, then map those results into a JSON object and send them back. Since globals are only updated occasionally, this object could be stored in dynamo/s3 and when the globals are updated it gets re-created, that way when the frontend wants it it's pretty quick to retrieve and doesn't need to be generated each time.

**Comment by nhakmiller** [comment]
If the type matters, we should use inspect. If it doesn't, dir is probably fine. Either way shouldn't be too hard, wiring up the plumbing will likely be more difficult than actually generating the schema.

**Comment by nhakmiller** [comment]
@3nvi, how do we feel about closing this issue and moving it to product board? While cool, I don't think we have any plans to do this task anytime soon.

**Comment by 3nvi** [comment]
Yeah, agreed
