### ISSUE TITLE
Support Reports for Rules

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#917]
### Description

Panther needs to support Reports. 

### Acceptance Criteria

- TBD

**Comment by jacknagz** [comment]
@kostaspap I believe this is closed, feel free to reopen if I'm wrong

**Comment by kostaspap** [comment]
> @kostaspap I believe this is closed, feel free to reopen if I'm wrong

Reopening. We do not properly support reports yet. The only way for users to create reports is if they use panther analysis tool. The UI doesn't offer them the option to manage them.
