### ISSUE TITLE
Cannot display Alert

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#93]
**Describe the bug**
When displaying the alert and error is shown:

Couldn't load alert
Cannot return null for non-nullable type: 'String' within parent 'AlertDetails' (/alert/eventsLastEvaluatedKey)

**To Reproduce**
1. Create a rule against CloudTrail as:
def rule(event):
	return True
2. Wait for match
3. Click on alert
5. Turn off rule

**Comment by 3nvi** [comment]
Most likely related to the fact that `eventsLastEvaluatedKey` can be `nil` in some cases
