### ISSUE TITLE
Ops Tuning: SQS Max Retries and 4XX Errors

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#961]
### Description

Currently, data hitting the log processor input queue will remain in flight for up to 150 minutes (15-minute lambda timeout * 10 retries), this should be shortened to 2-4 retries to it ends up in the DLQ sooner. 

Also, we should raise the 4XX ALB error alarm to something around 100.

**Comment by kostaspap** [comment]
4XX has already been removed with https://github.com/panther-labs/panther/pull/1049
