### ISSUE TITLE
Policy Status Updates Much More Slowly Than Resource Status

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#97]
**Describe the bug**

After updating a Policy that switches all resources from passing to failing or vice versa, the policy overview page updates all the resources' correct status very quickly (within 2-3 seconds). But it the policy status updates much more slowly (within ~ 1 minute). This leads to an inconsistent view presented to the users after a policy is updated.

**To Reproduce**

1. Go to a policy that has failing resources
2. Click on edit policy
3. Scroll down to policy body
4. Add a `return True` line at the beginning of the policy body
5. Update the policy and return to the policy overview page
6. All the resources will be Passing, but the policy status will still be failing
7. This state persists for ~1 minute

**Expected behavior**

I would expect as soon as the resources' status are updated, the policy status is updated as well.

**Screenshots**

![Screen Shot 2020-02-03 at 9 51 52 AM](https://user-images.githubusercontent.com/49166439/73679252-e0cb7b00-466e-11ea-89b7-d155d2f863e9.png)

Screenshot shows that all policies are failing but the policy is passing.

**Environment**
How are you deploying or using Panther?

- Current master 8ddce61

**Additional context**

@austinbyers tracked it to this line https://github.com/panther-labs/panther/blob/master/internal/core/analysis_api/handlers/compliance.go#L31

**Comment by austinbyers** [comment]
Right, I added some caching to the overall policy status because the way we query it isn't very efficient. 

But I'd rather have a better user experience, we can worry about query performance later if and when it becomes an issue. As long as no backend services are relying on this caching, I'll just remove it

**Comment by austinbyers** [comment]
This also affects the resource summary - both `resources-api` and `analysis-api` hit the same `DescribeOrg` endpoint in the compliance api

Without this caching, that endpoint might be able to be removed completely
