### ISSUE TITLE
Enhachements for Cloud Security dashboards

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#975]
### Description

The dashboard has currently the following diagrams: 

![Screen Shot 2020-06-03 at 10.17.12 AM.png](https://images.zenhubusercontent.com/5e4fc81c2009ef65e12fafd8/0131f090-32bd-41ba-bdd0-f796609600b3)

Some notes: 
* Top left chart is named "Policy Failure" but also includes passing policies. I am thinking we should just remove the passing policies and just display the failing policies. Maybe rename to "Failing Policies"
* "Policy Severity" maybe rename to "Enabled Policies"? It took me a bit to understand that this was not displaying the failing policies but just the policies that were enabled (failing or not)
* In the existing bottom left diagram, the "Failing, Passing" in the legend is in reverse order than it is displayed in the diagram. Should show first "Passing" then "Failing" in the legend. 
* I think it makes sense to remove the existing diagram that just displays "AWS"  resources and just have a "Policy Health" diagram which shows two bars, passing and failing policies. 

I was thinking maybe the charts would be organized like this:

"Policy Health" | "Failing Policies"
"Resource Health" | "Enabled Policies"

### Acceptance Criteria

- Above changes are implemented

**Comment by rleighton** [comment]
+1

**Comment by jacknagz** [comment]
Also - the totals don't seem to be dynamically updating (as they did in the past) if you were to de-select a category:

![cloudsec-new-overview](https://user-images.githubusercontent.com/11466941/83699890-1d29cc00-a5ba-11ea-9095-6adf2aeb681a.gif)
