### ISSUE TITLE
Panther should allow pushing logs to an S3 bucket managed by Panther application

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#976]
### Description

Our current S3 onboarding flow allows onboarding data that is an existing S3 bucket. Many users however don't have existing S3 buckets. We could offer a simpler workflow for such usecases where  Panther creates and manages the S3 bucket, and gives the users permissions to send data to it. 

### Acceptance Criteria

- Panther creates an S3 bucket where users can send data to. Bucket expires data after 7 days
- Bucket has already configured S3 bucket notifications
- When users go in the S3 onboarding flow, they can choose if they have an existing bucket that they want to onboard or if they want to send data to the Panther bucket. 
- Users can specify the Log type(s) they want to send to Panther and the AWS Accounts/roles that want to be given access to send data to the bucket. Panther returns them the name of the bucket and the prefix they can use (prefix will be the integration UUID)

**Comment by jacknagz** [comment]
@kostaspap this is a great idea that could simplify the onboarding process.

**Comment by kostaspap** [comment]
Moved to productboard
