### ISSUE TITLE
False alarms sent by panther-kv table

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#977]
### Describe the bug

Clean deployed Panther. Two alarms fired in my account due to "low" read/write capacity usage of `panther-kv` table. 

### Steps to reproduce

1. Clean deploy Panther
2. Wait a bit
3. See alarm

### Expected behavior

We shouldn't have such alarms in place. Low table usage is not a reason to alarm. 

### Environment

How are you deploying or using Panther?

- Panther version or commit: a8ae2e142743bb0304d7de31deeb4958607b3397

### Additional context

None

### Screenshots

![Screen Shot 2020-06-03 at 10.45.14 AM.png](https://images.zenhubusercontent.com/5e4fc81c2009ef65e12fafd8/516f5665-ec8d-44b1-947a-f1f3493fb576)

**Comment by rleighton** [comment]
Apparently this is how autoscaling works (we do not create these alarms). You can turn them off in the display: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/hide-autoscaling-alarms.html

Austin set this up, I've never used this service before. Austin, any comments?

**Comment by kostaspap** [comment]
> Apparently this is how autoscaling works (we do not create these alarms). You can turn them off in the display: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/hide-autoscaling-alarms.html
> 
> Austin set this up, I've never used this service before. Austin, any comments?

Ah, you are right. It's not really a critical issue, but it's confusing since it is a Panther-created resource that shows up to be in alarm.
