### ISSUE TITLE
Rule Testing: Show Dedup and Title Output

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#983]
### Describe the ideal solution

Today, rule tests only give an indication of if the rule returns true/false. The CLI workflow has slightly more functionality beyond that to validate the title() and dedup() workflows:

```
AWS.S3.ServerAccess.Unauthenticated
	[PASS] Authenticated Access
		[Title] Unauthenticated access to S3 bucket  example-bucket
		[Dedup] example-bucket
	[PASS] Unauthenticated Access
		[Title] Unauthenticated access to S3 bucket  example-bucket
		[Dedup] example-bucket
```

The UI workflow should also test these same functions.

### Describe your use cases

Validation of if the Title and Dedup functions work in addition to the Rule function.

### How frequently would you use such a feature

Daily

### Describe alternatives you have considered

CLI 

### Additional context

![Screen Shot 2020-06-03 at 9.45.54 AM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/51b84a1e-2957-4b54-befd-77e1fd7396a9)

**Comment by kostaspap** [comment]
I think it is implied already, but we should make sure that if the title or dedup functions fail, the tests should fail as well.

**Comment by kostaspap** [comment]
Backend code merged in `title-dedup-epic` branch
