### ISSUE TITLE
The Sidebar Doesn't Reset When Navigating

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#996]
### Describe the bug

When navigating around the product, the sidebar should reset on each page click to stay current with where the user is. It can get confusing otherwise.

### Steps to reproduce

1. Go to any page, such as the Cloud Security Overview
2. Click on the Log Analysis Icon
3. Now click somewhere in the Cloud Security Overview, such as one of the top failing resources
4. Notice the navbar is still showing Log Analysis

### Expected behavior

Upon navigation to a new page, the navbar should reset to your correct place.

### Environment

Plan: Enterprise
Version: v1.3.0-119-gb7e19ed9

### Additional context

None!

### Screenshots

![Kapture 2020-06-05 at 11.01.20.gif](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/4c7cd726-ee09-45cc-89d5-115cd056a1e0)

**Comment by 3nvi** [comment]
This issue is fixed in master
