### ISSUE TITLE
Parser: NGINX JSON

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#997]
### Describe the ideal solution

Support for NGINX Access logs in JSON format

### References

http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format

NGINX can also be installed locally with brew for end-to-end validation

**Comment by alxarch** [comment]
The NGINX `log_format` directive uses `escape=json`  for escaping strings using JSON escaping rules but the format itself has no specific schema. To support this we must write an NGINX parser that takes the `log_format` as a parameter and can handle arbitrary NGINX logs. There is currently no way for passing user parameters to parsers. This relates to the mechanisms that will be required for custom logs (ie loading user-specified parameters for parsers at runtime). We can revisit the way we will implement the loading of customlog parsers so it can be more generic and support parameters for any parser type (and OSS that part). This seems like a very good idea that could help us cover a broad range of problems when developing new parsers. We should discuss this with the rest of the 'logs team'.

**Comment by jacknagz** [comment]
https://stackoverflow.com/questions/25049667/how-to-generate-a-json-log-from-nginx/42564710#42564710

**Comment by kostaspap** [comment]
@alxarch I believe now this is handled by Custom Logs?

**Comment by kostaspap** [comment]
Nginx logs have specific format - so it's seems we cannot provide a managed schema out of the box. 
Instead, anyone interested to process Nginx JSON logs, should use the custom logs feature.

**Comment by alxarch** [comment]
> Nginx logs have specific format - so it's seems we cannot provide a managed schema out of the box.
> Instead, anyone interested to process Nginx JSON logs, should use the custom logs feature.

This is a good example of the flexibility we'd get from decoupling parsers from schemas.
We could provide a managed NGINX AccessLog schema that would include all possible fields.
Users could provide their own custom parsers that map to the managed AccessLog schemas.  
To achieve that we would require to support a `map` type for schema fields to be able to include the `http_*`, `http_sent_*` and `arg_*` nginx variables that hold values of request/response headers and URL query params.

**Comment by jacknagz** [comment]
> We could provide a managed NGINX AccessLog schema that would include all possible fields.

I'd like this
